### ISSUE TITLE
I want additional filters

### ISSUE THREAD

**Issue by rpeter85** [blokadaorg/blokada#100]
The unified hosts list contains (at the moment) 55.023 hosts to block and doesn't contain fake news, gambling and porn sites.
However, the below list blocks all the aboves:
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
It has 66.740 sites in addition to the unified one, it may worth to have it as optional in the blocking list.

**Comment by kar** [comment]
(also check what is being used in pi-hole, ad-guard)

**Comment by kar** [comment]
http://www.fooldns.com/fooldns-community/english-version/

**Comment by kar** [comment]
> Please add the list of Hadjar (a french user).
Here the address : http://www.phonandroid.com/forum/comment-eradiquer-les-pubs-une-bonne-fois-pour-toute-t70204-40.html

**Comment by kar** [comment]
> https://www.bleepingcomputer.com/news/security/researchers-identify-44-trackers-in-more-than-300-android-apps/

**Comment by kar** [comment]
https://adzhosts.fr/hosts/adzhosts-android.txt

**Comment by kar** [comment]
`adblock.mahakala.is`

**Comment by kar** [comment]
https://wally3k.github.io/

**Comment by kar** [comment]
https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist

**Comment by kar** [comment]
Skipped lists, for future reference:
- https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist (its very big, probably overkill and i dont think Blokada can handle so big lists well yet)
- https://wally3k.github.io/ (lots of good stuff but it's too much at once, I'll go through it another time)
