### ISSUE TITLE
I want more default whitelisted apps

### ISSUE THREAD

**Issue by rpeter85** [blokadaorg/blokada#101]
The idea is to have a list of apps that should be in the on whitelist by default, otherwise they fail to function properly. For example:
- Google Play Store
- Google Gmail
- Google Authenticator
- Waze (this app freezes if it's not whitelisted)
- Magisk Manager (fails to download updates if not whitelisted)
- Xposed installer (same as Magisk)

List any app you use that fails/crashes if not whitelisted.

**Comment by xmiseggs** [comment]
I don't agree with the list, I think that the one that currently exists is perfect, each user should add what they think is necessary.

**Comment by rpeter85** [comment]
The goal is to have a list of apps that are widely used and if they aren't whitelisted, they crash or malfunction. For a normal user without deep IT knowledge it's not self-evident that (for example) a given app cannot update if the app isn't whitelisted. It is much more true if Blokada installed months before s/he wants to use the given function (for example updating modules in Magisk), which is blocked.
Of course this list shouldn't be too permissive.

**Comment by kar** [comment]
Lets keep building the list here anyway, and then we can think what to do with it. Maybe Blokada should display some information whenever one of apps from the list is installed.

**Comment by rpeter85** [comment]
I'm not sure if that's on the list, but the "Find my device" should be on the list as well.

**Comment by kar** [comment]
Sure. If possible, paste package name or play store links please.

**Comment by xmiseggs** [comment]
If we start adding applications from the installation, I understand that we went outside Blokada's objective. I see a proposal for applications as correct but I find it wrong to include them by default. Is it possible to show the user as a proposal and that the user decides with a check that he wants or does not want to include in the whitelist, by default no check. Oh, thank you.

**Comment by surfinette** [comment]
Hi,
I have no issue with the Android play store or download app even when they are not whitelisted.
However, I can't download any app from the xda-labs app when it is not whitelisted (even with the Download app whitelisted).
Here are the xda-labs details to include it in the whitelist:
app: XDA Labs
package: com.xda.labs

**Comment by BarryThrill** [comment]
I had that issue before that my whitelist always after restart cleans automatic but now it doesnt so I dont mind! However something that should be as default is:

Google photo
Google duo
Google allo
Gmail?
