### ISSUE TITLE
I can't add some apps to white list

### ISSUE THREAD

**Issue by Klusek1983** [blokadaorg/blokada#102]
When I try add some apps to white list ex. Sky Forge Reloaded or Gear Club Blokada give me message that "This app doesn't exist or cannot be whitelisted"

**Comment by dewingerd** [comment]
Can someone explain to me why I cant whitelist the Aquamail app ?
I get the following message : "This app doesn't exist or cannot be whitelisted"

**Comment by kar** [comment]
We don't know yet, but keep posting the names (or package names) of problematic apps and I'll investigate what's the problem.

**Comment by alenjularic** [comment]
Don't know if it's still relevant, but Slack also can't be white listed.

**Comment by alenjularic** [comment]
Don't know if it's still relevant, but Stack also can't be whitelisted.

**Comment by jontieh** [comment]
Can’t whitelist Canon Camera Connect either. With blokada on it’ll disconnect while transferring photos via wifi
