### ISSUE TITLE
I want Blokada blog be on Medium

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#105]
Maybe it's better to use it instead of static pages. Not sure.

**Comment by IsaakGroepT** [comment]
Your blog now is blazing fast though. I'm making the move other way around myself to increase speed and customizability

**Comment by kar** [comment]
Thanks for your feedback. Indeed I am reconsidering this... Btw I'm using hugo for static page generation (gohugo.io), can recommend.

**Comment by IsaakGroepT** [comment]
Great tip, thanks!
