### ISSUE TITLE
I want another chat platform

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#107]
We are currently using gitter. It seems nice but is focusing on developers and requires github/twitter to sign up. We may want to use a more accessible platform for users.

Comments welcome.

**Comment by cubakcabak** [comment]
many opensource project use telegram:
* channel for the announcement
* group for discussion (features, bug reporting, FAQ)

it seems to works fine to accommodate the need of user <> developer communication.

and the group can be used as support for user by user answer too, such as common repetition: * how do i use this?
* which setting doing what needed
* mistakes user make that have "easy" answered by other users

**Comment by SkyzohKey** [comment]
Tox, Wire, Slack, Discord, Telegram, Matermost

**Comment by kar** [comment]
Thanks for the feedback everyone! I checked all suggestions and it seems that Telegram is the best option. I invite everyone to join the channel and try it out.

http://go.blokada.org/chat
