### ISSUE TITLE
I want the ability to set custom DNS servers

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#110]
The ability to change DNS servers

**Comment by kar** [comment]
Anyone willing to give some suggestions about any dns servers you would like to see listed by default?

**Comment by cubakcabak** [comment]
maybe 3 public dns for initial default option:
- google dns
- opendns
- adguard dns

and custom dns port for opendns (443) and adguard dns (5353)

**Comment by rpeter85** [comment]
Comodo's Secure DNS service: https://www.comodo.com/secure-dns/

**Comment by kar** [comment]
Thanks guys, very helpful.

For future ref: https://www.lifewire.com/free-and-public-dns-servers-2626062

**Comment by szaimen** [comment]
@kar is this already implemented in Blokada v5, too?

**Comment by peterroth** [comment]
@szaimen not yet.
