### ISSUE TITLE
Update translations for v3.0

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#113]
- fetch all ready translations
- update translation fetching script if needed
- test if switching language reloads web screens properly

**Comment by rpeter85** [comment]
HU translation is done.

**Comment by kar** [comment]
- [ ] Check how update_credits should be formatted to be displayed properly
- [ ] Update instructions about credits formatting
- [ ] Update credits for all languages
- [ ] Redownload translations

**Comment by rpeter85** [comment]
Something went wrong, if I try to open something from the menu (like the Help or Get involved) it doesn't show up, shows an error that http://localhost isn't available (which is expected). I turned off Blokada and the issue still happens.
