### ISSUE TITLE
Hosts count seems off when enabled several filters at once

### ISSUE THREAD

**Issue by rpeter85** [blokadaorg/blokada#115]
I downloaded today the unified hosts (contains 55.983 hosts) and the one which blocks fake news, gambling, etc (contains 67.702 hosts).
I merged them, filtering the lines with # and localhost out, furthermore the empty lines:
peter@localhost$ egrep -v "#|localhost" gambling | sed '/^$/d' > hosts
peter@localhost$ egrep -v "#|localhost" unified | sed '/^$/d' >> hosts
I verified and there is really no empty lines in the result (hosts) file. Then I ran a command to list all the unique hosts within the file and count them:
peter@localhost$  awk '{print $2 }' hosts | uniq | wc -l
  123695

Blokada shows that the number of hosts in the blacklist is 68.566 (I have a list with 1011 hosts in addition to the above 2). Is there any criteria which must be met to block the host? Which number of hosts are blocked in this case?

**Comment by kar** [comment]
Just a wild guess, can you try case insensitive duplicates `uniq -i`

**Comment by rpeter85** [comment]
Yep, I just did:
peter@localhost$  awk '{print $2 }' hosts | uniq | wc -l
  123695
peter@localhost$  awk '{print $2 }' hosts | uniq -i | wc -l
  123695

They are identical.

**Comment by kar** [comment]
Just checked this, working as expected. Your method doesn't take into account that `uniq` is only eliminating neighbouring duplicated. 

```
➜ awk '{print $2 }' hosts | wc -l
  123729
➜ awk '{print $2 }' hosts | uniq | wc -l
  123729
➜ awk '{print $2 }' hosts | sort | uniq | wc -l
   67726
```
