### ISSUE TITLE
I want more questions answered in Help screen

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#117]
- [ ] that hosts lists and abp lists like easylist are not the same and they dont work with Blokada

Feel free to add more questions.

**Comment by kar** [comment]
- [ ] How to fully close / restart Blokada (deactivate + turn off keep alive + swipe out from recents)

**Comment by rpeter85** [comment]
How to set Blokada on exception list of battery- or memory optimisation (even it mostly depends on the system)

**Comment by kar** [comment]
To include the "vpn always on" option as a potential solution for when blocking stops...

> When wi-fi switches to cellular or vice-versa, ads were going through Blokada even it was ON and VPN sign was presented. Blokada had keepalive ON and "Online only" OFF. I was "fixing" it by toggling Blokada OFF/ON. I looked closer in VPN setting on my phone and found and an option to set a particular VPN to "Always-on VPN". Since then the problem is gone. After 12 hours of testing and active switching across all kinds of networks, Blokada still cuts all ads like a champ. It's also quite possible that Blokada's keepalive cannot survive battery optimization of Oxygen OS - the same problem affects Telegram. I had to remove Telegram from "battery optimization" option to receive notifications without a delay. However, I didn't try this for Blokada because "Always-on VPN" in the system settings seems to mitigate the problem.

**Comment by rpeter85** [comment]
A more detailed help page article is provided along with a welcome screen page.
