### ISSUE TITLE
I want application ranking and blocking history / activity log

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#121]
This feature request is about adding a blocking history / log with the goal to be able to easily see which domains and apps are accessed / blocked most often and to be able to tell which of then should be blocked or unblocked.

- [ ] A list of recently blocked ad domains, with counters on how many times they were blocked
- [ ] A list of recently accessed domains, with a possibility to block them
- [ ] A ranking of applications with counters how many ads were blocked for them (#55)
- [ ] Be able to see which ads were blocked and when. Have a possibility to filter / sort the list by time / counter / app

The idea is to be able to identify apps which are "the biggest offenders".

**Comment by kar** [comment]
> I truly love this app. However, after 3 days of use, I'm still getting a significant number of ads coming through. It would be really amazing, if, when ads are able to slip through, you could have a switch or checkbox that you could easily engage. It would add the source, and any other  pertinent info necessary to block transmission of those ads, forever.

**Comment by kar** [comment]
> adaway

**Comment by kar** [comment]
> advised

**Comment by kar** [comment]
> For apps wich still display ads an option to record all traffic and list all the connections and hosts might be helpful to find the domain/host adress displaying the ad. Of course finding that particular host showing the ad might still be a piece of work. But I would be able to progressively block the listed addresses until I get the ad domain.

**Comment by kar** [comment]
> This is a must have for me! I love Blokada, but a log of blocked stuff (url, date time, matched list and if possible (root feature?) the app responsible for the request.

**Comment by kar** [comment]
> Would be even better if there was some kind of data visualization in-app. Could be a great way to share what's really happening on a phone over social media.

**Comment by kar** [comment]
> It would be good if you can choose in which apps you want Blokada to work

**Comment by alexanderadam** [comment]
Just to have it on this feature ticket as well:
As [Hosh explained on issue 178](https://github.com/blokadaorg/blokada/issues/178#issuecomment-386793472) it would be very useful to see which rule _of which list_ is blocking something.

**Comment by LewisLebentz** [comment]
Very interested in this too. Just moved from iOS to Android and this is my favourite ad blocker so far, this is the only thing it's missing.

It's very useful to see what domains slipped through (and what was definitely blocked) so you can add it to the blacklist. Notifications are nice, but it's annoying having them on constantly - and just not as easy as seeing a time stamped log file.

The only app I have experience with is AdGuard on iOS (and one other that wasn't as good) and despite being a bit ugly looking, they did do quite a nice job of it.

**Comment by towo** [comment]
Another vote for the log file at least; currently, selectively debugging what to allow and what to reject is pretty difficult.
