### ISSUE TITLE
[Puffin browser] Not blocking ads

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#122]
### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by patrickdrd** [comment]
it cannot block ads in puffin, no adblocker can,
because puffin uses its own server to send you the pages you request
