### ISSUE TITLE
Is there any way to install v3.0 on Android 4.3?

### ISSUE THREAD

**Issue by my-password-is-password** [blokadaorg/blokada#129]
### Steps to reproduce
1.  Install the v3.0 apk

### Expected behaviour

I expected it to install.

### Actual behaviour

![error](https://user-images.githubusercontent.com/6408935/36972633-b5180e78-2024-11e8-85bd-5638d4b5aece.jpg)

### Configuration
1. Blokada v2.2.3

2. Device model
Samsung Galaxy Note 2

3. Android version / ROM
Android 4.3 / Stock

### Questions
1. How long have you been using Blokada? 
I've been using Blokada v2.2.3 since Dec. 2017.

2. How long time ago has the problem started to happen? 
Just tried installing v3.0 a day ago.

3.  How often does this problem happen to you?
Whenever I try installing the newest v3.0.

**Comment by kar** [comment]
Thank you for this report @my-password-is-password. Blokada v3 is Android 5 or up only. 

Refer to changelog: https://blokada.org/api/v3/content/en/changelog.html
