### ISSUE TITLE
Blokada cuts off internet when connected to some routers WiFi

### ISSUE THREAD

**Issue by BlokadaAdBlocker** [blokadaorg/blokada#13]
Netgear Nighthawk
Netgear Genie

http://forum.xda-developers.com/showpost.php?p=70050680&postcount=55

**Comment by blokadaorg** [comment]
Also Netgear N150

**Comment by blokadaorg** [comment]
BLU Life
X2 with Android 6.0.1

**Comment by cdysthe** [comment]
I tried to connect my phone to a bypass account on my Netgear R7000 to avoid the OpenDNS based parental controls. Still didn't work. Could the problem be related to OpenDNS which is the one I use on my home network?

**Comment by blokadaorg** [comment]
@cdysthe I will investigate this by trying to replicate your setup. Are you using OpenDNS Family Shield or OpenDNS Home?
