### ISSUE TITLE
Trying to run downloaded 3.0.0.apk -> Parse error

### ISSUE THREAD

**Issue by OS2User** [blokadaorg/blokada#131]
### Steps to reproduce
1. manually downloaded v3.0.0.apk via blokada.org/#download
2. navigate to downloaded apk in File Manager
3. tap apk

### Expected behaviour
apk should run and update current Blokada to v3.0

### Actual behaviour
after tapping apk -> "Parse error. There was a problem parsing the package."

### Configuration
1. Blokada version
currently 2.2.3
trying to install 3.0 -> parse error

2. Device model
ZTE N9130

3. Android version / ROM
Kitkat 4.4.4

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?
every time I download and try to run v3.0.0.apk

**Comment by my-password-is-password** [comment]
I opened a similiar issue (https://github.com/blokadaorg/blokada/issues/129) and found out Android 4 no longer supported. 

Change log: https://blokada.org/api/v3/content/en/changelog.html

**Comment by OS2User** [comment]
Thank you. That explains it then. How unfortunate that it now is A5+ only.
