### ISSUE TITLE
I want Blokada to optionally store my settings like white- and blacklist on a cloud storage (settings import / export)

### ISSUE THREAD

**Issue by alexanderadam** [blokadaorg/blokada#144]
Something like "Google Auto Backup for Apps" would be neat as it pretty intelligent regarding battery usage and encryption but F-Droid comprehensibly prohibits the closed source components. So maybe a general, not linked approach would be useful.

As you see I have no idea about the details. I like the general idea.

**Comment by patrickdrd** [comment]
one option would be to login with our account and sync all settings,
but I don't know what would happen with possible local files used (in black/white lists),
I suppose they should be uploaded in the sync server,
there's always the simpler option of adding an import/export functionality,
in which settings are imported/exported in local storage

**Comment by alexanderadam** [comment]
IMHO local storage export would _definitely_ be useful as a first step.

I just described the "online export" because this is usually something simple. Think of not-so-techy-users that forget about backups in general. Even _if_ there are _automatic_ exports to local storage, they would probably not backup them from to external sources then.

But I guess it will be complicated to find something that is simple and compatible to F-Droid at the moment.

@kar would it be useful/easier to split this issue up for
1. general exports 
2. make it easy & reliable?

**Comment by kar** [comment]
Yes you're right. I already started to look into it while redoing some persistance codee

**Comment by kar** [comment]
General export functionality to external storage is implemented in 3.5. Further work will be done in the future as new issues.

**Comment by alexanderadam** [comment]
awesome! Thank you!

**Comment by alexanderadam** [comment]
@kar just to clarify this: this isn't implemented yet, right?
Or where could someone find the export?

**Comment by alexanderadam** [comment]
Any news regarding this feature? :thinking:

**Comment by alexanderadam** [comment]
Hi @kar, I'm very sorry for asking (nearly) every year but since you wrote

> General export functionality to external storage is implemented in 3.5

I was never able to find this.
Any advice where someone could find the "general export functionality to external storage"?
