### ISSUE TITLE
I want Samsung-only version

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#146]
Samsung-only adblockers are allowed on Play. It could be beneficial to have a special Blokada version.

**Comment by kar** [comment]
https://forum.xda-developers.com/android/apps-games/app-sabs-simple-adblocker-samsung-t3751722

**Comment by CitizenXVIL** [comment]
Would the Samsung-only version be using Knox or still a local VPN?

**Comment by kar** [comment]
The intention would be to use Knox

**Comment by kar** [comment]
Undoable from Knox 3.4 and Android 10
