### ISSUE TITLE
Google Photos aren't automatically backing up: Waiting for Wi-Fi

### ISSUE THREAD

**Issue by AdnanHodzic** [blokadaorg/blokada#148]
### Steps to reproduce
1. Take photos and open Google Photos app. 

![blokada - waiting for wi-fi - upload](https://user-images.githubusercontent.com/1041579/37699161-75360ef8-2ce6-11e8-8df0-74d2c6a17373.png)

### Expected behaviour

My photos to be automatically uploaded. 

### Actual behaviour

Newly taken photos aren't uploaded automatically (Waiting for Wi-Fi). 

If you want photos uploaded, you'll have to manually select them and upload manually, or stopping Blokada so they get uploaded automatically.

Through research I found out that this problem can sometimes happen while users are connected to VPN. Disabling Blokada uploads my photos just as expected.

### Configuration
1. Blokada version
3.0.0

2. Device model
Google Pixel 2 XL

3. Android version / ROM
8.1.0

### Questions
1. How long have you been using Blokada? 
Few months (<=6)

2. How long time ago has the problem started to happen? 
It's possible this started happening after 8.1.0 upgrade. 

3.  How often does this problem happen to you?
All the time if Blokada is enabled.

**Comment by rpeter85** [comment]
Hey,
Did you set Google Photos on Whitelist? My impression that Blokada blocks the communication with Google.

**Comment by AdnanHodzic** [comment]
Nope, should I just add `photos.google.com` or there's some other specific URL I should add to whitelist?

**Comment by rpeter85** [comment]
Just open the Whitelist, tap on the + sign, tap on APP (that's the default in 3.1) and start typing 'photos', it will pop up. Save the config and check the result, let us know if you still face issues after this.

**Comment by bermeitinger-b** [comment]
This is a drawback of Android. Apparently, it identifies any VPN connection as a non-WiFi connection. This is not only an issue with Google Photos but also any other application that makes a distinction between WiFi and non-WiFi (e.g. Pocketcasts doesn't auto-download).

The only "solution" is to put the specific app to the whitelist, with the disadvantage that this app is then not ad-blocked anymore, I think.

**Comment by tiniwings** [comment]
Hi, This may be the reason Blokada don't update itself when we click 'update' button when there is a new update available. I am adding Blokada to whitelist will check when next update is ready.

@kar @rpeter85 - Can you please look into adding BLOKADA to whitelist by default.

**Comment by kar** [comment]
@tiniwings thanks however that's not the case - Blokada is designed to actually turn itself off before downloading update, however there is a bug in updater that prevents this and for now manual download may be required (but no need to uninstall existing version).

**Comment by AdnanHodzic** [comment]
@rpeter85 that worked perfectly thanks!
