### ISSUE TITLE
In app updater is crashing on some devices

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#149]
### Steps to reproduce
1. Get update notification
2. Try updating
3. Crash

### Expected behaviour

Should start the installer

### Actual behaviour

Crash

### Configuration
1. Blokada version
3.1.1

2. Device model
samsung s6

3. Android version / ROM
7

### Questions
1. How long have you been using Blokada? 
since the dawn of time

2. How long time ago has the problem started to happen? 
since 3.0

3.  How often does this problem happen to you?
every time

**Comment by cyberDrake** [comment]
Same issue here, on an LG g6.

**Comment by hoshsadiq** [comment]
FYI - v3.1.1 is not on GitHub so when I click download update, it fails, plus going on the website to download the APK, it still fails (github 404).

**Comment by kar** [comment]
Thanks for reporting this, my mistake. Fixed. Updater issue is separate though.

**Comment by hoshsadiq** [comment]
Aah, thought it might be related. Thanks for uploading the APK

**Comment by 6Sharky6** [comment]
Same issue on Pixel XL2 - try updating via the app, crashes trying to upgrade to 3.2
