### ISSUE TITLE
Blokada may increase battery drain on some devices

### ISSUE THREAD

**Issue by BlokadaAdBlocker** [blokadaorg/blokada#15]
When on WiFi I experience no battery drain. As soon as I jump on mobile data. I experience a significant battery drain as the app tends to run as a foreground app.

**Comment by iCoerce** [comment]
Using galaxy S7. SM-G930P on sprint to be precise. As stated earlier, not a single bit of battery drain when on WiFi but as soon as I jump on LTE i experience drain.

**Comment by blokadaorg** [comment]
htc 10 + nougat

**Comment by iCoerce** [comment]
I see this says it still needs input. The app runs in the foreground and commands a lot of data when on LTE OR mobile data.

**Comment by buzzboy** [comment]
Receiving zero battery drain with Pixel XL. Stock Nougat 7.1.1

**Comment by blokadaorg** [comment]
Huawei Mate 9 Pro

**Comment by blokadaorg** [comment]
7.1.1 on Nexus 6p
