### ISSUE TITLE
I want to see the number of ads blocked per app basis

### ISSUE THREAD

**Issue by tiniwings** [blokadaorg/blokada#150]
### Steps to reproduce
1.
2.
3.

### Expected behaviour

I want to see the number of ads blocked per app basis. A log with app icon/name and number of ads blocked.
- Can be optional feature with toggle on/off button
- Good to have clear/delete history button so the log won't keep getting bigger.
- Based on stats user can decide is it worth to keep the specific apps installed or not.
- If possible in future user can decide to block Internet access to specific apps.
### Actual behaviour

Apps shows a total number of ads blocked - clicking that icon won't show anything

### Configuration
1. Blokada version
3.1.1

2. Device model
Pixel 2

3. Android version / ROM
8.1

### Questions
1. How long have you been using Blokada? 
~3 Months

2. How long time ago has the problem started to happen? 
NA

3.  How often does this problem happen to you?
NA

**Comment by kar** [comment]
Is it something like #55?

**Comment by tiniwings** [comment]
Yes, sorry for opening new issue. I have searched the issues prior to posting but did't got any results.
