### ISSUE TITLE
I want blocked ads counter to never reset

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#151]
Seems like people actually care about the counter. Make sure it can never reset on updates. Maybe persist in the cloud. Maybe do some gamification around it to engage virality.

**Comment by kar** [comment]
Also improve its formatting depending on locale (with delimiter for thousands etc)

**Comment by rich123** [comment]
+1  Updating to 3.1 via FDroid today reset the counter back to zero.  Please do not reset the counter unless I explicitly request it be reset.

**Comment by patrickdrd** [comment]
how do you "explicitly request it be reset"?

**Comment by kar** [comment]
you can long tap the counter
