### ISSUE TITLE
Google play games doesn't work with default whitelist

### ISSUE THREAD

**Issue by Mygod** [blokadaorg/blokada#156]
### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version
3.1.1

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by rpeter85** [comment]
Hey,
Could you let us know a few example?
Did you try to whitelist those games? Steps to do it: https://blokada.org/api/v3/content/en/help.html#whitelist

**Comment by Mygod** [comment]
Basically every game even including the Play Games app itself. I haven't tried but turning off VPN worked.

**Comment by rpeter85** [comment]
Then please give it a try and let us know the result.

**Comment by Mygod** [comment]
Yep adding Google play games to whitelist fixes everything.
