### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by rpeter85** [blokadaorg/blokada#159]
Blokada uses over 160 MB of RAM during the day (in my case 183 MB, in rare cases more than 250 MB) which makes older devices or devices with less RAM working slow.
The default 'AdzHosts' is enabled with the 'Unified + porn' filter in the blacklist.

### Steps to reproduce
None

### Expected behaviour
Use less RAM.

### Actual behaviour
Uses over 160 MB or RAM

### Configuration
1. Blokada version: 3.1.1

2. Device model
Xiaomi Redmi 4 Prime

3. Android version / ROM
7.1.2

### Questions
1. How long have you been using Blokada? 
Over half a year

2. How long time ago has the problem started to happen? 
Did't check it earlier

3.  How often does this problem happen to you?
Daily

**Comment by rpeter85** [comment]
A user on XDA reported 238 MB memory usage with the Unified list and 10 whitelisted apps. Pixel 2, Oreo 8.1

**Comment by rpeter85** [comment]
Another XDA user: 250 MB RAM, Android 8.1 on Pixel 2 XL

**Comment by kar** [comment]
So after quite a bit of research, the increased memory usage comes from:
- Using a WebView to display welcome/donate dialogs
- Using bigger default hosts list
- Updating Android build environment to newest versions

Steps taken:
- Eliminate eager prefetching of lists, drop inactive lists from memory
- Optimise code related to WebView and dialogs (stage 1)
- Optimise cache logic of lists (significantly faster / less memory use)

Changes seem to have promising effects, although they don't reach v2 memory use levels. No leak has been found as such. More memory optimisation will come in future versions.
