### ISSUE TITLE
I want to see a pause similar to when your device goes offline for when the device sleeps

### ISSUE THREAD

**Issue by animeking9901** [blokadaorg/blokada#164]
This idea could help save battery since shutting keep alive off can result in a loss of blocking on low memory devices. If this could be accomplished even as a donation goal, that would be appreciated

**Comment by kiwiapple87** [comment]
Or even just a pause when screen off feature would be nice.

**Comment by animeking9901** [comment]
Sleep =screen off in most cases

On Apr 13, 2018 10:40 AM, "kiwiapple87" <notifications@github.com> wrote:

Or even just a pause when screen off feature would be nice.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/blokadaorg/blokada/issues/164#issuecomment-381156787>,
or mute the thread
