### ISSUE TITLE
Blokada kills other VPN on connectivity change even when inactive.

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#166]
### Steps to reproduce
1. Have Blokada off
2. Have another VPN app on
3. Switch between data / wifi

### Expected behaviour

Blokada doesn't do anything

### Actual behaviour

Blokada is killing the VPN connection.

**Comment by kar** [comment]
cant' reproduce. anyone?

**Comment by Avizini** [comment]
Coudnt reproduce, android version?
