### ISSUE TITLE
Blacklist can get reset after reboot

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#170]
### Steps to reproduce
1. Activate other-than-default blacklist
2. Reboot
3. Blacklist is reset to defaults

### Expected behaviour

Not reset, preserve persistance

### Configuration
1. Blokada version
3.2.4

2. Device model
OnePlus 5

3. Android version / ROM

I've seen some suspicious 'networking on main thread' error.

**Comment by aussie-damo** [comment]
i had this same problem and fixed it by enabling storage permissions in the app manager

**Comment by kar** [comment]
@esmoak are you able to provide a set of steps that consistently lead to reproducing problems with blacklist? I can't reproduce it.
