### ISSUE TITLE
Default filters come back after I delete them

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#176]
This is simply a result of a recent change to automatically add new lists from the api. If user deletes any of the default lists, it'll come back eventually on next refresh. It was made this way because people complained they don't see new additions - find a better way to solve this.

**Comment by aussie-damo** [comment]
i found if storage wasn't enabled on permissions it wouldn't save any config data for when the app reopened and would set back to defaults on my GS8. hope this helps troubleshooting.
