### ISSUE TITLE
google.com not loading in Samsung Internet Browser

### ISSUE THREAD

**Issue by decal08** [blokadaorg/blokada#179]
### Steps to reproduce
1. Enable Blokada
2. Open Samsung Internet Browser
3. Navigate to google.com

### Expected behaviour

Google page should be displayed

### Actual behaviour

Page does not load, but loading progress bar is displayed

### Other notes:
1. Same behavior either when connected to Wifi or Mobile Data
2. Other webpages is displayed instantly

### Configuration
1. Blokada version
3.2.4 18/04/04 (Official)

2. Device model
Samsung Galaxy S9+

3. Android version / ROM
8.0.0

### Questions
1. How long have you been using Blokada? 
Since V2

2. How long time ago has the problem started to happen? 
Since V3 i think

3.  How often does this problem happen to you?
Always when navigating to google.com

**Comment by kar** [comment]
Anyone could try reproducing this ticket on v2?

**Comment by decal08** [comment]
Reinstalled app directly from website the other day (previously got it from F-Droid), issue not encountered anymore. Under observation.

Enabled Blacklist files:
- AdZhosts
- MoAB
- HpHosts
- Social hosts
- Coin Blocker

Will keep you updated and report after a week of constant usage

**Comment by kar** [comment]
Ok thanks for input. Waiting for the next report.

**Comment by decal08** [comment]
After further tests and constant usage, I have not observed the issue. Google loads fine both on wifi and mobile data, with the previous filters enabled. Issue may now be closed

**Comment by kar** [comment]
Thanks for reporting back.
