### ISSUE TITLE
Recommended AdZHosts blocks AGPS server

### ISSUE THREAD

**Issue by n76** [blokadaorg/blokada#181]
### Steps to reproduce
1. Run Blokada
2. In notifications see that xtrapath1.izatcloud.net was last blocked
3.

### Expected behaviour

Shouldn't see a system required hosting service blocked

### Actual behaviour

xtrapath1.izatcloud.net, xtrapath2.izatcloud.net and xtrapath3.izatcloud.net are blocked.

### Configuration
1. Blokada version
3.2.4

2. Device model
Moto G4 Play (XT1607)

3. Android version / ROM
LineageOS 14.1 (Android 7.1.2)

### Questions
1. How long have you been using Blokada? 
One month

2. How long time ago has the problem started to happen? 
Since began using

3.  How often does this problem happen to you?
Daily

In black list area the first built-in entry is for "AdZHosts (recommended)" which caused me to enable it. However the file from https://adzhosts.fr/hosts/adzhosts-android.txt contains entries blocking xtrapath1.izatcloud.net, xtrapath2.izatcloud.net and xtrapath3.izatcloud.net.

xtrapath1.izatcloud.net, xtrapath2.izatcloud.net and xtrapath3.izatcloud.net are defined by /etc/gps.conf for many phones and are used by the GPS subsystem to provide satellite orbit information to make GPS time to first fix faster. By blocking those servers GPS fix can be dramatically slower (10 or more minutes instead of seconds).

I realize that Blokada does not maintain that list, but having it at the top of the list and marked as recommended will mean that is it likely to be selected and that may cause some issues when using the phone for navigation.

I suggest that the "recommended" be removed from the display for AdZHosts and/or a caution that it might affect your GPS acquisition performance be added.

**Comment by kar** [comment]
Nice catch! I've forwarded it to the creators of AdZHosts and the hosts have been removed from this list.

As for the recommendation, I have a plan to introduce a simple wizard that lets user preconfigure Blokada to his/hers use case, so then there will be no such thing as one recommended default. It's a lower priority task though. #182
