### ISSUE TITLE
I want to help create a hosts file that blocks the device from 'phoning home' to Google

### ISSUE THREAD

**Issue by StarTrekRocks73** [blokadaorg/blokada#190]
Hi everyone,

### The Problem
Android devices are constantly tracking and reporting many things that we do to Google, Facebook, Verizon, etc. They can only report this information if they can communicate with the hosts that receive the reported information. Therefore, if the hosts that they communicate with are blocked, then they cannot report our information. (I am aware that this does not block all forms of tracking, but it blocks a good chunk of it.)

### My Solution
I am interested in helping with creating a hosts file that will prevent android devices from 'phoning home' to Google and other companies. I would also like this hosts file to be an included hosts file under the Blacklist section of the app. 

It is relatively easy to figure out which hosts our android devices connect to in the background. I use a FOSS app from F-Droid called "Net Monitor". After running a network scan for a long time, it shows that my phone connected to *.myvzw.com, *.computer-1.amazonaws.com, and *.1e100.net many times. I only use FOSS apps without Gapps, but I imagine that people who use non FOSS apps with Gapps will have many more connections to many more hosts.

### Steps to Complete

1. Enable blocking hosts using wildcards and IPv4/IPv6 addresses. Issue #188 
2. Have multiple people with different phone carriers, app configurations, and Gapps statuses run "Net Monitor" and post their most commonly connected to hosts to GitHub.
3. Confirm that all of the user contributed hosts are valid.
4. Add contributed hosts to a hosts file.
5. Add hosts file to Blokada.

### How to Find the Hosts Your Phone Connects To:
1. Download the app called "Net Monitor" from F-Droid (Maybe Google Play)
2. Open app and run it in the background in the following circumstances:
    - For a few hours/overnight while your phone is connected to the internet and sleeping
    - For a few hours while you are using your phone normally (playing games, browsing the internet, etc.)
    - While making or receiving a phone call, SMS, MMS.
    - While using Facebook
    - Any other configurations that you thing are worthwhile.
3. Post your results (you can select which ones you want to post) to GitHub. If possible, please categorize them by the circumstances in which they occurred.

**Comment by DJJosephJumper** [comment]
I think this is an awesome idea. Would it work best to make a new repo where all the hosts can be put together? I'm looking to get some experience contributing to open-source and would be happy to make one. :grin:

**Comment by StarTrekRocks73** [comment]
I'm happy to hear that other people are also interested in making this hosts list. I think that I will make a repo for this host list and I can add you to it. Should it be under the GNU GPL 3.0 license?

**Comment by StarTrekRocks73** [comment]
This is the link to the repository that I made for the hosts list. The repository is under the GNU GPL-3.0 license. Is it OK that I used the word 'blokada' in the repository name? I can change it if needed.

[https://github.com/StarTrekRocks73/blokada-background-hosts](https://github.com/StarTrekRocks73/blokada-background-hosts)

**Comment by StarTrekRocks73** [comment]
@DJJosephJumper

Hi. I made a repository that we can use to make a host file. I invited you to it. Can you join it? https://github.com/StarTrekRocks73/blokada-background-hosts

**Comment by DJJosephJumper** [comment]
Yes, sorry, I wasn't able to get back on my computer earlier. 👍

**Comment by StarTrekRocks73** [comment]
@kar Thanks! Ill let you know when it is ready.

**Comment by Herbstfreud** [comment]
Is there a way to start net monitor app earlier. My only possibility right now is to start the app right after the home screen appears. I can imagine that some communication to Google takes place earlier at booting, too...

**Comment by DJJosephJumper** [comment]
@Herbstfreud You may be able to use an app like Tasker (or another automation app) to open Net Monitor on system boot.

**Comment by StarTrekRocks73** [comment]
@Herbstfreud @DJJosephJumper I agree with both of you. I think that we should research an effective way to figure out the communications. Although, if Google does communicate during boot, then Blokada couldn't do anything to prevent it.

**Comment by Herbstfreud** [comment]
@StarTrekRocks73 I have no idea what is the earliest point an app like Blokada can start and work. But maybe it is possible to start the app earlier on a rooted device? Again, I have no idea about this, but it could be useful if an earlier start were possible...

**Comment by noelkra** [comment]
You could try to activate the airplane mode of your phone and deactivate it after your phone has started so it has to send the data when you are connected to the Internet and therefore with netmonitor...

**Comment by StarTrekRocks73** [comment]
@noelkra That could work, but I have a feeling that airplane mode activates after bootup. I don't know how to test it. Does anyone have advice?

**Comment by kar** [comment]
dis dead
