### ISSUE TITLE
I want Blokada to be compatible with uBlock style block lists

### ISSUE THREAD

**Issue by StarTrekRocks73** [blokadaorg/blokada#193]
Hi everyone,

### The Problem
I think that Blokada should be compatible with uBlock style block lists.
#### My Reasons
1. Increases cross-compatibility
2. Would allow/require Blokada to work with wild cards '\*' (Issue #188 )
3. Makes it easier to incorporate 3rd-party blocking lists that already exist
4. Allows users to add specialized 3rd-party blocking lists that they are already familiar with (they might use the same list on their browser) such as the Fake News list or anti-tracking lists.

### My Solution
Modify the Blacklist section of the app to allow importing uBlock lists instead of just hosts lists.
#### Pitfall 1: uBlock lists also block page elements
 Have Blokada ignore lines that block page elements

### Notes
If there is some technical limitation that prevents this from working or already happening, please tell me.

Sincerely,
StarTrekRocks73

**Comment by kar** [comment]
Mainly the reason I haven't done it is your pitfall 1. I'm afraid a significant portion of those lists will be ignored, so their effect may be suboptimal, and confusing to users.

**Comment by giogziro95** [comment]
@kar, how about adding another tab besides _HOST_ to allow more advanced syntax, like wildcards and regex (perhaps when the entry is enclosed with two slashes, like in ABP-compatible lists)?
