### ISSUE TITLE
I want the name of the 'Chip in' page to be changed due to confusion

### ISSUE THREAD

**Issue by StarTrekRocks73** [blokadaorg/blokada#194]
Hi everyone,

### Confusion about the 'Chip in' page name

I recommend changing the name of the 'Chip in' section. I feel like it sounds too much like donating money. I think that its name should explain that the page is about voting for new features. Maybe something on the lines of "Vote for New Features" would be better.

I think that changing it would help us get new feedback regarding new features.

Sincerely,
StarTrekRocks73

**Comment by rpeter85** [comment]
Enter the Game, Let us know, Your opinion

**Comment by kar** [comment]
It needs to me short, and its not only about getting user opinion. It's a generic call to action section, which could be used, for example, for asking users to share blokada on social media.
