### ISSUE TITLE
Blokada is using a lot of background data even when background data is disabled for the app

### ISSUE THREAD

**Issue by bjwessels** [blokadaorg/blokada#195]
### Steps to reproduce
1. I just have blokada running
2. Background data for blokada has been turned off on android
3.

### Expected behaviour

No Background data should be used - I checked and every day I see
This started to happen on the 21st April. It uses between 2-6 Mb of background data
I think this has only started when I upgraded recently  

### Actual behaviour
No background data should be used 

### Configuration
1. Blokada version 3.3

Keep alive is on
start on boot is on
online only is on

2. Device model
Moto E4

3. Android version / ROM
Android 7.1.1

### Questions
1. How long have you been using Blokada? 
Several months

2. How long time ago has the problem started to happen? 
The 21st April

3.  How often does this problem happen to you?
Every day there is background usage 2 to 6 Mb a day
![screenshot_20180423-124736](https://user-images.githubusercontent.com/3920936/39141109-b8a0af36-46f4-11e8-8f68-d2ba24dcbe00.png)

**Comment by kar** [comment]
Can anyone link to an authoritative definition of "background data" in Android? I can't guess what it's counting, but basically data usage in Blokada is currently:

- Fetching filter configuration / defaults from blokada.org (tiny amount of text, roughly rechecked once a day)
- Fetching actual filters (much more text, depending on your filters choice), fetched roughly once a day  - this changed recently. used to be once a week, but people were unhappy they don't get newest filters. Also your actions (changing filter config) will cause refetch so it may add up - but this probably won't count as background data
- ACRA crash reports - sent only if you explicitly accept it (a dialog shows up after crash)

**Comment by bjwessels** [comment]
Just to clarify - I checked the usage history and it's once a day and about 3 Megs. Today (23/4/2018) there were 2 times each of 3 Meg. Going back further I see it was using a tiny amount < 0.1 Meg if at all.

I have a limited data plan

**Comment by kar** [comment]
which lists do you use?

**Comment by kar** [comment]
Thanks. Also may be related, there's a feature request to provide control over how often lists are refreshed, this could help your case.

**Comment by bjwessels** [comment]
Ok so using the default list AdZhost only and keep alive = on , online only = on
All times EST 
27/04/18 = 8am - 1.75b Mb 11am - 1.78Mb  3pm - 1.78,  total = 5.32 Mb of background data
26/04/18 = 8am - 1.78 Mb
25/04/18 = 8am - 1.78 Mb

So I go to work at between 8 and 9 am so that is when it switches from Wifi to Mobile data. The 27/04/18 I was out of the office a few times and it would of switched from wifi to mobile data...

The background data has been disable for the app

If I go back and look at the data for the previous version I only see tiny amounts of backgroud data.

I'm going to install the previous version - if you need more info let me know

**Comment by patrickdrd** [comment]
maybe this is related to mobile radio active I'm experiencing?

**Comment by kar** [comment]
What do you mean @patrickdrd ?

In general, I think the data usage is normal, it depends on which lists you select. They're refreshed once a day, which is way more often compared to older versions (once a week). Probably that's why you're seeing this difference. That said, it'd be good to have some configurability around this. However, that's #43.

**Comment by bjwessels** [comment]
I still think the app should respect the "restrict background usage" setting. I don't care how mych data it uses on wifi. I only have a 100 Mb plan so 2 Mb per day will eat it up.

**Comment by rpeter85** [comment]
@bjwessels I don't get your point. If you set something on the system level (lower level), how could the app (which is on the higher level) overwrite it? It simply can't.
And the "background usage" is the one that happens when the screen is off, the phone is in doze, so when you not actively use it, that isn't restricting an application to transfer data when you use the device. What you really need is the ticket #43
