### ISSUE TITLE
I want people to list the DNS servers that they want in Blokada

### ISSUE THREAD

**Issue by MatthewR37** [blokadaorg/blokada#197]
Hi everyone,

I have some suggestions regarding DNS servers.

### Suggestions
1. People can enter DNS servers that they think should be added in the comments. Before entering a server, please ensure that they respect user privacy (AKA: Not Google)
2. Add a privacy notice in the DNS selection page that lets people know that Google and other DNS servers on the list are harvesting data through their servers.
3. Maybe add a notice explaining that changing your DNS can partially protect you from being affected by Net Neutrality blocking.
4. Mybe remove DNS servers from the DNS list that do not respect user privacy.

**Comment by StarTrekRocks73** [comment]
https://servers.opennic.org
Please add these hosts (I think that they are the fastest):
Northeast US: 128.52.130.209, 198.199.84.126
Southern US: 198.206.14.241, 162.248.241.94
Western US: 198.206.14.241, 45.32.160.206

Also, somebody in the Insiders channel mentioned that these DNS servers are good:
https://forum.xda-developers.com/android/software-hacking/keweon-privacy-online-security-t3681139
I chose the use the New Jersey and Texas servers.

**Comment by StarTrekRocks73** [comment]
### Suggestions 2
- Reorder the DNS servers so that the private, secure ones are at the top.

**Comment by kar** [comment]
Nice. Please provide a better description for servers you think we should change description for, as well as suggested ordering.

**Comment by StarTrekRocks73** [comment]
OpenNIC preserves Net Neutralityand prevents censorship. The IPs that I listed have a no logging policy and the first one has DNS crypt support. The Keweon is a dns that does the following:
This word comes form the germany words "KEine WErbung ONline" which means translated to english "no advertising online".
In the meantime keweon is more than a stupid Adblock System:

    - Advertising Blocking
    - Privacy Protection
    - App Protection
    - Malware Protection
    - Popup Blocker
    - Privacy Protection
    - Ransomware Protection
    - Spyware Protection
    - Tracing Protection
    - Tracking Protection
    - Virus Protection
    - Faster Internet
    - Lower Bandwith usage on Mobile Phones
    - Fake Software Filter
    - Fake Online Shop Filter
    - Phishing Protection
    - and a lot of other things

Someone in the insider channel posted a bunch of Keweon IPs.

**Comment by StarTrekRocks73** [comment]
Also, please put the DNS servers that have logs and dont support privacy on the bottom of the page with a privacy warning.

**Comment by kar** [comment]
Thanks. Please provide suggested ordering.

**Comment by StarTrekRocks73** [comment]
@kar The new DNS providers that I want to add have many IP addresses located throughout the world. How should I choose the IP addresses?

 I was thinking maybe 1 DNS pair for each half of the US (East West) for each DNS provider (4 Total options). The upside to this is that the user has more choices. The downsides to this method is that the user needs to scroll through extra options.

Should I also make international support?

**Comment by kar** [comment]
Good question. I think what you describe is fine as the first approach, later on we can expand Blokada it to make it better. Yes please include the international servers too.

**Comment by rpeter85** [comment]
I took a look on this request.
1.) OpenNIC DNS servers are added
2.) the other things are very hard to track with changing regulations and policies

If there are no further requests or lists to do, I want to go ahead and set it to closed.

**Comment by rpeter85** [comment]
User request:
OpenDNS Family Shield
Preconfigured to block adult content
208.67.222.123; 208.67.220.123

OpenDNS Test
https://welcome.opendns.com/

**Comment by peterroth** [comment]
This issue won't track the requests anymore, closing it.
