### ISSUE TITLE
[HTC One E9 Plus Dual Sim] App only report domain that blacklisted, but it doesn't blocked

### ISSUE THREAD

**Issue by kowith337** [blokadaorg/blokada#200]
### Steps to reproduce
**Note**: Mobile carrier that collaborate with Facebook to allow access "Free Basics" service is needed.
1. Install Blokada and wait until blacklist, whitelist and DNS preloaded.
2. Try add these domains
   - `h.facebook.com`
   - `mobile.facebook.com`
3. Use any Facebook wrapper app or try navigate to `mbasic.facebook.com` (login needed) with your mobile browser, make sure you're connect to cellular data.
   - If the site have suggest to use "Free Basics", decline it.

### Expected behaviour
- Have notifications or keep-alive notification report that it's blocked those domains
- A redirect attempt that navigate to `h.facebook.com` and then `mobile.facebok.com` should be blocked, then show navigation error.

### Actual behaviour
- Notifications reported those domain blocked
- In fact, redirection doesn't blocked.

### Configuration
1. Blokada version
    3.3 F-Droid

2. Device model
    HTC One E9 Plus Dual Sim (a55ml_dtul / mt6795)

3. Android version / ROM
    Lollipop 5.0.2 + SenseUI 7.0 (Stock)

### Questions
1. How long have you been using Blokada? 
   - I've setup this app for my parent's phone (Nokia 6 + Android 8) about 2-3 months ago, to prevent some ads that auto subscribe SMS or WAP push contents without any confirmations that experienced last year
 and seems like it does the job
   - But for my device, it's just a fresh install

2. How long time ago has the problem started to happen? 
   - I've testing around 3 days before report this issue

3.  How often does this problem happen to you?
   - From Qestions 2, try force stop, then clear data and start over again, still got same issue.

**Comment by kar** [comment]
Can you reliably reproduce this issue after

a) cleaning up app data for Blokada and the app you are testing
b) setting up Blokada with hosts mentioned (make sure you go back to home screen after adding the hosts, and you should see the hosts counter increase by 2)
c) rebooting your phone

**Comment by kowith337** [comment]
I've follow you step and seems like it's work, but I think I could have manually reboot in order to make a change apply, I'm expected this might be work when setup as first time without rebooting or something...
