### ISSUE TITLE
questions about usage

### ISSUE THREAD

**Issue by patrickdrd** [blokadaorg/blokada#202]
I notice mobile radio active is increasing over time,
why is that? is it normal?
does it need an internet connection in order to operate?

maybe it's better if I create my own blacklist file and use this one only (no external sources)?
of course I would have to update it myself, obviously,
but would any changes to the file be reflected in blokada app?
maybe each time it reloads?

**Comment by kar** [comment]
I don't understand the questions. Also, please ask questions at go.blokada.org/chat or other social media, this place is for bug reports (that should follow the template unless self explanatory), and feature requests.
