### ISSUE TITLE
random persistent crashes 

### ISSUE THREAD

**Issue by ScottMccay** [blokadaorg/blokada#203]
blokada 3.3 perstantly crashes when starting and while running  

### Steps to reproduce
1.start the app
2.
3.

### Expected behaviour

the app runs

### Actual behaviour

it crashes

### Configuration
1. Blokada version
3.3

2. Device model
?

3. Android version / ROM
lollipop and marshmallow 

### Questions
1. How long have you been using Blokada? 
?

2. How long time ago has the problem started to happen? 
started with 3.3

3.  How often does this problem happen to you?
repeatedly alot

**Comment by kar** [comment]
What comment did you put when you sent the report? I'll have a look at it.

**Comment by sterno1966** [comment]
i had to go back to 3..2

**Comment by sterno1966** [comment]
i just put that it crashed when i opened it

**Comment by sterno1966** [comment]
it does it on nougat to
