### ISSUE TITLE
Whitelists/Blacklists misbehave, lack persistence when android battery saving features enabled

### ISSUE THREAD

**Issue by Alex1238** [blokadaorg/blokada#207]
### Steps to reproduce
1. Settings > device > battery > battery optimisation > options > advanced optimisation (enable) THEN battery optimisation > Blokada > don't optimise (enable)
*OR*
Settings > advanced > recent app management > deep clear (enabled), THEN 'lock' blokada from being closed when closing recent apps (small padlock icon on top right of each app in recent apps screen)
(*OR* both)
2. Open blokada, make any/various changes* to whitelists or blacklists, refresh filters, 'save' hosts links etc 
3. Force close blokada after making changes to whitelist/blacklist, reopen blokada.

*It seems to be random, I can find no specific procedure that will consistently induce this, sometimes I can be making changes for a minute or two, sometimes it happens after the very first whitelist deleted or hostfile saved

### Expected behaviour
Whitelist and blacklist should be saved and persist after force close regardless of battery optimisation options.

Following the steps above includes whitelisting blokada against the effects of the battery saving options so theoretically blokada should not be affected at all and behave the same as it does without either optimisation enabled (which is perfectly).  

### Actual behaviour
Adding/removing apps to whitelist is very slow, after clicking 'save' the app doesn't appear in the list for a while, and changes do not persist when force-closing then reopening blokada. 

After clicking on a particular hosts file and clicking 'save', the name of the hosts would change (e.g. change from "AdZHosts (recommended)" to "A link from https://adzhosts.fr/...") and the 'open hosts link in browser' button disappears.  Sometime later (hours) the button can reappear but when pressed always causes blokada to crash. After a crash blokada behaves normally for a short time.

Note: The core functionality of blokada i.e. blocking of hosts already loaded (and whitelisting apps already saved) works just fine, so if I configure blokada as needed and then enable the optimisations blokada works just fine until I need to update a hosts file or add an app to whitelist.

### Configuration
1. Blokada version
This has happened in v3.0, v3.2, v3.3 and v3.4 

2. Device model
Oneplus 5 

3. Android version / ROM
Android 8.1.0 / OxygenOS 5.1.1

### Questions
1. How long have you been using Blokada? 
Since March 2018

2. How long time ago has the problem started to happen? 
Initially I setup blokada and left it, its so straightforward there's not much to do, I didn't need to make any continual changes so I didn't notice anything.  I only noticed the problem a few weeks later when I became a blokada insider and started testing all the different functions.

3.  How often does this problem happen to you?
Every time I enable either of the battery optimisations and start changing blacklist/whitelist configurations.

**Comment by rpeter85** [comment]
Blokada should be exclided in battery- and memory saver apps. The blocker doesn't drain battery, those apps just cause different misbehaviours.

**Comment by Alex1238** [comment]
Blokada is excluded. These are not battery saver apps but inbuilt features of the OS. I know Blokada doesn't drain which why I have it excluded but I want to enable the features to cutail drain of other apps.
