### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by waqasanwar94** [blokadaorg/blokada#208]
Hello, @blokadaorgI want to contribute in "blokada" so i want to design a new logo for "blokada" and it's free.

I hope you like it. If you like it, I will send you to pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

Contact me on facebook for fast delivery 
https://www.facebook.com/waqasanwar68

**Comment by kar** [comment]
@waqasanwar94 thanks! We'd like to see your proposition.

**Comment by waqasanwar94** [comment]
Hi @kar  Thank you for accepting my proposal i will send you logo soon

**Comment by blubbsy** [comment]
Why not having it as an open discussion here on git? At the end Kar can decide on it's own

**Comment by waqasanwar94** [comment]
![112](https://user-images.githubusercontent.com/38813945/40105072-5cefba00-590b-11e8-992c-1a626f3b44a8.png)

Hi Sir here are some logos which i make for you please have a look and let me know if there are need to change anything or which number logo you are like

**Comment by TacoTheDank** [comment]
@waqasanwar94 *sigh* dude stop claiming these as your own (AS ONES YOU "MADE") and credit the actual creators for once; you get these all from Flaticons.com, any simple reverse Google image search can show that

I abhor people like you who take other people's creations and pass them off as their own

**Comment by TacoTheDank** [comment]
i like the blokada logo as well

**Comment by RandintN** [comment]
Hello guys, today I saw this topic about Blokada's Logo, and I've made [one try](https://drive.google.com/open?id=1qikfc4WT25M0Ol-pUR0auQ5aJG4GTXEU) and also found a Typeface that could be awesome for Blokada's name, the [Exodus Striped](https://www.behance.net/gallery/32070837/Exodus-Free-Typeface) and I can improve the logo even further if the feedback is good.
