### ISSUE TITLE
Power button and logo icons keep on rotating after tapping multiple times

### ISSUE THREAD

**Issue by RandomGuyJCI** [blokadaorg/blokada#210]
### Steps to reproduce
1. Open the Blokada app
2. Tap on the orange button on any menu on the bottom middle or the blokada logo on the top right very fast

### Expected behaviour

The icons should normally rotate a little, then go back to normal

### Actual behaviour

It would stay in the tilted rotation

### Configuration
1. Blokada version
3.4 Official

2. Device model
Samsung Galaxy J5 (SM-J500H)

3. Android version / ROM
Android Lollipop (5.1.1)

### Questions
1. How long have you been using Blokada? 
More than 3 months

2. How long time ago has the problem started to happen? 
Since installation

3.  How often does this problem happen to you?
Every time I reproduce the problem

**Comment by kar** [comment]
#173
