### ISSUE TITLE
I want Cloudflare's DNS (1.1.1.1 and 1.0.0.1) added as a default DNS option

### ISSUE THREAD

**Issue by RandomGuyJCI** [blokadaorg/blokada#211]
The title is pretty self-explanatory

**Comment by rpeter85** [comment]
It's a very bad idea. Not everybody want to use the Cloudflare DNS. Which fits for one, doesn't fit for the others.
In my case, I don't use any 3rd party DNS services, I go with the ones that my ISP provides.

**Comment by kar** [comment]
Cloudflare is among the default DNS options. I don't think most users wants to have it selected by default though.
