### ISSUE TITLE
"Share log" is not working properly.

### ISSUE THREAD

**Issue by Xeeshuu** [blokadaorg/blokada#212]
### Steps to reproduce
1.Install the app from f droid and open it. 
2.Then click on 3 dots mentioned on the top right corner of the app. 
3.Here appears some option, one of then is "Share log" ,click on it to reproduce the bug. 

### Expected behaviour
 After downloading the app from f droid. And i then started working in it. I saw a "share log" option, i clicked on it to share the log. It was expected

### Actual behaviour
 When i clicked on "share log" option, it shows some error or blockada report. 
Like that it is not working.

### Configuration
1. Blokada version
3.4.100500

2. Device model
Oppo a37f

3. Android version / ROM
5.1.1

**Comment by rpeter85** [comment]
Could you share what is the error message you got when you tried to share the log? Without that it's impossible to tell what is the issue and what causes that.

**Comment by Xeeshuu** [comment]
I will send you the screenshot what it shows.

**Comment by Xeeshuu** [comment]
Look at this?

**Comment by rpeter85** [comment]
Nothing attached, can't see the screenshot.

**Comment by Xeeshuu** [comment]
Is this one visible?

**Comment by rpeter85** [comment]
Still no. Use the web UI or an app to attach a screenshot, I think you can't use email for this.

**Comment by Xeeshuu** [comment]
For which i had to use email?

**Comment by rpeter85** [comment]
I mean you can't attach a screenshot via email. Use an app or the webui.

**Comment by Xeeshuu** [comment]
![Screenshot_2018-05-18-16-31-10-21.png](https://steemitimages.com/DQmTmumsFHwbcZcMjUvm8oFzCSknL2XyWmdNufCJLxXnj6Q/Screenshot_2018-05-18-16-31-10-21.png)

**Comment by Xeeshuu** [comment]
This is the screenshot which it shows.

**Comment by rpeter85** [comment]
It isn't an issue, what you see is expected.

**Comment by Xeeshuu** [comment]
How it is expected, 
I expect that i must be able to share log.

**Comment by rpeter85** [comment]
The log is generated in the background and uploaded for analysis. What you can type in is additional information to reproduce the issue.

**Comment by rpeter85** [comment]
Can you just join to our Telegram chat to discuss it? That's easier as tracking this github ticket. http://go.blokada.org/chat :)

**Comment by Xeeshuu** [comment]
So this is not an issue
Right?

**Comment by rpeter85** [comment]
Exactly.

**Comment by Xeeshuu** [comment]
Ok thanku for you convenience.
