### ISSUE TITLE
Blokada restarting if disconnected from the Notifaction

### ISSUE THREAD

**Issue by sathish804** [blokadaorg/blokada#213]
### Steps to reproduce
1. Open Blokada Notification from Notification bar
2. Select Disconnect option.

### Expected behavior
As per expected behavior, Blokada has to disconnect.

### Actual behaviour
Blokada getting re-activated automatically.

### Configuration
1. Blokada version
3.4

2. Device model
S7 Edge

3. Android version / ROM
Android 7

### Questions
1. How long have you been using Blokada? 
Last 4 days

2. How long time ago has the problem started to happen? 
From yesterday

3.  How often does this problem happen to you?
Always when I tried to disconnect from the Notification.

Thanks and Regards,
Sathish.
[t_video6048624763901838187.zip](https://github.com/blokadaorg/blokada/files/2016758/t_video6048624763901838187.zip)

![photo6048624764358077938](https://user-images.githubusercontent.com/14090242/40233882-f9476fe8-5aa4-11e8-8ed2-b7e90bd3ab69.jpg)

**Comment by kar** [comment]
Blokada is quite aggressive to keep the VPN on purpose, there's tons of reasons to temporarily loose VPN tunnel in Android. So in order to turn it off you have to deactivate it in app, not in system UI. Otherwise it'll try to reconnect. That's by design.
