### ISSUE TITLE
I want to see what applications are blocking which requests.

### ISSUE THREAD

**Issue by virtadpt** [blokadaorg/blokada#215]
Since I started running Blokada on my Samsung phone, I've noticed the number of blocked access requests steadily climbing (3411 since the last time I reset the counter).  What I want to do, however, is be able to look at what applications Blokada is preventing from phoning home and where they are trying to contact.  In this way, I can better assess my threat model and I can, depending on how egregious an application is acting, decide whether or not to uninstall the offending application entirely.

For example,

* FooDice
  * et.phone.home.com
  * legit.business.syndicate.ru
* FooVideo
  * bavaria.illuminati.gov
* FooSearch
  * seeker.nsa.gov
  * homer.kgb.ru

**Comment by rpeter85** [comment]
Isn't it similar to #121?

**Comment by virtadpt** [comment]
It is - somehow I missed that in my searches.  Thank you!
