### ISSUE TITLE
Blokada prevents automatic SMS backup

### ISSUE THREAD

**Issue by Portaleus** [blokadaorg/blokada#218]
Hello,

Blokada prevents the automatic sms backup (usually during the night, device plugged and on wifi). Working fine when I turn off Blokada before sleep. 

- others backups are fine (data, photo, settings)
- forcing a backup through ADB is ok
- Messages app is whitelisted (and almost all google services)

### Steps to reproduce
1. Wait for automatic backup on settings
2. SMS backup not working

### Expected behaviour
SMS need to backup in Google Drive along the others categories (app data, settings)

### Configuration
1. Blokada version : last
2. Device model : Pixel XL 2
3. Android version / ROM : stock, no root

**Comment by rpeter85** [comment]
@Portaleus may I ask if you face the same issue with Blokada 4.2? If you do, did you find a way to overcome this difficulty? Which app or which hosts had to be bypassed to make the SMS backup working?

**Comment by Portaleus** [comment]
Hi @rpeter85,
I did not have this is issue since I'm on Android 10 beta. Currently using blokada 4.2 with default hosts.
Regards,

**Comment by rpeter85** [comment]
Thanks for the info, I set this report to closed, feed free to message us if you run into the same issue.
