### ISSUE TITLE
Can't whitelist ACN Companion app

### ISSUE THREAD

**Issue by w4tadrag** [blokadaorg/blokada#219]
1. I tried going to the whitelist page to whitelist this app, it doesn't show up, I also tried com.acndps.voip still doesn't show up. 

Please make it easier to whitelist apps

This is the app: https://play.google.com/store/apps/details?id=com.acndps.voip&hl=en

### Expected behaviour
app supposed to show up to whitelist

### Actual behaviour
app doesn't show up on the list to whitelist

### Configuration
1. Blokada version
3.4.1

2. Device model
Oneplus 6

3. Android version / ROM
8.1.1

**Comment by rpeter85** [comment]
hi,
did you just install the app? Did you restart your phone after you installed the app that you can't whitelist? There's a known issue that Blokada doesn't recognize newly installed apps.

**Comment by w4tadrag** [comment]
Thank you, the restart did the trick 😊
