### ISSUE TITLE
Blokada blocking amp pages

### ISSUE THREAD

**Issue by hanesh** [blokadaorg/blokada#220]
Seems to have been fixed about 2 days after I posted..

**Comment by hanesh** [comment]
I.e. https://cdn.ampproject.org/v/s/amp.cnn.com/cnn/2018/06/11/entertainment/robert-de-niro-trump-tonys/index.html?amp_js_v=a1&amp_gsa=1#amp_tf=From%20%251%24s

**Comment by kar** [comment]
Can't reproduce. Please use issue template to provide more details.

**Comment by rpeter85** [comment]
No further info provided.
