### ISSUE TITLE
Blokada crashes other apps even on whitelist

### ISSUE THREAD

**Issue by fawzib** [blokadaorg/blokada#223]
Application: http://store.embratoria.com/Embratoria-G7.apk

This app crashes every time blockada is active. whitelisting the above listed app doesn't help. If I disable blockada then the above application will work.

**Comment by rpeter85** [comment]
Could you please let us know what that app does, exactly? Do you know if that app also generates a VPN connection?

**Comment by fawzib** [comment]
It is an iptv application. It doesn't create any vpn since I don't see any sign at the top. Please let me know what other information you need to be more helpful.

**Comment by noelkra** [comment]
Hello fawzib

Is it still crashing? If it does, could you tell me what OS you are using?

Kind Regards

Noël Kra

P.S.: Please use our [issue template](https://github.com/blokadaorg/blokada/blob/master/docs/issue_template.md) in the future. It helps us to reproduce your problem faster!

**Comment by rpeter85** [comment]
No further info provided.

**Comment by fawzib** [comment]
i updated to the latest version and this problem still persist. i have to disable blockada every time i want to open the app listed above.

**Comment by rpeter85** [comment]
Can it be that the app doesn't start up if you have an adblocker, or if the device is connected to a VPN?

**Comment by fawzib** [comment]
i checked today and i can say for sure that the app in question just crashes when vpn is detected. i believe this is crucial for blockada to function. thanks for all your help!
