### ISSUE TITLE
Several domains not counted/blacklisted

### ISSUE THREAD

**Issue by Laicure** [blokadaorg/blokada#226]
### Steps to reproduce
1. Remove all whitelist (then turn it off) (+ Default DNS) then Link [hosts.txt](https://github.com/blokadaorg/blokada/files/2159825/hosts.txt)
2.  Check the hosts count
3. There are some missing domains/not counted
(Can't check for the actual list of those missing domains though)
-- Errors encountered? None.

### Expected behaviour

The hosts file attached is generated from my [repo](https://github.com/Laicure/HostsY) and counted 81,025 as attached.
But Blokada only counts 81,001.
Are there any hard-coded whitelist inside Blokada?

### Actual behaviour

Should show 81,025 domains instead of 81,001

### Configuration
1. v3.5
2. Xperia XZ2, H8266
3. Stock Oreo 8.0.0

### Questions
1. How long have you been using Blokada? 
About a month.

2. How long time ago has the problem started to happen? 
Since installation. I did re-installed and did a Factory Reset too.

3.  How often does this problem happen to you?
Always.

**Comment by Laicure** [comment]
Again, this is sh*t you know. Is there a hidden whitelist?
I just updated my custom hosts file just now (I often update so the counts below will get outdated).



### Steps to reproduce
1. Upload custom hosts file somewhere (in my case, [Bitbucket](https://bitbucket.org/Laicure/publicview/downloads/hosts))
2. Use hosts file in blokada and nothing else, no whitelist and no other blacklist
3. Advance Settings > Download Lists Now


### Expected behaviour
- Blokada should show 142,346 hosts


### Actual behaviour
- Blokada only showing 142,271


### Configuration
1. Blokada version
- v3.6 (101900)

2. Device model
- Xperia XZ2 H8266

3. Android version / ROM
- Android 9 Pie, stock/unmodified/not rooted

### Questions
1. How long have you been using Blokada? 
- 2 months

2. How long time ago has the problem started to happen? 
- Always

3.  How often does this problem happen to you?
- Always

**Comment by Laicure** [comment]
Oh hey, calm down.

I asked this a long time ago, and different issues were answered but not mine.

Also, I'm not referring to the dev or the app being sh*t.
I'm frustrated why and why it doesn't count everything. Even before.

And you, even closed this without even answering the issue.

Note that I remove dups on my list.
And chill, man. I'm just a user wondering why it is like that and thinking there might be hardcoded whitelist.

**Comment by animeking9901** [comment]
I closed the issue cause you came off disrespecrful on the whole concept kf a hidden list,and if you clean duplicates ill reopen so maybe we can figure it out

**Comment by kar** [comment]
There is no whitelist. There is de-duping and sanitising for each entries in the list happening during import. Something must be dropped then, but we are not sure why. Maybe at some point we'll add an import log so you can see what was dropped, for now there are more important issues.

**Comment by Laicure** [comment]
> I closed the issue cause you came off disrespecrful on the whole concept kf a hidden list,and if you clean duplicates ill reopen so maybe we can figure it out

I'm really sorry about that. Nothing against you or the dev/app.



> There is no hidden whitelist. There is de-duping and sanitising for each entries in the list happening during import. Something must be dropped then, but we are not sure why. Maybe at some point we'll add an import log so you can see what was dropped, for now there are more important issues.

Ok, thanks for the reply. I will recheck my list. I used an [app](https://dev.azure.com/Laicure/OpenSource/_git/HostsY) for the generation for that one. It seems that it's the app's fault if it has dups.
And thanks in advance, it will be great to have an import logs.

I will close this one then.
Thanks and apologies.
