### ISSUE TITLE
I want WireGuard support

### ISSUE THREAD

**Issue by iamrohanbro** [blokadaorg/blokada#227]
Dev, I've noticed the recent hype for an actual VPN integration into blokada & that's why making this request.
Please consider adding wireguard support, I've recently gone through the VPN round 2 vote and noticed that you may be interested in adding wireguard support.
Previously I used orbot & blokada, but nowadays I use wireguard & blokada owing to the fact that wireguard is much more simple, fast & easy to audit. There's absolutely no point in adding open VPN now that something as advanced as wireguard is available and most android custom kernels has native wireguard support. WireGuard has more than 10 times lesser codes than most common VPN services.
![wireguard-vpn-1024x767](https://user-images.githubusercontent.com/37928125/42377424-e1cb81de-8140-11e8-9c2a-b0839fbe22d8.png)

Nowadays I've to use wireguard when browsing(because my browser "[Bromite](https://www.bromite.org/)" blocks all ads & trackers) and using regular apps, while blokada when playing games containing ads & numerous trackers(example pubg : 8-9 trackers and 100+ tracking requests in 30mins). So I'm forced to use 2 VPNs alternatively.
It'll really be great to put them together.

For users who don't know about WireGuard : https://www.wireguard.com/
WireGuard Git : https://github.com/WireGuard
WireGuard android app Git : https://github.com/WireGuard/wireguard-android
Also check [this](https://www.xda-developers.com/us-senator-pushes-government-use-wireguard-vpn/).

The app is available for all android users regardless native kernel support : https://play.google.com/store/apps/details?id=com.wireguard.android&hl=en_US

To add tunnels, go to [azirevpn website](https://www.azirevpn.com/), create trial account and get the tunnels, WireGuard tunnels are free even after azirevpn account trial expiry. Or you can use the tunnels I generated : [azirevpn-configs.zip](https://github.com/blokadaorg/blokada/files/2170301/azirevpn-configs.zip)

I'm doing this so that all users get to use & know how WireGuard is and support my request.
Thank you.

**Comment by kar** [comment]
Thanks for this request, Wireguard has been brought up to my attention some time ago and I'm definitely considering it. :)

**Comment by link2xt** [comment]
Related issues: #167, #111

**Comment by jeroen7s** [comment]
https://blog.cloudflare.com/boringtun-userspace-wireguard-rust/
Maybe can be used for this?

**Comment by hovancik** [comment]
Hey, I see that @kar has closes this one. Is it implemented, then? I can't see it in latest fdroid release.

**Comment by rpeter85** [comment]
Yes, implemented with v4, newest on F-droid is available here:
https://f-droid.org/en/packages/org.blokada.alarm/

**Comment by hovancik** [comment]
@rpeter85 so where can I setup my tunnels? I am on `4.1.6` and clicked through all of the available settings but still not seeing it.

**Comment by rpeter85** [comment]
Open the settings by swiping up, there tap on VPN, Account, activate your account.
Then in VPN, choose a gateway from the Gateways submenu.
But please let this ticket be closed, for further questions join us on Telegram :)

**Comment by hovancik** [comment]
Ah, I see. I was talking about custom tunnels (with provider that I already have) as is in original issue, not blokada vpn. I guess that's not on roadmap, then...

**Comment by User486375** [comment]
@hovancik Upvote #520
