### ISSUE TITLE
Add FDN dns to the current list

### ISSUE THREAD

**Issue by Devil505** [blokadaorg/blokada#228]
Hi, could you add FDN http://www.fdn.fr/ dns  to the list ?

DNS1 80.67.169.12
DNS2 80.67.169.40

French Data Network is the one of the best DNS server for french users. They care about network neutrality. More details here: https://en.wikipedia.org/wiki/French_Data_Network

**Comment by rpeter85** [comment]
We collect additional DNS service providers in [365](https://github.com/blokadaorg/blokada/issues/365). Thank you for bringing it up.
