### ISSUE TITLE
[Yalp Store] Does not download via Wifi when using Blokada

### ISSUE THREAD

**Issue by Krawei** [blokadaorg/blokada#231]
Dear team,

when I'm activating Blokada and want to download apps with Yalp Store I can't do it via Wifi anymore.

Yalp Store does not start downloading when clicking on thr download icon, I have to stop the Yalp Store app, stopp Blokada and try again.

There are no "blocked xyz" event messages from blokdada while this, but it works again when I'm disabling Blokada.

I hope I made my issue clear. Please fix this pity behaviour :).

Steps to reproduce
While connected to a Wifi and running Blockada in the background, open Yalp Store => search for any Apo (like Ryanair for example) => click on the download arrow.

Expected behaviour
Yalp Store should download the App without any issues.

Actual behaviour
Yalp Store stucks at 0%, the download status line stucks.

Blokada version
3.5

Device model
BQ Aquaris X

Android version / ROM
8.1.0
Questions

How long have you been using Blokada?
Since two months

How long time ago has the problem started to happen?
Since the beginning.

How often does this problem happen to you?
Everytime.

**Comment by Herbstfreud** [comment]
Hello,
with Yalp Store on LineageOS 14.1 (Android 7) and Blokada 3.4 (F-Droid version) I cannot confirm this. Every Download and Update works with Yalp which is not on the Whitelist.

**Comment by Avizini** [comment]
Looks like its related to #209

Blokada currently blocks all downloads via Android download manager.

**Comment by Herbstfreud** [comment]
Not really... I have issue #209, but not issue #231.
#209 seems to be a general failure if someone wants to download something via download manager during VPN activated. There it makes no difference if someone wants to download stuff with WIFI activated or not.

**Comment by Avizini** [comment]
I didn't get it, so can you download with Yalp Store with mobile data on and WiFi off?

**Comment by Herbstfreud** [comment]
Yes, and vice versa. With WiFi on it's also possible.

**Comment by Avizini** [comment]
I don't know how this is working for you. Something similar happened with me, Yalp store (anything that uses Android Download Manger) was working for me. After I did a factory reset and installed Blokada again, suddenly everything using ADM stopped working.

Can you reinstall Blokada and check if it still works for you?

**Comment by kar** [comment]
Please try reproducing on 3.6

**Comment by Krawei** [comment]
Seems being fixed in v3.6. No need for a whitelisting anymore.
