### ISSUE TITLE
Failed to retrieve https://blokada.org/api/v3/adblockerFdroid/beta/repo.txt

### ISSUE THREAD

**Issue by careylam** [blokadaorg/blokada#232]
### Steps to reproduce
1. Run Blokada from Android Emulator
2.
3.

### Expected behaviour

hosts configured to be blocked by Blokada should be loaded.

### Actual behaviour

1. 0 hosts configured to be blocked by Blokada
2. Blacklist inactive, Whitelist inactive
3. In the Android Studio Debug console, it throws:
java.io.FileNotFoundException: https://blokada.org/api/v3/adblockerFdroid/beta/repo.txt

### Configuration
1. Blokada version
Blokada 3.5 beta

2. Device model
Nexus 5X API 27 x86

3. Android version / ROM
Android 8.1

### Questions
1. How long have you been using Blokada? 
1 week

2. How long time ago has the problem started to happen? 
It only occurs in the Android Emulator

3.  How often does this problem happen to you?
All the time.

**Comment by kar** [comment]
I know this is not documented yet, but there is no beta build variant for adblokerFdroid flavor, hence your 404. Try building adblockerHome with beta, or debug, for testing or development. Let me know if you need more help.
