### ISSUE TITLE
Please only filter updates over WLAN!

### ISSUE THREAD

**Issue by tim1606** [blokadaorg/blokada#233]
Please only update the filters over WLAN not over LTE. There are no function to stop updates over LTE. I didn't have much high speed volume.

### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by kar** [comment]
#43
