### ISSUE TITLE
Why i cannot add any of these hosts?

### ISSUE THREAD

**Issue by k3lt** [blokadaorg/blokada#234]
Blokada keeps saying it's not hosts file or it cannot be downloaded, really frustrating.

https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt
https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt

**Comment by rpeter85** [comment]
Read this and you'll get the answer: https://blokada.org/api/v3/content/en/help.html#abplists

**Comment by k3lt** [comment]
So where i'm supposed to get compatible hosts for Polish sites since the default lists are useless for regional blocking?
None of the lists from https://github.com/MajkiIT/polish-ads-filter & https://www.certyficate.it/adblock/ or https://filterlists.com/ works.

**Comment by rpeter85** [comment]
You need to search for lists where the IP address and the hostname is present in the hostfile, Adblock Plus lists won't work.
Or if there are hosts in the file, you can convert them to a list that is compatible with Blokada, it's easy to do on a Unix/Linux based system.
Note that Blokada uses those filters, it has no own filter.

**Comment by xxcriticxx** [comment]
@k3lt https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt

Zapraszamy do nas!
