### ISSUE TITLE
battery drain

### ISSUE THREAD

**Issue by id2test2** [blokadaorg/blokada#235]
Hello,
Help says Blokada uses near to zero battery.
I installed the latest version from Fdroid on my Moto g5s with android 7, and left filter settings default. Blokada uses more battery than any other app. Had to uninstall. Is there a version that works better?

**Comment by rpeter85** [comment]
Hi,
Did you restart your phone before you uninstalled the app? Blokada uses a small amount of battety at the first start to download things.

**Comment by id2test2** [comment]
Hi,
I did not restart my phone.
The usage was over 2 days.

**Comment by rpeter85** [comment]
Then next time restart your phone and check the usage.
