### ISSUE TITLE
Android 9 pie problems

### ISSUE THREAD

**Issue by npgauth** [blokadaorg/blokada#237]
Blockada latest worked perfectly for me in Android 8, but in Android 9 it randomly stops and allows ads in chrome. Restart is the only way to fix the issue (toggling on and off doesn't help), but after a few times in my pocket it stops working again. I have tried different host files. I have disabled battery optimization. Nothing seems to work.

Blockada is a wonderful tool and i really hope this can be resolved. Thanks for all your hard work!

### Steps to reproduce
1. Install pie on pixel 2 XL
2. After phone goes to sleep, blockada no longer blocks ads
3. Toggling doesn't help, only full restart.

### Expected behaviour

Ads don't show up in chrome

### Actual behaviour

Ads show up in chrome.

### Configuration
1. Blokada version
3.5 (62000) official

2. Device model
Pixel 2 XL

3. Android version / ROM
9 -- pie

### Questions
1. How long have you been using Blokada? 
Maybe a year.

2. How long time ago has the problem started to happen? 
Last week immeditally following install of Android 9 pie.

3.  How often does this problem happen to you?
Until I restart. Then it happens again after it has been in my pocket a while.

**Comment by rpeter85** [comment]
Solution:
1.) open Chrome
2.) type: chrome://Flags
3.) disable the asyncDNS option
4.) save, quit, restart

The problem is, that the newest version of Chrome has a new DNS feature, it supposed to make browsing faster.

**Comment by noelkra** [comment]
Closed #237

**Comment by npgauth** [comment]
@noelkra Updated to chrome 69 and the problem is back. AsyncDNS is confirmed disabled. Any ideas?

**Comment by MaluNoPeleke** [comment]
Same issue here
