### ISSUE TITLE
Blockada doesn't stay on on Android 8.1

### ISSUE THREAD

**Issue by Themarshal2** [blokadaorg/blokada#239]
### Steps to reproduce
1. Use Blockada like usual, with the "Keep On" option 
2. Either wait or clean the RAM of the device

### Expected behaviour

I would expect it to stay on all the time

### Actual behaviour

It gets shutdown by my cellphone

### Configuration
1. Blokada version
Blockada 3.5 (62000) Official

2. Device model
Xiaomi Redmi Note 5 (4/64 GB) Global version

3. Android version / ROM
Android 8.1.0 OPM1.171019.011

### Questions
1. How long have you been using Blokada? 
1 year on my previous cellphone

2. How long time ago has the problem started to happen? 
Since I got the phone, maybe 1 month

3.  How often does this problem happen to you?

At least 5 times a day

Adding a line to say I love your work, your adblocker is extremely powerful and doesn't require root, I'd honestly pay for it

**Comment by ahmadsamhann** [comment]
lock it in MIUI recent list. MIUI is aggressive killing background services, so I think it's not really a Blokada's fault.

**Comment by barykaed** [comment]
This get killed even on a OnePlus 6 - Oxygen OS (Android 8.1).

**Comment by ahmadsamhann** [comment]
@barykaed got any task killer? and try to turn off battery optimization see if it bring any changes.

**Comment by barykaed** [comment]
No Task killers. Just out-of-the-box Oxygen OS. 

Yes, I tried to turn off battery optimization for Blockada only - that seems to help a little bit. 

But the best way seems to be to have the persistent notification.

**Comment by rpeter85** [comment]
Please try with the new, 3.6 version and let us know if it works with that.
