### ISSUE TITLE
Android P and blokada

### ISSUE THREAD

**Issue by RohanLodhi** [blokadaorg/blokada#240]
Blokada used to work great for me in Oreo but yesterday when I upgraded to Pie, it continuously stops and a window keeps popping up now and then, please help!

**Comment by rpeter85** [comment]
And what does the window say? Maybe that help to get a hint why the app is killed.

**Comment by RohanLodhi** [comment]
https://photos.app.goo.gl/qeZ2KEQcgBm9hRDA6

**Comment by rpeter85** [comment]
It's the crash report window. What happens before you get this? Can you ensure Blokada is set on the memory- and/or battery optimisation list in the system settings?

**Comment by rpeter85** [comment]
No further info provided, ticket closed.
