### ISSUE TITLE
F-droid version is still at 3.4

### ISSUE THREAD

**Issue by FatOrangutan** [blokadaorg/blokada#244]
### Expected behaviour
I would expect F-droid to host v3.5 of Blokada. For earlier updates to Blokada, there are [corresponding merge requests](https://gitlab.com/search?group_id=&project_id=36528&repository_ref=master&scope=merge_requests&search=blokada) on fdroid's gitlab, but I can't find any for v3.5.

**Comment by kar** [comment]
It's hasn't been pushed since I had some stability concerns with 3.5. Soon
3.6 will be available and will be pushed to fdroid.
