### ISSUE TITLE
I want a shortcut and/or Locale/Tasker plugin support for toggling Blokada on and off

### ISSUE THREAD

**Issue by moonspeak** [blokadaorg/blokada#245]
As the title says, it would be very handy to have a shortcut to toggle filtering. The quick settings pane can be difficult to reach and if you don't have it in the first row, it requires multiple swipes to get to. A shortcut would be very helpful as it would allow adding a toggle to sidebar apps such as Meteor or the Edge panels on Samsung devices, which are much quicker and easier to access.

If it's not clear, I'm referring to the native app shortcuts that can be added to launchers and other apps that can display widgets (https://developer.android.com/guide/topics/ui/shortcuts/).

Also, Locale/Tasker plugin support for toggling on/off would be great for advanced users to create their own shortcuts as they see fit and potentially automate toggling if needed.

**Comment by kar** [comment]
Quick settings tile already exists

**Comment by rpeter85** [comment]
Tasker support is requested in #56

**Comment by rpeter85** [comment]
No further question or request, ticket closed.
