### ISSUE TITLE
The built-in DNS manifest needs to be adjusted!

### ISSUE THREAD

**Issue by ghost** [blokadaorg/blokada#246]
Hello!
1.Norton DNS is about to shut down!
https://connectsafe.norton.com

2.Hope to add this set of DNS locations to the built-in list!
http://twnic-public-dns.twnic.tw
https://www.blahdns.com

Thank ypu!

**Comment by noelkra** [comment]
Hello ghost

1. We know about Norton DNS, and it will probably be removed in the future.
2. I'll pass them on to the devs. We will look into them.

Kind Regards

Noël

**Comment by noelkra** [comment]
As the dns are in experimental state, we will make a poll about the dns in our telegram group. Feel free to join in and vote if you haven't already!

https://t.me/blokadachat

**Comment by colbycdev** [comment]
I'd highly recommend using alternate DNS (alternate-dns.com)as an option. It also blocks ads. Not sure on privacy practice, though it's relatively fast in my experience.

**Comment by rpeter85** [comment]
We will collect additional DNS service providers in [365](https://github.com/blokadaorg/blokada/issues/365). This one will be closed.
