### ISSUE TITLE
Titles aren't downloaded for Italian language

### ISSUE THREAD

**Issue by rpeter85** [blokadaorg/blokada#248]
On Android 6 (Asus ZenFone 2) and Android 8 (Huawei P10 lite) with Italian system language the titles for the different Blacklist elements aren't downloaded(shown as "Un link da http://...), even though on Android 7 (Xiaomi Redmi Note 5, Italian system language as well) it works as expected (shown as Energized Blu or Spark, etc).
On Android 7, the description for the newly added Blacklists lists are English, while on the other phones (A6 and 8) there's no description at all.

The Blacklist was reset several times, even the app was reinstalled, but it didn't help.

**Comment by kar** [comment]
Newest strings have just been added to the translation platform. Once they are translated I will import them to the repo.
