### ISSUE TITLE
Specific Website (apkmirror.com) Cannot Be Excluded

### ISSUE THREAD

**Issue by DmitryN71** [blokadaorg/blokada#249]
### Steps to reproduce
1. Try to add www.apkmirror.com or apkmirror.com to the list of exclusions.
2. Open apkmirror.com
3. Try to download an apk and see the warning that you have an adblocker enabled and the countdown making you wait for the download link to appear.

### Expected behaviour

Ads must be allowed to be shown.

### Actual behaviour

Ads still blocked.

### Configuration
1. Blokada version
3.5

2. Device model
Samsung Galaxy S9+ Exynos.

3. Android version / ROM
8.0 Official ROM, not rooted.

### Questions
1. How long have you been using Blokada? 
A few months

2. How long time ago has the problem started to happen? 
Since I started using Blokada.

3.  How often does this problem happen to you?
Every time I open this web site.

**Comment by rpeter85** [comment]
Did you go back to the main page after you set the website on the Whitelist? That saves the config. If you don't return, the page won't be excluded.

**Comment by DmitryN71** [comment]
> Did you go back to the main page after you set the website on the Whitelist? That saves the config. If you don't return, the page won't be excluded.

Maybe I wasn't clear enough, but the ads on this domain don't get blocked after no matter what. You can even reboot your phone, restart Blokada, force-close Chrome etc.
Adds keep being blocked.
This only happens to apkmirror.com as far as I've noticed.

**Comment by ahmadsamhann** [comment]
ok I've tried this. the timer doesn't start when I use blokada, but it gets blocked when I use Brave built-in adblocker.

**Comment by colbycdev** [comment]
I know some apps, whitelist doesn't do anything. I've found that you are better off using URLs
Also, you need to whitelist the ads, not the site itself. This isn't uBlock or ABP

**Comment by rpeter85** [comment]
It's a bit old ticket, so I want to warm it up. Can you please check if you have the same issue with the current, 4.3.5 version?
