### ISSUE TITLE
No internet for 'Block connections without VPN'

### ISSUE THREAD

**Issue by piu130** [blokadaorg/blokada#250]
### Steps to reproduce
1. Go to Settings - Network & Internet - VPN - 'configure'
2. Turn on `Block connections without VPN`

### Expected behaviour
Internet should workin eg. Firefox and Play Store.

### Actual behaviour
No Connection/Website not found/ etc. errors

### Configuration
1. Blokada version
3.4 (100500) Release from F-Droid Store

2. Android version / ROM
Android 8.1.0 (1. August 2018) Stock

### Questions
1. How long have you been using Blokada? 
1.5 year

2. How long time ago has the problem started to happen? 
3 weeks (when I first tested it)

3.  How often does this problem happen to you?
Always

**Comment by jeroen7s** [comment]
this seems like intended behavior? android blocks all connections if VPN is not connected, so if blokada is off, it will block internet connection to firefox and the play store (and all other applications)

**Comment by piu130** [comment]
Blokada is running.

**Comment by jeroen7s** [comment]
aha, and the VPN icon (looks like a key) is visible in the tray on top of the screen?

**Comment by piu130** [comment]
Yep. And in VPN settings under `Blokada` is `Connected, Always-on active`.

**Comment by piu130** [comment]
Created a feature request [here](https://github.com/blokadaorg/blokada/issues/251).
