### ISSUE TITLE
I want Blokada to work with VPN setting 'Block connections without VPN' turned on

### ISSUE THREAD

**Issue by piu130** [blokadaorg/blokada#251]
This is the following up feature request for [this](https://github.com/blokadaorg/blokada/issues/250) issue.

Internet stops working as soon as I turn on `Block connections without VPN` in VPN settings.

> [...] the setting blocks all traffic going out of your device that's not going top your VPN
but since your VPN is on your own device (localhost), the local VPN itself also needs to connect to websites outside of the device, and is blocked because of "all data needs to go to VPN server" rule

**Comment by kar** [comment]
The big problem here is that Blokada routes only DNS through itself. We would need to route and proxy all UDP and TCP traffic, what is going to significantly increase battery usage, and break other protocols like ICMP. So I think realistically speaking this will only happen once we have the VPN feature in.
