### ISSUE TITLE
Let Blokada to serve as a local DNS Server to be used with other VPN Services

### ISSUE THREAD

**Issue by BlackDex** [blokadaorg/blokada#253]
I have seen requests for allowing support of OpenVPN and other VPN Services to Blokada.
What would be sufficient for me would be that Blokada serves as a local DNS Server if possible.
That way you can configure the OpenVPN configuration to override the DNS to a local setting.
Would be perfect if i can just set that to 127.0.0.1 or something in OpenVPN and that Blokada listens on port 53 locally.

I know that the VPN should allow all other traffic as else the forwarding request could be blocked.
But people can configure the DNS Which OpenVPN pushes in Blokada to be used as a forwarder.

Hopefully this is something which is easy to implement :).

**Comment by kar** [comment]
Sounds interesting. Could you provide a bit more details what would be required for this to work? For example, I'm pretty sure Blokada won't be allowed to listen on port 53, or any other below 1024. Is configuration of OpenVPN flexible enough?

**Comment by BlackDex** [comment]
I'm going to close this as it's no longer needed for my self. And this probably only will work on a rooted device.
