### ISSUE TITLE
Blocking Subdomain doesn't works

### ISSUE THREAD

**Issue by beerisgood** [blokadaorg/blokada#254]
If I block Facebook.com it works, but if I block m.facebook.com it doesn't even if I set both on blacklist 

Looks like Blokada ignore subdomains?

LineageOS 15.1 (Android 8.1)
Latest version from F-Droid (3.4.100500)

**Comment by BlackDex** [comment]
@beerisgood Did  you reboot your phone and have Bolkada setup to be started on boot?
It could be that this is cached on your phone/app.

**Comment by rpeter85** [comment]
Yes, Blokada blocks only top level domains (TLD), and can't block subdomains.

**Comment by BlackDex** [comment]
@rpeter85 That is not true.
Blokada blocks any domain which is requested via DNS.
So m.facebook.com or secure.m.facebook.com can all be blocked.

TLD's are only .com, .org, .net etc...

Blokada can't block (sub)folders like facebook.com/ads.

**Comment by rpeter85** [comment]
Please try to add a subdomain (like example.myhost.com) to the blacklist and let us know if you succeed.

**Comment by BlackDex** [comment]
@rpeter85 I did that, and it works perfectly. Just check all the host files you can enable online and you can see that all those have subdomains.

**Comment by BlackDex** [comment]
@rpeter85: Well i just did it with my own domain and it works.
Please first check before stating stuff that is not true.

I just tested to block www.mydomain.com and not mydomain.com and that works.
I wasn't able to connect www.mydomain.com and was able to connect to mydomain.com.

Also, you stated that blokada only does TLD's which is not true, please read what TLD's are https://en.wikipedia.org/wiki/Top-level_domain .

**Comment by rpeter85** [comment]
Yes, you were correct, it can block subdomains (like domain.myexample.com), I didn't check it just remembered for an older issue where it came up.

**Comment by beerisgood** [comment]
> 
> 
> @beerisgood Did you reboot your phone and have Bolkada setup to be started on boot?
> It could be that this is cached on your phone/app.

Yes both. 
Doens't make any difference.

**Comment by beerisgood** [comment]
*push*

**Comment by BlackDex** [comment]
@beerisgood, isn't it listed in the whitelist then? i tried to block it, ander and can't access it anymore after setting it. do you use a browser or the Facebook app? and when using a browser, please check if you have disabled the data saver option which will work as a proxy and bypasses the dns requests.

**Comment by beerisgood** [comment]
I solve the problem
Forgot that I use DoH DNS server in Fennec, so it ignore the local DNS.
