### ISSUE TITLE
Blokada doesn't work with Chrome 69

### ISSUE THREAD

**Issue by MaluNoPeleke** [blokadaorg/blokada#257]
After updating to Chrome 69 Blokada doesn't work within the browser. 
Async DNS is deactivated. 
With StopAd.it ads are still removed so there must be a possibility to get around the current Chrome version.
Related to #237

**Comment by noelkra** [comment]
Hello MaluNoPeleke

I'm sorry to hear that.

Could you please tell me on which websites you are experiencing the issue, so that I can try to reproduce your problem?

Kind Regards

Noël

P.S.: Please use our [issue template](https://github.com/blokadaorg/blokada/blob/master/docs/issue_template.md) in the future. It helps us to reproduce your problem faster!

**Comment by MaluNoPeleke** [comment]
Every website with ads is affected (e.g. www.golem.de) with Chrome 69+ as discussed at DNS66 as well: https://github.com/julian-klode/dns66/issues/289
Activating AdGuard DNS server solves the problem.

**Comment by kuro68k** [comment]
Can confirm same issue. DNS66 is affected as well.

**Comment by PHLAK** [comment]
I just switched to Blokoda from DNS66 and Blokada is working for me with Chrome v69.0.3497.100

**Comment by kuro68k** [comment]
Surprisingly Blokoda does seem to work for me to. Pixel XL, Pie.

**Comment by njbbaer** [comment]
Blokada is currently **not** working for me. Chrome 69.0.3497.100, Android Pie 9.0.0, Pixel XL 2.

**Comment by thanuj10** [comment]
Everyone try disabling this flag from chrome://flags
`Async DNS Resolver`

**Comment by hoolius** [comment]
> Everyone try disabling this flag from chrome://flags
> `Async DNS Resolver`

As noted in the original issue...it doesn't make a difference.

**Comment by kar** [comment]
Could you please join telegram and ask to join beta?

**Comment by manindersarao** [comment]
Blockada v3.6, Android 9 (oneplus 6), DNS set to cloudflare from within blockada.
Works fine on chrome 69. Tested with urls given in thread.

**Comment by rpeter85** [comment]
No information since 12th of Oct, setting this case to closed.
