### ISSUE TITLE
Blacklist inactive in Release build

### ISSUE THREAD

**Issue by RamanHaivaronski** [blokadaorg/blokada#258]
### Steps to reproduce
1. Start the app using the adblockerHomeRelease build (or any other except debug build that works fine)
2. Blacklist\whitelist inactive and i can't add my own list with host\link\file

### Expected behaviour
I want the behaviour to be the same as in debug build
- Have the access to the blacklists\whitelists
- Have the ability to add the blacklists
 (Other parts of the app are working as intended to be.)

### Actual behaviour
Blacklist\whitelist is inactive in RELEASE build, can't add the blacklist\whitelist also.

### Configuration
1. Blokada version
v3.5

2. Device model
Xiaomi Redmi 3, AVD several devices

3. Android version / ROM
5.1.1 and higher

### Questions
1. How long have you been using Blokada? 
Since 23.09.2018

2. How long time ago has the problem started to happen? 
Since the start of the testing

3.  How often does this problem happen to you?
Every time

**Comment by rpeter85** [comment]
By "debug" and "release" build, what do you mean exactly?
You can access the black- and whitelists on the public 3.5 as well, you can add blacklists manually from different sources.

**Comment by RamanHaivaronski** [comment]
> You can't make a release build, you don't have the release keys, so I assume you changed the build config file. In such case, it's probably incorrect and may try to fetch filters from the server in a wrong way. What are you trying to do?

I created my own keystore file, right. No other changes to proguard and build options.
So, is it impossible to make a release build without the original release keys?

**Comment by kar** [comment]
Oh, no then it should fly. Please do a clean build, start the app, activate, and send logs here.
