### ISSUE TITLE
Auto-Stopping of Blokada when another VPN is in use.

### ISSUE THREAD

**Issue by thanuj10** [blokadaorg/blokada#260]
### Steps to reproduce
1.Open any VPN app that allows to mask IP address and connects to another location(NordVPN)
2.Keep Blokada connected

### Expected behaviour
 Blokada stops its local VPN connection to allow the other VPN app to be connected.

### Actual behaviour
Blokada does not discconect/Disconnects and the other VPN does not connect.

### Configuration
1. Blokada Version 3.5

2. Samsung Galaxy core prime

3. Android 7.1.2/LineageOS

### Questions
1. How long have you been using Blokada? 
More than 5 months

2. How long time ago has the problem started to happen? 
Not a problem, But a feature request.

3.  How often does this problem happen to you?
Everytime another VPN wants to be connected

**Comment by rpeter85** [comment]
Could you please elaborate a bit? So the goal is that Blokada recognises if there's another active VPN service and turns off, and when the other VPN is disconnected then it turns on again, automatically?

**Comment by thanuj10** [comment]
Yes. That's what I wanted.

**Comment by rpeter85** [comment]
Ok, thanks

**Comment by animeking9901** [comment]
In the past I've seen where blockada will aggressively try to reconnect if it's disconnected in any way other than the big orange button

**Comment by colbycdev** [comment]
I've seen it when you have alway on set for Blokada mostly. I don't know if you have that set, just a thought  

_Sent from my TETRA using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by m-reiter** [comment]
Seconded, would be a very helpful feature. I've no idea whether it's feasible though.

**Comment by memphise** [comment]
Excuse me,  how about the progress of this  feature request?  I also had the same problem，the other vpn apps can‘t run when Blokada is on 。
If I want to use them, I have to turn off Blokada manually.

**Comment by kevinsithk** [comment]
Adguard has such feature. It's convenience.
But now I use blokada so I hope blokada has this feature too.

**Comment by thanuj10** [comment]
Seeing that this is fixed in v4.3, Can I close this issue now? 

Thanks for your work guys!

**Comment by kar** [comment]
Yes 4.3 is behaving correctly now. I noticed a small problem in detection in the UI that the VPN was taken away, but this will be fixed in 4.3.4. So I'm closing it.
