### ISSUE TITLE
will not turn on

### ISSUE THREAD

**Issue by bocad78209** [blokadaorg/blokada#263]
I am using a android box and I have tried downloading several versions. I can add blocked links and host fine, but when I go to turn it on, the button will not turn orange and I get a "blockada inactive" message. 
Can you tell me what is causing this because I would really like to use your product.

Thanks,
Bob Cadena
usl@usa.com

**Comment by rpeter85** [comment]
Can you please validate that the Android Box has VPN function? Blokada uses it and if the system doesn't support, the app won't turn on.

**Comment by bocad78209** [comment]
Hi Peter, yes it has vpn capability. I am using Nord. I have tried everything I know to make it work.  What happens is that when I install and follow instructions, I can add new host but when I go to activate by hitting the shield, instead of getting the notice that a vpn needs permission, It says blockada is inactive. The android box is  Mecool MS8 w  pro


________________________________

**Comment by rpeter85** [comment]
do you deactivate the NordVPN before you try to activate Blokada? The Android system won't let you have 2 active VPN connection at the same time, unfortunately.
Check in system settings if NordVPN is set to be 'Always on'

**Comment by bocad78209** [comment]
yes I have tried it both ways


________________________________

**Comment by bocad78209** [comment]
Also, it is NOT always activated.


________________________________

**Comment by rpeter85** [comment]
Can you generate a logcat file? That needs developer options activated and a PC or notebook to collect the file. Without logs, it's just educated guessing what happens.

**Comment by kar** [comment]
Install 3.6, grant storage permissions (in system settings) for Blokada, start it. Go to storage/Download/blokada and send blokada.log to us.

**Comment by rpeter85** [comment]
No further information provided, I close this ticket.
