### ISSUE TITLE
CoinBlockerLists URL not working any more.

### ISSUE THREAD

**Issue by BlackDex** [blokadaorg/blokada#265]
The URL for CoinBlockerLists in the default filter list is not working any more.

The URL currently in Blokada is: https://zerodot1.gitlab.io/CoinBlockerLists/hosts
A working link for this list is: https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts

**Comment by rpeter85** [comment]
The list on the original link works as expected. Can you please re-check and let us know if you really can't access it?

**Comment by BlackDex** [comment]
strange, it now works again.
i tried 2 days in a row, and it didn't worked. fot a gitlab 404 error. problems seems solved
