### ISSUE TITLE
Blokad shuts down after configuration is set.

### ISSUE THREAD

**Issue by primostylz** [blokadaorg/blokada#269]
Firstly I'd like to say that I love what you guys are doing with the app.  Im having an issue with an android box that seems to shut blokada down in the background and cant seem to find a workaround.  Ive checked the keep alive option as well as the online only (on and off) and still its being shut down.  Also tried the settings for background processes and still the same.  what should I donext? 

### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by rpeter85** [comment]
Hi,
Can you please check if you experience the same behaviour with Blokada 3.6.101401? That's the newest available on Blokada's website.

**Comment by rpeter85** [comment]
No further info provided, closing this thread.
