### ISSUE TITLE
White and Blacklists lost when migrating to 3.6

### ISSUE THREAD

**Issue by hayvan96** [blokadaorg/blokada#270]
Hi

I've upgraded from 3.4 to 3.6 via f-droid and I was surprised not to see the key icon even if Blokada says it's running. 
When I looked in the app settings I've noticed white and Blacklists are empty. Even if I force the download lists option, I don't have any preset blacklist. 
0 hosts. 
I hope my whitelist is not lost. 

### Steps to reproduce
1. Upgrade Blokada in f-droid (from 3.4 to 3.6)

### Expected behaviour
Settings are migrated 

### Actual behaviour
Blacklist and white lists are empty. 

### Configuration
1. Blokada version
3.6

2. Device model
Xiaomi Redmi note 4 

3. Android version / ROM
8.1, LineageOS 15.1 official

### Questions
1. How long have you been using Blokada? 
One year

2. How long time ago has the problem started to happen? 
When I've upgraded this morning

3.  How often does this problem happen to you?
N/A

**Comment by jerryn70** [comment]
I confirm this

**Comment by rpeter85** [comment]
Yes, there is an issue that neither the Black- or the Whitelists can be read up after the update. Currently we are analysing it to see if there's a pattern (happens only on X phones, or on Y android version, or if Z is configured), but we couldn't find out the reason so far.

**Comment by esmoak** [comment]
@rpeter85 I had the same issue and it seems like I was able to fix it when I turned off the keep alive function. 

I can't remember all of the steps I took, but I ended up toggling that off and rebooting and somehow it was able to show me the blacklist and whitelist again. Later on I was able to toggle keep alive on again with no issues.

**Comment by mincem** [comment]
Cleaning cache and storage (as suggested in #276) restored functionality. However, as may be expected, this reverts whitelist and blacklist to defaults. (I don't actually remember what my previous configuration was.)

**Comment by rpeter85** [comment]
The new Blokada build, 3.6.101401 aims to resolve the update issue, and the one that is reported here.
Please check it and report if you still face the initial problem.

**Comment by Hoerli1337** [comment]
3.6.101401 works again.
Had the same problem with a Samsung Galaxy Note 8 and Android 8.0.0.

I don't know if it's the multiple access points of my company, but he often reconnects OR the app crashes and restarts.
However, a crash is not detected by the system.

**Comment by 0xlne** [comment]
I had the same issue on Xperia XZ2, however, I have never been able to recover my whitelists.
Furthermore, the default blacklist blocks downloading from Play Store.
Lastly, the whitelist input no longer autocompletes; previously I was able to select Apps to whitelist with Blokada autocompleting, now I need to type the package name by hand.

**Comment by rpeter85** [comment]
Please check with the newest, 3.6.101900 and let us know if you still face the initial issue.

**Comment by hayvan96** [comment]
Everything works again, thanks
