### ISSUE TITLE
[BUG] Blokada goes back to main screen when rotating the screen / changing orientation

### ISSUE THREAD

**Issue by K0media** [blokadaorg/blokada#274]
### Steps to reproduce
1. Open Blokada app
2. Go anywhere else but the main screen
3. Rotate the device with auto-rotate on and then it goes back to main screen (no HW/SW buttons/gestures touched).
(Please view https://imgur.com/a/YiFSRXV or https://media.giphy.com/media/5PhpLQqxsXjWns5GI2/giphy.gif)

### Expected behaviour

It was supposed to remain on that specific screen, and not to go back to the main screen.

### Actual behaviour

It is going back to the main screen at any time I rotate the screen/device with the auto-rotate on.

No hardware or software buttons pressed. Just need to rotate the screen anywhere else that's not the home screen and it goes back to the main screen right after. (changelog, blacklist, whitelist, about, etc).

(Please view this: https://imgur.com/a/YiFSRXV or https://media.giphy.com/media/5PhpLQqxsXjWns5GI2/giphy.gif)

### Configuration
1. Blokada version
Latest official build - v3.6 (at this moment I'm posting)

2. Device model
Xiaomi Redmi Note 4X

3. Android version / ROM
7.1 Nougat, Stock MIUI Global 9.6.2.0
(I can provide more details if needed, but it happens on all devices I tested.)

### Questions.
1. How long have you been using Blokada? 
1 year or so.

2. How long time ago has the problem started to happen? 
Always?

3.  How often does this problem happen to you?
Always.

**Comment by yafp** [comment]
I can confirm this issue
