### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by ewuoso** [blokadaorg/blokada#275]
I think having an about us section will make people understand your project more.   If you don't mind, I can write that for you.

**Comment by kar** [comment]
Great idea. Go for it, I'll fill it in later on.

**Comment by rpeter85** [comment]
@ewuoso, did you have time to write a few words? :)

**Comment by ewuoso** [comment]
I have been sick but I have done it now

**Comment by rpeter85** [comment]
The new website ships information about us and about the vision.
