### ISSUE TITLE
version 3.6 does not block ads - no VPN symbol is seen

### ISSUE THREAD

**Issue by bjwessels** [blokadaorg/blokada#276]
### Steps to reproduce
1. Uninstalled 3.4
2. Installed 3.6
3. Ads are not blocked 

### Expected behaviour
Ads should be blocked

### Actual behaviour
There is no VPN symbol, I tried turning it on and off with the same result. On the install it did ask about setting up the VPN.

When I install 3.4 everything works fine and I see the VPN symbol

### Configuration
3.6
Keep alive on
Online only - Note it got renamed - I did try toggling this but it did not help

2. Device model
Moto E4

3. Android version / ROM
Android 7.1.1

### Questions
6 Months or a year

2. How long time ago has the problem started to happen? 
since the 14th October 2018

3.  How often does this problem happen to you?
Every time I install 3.6

**Comment by rpeter85** [comment]
Did you went through this site before you reported it: https://blokada.org/docs/help.html#unsupported ?

**Comment by bjwessels** [comment]
I read the link above. I don't have any other VPN and I toggled the online option several times. I also uninstalled 3.6 and installed the previous version 3.4 and that worked just fine (I've been using 3.4 since it was released), straight way. I then uninstalled 3.4 and installed 3.6 and that did not work. Uninstalled 3.6 and reinstalled 3.6 and it did not work.

**Comment by virtadpt** [comment]
+1.  Version 3.6 has been a total no-go.  Did the same thing above to try to shake it into working.  Can't even tell if it's downloading blocklists (it's not showing up on my local router).

**Comment by rpeter85** [comment]
Stop the Blokada. Clean cache and storage. Start Blokada. Check if it blocks.

**Comment by bjwessels** [comment]
Ah ok so that worked. 3.6 is working after doing that.

Thanks
On Oct 14, 2018, at 3:08 PM, Peter <notifications@github.com<mailto:notifications@github.com>> wrote:

Stop the Blokada. Clean cache and storage. Start Blokada. Check if it blocks.

**Comment by rpeter85** [comment]
so 3.6 is a go, and we are working to figure out what causes this update issue.
No-go is a strong word without providing information or help.
