### ISSUE TITLE
Blokada starts unexpectedly when switching to mobile data in v3.6

### ISSUE THREAD

**Issue by tkterris** [blokadaorg/blokada#279]
### Steps to reproduce
1. Install Blokada 3.6. Turn it on, then off again (to confirm Blokada has VPN permission).
2. Turn on Airplane Mode.
3. Turn off Airplane Mode.
Alternatively, turn on WiFi, then turn it back off. However, this doesn't always trigger the behavior.

### Expected behaviour

Since Blokada was turned off before applying steps (2) and (3), the expected behavior is that, after turning off Airplane Mode (and switching to the mobile network), Blokada stays off.

### Actual behaviour

Blokada turns on after disabling Airplane Mode. It also can turn on when disabling WiFi, so I suspect it turns on whenever the internet connection is the mobile network.

Strangely, the UI does not seem to update - the Blokada quick settings tile stays greyed out, and in the Blokada app, the main "power" button is white instead of orange.

### Configuration
1. Blokada version
3.6 (the expected behavior occurs in 3.5).

2. Device model
Nexus 6P

3. Android version / ROM
8.1.0 (stock, unrooted)

### Questions
1. How long have you been using Blokada? 
A couple months.

2. How long time ago has the problem started to happen? 
It just started a few hours ago, when I updated Blokada to 3.6.

3.  How often does this problem happen to you?
Every time I switch from WiFi to a mobile network - whenever I leave my house, etc. Multiple times per day.

**Comment by kar** [comment]
Fixed for the next minor release.
