### ISSUE TITLE
Question: are blacklists merged or not

### ISSUE THREAD

**Issue by yafp** [blokadaorg/blokada#282]
Sorry for hijacking Github issues for posting a question, but as i don't use telegram i havent found another place where to ask questions about how blokada is using blacklists.

Feel free to close this issue if this is abuse.

Question:
Assuming i am using 3 blacklists, is blokada merging the content of those lists to 1 unique internal list or do i end up with having several duplicate hosts due to my amount of blacklists?

**Comment by rpeter85** [comment]
Blokada merges those lists and filters out duplicates, generating one big list with only unique hostnames. The more and bigger list you use, the bigger the memory consumption is.

**Comment by yafp** [comment]
thanks @rpeter85
