### ISSUE TITLE
Locally domain name resolution

### ISSUE THREAD

**Issue by rohanvakharia** [blokadaorg/blokada#285]
Is there any way using that I can link specific IP address to specific hostname? 
The point here is that sometimes some hostname resolution requests are discouraged by firewall, so even if I use different DNS servers IP resolution will not happen.
If this is not possible in the current version could you be consider this as a feature and add in the next update?

**Comment by rpeter85** [comment]
Create a list with IP addresses and hostnames you want to map togerher and add that to Blacklist.
Blokada will resolv those hostnames for the IP you entered.

**Comment by rohanvakharia** [comment]
I am talking about using specific IP address with hostname.
For example if google has 5 IPs. Instead of getting random resolution, get specific IP resolution.

In this case, request will not go to DNS via firewall, it will be resolved at VPN level.

**Comment by rpeter85** [comment]
I talk about the same.
1.) Create a file.
2.) Add IP address you want to use
3.) Add the hostname
4.) Import to Blacklist in Blokada

**Comment by rohanvakharia** [comment]
There was confusion because option says blacklist and the file name must be `hosts.txt` otherwise app will not accept.
Though thanks for you help @rpeter85 I managed to whitelist using blacklist option.
