### ISSUE TITLE
I want to add this blacklist which blocks advises about cookies

### ISSUE THREAD

**Issue by alleluia20** [blokadaorg/blokada#286]
Advises about cookies (mandatory in the European Union) can be exasperating. I found a list that can be added to Blokada (it may be disabled by default if you think it is better, but the user would have the option to turn it on):

https://www.i-dont-care-about-cookies.eu/abp/

Regards.

**Comment by rpeter85** [comment]
Did you validate if the list really works in Blokada or you just opened the request?
Because as I went through it, isn't a hostname-IP list.
Details are here: go.blokada.org/help.html#abplists

**Comment by alleluia20** [comment]
Well, I thought it was working because some cookies warnings were not displaying (although others were still shown). But, after doing a more thorough test, I think there is no difference when the list is enabled or disabled, so it is probably not working.

But a question arises: is Blokada actually blocking some advices of cookies? If yes, is there any list that blocks more of them than the three lists that are enabled by default?

Regards.
