### ISSUE TITLE
Blokada download hosts everytime i use

### ISSUE THREAD

**Issue by T4P4N** [blokadaorg/blokada#290]
### Steps to reproduce
1. Open app and press turn on

### Expected behaviour

It should connect fast like before  the update

### Actual behaviour

It just says downloading hosts

### Configuration
1. Blokada version
Blokada 3.6 (101900) Release

2. Device model
Xiaomi Redmi 4a
2016116
3. Android version / ROM
7.1.2
MIUI 9.6 Global Stable
### Questions
1. How long have you been using Blokada? 
1 Year

2. How long time ago has the problem started to happen? 

few days ago after the update
3.  How often does this problem happen to you?
3 times Today ;___;

**Comment by rpeter85** [comment]
So the issue you are facing is total fresh, you observed it only today.
In the title stays it downloads every time you connect, while in the message I can see it isn't fast enough for you. What's the actual issue?
How much lists and which DNS server do you use? It happens on mobile or on wifi only? By default the "wifi only" is enabled for download the lists in the Advanced settings, did you disable it?

**Comment by T4P4N** [comment]
it takes about 2 mins to download hosts and connect automatically after that. AdZhosts & Energized Blu , and default DNS, didn't tried on mobile data yet! ,on wifi it does download hosts everytime i try to connect, wifi only is enabled

**Comment by T4P4N** [comment]
I reinstalled the app and now it is working fine! Thanks! :)
