### ISSUE TITLE
Blokada blocking internet access on OnePlus 6 

### ISSUE THREAD

**Issue by w4tadrag** [blokadaorg/blokada#292]
I keep on noticing that Blokada blocks all internet access on my device from time to time. I believe this issue is very similar to this one https://github.com/blokadaorg/blokada/issues/284. I have to go back to the app and turn it off and on to make my internet work again. Yet I get the issue again. At first I noticed it happening after 12am EST, but I am seeing it happen during the afternoon now. I have done a lot of troubleshooting and have come to the conclusion that it was Blokada.  

### Steps to reproduce
Not sure, as it happens by itself

### Expected behaviour
Shouldn't block access to the internet

### Actual behaviour
Blocks all access to the internet

### Configuration
1. Blokada version: 3.6

2. Device model: OnePlus 6

3. Android version / ROM: 9.0

### Questions
1. How long have you been using Blokada? 
Since ver 2

2. How long time ago has the problem started to happen? 
After installing 3.6

3.  How often does this problem happen to you?
Once or twice per day

**Comment by colbycdev** [comment]
I have an Alcatel(Android 8.1) as well. I know there is a built in function that harms VPN functionality. Since Blokada doesn't run a service, on mine it kills it. On the other Alcatel I had(Android 7.1.1), I had the same issue.
________________________________

**Comment by colbycdev** [comment]
Breaking the built in smart manager helped for me. Though I don't remember when exactly I started using a custom dns...

**Comment by piehei** [comment]
I'm having the same issue. Stock Android (9.0) with OnePlus 6T and latest Blokada.

It randomly stops all network connectivity. This happens multiple times a day. Toggling it fixes the issue.

**Comment by w4tadrag** [comment]
I think I know why it was causing it. I removed it from battery optimization and stopped seeing issues with it for few days now. You guys should try that.
