### ISSUE TITLE
I want Blokada in Android 9 pie work without VPN

### ISSUE THREAD

**Issue by Lucuz91** [blokadaorg/blokada#293]
Hi guys,

from android 9 you can change DNS without use a VPN connection (Settings → Network & internet → Advanced → Private DNS).
In this case blokada could work without create a VPN connection, simply activating DNS service and manual set DNS to localhost (or a local ip inside android, like 192.x.x.x or 172.x.x.x).
Is it technically possible or not?

**Comment by animeking9901** [comment]
Without root? No. Apps cannot bind to ports lower than 1024 without root,unless android 9 can take nonstandard port numbers(meaning higher than 1024),in which case,using the dns changer on Gplay as a base,maybe

**Comment by colbycdev** [comment]
If you have Root, I believe it's already possible. Otherwise complain to Google

**Comment by rpeter85** [comment]
No further comment, closing this thread.
