### ISSUE TITLE
Block ada not working

### ISSUE THREAD

**Issue by cybern4t** [blokadaorg/blokada#296]
Whenever i connect to blockada,it shows blockada active but in real it doesnt block anything at all.I tested it on my old phone as well as on new phone but it is not working.When i pull my notification drawer it shows key icon as it is connecetd but when go out of it its not showing anything.I dont know what is wrong here.

**Comment by rpeter85** [comment]
If you just installed Blokada, restart the phone, after that clear apps' cache.
Furthermore, it worth to make Blokada exception for battery- and memory-optimisation, as it is stated here: http://go.blokada.org/help#kill

**Comment by animeking9901** [comment]
App cache's will store ads,like Peter said. Issues like this need to be on telegram chat,as it's generic enough to A. Be solved by other end users and B. Depending on the specifics,helpful to someone not on GH. Had it been a more specific issue it would have been put here
