### ISSUE TITLE
auto update lists

### ISSUE THREAD

**Issue by gkalemis** [blokadaorg/blokada#298]
### Steps to reproduce
1. Start application
2. Change update interval to weekly
3. Close an restart

### Expected behaviour

To start without updating the lists

### Actual behaviour

Always downloads and updates lists

### Configuration
1. Blokada version
Latest 3.6.101401

2. Device model
Xiaomi 5 plus

3. Android version / ROM
8.1.2

### Questions
1. How long have you been using Blokada? 
6 months

2. How long time ago has the problem started to happen? 
When  updated from 3.4

3.  How often does this problem happen to you?
Always

**Comment by rpeter85** [comment]
Blokada downloads the list once, then it activates the schedule you set up. If the first download fails for some reason (download took long, or it still merges the lists) the process will restart the next time.

**Comment by colbycdev** [comment]
It will say updating, but in my experience it doesn't actually update. Mind you, I've noticed that if the last time the app stopped was due to a crash, it'll re-download
________________________________

**Comment by rpeter85** [comment]
Why do you think it doesn't do anything?

**Comment by colbycdev** [comment]
A) it did it once, when I had NO internet
B) file dates
Mind you, I haven't checked every time, but when I did, that was the scenario
________________________________
