### ISSUE TITLE
Blokada can turn off / die when it should not (battery saving)

### ISSUE THREAD

**Issue by lindatmuller** [blokadaorg/blokada#3]
I tap the sheild. App is on. Stays on for a while 30-90 minutes then is no longer active.

**Comment by blokadaorg** [comment]
Thank you for this report @lindatmuller! I just confirmed the problem. Fix will be released soon, in the meantime you may want to try to check your battery savings settings on your device, and if possible, add Blokada to whitelist.

**Comment by blokadaorg** [comment]
It also happened for Huawei P8 Lite (6.0). Blokada would die when screen is locked. It stopped when the app was whitelisted in battery saving settings.

**Comment by lioryte** [comment]
Possible fix: disable blokada battery optimization

**Comment by lindatmuller** [comment]
Did it. Seems to work great. Thanks!

**Comment by kar** [comment]
Also, 1.1 has the "keep alive" switch, which will help in such scenario.
