### ISSUE TITLE
Blocking npr.org podcasts

### ISSUE THREAD

**Issue by Nemi5150** [blokadaorg/blokada#303]
### Steps to reproduce
1. Install podcast app (I am using https://play.google.com/store/apps/details?id=fm.player)
2. Subscribe to Planet Money NPR podcast 
3. Stream/Download fails with http error message

### Expected behaviour

Podcast should download

### Actual behaviour

Podcast download fails

### Configuration
1. Blokada version
3.6 (101900)
Adguard DNS
Energized BLu and Coinblocker blacklists

2. Device model
Pixel 2 XL

3. Android version / ROM
9

### Questions
1. How long have you been using Blokada? 
9 months

2. How long time ago has the problem started to happen? 
when I updated to 3.6

3.  How often does this problem happen to you?
Every time

**Comment by rpeter85** [comment]
Blokada uses 3rd party lists. It means, it blocks what is on the list.
Try with another list or add the blocked domain or app to whitelist.
