### ISSUE TITLE
I want better explanation of what Google Play store version of Blokada is vs blokada.org

### ISSUE THREAD

**Issue by Flightkick** [blokadaorg/blokada#304]
The website https://blokada.org/ states the following:

> Note: Blokada isn't allowed on Google Play because it interferes with Google's business model. Please contact us in case you experience any problems. If for some reason you don't want to use the recommended way, Blokada is available on app stores listed below. Pick the one that suits you the most!

But the app seems available there: https://play.google.com/store/apps/details?id=org.blokada.alarm.dnschanger

I've currently got the app installed through F-droid. When going through the Menu > About
The app also states it will be automatically updated when downloaded through F-droid or the Play Store.

I'm confused by the text on the website, is it outdated?
Is the app which I've linked above official?

**Comment by rpeter85** [comment]
The app from blokada.org is a full-featured ad-blocker. The same is true for the F-Droid version.
The one one Play Store is "just" a DNS changer which helps you change the DNS service, but the app itself doesn't block ads (the used DNS servers, however, can).

Let us know if you have further questions.

**Comment by rpeter85** [comment]
Noted, thank you for the feedback.
