### ISSUE TITLE
I would like a button to disable Blokada from the Keep Alive notification

### ISSUE THREAD

**Issue by ogarcia91** [blokadaorg/blokada#308]
Currently, there is no way to disable Blockada outside of launching the app.

Extending the functionality of the existing Keep Alive notification by adding such a toggle would allow me to quickly disable Blokada prior to opening affiliate referral links (which are frequently part of blacklists) from websites such as SlickDeals.net.

**Comment by colbycdev** [comment]
There's already a quick tile to do so. Swip down twice, touch pencil, scroll, tap and drag blokada icon up, confirm

**Comment by rpeter85** [comment]
Isn't the quick tile that is accessible in the Notification pull down enough to achieve what you want?

**Comment by ogarcia91** [comment]
> 
> 
> There's already a quick tile to do so.
> To get it, swipe down twice from top of screen, touch pencil, scroll, tap and drag blokada icon up, confirm



> 
> 
> Isn't the quick tile that is accessible in the Notification pull down enough to achieve what you want?

You guys are right! I wasn't know the Quick Tile existed.

Thanks.

**Comment by colbycdev** [comment]
Welcome
