### ISSUE TITLE
About blocking StartApp advertising 

### ISSUE THREAD

**Issue by jesusgarcia2** [blokadaorg/blokada#31]
Hi, 
I wanted to notice Blokada's team that application doesn't block StartApp advertising on any Android application. Can you solve it? 
Thank you for this fantastic application and congratulations for your work. 
Regards

**Comment by kar** [comment]
Thanks for your input! We have a separate tracker for problems with ads in apps. I've added this app. You can track updates there: https://github.com/blokadaorg/apps/issues/
