### ISSUE TITLE
Build blokada from source

### ISSUE THREAD

**Issue by alexa-v2** [blokadaorg/blokada#311]
Whenever I attempted to build blokada, Gradle sync would fail stating "couldn't get property 'blokada_key_password'"
What am I doing wrong?
All I managed to do so far is import the project into Android Studio.
-------------Enviroment--------------
Ubuntu 19.04 (same issue on 18.10, 18.04)
Android Studio 3.2.1
-SDK platforms 28, 27, 22
-Gradle plugin 4.6 (that's what downloaded when I attempted to do initial Gradle sync) 

Here is a screenshot of it (Google drive link, can't figure out how to add a pic)
https://drive.google.com/file/d/1HuzoEephL63uXXdBo2_2JYYtQbKZoFLu/view?usp=drivesdk

**Comment by ant9000** [comment]
Disable apk signing in gradle configuration - see the attached patch.

You might want to setup a password store and use your own key to sign the app, instead - it is left a simple exercise for the reader.

Antonio

**Comment by colbycdev** [comment]
@ant9000 Where is said attached patch? And will Android let you install unsigned apps? 

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ant9000** [comment]
Sorry, Github preview mangled my attachment. Edited the answer, now the patch is in place.

And yes, Android lets you install unsigned apps - you explicitly tell it to trust unverified sources, install what you need and the revert to safe settings.

Antonio
