### ISSUE TITLE
Feature request: log DNS request (local)

### ISSUE THREAD

**Issue by dic1911** [blokadaorg/blokada#312]
(since I'm doing feature instead of actually reporting issue, I removed the template) 

Hello devs, first of all I'd like to thank you for this awesome app. 

Sadly I just saw the first ad after I installed blokada earlier today, I'd like to see which domain serves the ad I saw(so I can add it to blacklist manually), however I didn't see such feature in blokada

anyway, thanks for reading this request uwu

**Comment by colbycdev** [comment]
Duplicate of #178

**Comment by dic1911** [comment]
oops, sorry for didn't notice there's already a similar request
