### ISSUE TITLE
Ranking for the lists (feature request)

### ISSUE THREAD

**Issue by sarang-pitale-mpf** [blokadaorg/blokada#313]
Feature request
The app should collect and send the configured blacklist and whitelist for all users on every list download and have some ranking created to figure out the most popular list. This ranking can be displayed in the app besides the list itself and I believe this will help the users choose top 3 based on #crowdsourcing

**Comment by rpeter85** [comment]
Most probably the default list is the most downloaded :)
Other than that, Blokada doesn't collect any user related information and it won't change.

**Comment by colbycdev** [comment]
I'd like to see lists assigned based on device resources. So my 2gb ram gets Blu go maybe, and a 6gb ram, gets basic 

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rpeter85** [comment]
Having extensive list not always a good way, even if there is enough RAM in the machine. Most of the time only a small part of the domains are accessed that can be found on a list, based on the internet usage pattern.

**Comment by rpeter85** [comment]
Taking in account that Blokada doesn't collect user usage patterns, the requested feature cannot be implemented. I'm closing this request.
