### ISSUE TITLE
I want Blokada to have the option to be turned off only if you enter a password

### ISSUE THREAD

**Issue by matteocoder** [blokadaorg/blokada#314]
I'm using Blokada not only as an ad blocker, but also as a general site blocker for distracting websites. However sometimes it is very easy for me to just turn the app off and waste time anyway, making all my efforts useless. 

I think that requiring a password to turn Blokada off would introduce enough friction to avoid the temptation of doing so.

I cannot thank you enough for developing this app.

**Comment by matteocoder** [comment]
Thanks for your response @animeking9901 . I'm already using OpenDNS as an additional site blocker on all my machines, but unfortunately on Android it is still very easy to circumvent by turning off Blockada completely.

Now that I think about it, however, adding a password feature might add problems with users losing their passwords and thus add more support headaches.

**Comment by rpeter85** [comment]
@matteocoder in this case, do you still want this feature or should we discard it?

**Comment by matteocoder** [comment]
@rpeter85 Feel free to discard it.
