### ISSUE TITLE
Missing googlemail.com on whitelist blocks sending Emails

### ISSUE THREAD

**Issue by steffomix** [blokadaorg/blokada#318]
It would be nice to add "googlemail.com" to default whitelist, otherwise you can't send emails.
Thank you.

Regards
St. Brinkmann

**Comment by rpeter85** [comment]
hi,
The hostsname googlemail.com redirects to the Google account login screen, where I was able to log in and send a mail.
By default, no domain is whitelisted, only applications, but as the Gmail application didn't seem to malfunction without whitelisting it, it wasn't added to the list.
Do you use the application or only the website to send mails?

**Comment by steffomix** [comment]
I use an application to send mails: "Samsung Email".

**Comment by rpeter85** [comment]
I see. Can you try to set that application to whitelist, if that cannot send e-mails? I'm curious if the host 'googlemail.com' really must be on whitelist, as the applications shouldn't use that host.

**Comment by rpeter85** [comment]
@steffomix I'm checking in to ask if you had time to read my message.

**Comment by steffomix** [comment]
Yes, that's right. I have an old googlemail account based on googlemail.com and somehow it messed up with my main account based on gmail.com.
Sorry, it's my fault that it doesn't work and impossible to fix from your side.

However, very thanks for your really impressive effort to make you app better.

Regards
Stefan

**Comment by rpeter85** [comment]
Happy to help :) Let us know if you have further questions or you run into issues.
You can contact us on Telegram as well, that's faster: https://go.blokada.org/chat
