### ISSUE TITLE
Allow wildcards in whitelist

### ISSUE THREAD

**Issue by drzeller** [blokadaorg/blokada#319]
-->
Would like to be able to enter a wildcard in a whitelist for hosts.

I think I did my due diligence before creating a new issue:
#48 was about blacklists only
#188 had both, but discussion was on blacklist, referred to #48, and then was closed

### Steps to reproduce
1. Add new whitelist host
2. Enter host with wildcard, e.g. *.indiegogo.com
3. Get error message: This does not look correct.  Enter a domain name, like example.com

### Expected behaviour

The domain entered, and its subdomains, to be whitelisted.

### Actual behaviour

You cannot enter the wildcard host name, and therefore cannot blanket whitelist subdomains of the specified domain.

### Configuration
1. Blokada version
3.6, 101401

2. Device model
Galaxy Tab S3
Galaxy Note 8

3. Android version / ROM
Android 8.0 on Tablet
Android 9 beta on Note 8

### Questions
1. How long have you been using Blokada? 
A couple of weeks

2. How long time ago has the problem started to happen? 
Since I started using app

3.  How often does this problem happen to you?
Always

**Comment by kar** [comment]
It's been added in 4.4
