### ISSUE TITLE
Add listener that listens to network changes

### ISSUE THREAD

**Issue by sr-rao** [blokadaorg/blokada#32]
When I switch of the Mobile Data the VPN is disconnected but when I on it again, it is not connected. I will have to manually open the app every time and click on connect. However, the app still runs in background (as I have set it so) even if the mobile data is off.

So since the app is running in the background, add a listener to the network change (Wifi and Mobile Data) and then automatically switch on the VPN when mobile data/wifi is on.

Device info:
Redmi Note 4
Android 7.0 (MIUI 8.5.10 Stable)

**Comment by kar** [comment]
It already exists. Do you have "online only" set to on?

**Comment by sr-rao** [comment]
No. I have set it to on now. I will see

**Comment by sr-rao** [comment]
By the way what does that option mean? One more problem that arised is that when I switch off both mobile data and WiFi and reboot the device then the VPN did not start even after I have started the Mobile data or wifi. However if at the time of OS start if the Mobile data or wifi is on then automatically the VPN is started., Otherwise it isn't started

**Comment by sr-rao** [comment]
One doubt: when there are duplicate entries in hosts files what does the blokada do? For example if a website is blacklisted in both unified hosts and MVPS hosts does the blokada automatically cache only one copy eliminating the duplicates. Because caching of multiple entries of the same website is redundant and consume lot of memory and cpu

**Comment by kar** [comment]
This option enables Blokada to monitor your connectivity changes and react accordingly (turn itself off and on when needed).

Boot usually works but with delay, how much time you gave it after connecting?

Blokada removes redundant entries. You can select all filters you want.

**Comment by sr-rao** [comment]
Yeah! Setting the option Online only did the job. Thank you.
