### ISSUE TITLE
Standard DNS is blocking more than cloudflare

### ISSUE THREAD

**Issue by Chippel** [blokadaorg/blokada#321]
I did a little bit of testing with Firefox beta on my pixel 3 XL. 

When visiting (nsfw) p**ub for example the standard DNS service does block more trackers than the cloud DNS service. Why is that? Cloud DNS blocks 10 trackers while standard DNS is blocking like 20 trackers. I did delete my browser history and reopened the app. 

Does that mean I should using the standard DNS since it is blocking more?

**Comment by rpeter85** [comment]
The Cloudflare DNS doesn't block ads, at all.
The default/standard DNS is your ISP's DNS server or servers, it depends on them what they are blocking, it worth to reach out to them and ask about it.

Blokada only uses the DNS server you set up, has no effect on the queries accessing the DNS servers (if that query isn't redirected by Blokada, based on the list you use).

**Comment by rpeter85** [comment]
Is there anything else we can do for you, @Chippel ?

**Comment by Chippel** [comment]
@rpeter85
Thanks for asking. No the thread can be closed.
