### ISSUE TITLE
I have a Nordic hosts file you could add to Blokada

### ISSUE THREAD

**Issue by DandelionSprout** [blokadaorg/blokada#326]
Opening note: I would normally have been able to make a pull request about it instead of a mere issue report, but I couldn't figure out where Blokada stores its hosts sources and listings in the GitHub source code.

Hello, Dandelion Sprout here. I have a long history of making adblock lists for e.g. uBlock Origin, having more than 30 of them to my name (1 of them is natively included in uBO), but I've also maintained a small hosts file from time to time, as a reduced hosts version of my Nordic uBO list.

So now that I'm going through Blokada's settings for hosts files, and am seeing that there's far more such online files listed in Blokada's default settings than in other popular hosts-file tools (14, compared to 6 in uMatrix, and 3 in AdAway), as well as how Blokada is well maintained (which AdAway doesn't really seem to be), I figured that I could ask if you would want to add one-ish more list to those ranks?

* Title: Dandelion Sprout's Nordic Filters (The "hosts" version)
* Subscription address: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/AdawayHosts
* Description: This hosts file has special focus on Norway and Denmark, and chiefly blocks scam and phishing domains, as well as some ad and malware domains.

Notes:
* If my suggested title is too long for Blokada's settings, you can shorten it to "Dandelion Sprout's Nordic Hosts"
* If 211 domain entries is too short for inclusion in Blokada, I could try to negotiate a merging of my hosts file and [*Frellwit's Swedish Hosts File*](https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt), which'd bring it to just north of 500 entries.
* If Blokada supports multiple addresses for hosts files, I have active mirrors of my hosts file [here](https://repo.or.cz/FilterMirrorRepo.git/blob_plain/refs/heads/master:/NorwegianExperimentalList%20alternate%20versions/AdawayHosts) and [here](https://gitlab.com/DandelionSprout/adfilt/raw/master/NorwegianExperimentalList%20alternate%20versions/AdawayHosts).

### Configuration
1. Blokada version
3.6 Release

2. Device model
Lenovo K5 Vibe

3. Android version / ROM
LineageOS 14.1 (Android 7.1.2)

### Questions
1. How long have you been using Blokada? 
Two days.

**Comment by rpeter85** [comment]
Hello,
Good catch, this file isn't on the list right now. However, if we add all the regional filters, the list would contain a lot of regional lists, most of them used by only a small number of users. Keeping more lists also mean more housekeeping, checking if all of them up-to-date and available.
We will consider adding regional files, but don't know when it will happen.
