### ISSUE TITLE
The link to Dan Pollock's list should be changed to HTTPS

### ISSUE THREAD

**Issue by DandelionSprout** [blokadaorg/blokada#327]
When browsing through the `(n) in blacklist` menu in the Blokada app, I've noticed that the link to *Dan Pollock's hosts file* still begins with `http://someone(...)`. However, that website began using HTTPS about a year ago, as can be seen in https://someonewhocares.org/hosts/hosts. I therefore request that the link to it (and presumably also the source link for when Blokada looks for updates from it) is changed accordingly.

### Configuration
1. Blokada version
3.6 Release

2. Device model
Lenovo K5 Vibe

3. Android version / ROM
LineageOS 14.1 (Android 7.1.2)

### Questions
1. How long have you been using Blokada? 
Two days.

**Comment by rpeter85** [comment]
Pull request to change to HTTPS is created, waiting for merge.

**Comment by rpeter85** [comment]
PR merged, link updated.
