### ISSUE TITLE
Blokada returns to the Get involved screen from the Translation details page after a few seconds

### ISSUE THREAD

**Issue by WinDanesz** [blokadaorg/blokada#33]
Whenever I click on the  < > Get involved button or choose it from the drop down menu, then click on the "You'll find details here" link under the Translate section, the App displays the Translating Blokada article, but suddenly returns to the previous page after about 4-7 seconds.

Attached a video made with AZ Screen recorder, reproducing the problem.
[Blokada_problem.zip](https://github.com/blokadaorg/blokada/files/1247117/Blokada_problem.zip)

My device:
Xiaomi Redmi Note 4 Global
MIUI Global 8.5 stable
Android verison: 7.0 NRD90M

**Comment by kar** [comment]
This is a great report, thank you! Will be fixed in the next release.
