### ISSUE TITLE
Blokada being closed

### ISSUE THREAD

**Issue by Imparium** [blokadaorg/blokada#330]
### Steps to reproduce
1. Have a Xiaomi Redmi 6 device with MIUI Global 10.2
2. Clean recent apps even with "Keep Alive" option. Even with disabled xiaomi's save energy config.

### Expected behaviour
Blokada not being closed.

### Actual behaviour
Everytime I clean the recent apps, Blokada is killed.

### Configuration
1. Blokada version
3.6

2. Device model
Xiaomi Redmi 6

3. Android version / ROM
MIUI 10.2
Android 8.1

### Questions
1. How long have you been using Blokada? 
Some days.

2. How long time ago has the problem started to happen? 
It never worked correctly.

3.  How often does this problem happen to you?
Always.

**Comment by rpeter85** [comment]
Hi,
The system kills the application. On the recent app screen lock it into memory.
The lock should be in the top right corner of the preview window.

**Comment by Imparium** [comment]
Gosh you are a savior <3

**Comment by Imparium** [comment]
I think this could be added to the FAQ. Not everyone knows about that feature.

**Comment by blubbsy** [comment]
you really are a savior. I was trying so much to avoid this, and then it is that simple! i though that the lock is only there to not close the app when you close all other applications, didnt know that this also avoids that the system kills the app...
