### ISSUE TITLE
FireStick Bugs

### ISSUE THREAD

**Issue by Thomas499** [blokadaorg/blokada#331]
Been using Pi Hole for a while. Almost everyone who comes over to the Frat house mentions they want me to set up their routers to block the ads. But setting up a Raspberry Pi is a pain, and cost a lot. Recently a buddy mentioned the Blokada for firestick and I have been testing it for a week or so. I read that you were working on a DNS sever like app similar to Pi Hole and that would be a perfect network wide solution that would be easy to implement for all my friends who already have fire-sticks. Whats even better is the raw speed that the firestick has, Quad core 1.7 GHz processor. The raspberry pi 3 B+(highest end raspberry pi) only has a quad core 1.4 GHz processor and the raspberry pi 2 B+ (which is what I am using to run pi hole) only has a quad core 900 MHz processor. The firestick is half the price, has a much faster processor and everyone already wants one to watch movies. It is perfectly logical to assign the firestick in the guest bedroom as a personal DNS server for the entire network so that phone processing isn't slowed down to run the DNS on the phone side and doesn't use the phones battery power for the look up in curries and downloading newest list. I am very excited about having a firestick replace the pi hole, given the difference on time required to get the system set up and cost. 

While waiting on the DNS server addition, I started installing blokada on my friends 4k firesticks. I noticed a few bugs. I did not list the issues that I believe you are already aware of as the roadmap shows firesticks are an upcoming project and many issues which warrants this upcoming addition are pretty easy to identify. I only listed the issues that I believe you may not be aware of. 

**Issue 1** - Custom Files are not supported. First, you can not select hosts file on firestick. There is an issue with the work around. First, work around is downloading blokada onto phone, using the phones keyboard to quickly enter all the custom links and get upload the custom files that you want. Then export the settings to the download folder, then use filezilla to save the file setup on computer, to easily transfer the file quickly to each firestick using ES file explorer. Then import the file through Blokada. This transfers all the custom list and even the custom files which makes distribution of the blokada custom setup very quick. This will work for transferring the custom list but the problem is that blokada says the custom files do not appear to contain host names. 

**Issue 2** - Using to many links results in many host not showing up. I think the issue is that the cleanup which removes duplicates does not happen until the end, so even though if you go into advanced and it says it can store 900,000 host, you will actually consider yourself lucky to get 500,000. If you have 500,000 host already adding one more list can actually result in only 20,000 total host being saved.  I think what happens is that during the consolidating blocklists process, when it is capturing all the host on all the list, the max number of host caps out before the clean up duplicates process occurs. When this happens I think it completely empties out the existing list and starts over rather than just over riding the first on the list. I have noticed this on my android phone android 5.1.1 as well. The most logical solution to this would be to have it "clean up duplicates" during each addition (each link that is added immediately) rather than collecting all the host names from each link then cleaning up at the end after all the host from all the links are collected. 

**Issue 3** - No way to quickly identify which links are causing problems. You can't see which host are blocked in real time, and you can't tell which links are the culprits. Pi hole shows the past 10 pages of blocked hosts which allows you to quickly debug which host you need to whitelist to fix the problem of why suddenly your favorite website isn't opening. What pi hole doesn't do, which would be a very helpful is to have a counter show which links list how many webpages that you have in your whitelist to show which links are causing the problems. If one link is the culprit of listing 10 host that you had to whitelist, then you can quickly figure out that the link is more trouble than it is worth. 

**Issue 4** - This is a problem identified on pi-hole, but I suspect if not considered it will happen on the blokada project so I wanted to bring it to attention sooner than later. If your list is massive, and you have a lot of devices connected to the internet using the DNS server, then the pi hole gets backed up on cache and starts deferring the look ups straight to the listed DNS server that the pi hole uses. While it is logical, it doesn't have any way to identify how many request are skipped. Last night, I added a rather large list to the Pi hole and everything worked fine for many hours. Later that night sites which had worked minutes before randomly started showing up as blocked. Trying to figure out why they worked one minute then didn't the next, I identified that the block list was over 1 million and 32 smart devices were hounding the pi hole. I assume the size of the block list and the number of request forced the pi hole to forward some the request straight to the DNS, which would explain why it worked for a while, then when traffic was lessened the pi hole started processing a larger percentage of the request which would explain why the websites suddenly started being blocked. If blokada is only used on the device it is installed on, this probably won't be an issue. But if used as a local network DNS like pi hole is used for, it would be nice to be notified what percentage of request are not processed and sent straight to the main DNS sever used by blokada. 

Other recommendations 

**Recommendation 1** Add wildcard and regex so that user can block sites like doubleclick without using a lot of memory to have a list list each and every possibility. 

**Recommendation 2** Add functionality to save number of times each hosts was blocked. Then add functionality so that if the max number of host is reached, to start deleting host from 1. the list that provides the least value per number of host listed in it but taking into consideration how long the file has been used. 2. not deleting the host that have been blocked on the network before. - Also, add option of user saving a list of host that have been blocked on the network so that list can be easily transferred to other fire sticks. 

**Recommendation 3** Copy every feature from Pi Hole. College students love to gain experience for their resumes, ask around for students willing to covert the linux code used in pi hole to kotlin for android. I will see if I can get a few students to help from the local universities. 

**Recommendation 4** Noticed a few people complaining about data usage on limited plans. Could easily create a premium version which cost some amount or whatever and saves their list on a cloud. Then when it comes time for the firestick to update, have it ping the cloud then the cloud would update its list, identifying what changed, then send only what is supposed to be changed to the firestick. Would really cut down on data. Wouldn't take much to implement that on the list that are displaced on blokada by default.  I don't see a point in forcing the host list to be completely re-downed every day on every single device.

**Comment by PrintableCharacter** [comment]
Fire sticks are supported since v4

**Comment by Thomas499** [comment]
Well firesticks still have three issues (that I found before I was banned from Telegram thus lost motivation to help) 

1st - Once you get to the screen below, only way to exit it is to clear data or do a fresh install. You can hit left and right and thats how you switch from Default DNS to VPN Account at the bottom. But if you hit up, down, back, whatever it does nothing so you are pretty much stuck on that page

![image](https://user-images.githubusercontent.com/38442058/60270009-5fc03000-98a4-11e9-86ec-1de0428b036b.png)
![image](https://user-images.githubusercontent.com/38442058/60270020-651d7a80-98a4-11e9-8ac3-5da4758cc11c.png)

2nd - when you click the could be improved click for details it starts this slow white circle starting from the shield in the upper right corner. Extremely slow and once that starts blokada freezes none of the buttons will make it do anything until first circle exits page (takes about 90 seconds). clicking right after that makes that page come up that shows default dns servers at bottom of screen. Even the back button won't work at this point. If you exit the app and re-open it thousands of circles start appearing. Each extremely slow. Some of the circles disappear before they make it to the "how to use ui" section. Others keep going after that. If you click the down button while 100 circles are on the page it will clear all of them. But if only 10 or circles are on page and you click down button it doesn't clear them. 

3rd - If user clicks activate account the loading screen never goes away. 
![image](https://user-images.githubusercontent.com/38442058/60270492-600cfb00-98a5-11e9-9d8a-8e08ef164916.png)


If user hits back button at this point this blurred out screen comes up. The blur isn't from the camera I couldn't make out what the screen said when looking at tv directly. 
![image](https://user-images.githubusercontent.com/38442058/60270545-7ca93300-98a5-11e9-85b0-1ec17ec8f87d.png)


Often, the only way to fix the issue is to clear data on the app or do a fresh install or completely reboot the device. Exiting the app then re-opening it doesn't fix the issue and the back button doesn't do anything. 

Personally, I hate the slow motion circles that take two minutes to exit the page. I also hate that i am banned from telegram.

**Comment by kar** [comment]
4.1 fixes those things.
