### ISSUE TITLE
3.7 not being applied

### ISSUE THREAD

**Issue by terrorist96** [blokadaorg/blokada#332]
### Steps to reproduce
1. Download 3.7 update

### Expected behaviour

For 3.7 to be applied

### Actual behaviour

Opening Blokada keeps opening the 3.6 version and keeps telling me there's an update available despite installing it several times now. Tried clearing cache but that didn't help.

### Configuration
1. Blokada version
3.6/3.7

2. Device model
Note8

3. Android version / ROM
8.0

### Questions
1. How long have you been using Blokada? 
Over a year

2. How long time ago has the problem started to happen? 
Just now

3.  How often does this problem happen to you?
Just now

**Comment by rpeter85** [comment]
Restart the phone and let us know what is shown in the app.

**Comment by terrorist96** [comment]
Restarted. Here's the app.
![screenshot_20190219-110045_blokada](https://user-images.githubusercontent.com/12802056/53028960-e916b000-3435-11e9-99fc-0838b89e0840.jpg)

**Comment by terrorist96** [comment]
I deleted the blokada-update.apk file(s) in my download folder and tried to download the update again and it updated successfully now. Still there's some bug that caused this to begin with.

**Comment by animeking9901** [comment]
Export settings uninstall then reinstall from the 3.7 apk

**Comment by animeking9901** [comment]
Interesting. Ive not seen that before
