### ISSUE TITLE
Latest Blokada not blocking ads at all. (V3.7)

### ISSUE THREAD

**Issue by thanuj10** [blokadaorg/blokada#333]
### Steps to reproduce
1. Open Blokada 3.7 and set it up
2. Activate Blokada
3. Ads are not blokada

### Expected behaviour
Ads must be blocked when Blokada is set up.

### Actual behaviour
Ads not being blocked.

### Configuration
1. Blokada version - 3.7(Latest Release)

2. Device model - Nokia 6.1 Plus

3. Android version / ROM - Stock ROM on January Patch/9.0 Pie

### Questions
1. How long have you been using Blokada? 
About a year

2. How long time ago has the problem started to happen? 
Yesterday

3.  How often does this problem happen to you?
Always Blokada is on

**Comment by rpeter85** [comment]
In Chrome? Disable async DNS.
For such reports you can join our Telegram channel, there you get the answer much earlier.

**Comment by thanuj10** [comment]
Version 3.6 works just fine. I thought it was due to DNS fallback but switching that off, Refreshing and restoring the deafult DNS servers did not work.
No other settings were changed though.

**Comment by rpeter85** [comment]
Join Telegram, you will get the answer. All those were revolved overnight.

**Comment by thanuj10** [comment]
Okay.

**Comment by areynaldos** [comment]
@thanuj10  how was it fixed? I am getting the same problem.

**Comment by thanuj10** [comment]
@areynaldos Install the latest available version from GitHub or F-Droid, Turn off async DNS resolver in Chrome and be sure to clear cache data of Blokada
