### ISSUE TITLE
Blokada updates blocklists on every restart (even if configured once a month)

### ISSUE THREAD

**Issue by GoodSoulGermany** [blokadaorg/blokada#335]
### Steps to reproduce
1. Start blokada, configure to update once a month.
2. Restart tablet, phone, <android device>
3. Observe blokada after start. You will see that blokada fetches all blocklists again.
4. Restart device again, after that start blokada again. Blokada fetches all blocklists again.

### Expected behaviour
When I configure to update the blocklist once a month it should update once a month and not on every reboot/restart.

### Actual behaviour
Blokada always updates blocklists on start/restart.

### Configuration
1. 3.7.022000

2. Device model
OnePlus 6, Galaxy Tab A6, Genymotion Emulator

3. Android version / ROM
Pie (9), Orea (8.1)

### Questions
1. How long have you been using Blokada? 
Since the early days.

2. How long time ago has the problem started to happen? 
Noticed it with version 3.5 I guess, not sure.

3.  How often does this problem happen to you?
Always.

**Comment by rpeter85** [comment]
There was a finding yesterday, that at start-up time Blokada reports "updating" the lists (while when it actually downloads is says "Downloading lists"Ö, however what happens actually is that it just loads the list into memory from the storage, no update started. The first "loading" message should be "loading", not the current, "Updating".
