### ISSUE TITLE
Dubovszky Károly 3265 Vécs Kossuth Lajos út 32.

### ISSUE THREAD

**Issue by Dubovszky** [blokadaorg/blokada#336]
### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by Dubovszky** [comment]
Nem tudom letölteni a Blokadát, 2-3 hónapja  megvolt, aztán törlődött. Nagyon szeretném , ha újra lenne!!
Segitsetek, Samsung  T561N Tab E 9.6 3G eszközöm van, 4.4.4 versió.Mire a telepitésig jutok, nem engedi  letölteni. Kérem, segitsetek, üdvözlettel, Dubovszkyné Éva

**Comment by rpeter85** [comment]
Is there anything we can help you with? Why did you provide your address?

**Comment by Dubovszky** [comment]
Nem tudok angolul, kérlek, forditsatok magyarra! Köszönöm.
Peter <notifications@github.com> ezt írta (időpont: 2019. febr. 27., Sze
16:07):

**Comment by rpeter85** [comment]
Nehéz érteni a fordítádi kérelmet magyarul ha nincs valaki aki beszéli a nyelvet.
https://blokada.org
Innét lehet letölteni a legújabbat. Ha android 5 előtti rendszer fut akkor egy régebbi verzió szükséges, a 2.x-es.

**Comment by rpeter85** [comment]
Megoldódott a probléma?

**Comment by Dubovszky** [comment]
Kedves Péter!


Akármit próbálok, nem sikerül letölteni a Blokadát. A tableton nincs is
olyan opció - policy, uknow -, mint az ajánlott  kis videon.
Jelenleg is tölti le a tablet, de mire a telepitésig jut, azt már nem
hagyja.Teljesen el vagyok keseredve, sokkal jobb volt netezni a Blokadával,
de valahogy törlődött.Akkor nem is tudom, hogy sikerült letölteni.
Tudsz valahogy segiteni?


Üdvözlettel, Dubovszkyné Éva

Peter <notifications@github.com> ezt írta (időpont: 2019. febr. 28., Csü
8:24):

**Comment by rpeter85** [comment]
A rendelkezésre álló információk kevesek. Innét lehet direktben letölteni:
https://github.com/blokadaorg/blokada/releases/download/3.7.022000/blokada-v3.7.apk

Utána a mappában ahova az eszköz letölti a fájlt csak rá kell koppintani és azzal telepítenie kell.

**Comment by Dubovszky** [comment]
Kedves Péter!



Órák óta tölti a tabletom a Blokadát (a képernyő tetején mozog a kis nyil).
Ez normális dolog, ennyi ideig ? Közben a Chrome átirányitott a Play
Áruházba, ott meg azt irták ki, hogy az eszköz nem kompatibilis ezzel a
verzióval.
Most mit tegyek!?


Üdvözlettel, Dubovszkyné Éva

Peter <notifications@github.com> ezt írta (időpont: 2019. febr. 28., Csü
10:08):

**Comment by rpeter85** [comment]
Hányas verziójú android van a tableten? Ezt a rendszerbeállítások között lehet megtalálni.
A Play Store-on a reklámblokkoló nincs fent, a Google tiltja, ott csak egy DNS váltó található meg.
Az nem normális, hogy órákig tölti le, pár mb a fájl, nem több.

**Comment by Dubovszky** [comment]
Kedves Péter!



A tabletem versiója  4.4.4.


Üdv., D Éva

Peter <notifications@github.com> ezt írta (időpont: 2019. márc. 1., Pén
15:39):

**Comment by rpeter85** [comment]
Kedves Éva!

Arra a verzióra ezt töltse le: https://bitbucket.org/blokada/blokada/downloads/blokada-origin-v2.2.3.apk

Az újabb verziók már valóban nem kompatibilisek sajnos.

**Comment by Dubovszky** [comment]
Kedves Péter!



Letöltöttem, kiadott egy hosszu formátumot, az alján:  Telepités
Rányomok, semmi. Nem tudom, mi lehet a baj.Már kikészit ez a dolog, 3 napja
próbálkozok és semmi.
Elnézést kérek, hogy ennyit zavarok.

Üdv. D Éva

Peter <notifications@github.com> ezt írta (időpont: 2019. márc. 1., Pén
15:47):

**Comment by rpeter85** [comment]
Ha van olyan program vagy alkalmazás ami els@rgítja a kijelzőt vagy csak csinál egy képernyőátfedést, akkor azt ki kell kapcsolni.
Más ötletem nincs, távolról többet nem tudok segíteni sajnos.

**Comment by Dubovszky** [comment]
Kedves Péter!


Nagyon szépen köszönöm az eddigi segitséget, talán a géppel van valami hiba.
 Pl., ha bluetoothal küldök át a telóról a tabira, csak a fotókat engedi,
az alkalmazásokat nem. Akkor is kiadja azt a felsorolást, a végén a TELEPIT
szóval,és hiába nyomom le, nem telepit.

Még egyszer köszönök mindent, szép napokat kivánok, D Éva.

Peter <notifications@github.com> ezt írta (időpont: 2019. márc. 1., Pén
17:25):

**Comment by Dubovszky** [comment]
Kedves Péter!



Csak azért irok, mert sikerült végül letölteni a Blokadát!!! Én olyan
boldog vagyok - mit kinlódtam vele napokig. 2.2.3 verzió, tökéletesen
működik, a kis kulcs ábra is fenn van a képernyő tetején, reklámok
eltűntek, minden sikerült.
Még egyszer köszönöm a segitséget, legyen mindig szép napja!


Dubovszkyné Éva

Károly Dubovszky <kdubovszky@gmail.com> ezt írta (időpont: 2019. márc. 1.,
Pén 17:41):
