### ISSUE TITLE
[Feature Request] I want to be able to disable Blokada based on location

### ISSUE THREAD

**Issue by PaxVobiscuit** [blokadaorg/blokada#340]
I have router-based ad blocking at home and would like to be able to disable Blokada to reduce resource consumption.  It could either be location based detection or SSID based detection.

Blokada version 3.7 (022000) Official

Samsung S9+ SM-G965U

Android 9

Using Blokada for about 1 month

**Comment by rpeter85** [comment]
Doesn't #56 cover this request? With Tasker you can automate everything.

**Comment by PaxVobiscuit** [comment]
That would require installing another app, which defeats the desire to reduce resource consumption.

**Comment by miwie** [comment]
I back this feature request!

**Comment by animeking9901** [comment]
SSID based would be great! I use AdGuard DNS on my home router so it seems counterproductive to use blockada and adguard. I mainly use blockada in Mobile data

**Comment by kar** [comment]
In 4.3 you'll be able to do this using Tasker. At least it's a first step. A more advanced funcionality will have to wait a bit more.

**Comment by peterroth** [comment]
I checked and disabling Blokada based on location is possible using Taster. I'm closing this ticket.
