### ISSUE TITLE
Why white-listing is required for some applications?

### ISSUE THREAD

**Issue by renaudcerrato** [blokadaorg/blokada#341]
Android Developer here. I'm a user of Blokada (Adblock flavor), and I'd like to contribute to it. I went through the source code, and I can't understand WHY some applications (like Google Play) needs to be white-listed in order to work, **even if Blokada is patched to not filter anything (forwarding only)**.

The VPN is advertising itself as a DNS server (on address xxx.xxx.xxx.2), and ONLY route packets coming to that address through him, I can't see what could go wrong on such apps if DNS packets are correctly forwarded.

Anyone?

**Comment by renaudcerrato** [comment]
Digging deeper, IPV6 disabled, I'm seeing ICMP packet(s) discarded by Blokada. Could it be related?

```
[IPv4 Header (20 bytes)]
      Version: 4 (IPv4)
      IHL: 5 (20 [bytes])
      TOS: [precedence: 6 (Internetwork Control/ECP)] [tos: 0 (Default)] [mbz: 0]
      Total length: 576 [bytes]
      Identification: 53819
      Flags: (Reserved, Don't Fragment, More Fragment) = (false, false, false)
      Fragment offset: 0 (0 [bytes])
      TTL: 64
      Protocol: 1 (ICMPv4)
      Header checksum: 0x2dbd
      Source address: /203.0.113.1
      Destination address: /203.0.113.2
    [ICMPv4 Common Header (4 bytes)]
      Type: 3 (Destination Unreachable)
      Code: 3 (Port Unreachable)
      Checksum: 0x791b
    [ICMPv4 Destination Unreachable Header (4 bytes)]
      Unused: 0
    [IPv4 Header (20 bytes)]
      Version: 4 (IPv4)
      IHL: 5 (20 [bytes])
      TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
      Total length: 1052 [bytes]
      Identification: 64620
      Flags: (Reserved, Don't Fragment, More Fragment) = (false, true, false)
      Fragment offset: 0 (0 [bytes])
      TTL: 64
      Protocol: 17 (UDP)
      Header checksum: 0xc25f
      Source address: /203.0.113.2
      Destination address: /203.0.113.1
    [UDP Header (8 bytes)]
      Source port: 53 (Domain Name Server)
      Destination port: 44335 (unknown)
      Length: 1032 [bytes]
      Checksum: 0xdc64
    .payload   <--   Thread[tunnel-11,5,main]
```

**Comment by kar** [comment]
I can't remember right now exactly, but afair it's related to some android bug. if you search through closed issues here for Google play, its probably there.

**Comment by renaudcerrato** [comment]
Yeah, I searched the issues, but I can't find it. I'm also suspecting an Android bug, but I'd love to find an official reference to it.

The addRoute may be the culprit since real VPN applications doesn't exhibits such behavior.

**Comment by renaudcerrato** [comment]
It seems the Android related bug is [this one](https://issuetracker.google.com/issues/37105245). Marked as fixed, though? [Another one](https://issuetracker.google.com/u/0/issues/111574523). This is related to the ConnectivityManager...
