### ISSUE TITLE
Other-DNS not using local DNS provided by DHCP

### ISSUE THREAD

**Issue by thecanadianroot** [blokadaorg/blokada#342]
### Steps to reproduce
1. Install or upgrade blokada to version 3.7
2.
3.

### Expected behaviour

Other-DNS should use DNS obtained by DHCP of local network

### Actual behaviour

Other-DNS uses cloudflare's DNS

### Configuration
1. Blokada version
3.7

2. Device model
LG G7 One (Android One device) - LM-Q910UM

3. Android version / ROM
Android Pie (9), January 1 2019 security path

### Questions
1. How long have you been using Blokada? 
About a year

2. How long time ago has the problem started to happen? 
Since 3.7 release

3.  How often does this problem happen to you?
Haven't been able to use Other-DNS on the 3.7 version without it defaulting to cloudflare's DNS even though local DHCP provides a local DNS server

**Comment by rpeter85** [comment]
It is expected on 3.7. The "DNS fallback" option sets Cloudflare DNS if the devices gets a local (192.168.0.0/32) address. It was set due to #284.
Solution: turn off DNS fallback.

**Comment by thecanadianroot** [comment]
Oh... Haven't seen that option, my bad
