### ISSUE TITLE
Recommending inclusive alternatives to UI wording

### ISSUE THREAD

**Issue by gkrishnaks** [blokadaorg/blokada#343]
Thank you for the fantastic application. I use it and actively promote it to other people. I wished to highlight something we have in UI unintentionally because it's in common usage.

### Steps to reproduce
1. See main UI page and other UI pages
2. markdown files in repo

### Expected behaviour
I recommend that you consider inclusive alternatives like "BlockList/AllowList' instead of BlackList and Whitelist (refer etymology of these words). Or any other word pair that makes clear and concise semantic meaning of BlockList and AllowList words. 

### Questions
1. How long have you been using Blokada? 
5 months. Earlier I used Netguard with hosts for a long time. 

Thank you for creating and working on this application.

**Comment by kar** [comment]
Good feedback. It's going to be "Blocked" and "Allowed" in v4
