### ISSUE TITLE
After upgrading to Blokada 3.7 it will block all normal traffic unless disabled/uninstalled.

### ISSUE THREAD

**Issue by motorious1** [blokadaorg/blokada#344]
After upgrading to Blokada 3.7 it will block all normal traffic unless disabled/uninstalled.

### Steps to reproduce
1.  (Oreo 8.1) Huawei Honor 5x
2. Upgrade from 3.6 (101900) to 3.7
3. Only Modified Advanced Settings from default:
   Lists download frequency= Once a week
   Keep Alive = True
4. 2 in Blacklist:
    Energized Blu (recommended)
    Goodbye Ads by Jerryn70
5. Connect to WiFi, open any app that needs internet access (browser, reddit, pandora, etc.)
6. App says no network detected or failed to load
7. Disable all blacklists  "0 Blacklists" displayed (still no traffic)
8. Completely disable Blokada (everything works)
9. Uninstall 3.7 and install previous version from October 2018 (everything works flawlessly)
10. 3.7 don't work for me ya'll....

### Expected behaviour
Apps to work normally and access internet/www

### Actual behaviour
Any app that needs access to the web fails, cannot communicate, no network etc.

### Configuration
1. Blokada version 3.6/7

2. Device model
Huawei Honor 5x

3. Android version / ROM
LineageOS 15.1 MicroG March 12, 2019 build  Oreo 8.1

### Questions
1. How long have you been using Blokada? 
Almost a year I think...?

2. How long time ago has the problem started to happen? 
Within the last day or so

3.  How often does this problem happen to you?
Everytime I use 3.7 and it is enabled.  Rebooting, uninstalling/reinstalling 3.7 doesn't help.

**Comment by rpeter85** [comment]
Did you restart the phone after the update?

**Comment by motorious1** [comment]
I don't remember if I rebooted after the update. (Shouldn't have to IMHO) but I uninstalled 3.7 completely and reinstalled taking the 'update' completely out of the equation and it didn't work no matter what I did.

**Comment by rpeter85** [comment]
Only on wifi, mobile or both? What DNS did you get in the DNS section?
Is Blokada installed now on your device?

**Comment by motorious1** [comment]
Both. Default DNS.

Yes, 3.6 is currently installed and works great!

**Comment by rpeter85** [comment]
Ok. Can you do some further tests with 3.7 and report if the issue is persistent? If you still face the same behaviour, can you disable "DNS fallback" and run a test again?

**Comment by motorious1** [comment]
I'm not seeing a option to disable "DNS fallback" is that in the Blokada app or somewhere in the Android system setting somewhere?

**Comment by rpeter85** [comment]
You can find it among the Advanced settings in v3.7.

**Comment by motorious1** [comment]
Gotcha...
Updated to 3.7, rebooted...
open local terminal...
(on wifi)
$ su
# ping google.com
ping: unknown host google.com      <<<-------------
(on 3G)
# ping google.com
(after approx 30-45sec wait:)
PING google.com (172.217.14.174: icmp_seq=11 ttl=53 time=1065ms
PING google.com (172.217.14.174: icmp_seq=11 ttl=53 time=1211ms
...
(open browser "Firefox Focus" still on 3G network)
navigate to google.com...
nothing loads
eventually times out with "Unable to connect screen"
disable blokada...
click "try again" in browser screen..
page loads very fast
re-enable blokada on 3G network....
clear browser cache
page loads very fast...(must have been a bad cellular connection)

switch to wifi
page doesn't load (blokada 3.7 active default setttings)
(disable DNS fallback)
no change...google.com fails to load and cannot ping domain

# netstat -nr
Destination      Gateway        Genmask          Flags       MSS      Window       irtt  iface
10.77.XXX.0     0.0.0.0         255.255.128.0       U            0             0             0     wlan0
10.180.XX.XX   0.0.0.0         255.255.255.252   U            0             0             0     wlan0
203.0.113.0     0.0.0.0         255.255.255.255   U            0             0             0     tun0

I was going to try the nslookup or traceroute but apparently those aren't installed/available to me....

**Comment by motorious1** [comment]
Don't know if this helps, but My DNS on wifi are the local DNS when using the company's 802.1X EAP network:

DNS:
10.236.N.NN
10.236.N.NN

I tried selecting different DNS in blokada (AdGuard DNS for example) and the DNS never changes in my wlan0 settings.

**Comment by The-Michael-R** [comment]
I think I have the same problem. Unfortunately I don't know the other end of the the "WLan cable" as it is a hotel hot-spot. It worked well on other hot-spots without any problems.

But even with the one I have trouble with seemed to work for some time. And enabling of Blockada on that hot-spot takes quiet some time. Also I noticed that during that time the WLan symbol shows an exclamation mark.

Sorry I can't provide more information as I'll be out of reach very soon.

**Comment by motorious1** [comment]
> Ok. Can you do some further tests with 3.7 and report if the issue is persistent? If you still face the same behaviour, can you disable "DNS fallback" and run a test again?

Been awhile...I tried this , no luck.  Any other suggestions I can try to troubleshoot this issue further?
