### ISSUE TITLE
Sliders for Blocklist and Nameserver Settings go to "OFF" unecpected / Settings not accepted

### ISSUE THREAD

**Issue by bitranox** [blokadaorg/blokada#345]
### Steps to reproduce
1. go to Settings Menue -->  Nameservice
2. Switch off Default DNS, Switch on Cloudeflare and Quad9
3. leave the menue, and re-enter the menue 

same on Blocklists. You switch one on, another one is off after re-entering the menue.

### Expected behaviour
Sliders should reflect the correct Settings

### Actual behaviour
Sliders show erraticly wrong values - it seems not to accept some settings - sometimes.
If You try several times it "might" accept the settings You want. Annoying !!!

### Configuration
1. Blokada version 3.7

2. Device model
Samsung S9+, Note3

3. Android version / ROM
LineOs (on Note3) and Stock Rom on the S9+

### Questions
1. How long have you been using Blokada? 
1 Day

2. How long time ago has the problem started to happen? 
from Day 1

3.  How often does this problem happen to you?
always

**Comment by rpeter85** [comment]
You can enable 1 DNS service, can't use 2 at the same time, thus, only one can be enabled.
The lists, when you enable them in Blacklist, are downloaded and merged, which takes time, this is why you can see what you do, most probably.

**Comment by bitranox** [comment]
> You can enable 1 DNS service, can't use 2 at the same time

ok, but then radio list or radio button would be the right choice for the gui.
if You have many sliders, the user will think that he can use more then one (like on the blocklists).
If You want to keep the sliders, make sure all others slide to "off" if You enable another one - but I think thats not a good choice for the GUI

The nameservers settings are very limited : 
- why we can only use one predefined Setting ?  cloudflare + quad9 would make perfect sense, for instance.
- why there are only 2 Nameservers / Settings allowed ? 
- if You would be able to select "Standard" AND Cloudflare then You can get rid of the extended Setting "DNS-Fallback"
- I miss the setting to ask Nameservers in Order, or all parallel (fastest wins) (Android Limitation ?)
(and to be able to slide the entries in the Nameservice Menue up and down, to define the order in which the nameservers are queried.

And for the Blocklist Settings its really annoying - just try to delete some, select many, and go back.
There are some GUI Errors (delete icons disappear on some entries sometimes) and sliders go to "off" erraticly.) 
If You need to merge in the backround before any other action, then You should make a popup and block further entry.
Just try : put all sliders for the blocklist to "on" and go back.
The behaviour is not really predictable.

**Comment by rpeter85** [comment]
The sliders are retired in v4, so that won't cause confusion.

In case you enable 2 different DNS services, what would be the priority? So, for example, you enable Cloudflare **and** Quad9, which would be the first to resolve a hostname?

**Comment by bitranox** [comment]
there are two possibilities : 
#1 - ask nameservers  by order (You might slide up/down the entries in the Nameserver List) 
#2 - ask nameservers in parallel - the first answer is taken (unless the anser is "not found", then we wait until all Nameservers say "not found" or timeout)
that would require one more setting in "extendedSettings" - like : ask Nameservers parallel / in Order

**Comment by bitranox** [comment]
and i would still suggest to aff "type-B" - have You aver tried to set different nameserver ? 
Sometimes it takes the Setting, sometimes not ... 
I switched off all Nameservers and just selected "Standard", go back - and bang - still cloudflare the active nameserver.
Now I wait about 30 Sekonds after each change of settings, tht somehow helps.

**Comment by rpeter85** [comment]
Turn off the "DNS fallback" and test then. It may happen Blokada gets a 192.168.0.0/32 IP address and then it sets Cloudflare automatically.

**Comment by bitranox** [comment]
DNS Fallback WAS switched off. Because of Split-DNS I set now "internal Nameservers" on and after that "DNS Fallback" on.
However - do You agree that it is somehow behaving not right ?

**Comment by Thomas499** [comment]
> However - do You agree that it is somehow behaving not right ?
Just try to set all Blacklists to on - and then slide up/down - some sliders go back to "off" position itself.
Its almost impossible to set what You want.

I had a similar experience. The fix was to only make two or three changes at a time, then hit the back button, let it reload, then make the rest of the changes. Once reloaded, if the changes sticked, they will stay the same. Thus, you can make more changes without risking the previous changes not being saved. If you make to many changes at once without letting it reload for some reason the system goes nuts and none or some of the changes are not saved.

**Comment by bitranox** [comment]
its even worse then that. Sometimes You swich one slider "ON" and another one goes "OFF". 
weired !
