### ISSUE TITLE
Blokada randomly closes/crashes itself

### ISSUE THREAD

**Issue by farvell** [blokadaorg/blokada#346]
Hi, after I updated to V3.7, I started to notice blokada randomly closes itself. It shows the issue report window for a split second, closes and takes me back to the home screen, interfering with my phone use. (There was one time it showed the window for a good few seconds but ultimately spontaneously closed.) When it does this, it seems that blokada is actually crashing because it gets disconnected.

Also every time I open Share log it exhibits the same behaviour, showing the issue report window for a spilt second and then closes itself. But this time, blockada doesn't seem to be crashing because it doesn't get disconnected. The state of the app is perfectly preserved when reopened.

I am not sure the two problems are the same problem or separate problems. But the behaviour is definitely similar, so I put them in one report. Feel free to ask me questions if need be. Thanks.

### Steps to reproduce
It's a random crash so I haven't figured out the steps to reproduce. But regarding the crash with Share log:

1. Open blokada
2. Tap the three dots on the top right-hand corner
3. Tap Share log

### Expected behaviour

Blooada opens the issue report window and holds it until I close it. 
Or, blokada runs without killing itself for no reason.

### Actual behaviour

Blokada shows the issue report window for a split second, closes and takes me back to the home screen. 

### Configuration
1. Blokada version

3.7.022000

2. Device model

OnePlus 5t

3. Android version / ROM

Oxygen OS 9.0.4, Android P

### Questions
1. How long have you been using Blokada? 

About 2 or 3 months.

2. How long time ago has the problem started to happen? 

When I updated to v3.7, so I suppose it started a few weeks ago.

3.  How often does this problem happen to you?

Probably once a day or two. Could be less often.

**Comment by rpeter85** [comment]
Blokada isn't a suicide application, it won't kill itself, because that makes no sense.
Your system kills it to save battery, and some memory. Check your system's settings, exclude Blokada from battery optimisation.

**Comment by rpeter85** [comment]
I forgot to add: even though there is a "Keep alive" in the app, the system can override it. You can try and enable that option, but it's not guaranteed that will solve the issue.

**Comment by farvell** [comment]
Yes, blokada is of course excluded from battery optimisation. And Keep Alive is of course turned on. I think I have done all the usual, go-to measures I should first look into. This didn't happen even once on the previous v3.6. It started on v3.7, just like I wrote it. And it isn't possible that my blokada is working correctly because one of the app's features, issue report is completely useless.

**Comment by rpeter85** [comment]
In this case, did you check the log file in /Download/Blokada directory? What that say, why Blokada shuts down? Do you see OOM messages?

**Comment by farvell** [comment]
No, I haven't checked it. So I just checked it. I searched for "kill", "oom" in vain. But "error" has 13 results. Many of them say "onwifi: changed tunnel thread error, will restart after 0 ms". And there was one instance where it says "I/O error during system call, Software caused connection abort". I don't know if these are relevant. So please tell me if there are more effective ways to search in the log.

**Comment by farvell** [comment]
Oh. Now when I tap "Share log", it doesn't even open the window and the app seems to hang for a second or so.

**Comment by rpeter85** [comment]
Try to turn off "DNS fallback" in Advanced Settings and check if Blokada connects then.

**Comment by farvell** [comment]
I turned that off just a while ago. I'll see if that helps.

But I need to clarify; 
Blokada is connected most of the time. But once in a while, it shows the issue report window for a split second, closes this window without me touching the screen at all and takes me back to the home screen even when I'm using other apps, say like when I'm browsing on Chrome. And it gets reconnected after a few seconds without me doing anything with the app or the system.

And in addition to this spooky behaviour, I cannot send the log using "Share log" because, as I said, it either closes the app altogether and takes me back to the home screen, or doesn't even open the window at all.

**Comment by rpeter85** [comment]
Did you grant external storage access permission for Blokada in system settings? Can it be Blokada can't write the log, but because it crashed, tries to send the log which isn't generated?

**Comment by farvell** [comment]
Yes, I did. The current log has been recorded from March 3, 2019.

**Comment by rpeter85** [comment]
Debugging it would be more easier on Telegram, you can join with the below link:
https://go.blokada.org/chat

**Comment by farvell** [comment]
I need to first create my account on telegram and I'm not available just yet so I will join there after a while. Thanks for your directing!

**Comment by rpeter85** [comment]
Welcome. Let's see if we can resolve it on the chat.
