### ISSUE TITLE
blokada.win - inofficial website

### ISSUE THREAD

**Issue by The-Compiler** [blokadaorg/blokada#349]
Hi! When currently searching for Blokada, blokada.win shows up quite prominently:

![image](https://user-images.githubusercontent.com/625793/54903832-18a95400-4edd-11e9-83aa-1d27eddc065d.png)

(second result on DuckDuckGo, 6th result on Google)

Looking at that page, it seems to be quite deceptive. I downloaded the v3.6 APK offered there, and as expected, it doesn't match the official v3.6 release. Taking a very quick look at it (using `strings`), it doesn't contain translation updates from e2be40ecc17637ac9622e272884085219a965a5e, so it's older than 3.6.101900. It doesn't match up with the official v3.5 release either.

I assume this is some self-built thing, quite likely with some malicious code added. Unfortunately I currently don't have the time to do a more detailed analysis of their APK.

I'm aware there isn't that much you can do against it - however, I'd suggest:

- Warning about the unofficial site somewhere on the official page, and/or GitHub readme, to make it clear that users shouldn't trust it.
- Contacting Namecheap (who's the domain registrar and hoster) asking to take it down.
- Reporting it to [Google SafeBrowsing](https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en) so (hopefully) browsers start to block the page.
- Maybe getting it added to e.g. StevenBlack's blocklist (and/or others) to protect more users.

**Comment by animeking9901** [comment]
Since I don't own Blockada,I don't have the right to go to namecheap,but I've submitted it to Google SafeBrowsing,this site has been around for a while actually

**Comment by ps100000** [comment]
I just checked the hash of the older apk on the .win page. It's the official 3.4 release. For the 3.6 version a quick look on virustotal didn't find any viruses but another filename containing the build number 3.6.101401. At least on github there is no official apk for this release so this is probably a custom build. If there was a apk for this release maybe @kar can check the hash.

**Comment by kar** [comment]
it's down
