### ISSUE TITLE
Youtube with Android 7

### ISSUE THREAD

**Issue by xmiseggs** [blokadaorg/blokada#35]
Congratulations on your application is very good.
I'm in a Telegram group and there are a lot of users who like it but for some reason there are 2 with Samsung S8 and Android 7 in the Android Youtube app that appears advertising. I with Android 6 and many others have no advertising. I'll detail it for you in case you can fix it.
Thank you very much.

![photo_2017-09-05_19-06-47](https://user-images.githubusercontent.com/29940632/30073440-16a1a8b0-926e-11e7-8542-6dd0d67bbd59.jpg)

**Comment by Tadly** [comment]
Same here with a stock Nexus 6P and Android 8.
If you require further informations, let me know. I'm happy to help

**Comment by SkyzohKey** [comment]
Same with Ulefone Gemini 7.0 Nougat

**Comment by SkyzohKey** [comment]
A nice way to not have ads on YouTube i s to ditch the official app and to use NewPipe ;)

**Comment by w4tadrag** [comment]
Hey guys, I ditched the official Youtube app with the iYTBP few months ago. It's basically the Youtube app with no ads. This works on both rooted and non-rooted phones. Just download the one that applies to your phone. Here is the xda page:
https://forum.xda-developers.com/android/apps-games/app-iytbp-injected-youtube-background-t3560900


Here is the link to download the Youtube app: https://androidfilehost.com/?w=files&flid=236407 

Also if you want to login to your youtube, download and install MicroG for iYTBP v0.2.4.apk : https://androidfilehost.com/?fid=745425885120744371

Hope this helps :)

**Comment by kar** [comment]
Great advice guys. There's not much we can do about it right now, except experimenting with lists. The next release will have some more lists added, so feel free to turn them on and report back if they have any effect.
