### ISSUE TITLE
"Disconnect" option from notification menu not working properly

### ISSUE THREAD

**Issue by Max1234-Ita** [blokadaorg/blokada#352]
This bug might be similar to [#213](https://github.com/blokadaorg/blokada/issues/213)

I think there's an issue with  the menu you can access from notification: when I select "Disconnect" I would expect Blokada to stop working, instead ad-blocking is still applied.
If I wait for some time (say 20 seconds) before re-entering the previous application, often the icon in the notification goes away and Blokada stops working (as expected).

### Steps to reproduce
1. Open an app (in my case, it's the "Real Racing" game.)
2. Notice you forgot to disable Blokada (in that app, ads are part of the game since they allow to get bonuses)
3. Drag the notification bar down and  touch the "VPN enabled by Blokada" item
4. Select "DISCONNECT" and re-enter previous app (this is automatic, once the options pop-up message goes away)
5. Drag the notification bar down: most probably the Blokada icon is not present
6. Wait for some time (say 20 seconds)
7. Drag the notification bar down: the Blokada icon is there again: the app will not work properly
---------------------------------------------------------------------------------------------
8. With the desired app/game running, press the device's "Home" button and wait for the Home screen to appear.
9. Drag the notification bar down and  touch the "VPN enabled by Blokada" item
10. Select "DISCONNECT"
11 Wait for some time (say 20 seconds). 
12. Drag the notification bar down: most probably the Blokada icon is not present.
13. Re-enter previous application (i.e. from Recent apps menu)
14 Wait for some time (say 20 seconds). 
15. Drag the notification bar down: the Blokada icon is not present and the app works as expeccted.

### Expected behaviour
Blokada should be disabled as soon as DISCONNECT option is selected, and stay like that until user re-enables it.

### Actual behaviour
Blokada continues working, unless the "disconnect" option is selected from the Home screen, or the user selects "Configure option" and disables it from inside the main menu.

### Configuration
1. Blokada version
v. 3.7

2. Device model
Samsung Galaxy S5 - G900F

3. Android version / ROM
Android v. 6.0.1 -- OmniDroid ROM

### Questions
1. How long have you been using Blokada? 
Since version 3.3

2. How long time ago has the problem started to happen? 
Noticed since I updated v.3.5  to v. 3.6. 
Issue happens with both Wi-Fi and Mobile network.

3.  How often does this problem happen to you?
Always

**Comment by kar** [comment]
Reproduce in 4.3.5?

**Comment by Max1234-Ita** [comment]
Hi
Sorry for the delay but I'm receiving Blokada through F-Droid and it didn't
update until yesterday.

I have now v.4.3.11 and can confirm that it does not fire up again if the
Deactivate option is selected from notification menu.

Regards, and thanks for your work!
Massimo

Il Gio 10 Ott 2019, 16:41 Karol Gusak <notifications@github.com> ha scritto:
