### ISSUE TITLE
Problems with "Standard-DNS-Server" Option

### ISSUE THREAD

**Issue by hneemann** [blokadaorg/blokada#359]
### Steps to reproduce
1. Use the DNS-Option "Standard-DNS-Server"
2. Nothing special, just start Blockda in the default configuration.

### Expected behaviour
Blokada should use the system provided DNS Server.
In my case the DNS server running on my FritzBox router, which is able to resolve "[name].fritz.box" domain names to local IP addresses.

### Actual behaviour
I can't resolve DNS entries like "myserver.fritz.box".
Using the IP address of "myserver.fritz.box" in the browser directly works fine.
Also creating a new Blokada DNS server entry, by using the FritzBox DNS IP address works fine. But in this case i have to switch the DNS server if I'm not connected to my home network.

### Configuration
1. Blokada version
3.7 (022000)

2. Device model
Moto G4

3. Android version / ROM
Android 7.0

### Questions
1. How long have you been using Blokada? 
For a few weeks now.

2. How long time ago has the problem started to happen? 
From the beginning.

3.  How often does this problem happen to you?
Every time I try to reach a server like "myserver.fritz.box"

**Comment by jo-me** [comment]
Same issue here, however I cannot even access local hosts by name if I put the routers IP as custom DNS server in blokada..

Maybe the issue is more general: how can you whitelist traffic to the local network?  Non-FQDNs could be regarded as local traffic.

**Comment by jo-me** [comment]
I cannot even reach "fritz.box" even if my blokada DNS is set to the routers IP

**Comment by rpeter85** [comment]
It is because Blokada gets an internal IP address and generates a tunnel with it, which isn't routed to another local addresses, which means, it can't address hosts in another IP range.

**Comment by rpeter85** [comment]
Do you guys have further questions?

**Comment by DOliana** [comment]
The question still remains: is there a way to look up local addresses? Or maybe disable it for specific networks? (I have pi hole at home, so I wouldn't need blokada when at home)
