### ISSUE TITLE
Blokada randomly closes after 1-2 days

### ISSUE THREAD

**Issue by shawn-j** [blokadaorg/blokada#360]
### Steps to reproduce
1.not quite the same as other "random close" bug reports
2. seems to randomly crash every 1-2 days or so.  idk how it happens, it does it while i'm away.   i come back & the icon is missing.  i have to force close it & restart once or twice, sometimes i have to reboot the phone

### Expected behaviour

i would expect it to stay open. i have it on another phone and it's never done this.

### Actual behaviour

it crashes.  not sure what else to say here, as i've always been away when it happens

### Configuration
1. Blokada version 3.6

2. Device model huawei mate se

3. Android version / ROM stock 8.0.0

### Questions
1. How long have you been using Blokada? 
about 2 months

2. How long time ago has the problem started to happen? 
the whole time

3.  How often does this problem happen to you?
every 1-2 days or so

**Comment by StarPicard** [comment]
Maybe it happens on a restart? #381

**Comment by animeking9901** [comment]
That phone brand LOVES to kill apps,you'll need to fight the memory
management system

**Comment by micw** [comment]
I have a similar issue on my Oneplus 3T. I'm switching from Battery "optimized" to "none optimized" for the app and check if that helps.
