### ISSUE TITLE
I want to be able to see a chronologically ordered list of recently blocked domains

### ISSUE THREAD

**Issue by QuestofIranon** [blokadaorg/blokada#361]
It'd be nice to have access to a list of recently blocked domains in order of when they were blocked. An example use case for this would be white listing; often the notification for a domain I want to white list will get replaced by another notification before I can white list (in Android 8).

Intuitively, I think that pressing the x blocked button could be a sane way to access the list. This is the first method I tried for accessing such a list.

**Comment by rpeter85** [comment]
You can see the blocked domains in the log.

And in v4, you'll be able to see them on the UI.

**Comment by QuestofIranon** [comment]
Sorry I found an identical issue #178  (I didn't use the right search terms before) after posting this. I probably should've closed it.
