### ISSUE TITLE
Suggestions for adding more dns server links

### ISSUE THREAD

**Issue by zakirhussain1988** [blokadaorg/blokada#365]
Guys feel free to add to the list of dns servers that blocks ads that are not currently on the blokada list.

Heres the two I found works good

https://www.epsiloneight.com/private-dns#

 https://alternate-dns.com/

I will add more if I find.

**Comment by rpeter85** [comment]
Added 246, which already mentioned alternate-dns.

**Comment by rpeter85** [comment]
[228](https://github.com/blokadaorg/blokada/issues/228), to add fdn.fr

**Comment by rpeter85** [comment]
I checked and epsilon eight has only one public DNS server, thus that's a bit risky.

**Comment by rpeter85** [comment]
Alternate is added.
