### ISSUE TITLE
Updates via mobile network while only wlan is selected

### ISSUE THREAD

**Issue by Slarti4711** [blokadaorg/blokada#366]
### Steps to reproduce
1. Turn on WLAN and Blokada
2. Select updates only over WLAN in advanced settings
3. Turn off WLAN, Turn on LTE
4. Updates are occuring over LTE

### Expected behaviour

No updates, when not connected to WLAN

### Actual behaviour

repo (about 2MB) and
blacklists (about 8MB) got updated.

### Configuration
1. Blokada version
3.7 (022000)

2. Device model
Acer Z630 (T03)

3. Android version / ROM
5.1 Acer_AV0L0_T03_RV01RC30_EMEA_GEN1
(Standard latest stock - not rooted)

### Questions
1. How long have you been using Blokada? 
A few weeks

2. How long time ago has the problem started to happen? 
some days

3.  How often does this problem happen to you?
I noticed it once.

**Comment by rpeter85** [comment]
Can you please try to reproduce it and report back? In most cases, we can see the Blacklists are not downloaded, neither updated when the user has only mobile network, no wifi.

**Comment by L31FY** [comment]
I am noticing the same behavior on two of my own devices a few times now and it is reproducible although I'm not sure the cause. One of them will do it after killing the process/app for sure it seems and then restarting Blokada will make it update.

**Comment by rpeter85** [comment]
There was a finding yesterday, that at start-up time Blokada reports "updating" the lists (while when it actually downloads is says "Downloading lists"Ö, however what happens actually is that it just loads the list into memory from the storage, no update started. The first "loading" message should be "loading", not the current, "Updating".

**Comment by kar** [comment]
Duplicates #335
