### ISSUE TITLE
Blokada not starting up at all

### ISSUE THREAD

**Issue by Slarti4711** [blokadaorg/blokada#367]
### Steps to reproduce
1. Configure Blokada
2. Start the app
3. Try to start it up

### Expected behaviour

After a short while Blokada should go to "active" and VPN symbol should appear

### Actual behaviour

1.  Blokada is inactive - blinking light red,
2. Host blacklists do not stop updating
3. Activating Blokada..
4. endless same states 1 through 3 until interrupted by ending Blokada

Other VPN solutions start up on the device (e.g. Proton VPN).

### Configuration
1. Blokada version
3.7 (022000)

2. Device model
Medion/Lenovo LIFETAB P9702

3. Android version / ROM
7.1.2 / P970X_20180830_V2.3
(actual stock version, not rooted)

### Questions
1. How long have you been using Blokada? 
A few weeks

2. How long time ago has the problem started to happen? 
Ever since

3.  How often does this problem happen to you?
Every time

4. Counter measures taken
- VPN is not permanently enabled (from FAQ)
- reinstallation of Blokada
- reboot of the device (from FAQ)

**Comment by rpeter85** [comment]
Do you have any other, active VPN while you try to start Blokada?

**Comment by Slarti4711** [comment]
No, no other VPN active.
I am aware that this will not work.

Strange is the continued tries to download the Blacklists.

Could it be that some rigths are missing on Android 7.1.2 level that should be requested before downloading?


Am 10. April 2019 09:16:13 MESZ schrieb Peter <notifications@github.com>:

**Comment by zakirhussain1988** [comment]
Just clear the cache this should fix it happned to my Samsung tablet once

**Comment by rpeter85** [comment]
The system can always override the app's settings because the system has higher priority. Thus, if you enabled "start at boot" in Blokada, but that doesn't do it, go to your system's settings, to Applications, search for Blokada and allow start on boot.
As this settings differs between manufacturers, you might find it in another place.

**Comment by Slarti4711** [comment]
It does not even start up in manual mode.
i.e. it never enters the actve state.

Am 10. April 2019 15:57:41 MESZ schrieb Peter <notifications@github.com>:

**Comment by RashadBasharat** [comment]
I've noticed this starting to occur for me along with my upgrade to Pie, it doesn't seem like it's an OS specific issue.
In my case the vpn permission request never appears whereas it does for something like Nord

**Comment by Slarti4711** [comment]
I think the request appeared just once.

Am 17. April 2019 09:21:55 MESZ schrieb RashadBasharat <notifications@github.com>:

**Comment by RashadBasharat** [comment]
Strange I never got any requests, did you accept the time it did appear?

**Comment by Slarti4711** [comment]
I retried. After reinstalling, activating blacklists right after activating blokada a popup appears that the key symbol will appear when vpn is active.
I should only accept when trusting that app.

Ok or stop. I choose ok, but Blokada does never enter the active state.
Only blinking light red activating...

Am 17. April 2019 18:52:05 MESZ schrieb RashadBasharat <notifications@github.com>:

**Comment by rpeter85** [comment]
@Slarti4711 can you join our Telegram channel and share your log? That will carry the information we need to determine the root cause. The chat is available here: go.blokada.org/chat

**Comment by Slarti4711** [comment]
Please how do I generate that log?
I think the chat clarified that all standard measures did not work.

**Comment by rpeter85** [comment]
It's better not to send the log file here :) This is why I asked if you can join the Telegram group where we can analyse the issue on the fly and get all the info we need.

**Comment by RashadBasharat** [comment]
For what its worth I have solved the problem for myself, seems like certain custom rom devs like to disable VPN's by default and you should opt in at the install menu

**Comment by rpeter85** [comment]
Same is true in some cases if you don't install gapps. The basic also provides the VPN function.

**Comment by dolour** [comment]
Whats weird is that it works "sometimes". If it would just not work at all, ok its a permission issue.
But since it DOES successfully start once ina while, its definitely not permission related.
At least i gave it all the permissions possible,, with no change in behavior.

**Comment by kar** [comment]
Anyone on 4.2 with this issue?
