### ISSUE TITLE
I want to optimise list handling

### ISSUE THREAD

**Issue by terrorist96** [blokadaorg/blokada#369]
### Steps to reproduce
1. Add several domains to the whitelist (e.g. enable notifications, browse the web and tap the whitelist button in the notification for several different domains)
2. Go to blokada whitelist page and delete recently added domains.
3. First one deleted, second or subsequent will lag.

### Expected behaviour

No lag

### Actual behaviour

Lag. Can be fixed if you first turn off blokada (orange button at bottom of home page) then trying to delete items from whitelist.

### Configuration
1. Blokada version
3.7.022000

2. Device model
Note 8

3. Android version / ROM
8

### Questions
1. How long have you been using Blokada? 
Several years

2. How long time ago has the problem started to happen? 
As long as I can remember

3.  How often does this problem happen to you?
Very often. Side issue, but it would be nice if the entire right hand side was the trash can button. If I tap slightly above or below the trash, it brings up the edit panel.

**Comment by rpeter85** [comment]
I mark it as a feature request: optimise the load of lists, list handling.
The behaviour you described is due to the current method of handling the loaded host lists.

**Comment by terrorist96** [comment]
Ok thanks. Please also consider the last part.
 > Side issue, but it would be nice if the entire right hand side was the trash can button. If I tap slightly above or below the trash, it brings up the edit panel.

**Comment by rpeter85** [comment]
That'll be redesigned in v4.
