### ISSUE TITLE
[Chrome] Back button of browser often not working

### ISSUE THREAD

**Issue by alleluia20** [blokadaorg/blokada#37]
Using Chrome on Android (and under Blokada's VPN). When I do a search in Google, follow the link to one of the results, and I then press "back", it often fails (more than 50% of the times).
The URL bar briefly shows "google"  but then (after less than one second afterwards) it forwards to the current page. In practice, it is as though the back button were reloading the current page.

**Comment by alleluia20** [comment]
The submitted issue always (or almost always) happens when using an *incognito* tab in Chrome, and the search result is a video on YouTube (choosing to play the video in Chrome, not in the YouTube app) or a tweet on Twitter. 
Then, the only way to actually reach the previous page is to double tap (quickly) the back button, and sometimes it may be necessary to triple tap.

**Comment by kar** [comment]
I cannot confirm this. Is this still happening?

**Comment by alleluia20** [comment]
Yes. If I strictly follow the steps described in the two first posts, it
still happens. DNS66 has the same issue.

Regards.

**Comment by noelkra** [comment]
Hey alleluia20
Is it still happening? If yes, does it work on other Browsers like Firefox or Opera?
I tried to reproduce it but it works fine for me on Android 8.0 and 6.1.
Regards.
Noël

**Comment by alleluia20** [comment]
Honestly, I am now using DNS66. For DNS66, I do not remember it happening
recently, so maybe it will not happen with Blokada either. But it is up to
Blokada's users to verify it :-)

Regards.

**Comment by kar** [comment]
Nobody reported it since.
