### ISSUE TITLE
Fake version on Playstore?

### ISSUE THREAD

**Issue by beerisgood** [blokadaorg/blokada#370]
Is this a fake Version?:
https://play.google.com/store/apps/details?id=org.blokada.alarm.dnschanger

**Comment by ahmadsamhann** [comment]
no. it's just a DNS Changer. not an adblocking app. download Blokada (adblockers) from Fdroid or website.

**Comment by beerisgood** [comment]
But it's not the original Blokada? So it's a fake

**Comment by animeking9901** [comment]
No,it's a crippled version that is Google Friendly to help people find the
full featured one

**Comment by ahmadsamhann** [comment]
@beerisgood it's clearly stated DNS Changer. do you really understand what "fake" means?

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by animeking9901** [comment]
I actually do understand what fake means,I'm not gonna argue with you. It
is what it is

**Comment by ahmadsamhann** [comment]
@animeking9901 did I somehow offended or mistakenly mentioned you?

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rpeter85** [comment]
Due to Google's policy, no ad-blocker allowed on Play Store. Thus, a limited version of the full-featured app can be found there, that's the DNS changer you found there. That's not fake, comes from the dame developer as the one on blokada.org or other official sources.

**Comment by animeking9901** [comment]
@ahmadsamhann Sorry,was using Email thread and wasn't paying full attention. Haven't had coffee yet this morning. My dearest apologies

**Comment by beerisgood** [comment]
Alright. I close this then
