### ISSUE TITLE
Blokada prevented phone from logging in to Samsung Account

### ISSUE THREAD

**Issue by tungmilan** [blokadaorg/blokada#377]
### Steps to reproduce
1. Login to Samsung account on a Samsung Galaxy S phone (I used S10 Unlocked).   
2. Install and activate Blockada 3.7.  
3. Change Samsung account password on a PC or laptop then choose logout everywhere.   
4. The phone will ask user to login again and will fail every time (Processing Failed error message).   
5. Problem is gone if Blockada is turned off.

### Expected behaviour

Login to Samsung account as normal

### Actual behaviour

Could not login to Samsung account. Received "Processing Failed" error message instead

### Configuration
1. Blokada version: 
3.7

2. Device model: 
Samsung SM-G973U1

3. Android version / ROM: 
Stock ROM, Android 9.0

### Questions
1. How long have you been using Blokada? 
3 days

2. How long time ago has the problem started to happen? 
A day

3.  How often does this problem happen to you?
Not often

**Comment by rpeter85** [comment]
There are a bunch of ways to resolve it.
1.) whitelist the blocked domain (enable Notifications to see what is blocked)
2.) whitelist the application
3.) set another blacklist

**Comment by tungmilan** [comment]
@rpeter85 Thanks! I didn't have Blokada notifications turned on in the beginning so I had no idea what went wrong. Spent a good amount of time figured out the cause with a Samsung CSR. Eventually I needed to whitelist Samsung Account app `com.osp.app.signin`.

**Comment by rpeter85** [comment]
Great to read it is solved, thanks for your feedback.
Enjoy using Blokada.
