### ISSUE TITLE
Constantly crash

### ISSUE THREAD

**Issue by mneamtu** [blokadaorg/blokada#379]

**Comment by mneamtu** [comment]
Blokada latest version 3.7
Device model: MI A2 Lite
Android version: PIE latest stock rom
I've been used for 2 days.
Problem starting soon after installation.
Crashing appears constantly.

**Comment by rpeter85** [comment]
Xiaomi is famous about their agressive battety  management. Add Blokada to exception list of battery optimisation and lock the app into memory on the recents screen.

**Comment by mneamtu** [comment]
I have Android One on my phone, which is pure Android, not modified by Xiaomi.

**Comment by mneamtu** [comment]
Closed because i uninstalled Blokada, so i not use anymore.
