### ISSUE TITLE
Airplane mode

### ISSUE THREAD

**Issue by xmiseggs** [blokadaorg/blokada#38]
At night I activate the airplane mode and remove the Blokada key (correct) and when I wake up in the morning I deactivate the airplane mode, there are occasions when Blokada does not activate automatically, I have to run Blokada and it tells me that there has been a problem in the network, then I click on the shield or on power up and it starts to work.

Android 6.0.1

**Comment by kar** [comment]
Do you give it at least 30 seconds to start?

**Comment by xmiseggs** [comment]
I'll check it out and give you the details. Oh, thank you.

**Comment by xmiseggs** [comment]
It's working fine. For some reason I don't know the online only option was disabled.
Thanks for your work.
