### ISSUE TITLE
Blokada stops all traffic when enabled on LG V40

### ISSUE THREAD

**Issue by iff7378** [blokadaorg/blokada#380]
### Steps to reproduce
1. Happens anytime Blokada is enabled

### Expected behaviour

Blockada should not stop all internet traffic on the device

### Actual behaviour

All apps lose connectivity

### Configuration
1. Blokada version
3.7

2. Device model
LG V40

3. Android version / ROM
8.1

### Questions
1. How long have you been using Blokada? 
About a month

2. How long time ago has the problem started to happen? 
approximately 2 weeks

3.  How often does this problem happen to you?
Anytime Blokada is enabled.

**Comment by rpeter85** [comment]
Hey, 
What did you do so far to prevent or resolve it? Did you restart the phone after you installed the app?

**Comment by iff7378** [comment]
I have tried changing multiple settings in Blokada (different DNS servers, enable disable watchdog and DNS fallback) and reinstalling the app. Also tried a downgrade to 3.6. 

I will try a restart and see if that helps.

**Comment by iff7378** [comment]
Restart seems to have helped. Been working fine. Thanks!
