### ISSUE TITLE
Not auto starting on system restart

### ISSUE THREAD

**Issue by StarPicard** [blokadaorg/blokada#381]
### Steps to reproduce
1. Turning Blokada on and enabling the switch "Start on boot"
2. Restart device

### Expected behaviour

Blokada should "Start on boot"

### Actual behaviour

Blokada does not start and the switch "Start on boot" is set back to "disabled".

### Configuration
1. Blokada version
3.7 (022000)

2. Device model
Oneplus A3003 (Oneplus 3)

3. Android version / ROM
8.0.0  - OxygenOS 5.0.8

### Questions
1. How long have you been using Blokada? 
Two Months

2. How long time ago has the problem started to happen? 
Noticed it ~ three weeks ago.

3.  How often does this problem happen to you?
On every restart

**Comment by rpeter85** [comment]
Check system's settings and allow Blokada to start at boot.
The system always has higher priority, thus it can override apps settings.

**Comment by rpeter85** [comment]
@StarPicard did you have the chance to check my previous comment?

**Comment by Herbstfreud** [comment]
I had a similar issue on my Pixel with LineageOS 16: On restart Blokada haven't gone into active state.
Short term solution: I had to go into the Blokada App after phone start and just had to wait. There I could see that the App tries to get active over and over again, in the end Blokada made it and was active. But the switch of Autostart inside the app never got back - that's the little difference to this issue here.
Long term solution: On the device under VPN settings I had to turn on "Permanent VPN active". This solved the problem also on the Xperia phone of my daughter with LineageOS 14.

**Comment by shawn-j** [comment]
@rpeter85 i've already changed all settings possible, been through all advice i could get on the TG channel, didn't work

@herbstfreud this is a different issue.. I can start the app, then go off & do other things, and it will activate.  also I don't have any VPN setttings (EMUI limitation).

I'm not sure it's even the phone killing the app.  I think it's just crashing.  it takes a looooong time, more than a day, longer than any batery-saving feature would take to kick in.  and when it happens, usually I have to force close & restart the app.  sometimes i have to do that twice.  and sometimes i have to restart the phone.  it's acting more like a bug crashing it than anything else.

**Comment by StarPicard** [comment]
> @StarPicard did you have the chance to check my previous comment?
Hey, sorry for the late response. I checked everything and its all enabled.



> I had a similar issue on my Pixel with LineageOS 16: On restart Blokada haven't gone into active state.
> Short term solution: I had to go into the Blokada App after phone start and just had to wait. There I could see that the App tries to get active over and over again, in the end Blokada made it and was active. But the switch of Autostart inside the app never got back - that's the little difference to this issue here.
> Long term solution: On the device under VPN settings I had to turn on "Permanent VPN active". This solved the problem also on the Xperia phone of my daughter with LineageOS 14.
This is kind of a workaround by now, because everytime Blockada shuts down I get notified, thanks!

**Comment by Rafi993** [comment]
> Check system's settings and allow Blokada to start at boot.
> The system always has higher priority, thus it can override apps settings.

https://dontkillmyapp.com

**Comment by kar** [comment]
Experiencing it on 4.1?

**Comment by StarPicard** [comment]
Everything is fine in v4 :+1:

**Comment by Herbstfreud** [comment]
Also on LOS 14 and 16. It works now without the system VPN switch, too.
