### ISSUE TITLE
Ads got blocked by blokada,but it still shows up on the screen

### ISSUE THREAD

**Issue by brother12355** [blokadaorg/blokada#382]
### Steps to reproduce
1.Make sure blokada is working.
2.Open some app with ads inside it, and those ads should be block by blokada as usual.

### Expected behaviour

Those ads should be blocked by blokada.

### Actual behaviour

Notification told me that blokada already detect those ads, and stop those ads through, but those ads still pop on the screen.

### Configuration
1. Blokada version
3.7(022000) Official

2. Device model
ASUS Zenfone 4 Pro (ASUS_Z01GD)

3. Android version / ROM
8.0.0

### Questions
1. How long have you been using Blokada? 
It's been a long time...since last year.

2. How long time ago has the problem started to happen? 
Middle of April, or after that.

3.  How often does this problem happen to you?
Everytime.

**Comment by rpeter85** [comment]
Clear apps cache after you installed Blokada, the ads you see  are cached.

**Comment by brother12355** [comment]
> Clear apps cache after you installed Blokada, the ads you see are cached.

Oh, I did that, but nothing change... :(
I did everything on [https://blokada.org/docs/help.html#ads](url), unfortunately, nothing change.
Maybe I should reinstall Blokada?
btw, my whitelist is not enable, is that cause this to happen?

**Comment by ps100000** [comment]
Do the apps in which you still see ads have anything in common? E.g. they are all from the same publisher or all use certain APIs like Facebook.

One possibility would be that the ads you see are delivered from a different domain. In this case it would probably be a good idea to see what requests the app sends or try to add other lists. :)

**Comment by brother12355** [comment]
> Do the apps in which you still see ads have anything in common? E.g. they are all from the same publisher or all use certain APIs like Facebook.
> 
> One possibility would be that the ads you see are delivered from a different domain. In this case it would probably be a good idea to see what requests the app sends or try to add other lists. :)
I have no idea about this problem...
I have not update those apps for a long time(sometimes, update them might cause some bad problem happen.)
Those ads just pop out few weeks ago, even I enable blokada, I have tried few ways, but no one of them working.
1. Clean data and cache.
2. Reinstall Blokada.
3. Change DNS server.
Maybe I should change my title of this issue. Blokada detected those ads, and shows on notification, told me they should be blocked, but they still there, I believed those lists are working with me, but some weird point may cause this kind of sh*t keep happen :|

**Comment by ps100000** [comment]
I think you didn't understand what i wanted to say so I'll try again.
Lets they a webpage or game shows ads from two providers. the following can happen:
 - evil-ads.example.com -> Blocked -> shows notification in Bokada and the ad is gone
 - super-evil-ads.google.com -> not blocked -> no notfication in Blokada and ad is visible

Blokada would show you the blocked ads from one provider but the ad from the second provider is still visible.
If that is the case you need to find what your equivalent to "super-evil-ads.google.com" is and block it.
You can do this by monitoring the requests the app makes.

**Comment by brother12355** [comment]
> I think you didn't understand what i wanted to say so I'll try again.
> Lets they a webpage or game shows ads from two providers. the following can happen:
> 
> * evil-ads.example.com -> Blocked -> shows notification in Bokada and the ad is gone
> * super-evil-ads.google.com -> not blocked -> no notfication in Blokada and ad is visible
> 
> Blokada would show you the blocked ads from one provider but the ad from the second provider is still visible.
> If that is the case you need to find what your equivalent to "super-evil-ads.google.com" is and block it.
> You can do this by monitoring the requests the app makes.

ahh, I see.
but here is the problem:
evil-ads.example.com -> should be blocked -> already shows notification in Blokada, BUT those ads still there, they did not get block by blokada.
That's the weird point, I wasn't change any setting on blockada or my cellphone, but it just happened.
I have no idea about this.
Ads on those apps used can be blocked by blokada, but few weeks ago, that doesn't work anymore.
It's not like the second example you told me, now I am wondering is that some virus get in my phone and killed blockada and my anti-virus app...
situation is getting worse, I think?

**Comment by rpeter85** [comment]
Are the ads changing? I mean, do you see all the time the same ads or different ones? Do you see ads in every app? Reason I'm asking is that the situation you describe is very similar to the ones where the phone is infected with a malware, and with that, Blokada can't do anything.

**Comment by brother12355** [comment]
> Are the ads changing? I mean, do you see all the time the same ads or different ones? Do you see ads in every app? Reason I'm asking is that the situation you describe is very similar to the ones where the phone is infected with a malware, and with that, Blokada can't do anything.

I was also wondering is my phone got infected by some kinds of malware, but I don't think so.
Some apps' ad could be block by Blokada, but some can't.
Yes, those app which can't be block always shows same ad.
But I use anti virus application scan my phone, there are nothing wrong.

**Comment by rpeter85** [comment]
Ok. It might be because it doesn't block every host your phone tries to access. go.blokada.org/help#refresh - do this, if doesn't help then enable a bigger list.
If that still doesn't block the ads, do a factory reset and check if you run the same issue.
