### ISSUE TITLE
Intermittent issues with 3/4G & Wifi

### ISSUE THREAD

**Issue by GusGF** [blokadaorg/blokada#384]
First of all I would like to say thank you for the app it's a life saver. It has successfully blocked ads that had me tearing my hair out.

I will say I'm new to this app and the technology it uses so consider me a newbie so I apologise if your patience wears thin but I'm happy to learn and really want to be able to use this app properly. So if there are any links to help me, pls throw them my way.

Anyways back to the issue I'm having from time to time I would say weekly ATM I'm finding I'm having to power cycle blockada as my data traffic is blocked. This works and it's no big deal but I'd really like to have to not do this and to understand why it's happening. 

### Configuration
1. Blokada version: 3.7
2. Device model: Honor 8x
3. Android version / ROM: 8.1, EMUI: 8.2
### Questions
1. How long have you been using Blokada? nearly 2 weeks
2. How long time ago has the problem started to happen? From install
3.  How often does this problem happen to you?  weekly on average 

Great work folks :)

**Comment by rpeter85** [comment]
Hi there,
EMUI is famous of restricting apps to save memory and battery. Can you please ensure Blokada is whitelisted for memory- and battery optimisation in the EMUI system? Here is what you need to search for:
https://dontkillmyapp.com/huawei
