### ISSUE TITLE
No ads blocked on cell data (ok with wifi)

### ISSUE THREAD

**Issue by facted** [blokadaorg/blokada#385]
### Steps to reproduce
1. Enable blokada and disable wifi.
2. Open chrome on Pixel 3XL.
3. No ads blocked using cell data (blokada still appears enabled). Turn on wifi and connect to WiFi network and ads are now blocked.

### Expected behaviour
Ads to be blocked 

### Actual behaviour
No ads blocked when using cell data (T mobile).

### Configuration
1. Blokada 3.7

2. Pixel 3XL

3. Stock Android.

### Questions
1. About 1.5 years.

2. How long time ago has the problem started to happen?  Rarely over the last few months, now every time over the last week or two.

3.  How often does this problem happen to you?
Every time I use cell data.

**Comment by rpeter85** [comment]
The reason and the solution:
https://www.xda-developers.com/fix-dns-ad-blocker-chrome/
