### ISSUE TITLE
Whitelisted games still block ads

### ISSUE THREAD

**Issue by stormaxim** [blokadaorg/blokada#387]
### Steps to reproduce
1. Close game.
2. Add games to whitelist
3. Refresh filter(?)
4. Reload game (in my case its "Fishercat" and "Green the Planet 2")

### Expected behaviour

Reloading the games and clicking on "load ads" should load and play.

### Actual behaviour
Ads do not load when blokada is enabled. When disabling Blokada the ads load.

### Configuration
1. Blokada version
3.7

2. Device model
Oneplus 5T

3. Android version / ROM
9.0 Pie

### Questions
1. How long have you been using Blokada? 
~1 year

2. How long time ago has the problem started to happen? 
3-4 months ago

3.  How often does this problem happen to you?
Every time some games are added to whitelist.

**Comment by rpeter85** [comment]
Did you fully exit the game? Close it, removed from memory? Otherwise the game is still running from cache and Blokada can't exclude it from the VPN tunnel.
