### ISSUE TITLE
Blokadas browser hijeck on Firestick Silk browser

### ISSUE THREAD

**Issue by Thomas499** [blokadaorg/blokada#388]
![image](https://user-images.githubusercontent.com/38442058/57536552-41ed3a80-72f9-11e9-99a6-a056bb597959.png)
I verified this does happen.

**Devices effected:** 
All Firesticks

**Steps to reproduce:**
Step 1. Download official blokada 
Step 2. allow list to download
Step 3. turn on blokada
Step 4. download amazon silk browser
![image](https://user-images.githubusercontent.com/38442058/57536854-eec7b780-72f9-11e9-91da-47fa3e0e4dad.png)
![image](https://user-images.githubusercontent.com/38442058/57536954-23d40a00-72fa-11e9-98bb-593b96c7f5f0.png)
Step 8. Not really a step, but this is what will come up
![image](https://user-images.githubusercontent.com/38442058/57537094-685fa580-72fa-11e9-9f94-cd4d30ca2660.png)
Step 9. Exit the donate page
Step 10. Open Amazon silk browser. This is what you will see. Amazon silk homepage is blokada donation page
![image](https://user-images.githubusercontent.com/38442058/57537118-757c9480-72fa-11e9-89da-ff6a63582d62.png)

**Comment by Thomas499** [comment]
**Underlining Problem** 
The problematic pages aren't shown inside blokada like normal but rather open the browser directly


**Details of farther debugging**
Most links do not cause this problem because the page is opened within blokada. I.e. notice the blokada title. Means that page will not cause a problem with Silk browser
![image](https://user-images.githubusercontent.com/38442058/57570017-50e3f380-73b2-11e9-864d-fe62d12b43ff.png)

Its only when the link opens a browser to open the page. In first post, after step 7 is clicked the following will show up for a few seconds
![image](https://user-images.githubusercontent.com/38442058/57570056-bb952f00-73b2-11e9-9b4b-e0460457f36b.png)
this only happens when a link from within blokada is opening the silk web browser.

![image](https://user-images.githubusercontent.com/38442058/57570132-948b2d00-73b3-11e9-82a4-54bf7ecf052e.png) This means when amazon silk web browser is opened next, this will be the homepage. 

**Root cause**
The amazon web browser is terrible. It automatically opens to the last page visited and if you didn't enter the last page through the search bar in the browser (i.e. you clicked a link from blokada which opened the web browser) then you can't even hit the back button. Thus, you can't get the search bar to show up. 

Another experiment that explains this in more detail. I opened youtube. I closed silk and reopened silk. the home page was youtube. But if I hit the back button it took me back to the homepage where I could search for other things. I then repeated experiment but before I re-opened browser I forced closed silk browser. This time, I was not able to hit the back button and thus could not search for anything else. 

**Recommended solutions**
1. Developers to make all links found in blokada to open from within blokada directly without using an external browser. t
2. User to not use silk browser. Download firefox, and a virtual mouse and an ad blocker add-on within the web browser such as uBlock Origin or ad block plus. This will block ads on youtube etc. Silk browser does not support ad ons. 
3. If user insist on using silk browser (because you don't need to use the virtual mouse) and user experiences this problem of homescreen being one of blokadas sites, then user should go to firestick homepage, then up top scroll all the way to the right and click on "settings" then click on "Applications" then click on "Manage Applications", then click on "Silk Browser", then click on "Clear data" this is basically the same as a fresh install of the app.

**Comment by kar** [comment]
We dont want to use internal webview since it often is causing problems. It's Silk browser's issue that users dont understand it opens most recent site by default. There is no "hijacking".
