### ISSUE TITLE
How to stop excessive updating of hostfiles?

### ISSUE THREAD

**Issue by Droidhck** [blokadaorg/blokada#392]
It's downloading/updating way too often and ofcourse always at the wrong time. Updates take 5 - 20 minutes, many times per day. Tried reinstalling the app, use different hostfiles, clearing cache etc. Also Blokada frequently resets itself to default hostfiles. Thanks.

### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by dolour** [comment]
On startup it tries to load up for several minutes without success, flickering between
"loading" and "inactive".
Same happens, as described above, numerous times over the course of the day, with
Blockada not loading at all most of the time.
Going in manually and mashing the start buttin for a couple of minutes solves it, but
thats hardly practical...

**Comment by rpeter85** [comment]
@dolour it can happen when you are on mobile, but update can be done only on WiFi. Then, of course, it won't download lists.

@Droidhck join our Telegram group, it would be extensive and hard to debug this issue here.

**Comment by dolour** [comment]
Nope, allso happens when im at home on wifi.

**Comment by Droidhck** [comment]
Thanks but don't have Telegram. Is there also a Viber group?

**Comment by rpeter85** [comment]
No. Telegram is the only channel.
