### ISSUE TITLE
Threema Web doesn't work with AdGuard DNS

### ISSUE THREAD

**Issue by kuerbis42** [blokadaorg/blokada#393]
Hi,

I don't know if I adress this issue to Blokada or to AdGuard DNS - but at AdGuard I can't find a matching git.

### Steps to reproduce
Activate Blokada with AdGuard DNS and ThreemaWeb stops at 60% connecting to your PhoneApp.

 Configuration
1. Blokada 3,7
2. BQ Aquarius
3. Android version 7.1.1

If you use any other DNS-Service it works.

I hope, this will help others

Greets, Kuerbis42

**Comment by rpeter85** [comment]
Hey,
Please contact AdGuard, Blokada only uses AdGuard's DNS server if you enable that, and we won't be able to effectively help you here.
