### ISSUE TITLE
Internet intermittently being blocked

### ISSUE THREAD

**Issue by alexa-v2** [blokadaorg/blokada#394]
### Steps to reproduce
1. Start blokada
2. wait some random amount of time
3. All internet access attempts result in "address not found" or similar

### Expected behaviour
To block ads not internet

### Actual behaviour
Well ads are blocked but so is everything else

### Configuration
1. Blokada version
3.7

2. Device model
Moto Z3 play

3. Android version / ROM
Resurrection Remix 7.0.2

### Questions
1. How long have you been using Blokada? 
About a year ago

2. How long time ago has the problem started to happen? 

Since 3.7  (which supposed to _fix_ the issue)

3.  How often does this problem happen to you?
Randomly, until I toggle blokada off and on or sometimes I have to completely kill blokada

**Comment by rpeter85** [comment]
Can you let us know how to reproduce it? I need it to get the root cause and eliminate that.

**Comment by alanlai-ms** [comment]
The repro is literally .

1) Start blokada
2) wait some random amount of time
3) All internet access attempts result in "address not found" or similar

**Comment by rpeter85** [comment]
Can you join our telegram group and send me (rpeter) the logs of Blokada? That may carry some information to determine the cause.

**Comment by rpeter85** [comment]
Ok, initial message is from alexa-v2, now from alanlai-ms. Same person or different? Which phone do you use? Is Blokada excluded for memory- and battery optimisation?

**Comment by alexa-v2** [comment]
Different people. I don't have Telegram, but can sign up if it's not too much hassle if needed

I'm on Resurrection Remix 7.0.2 on a Moto z3 play (arm64). Issue is not limited to a specific network type, timing, or phone idle killing it (just to be safe it is whitelist in battery saving and greenify). When it does occurr, all the errors I get are related to dns resolution (when it tells me the cause). Constant connection (eg, downloads) also tend to stutter and randomly seems to give up (download manager is whitelist in blokada but referring to apps that have built in manager). 

Also not sure if this is related to blokada but randomly sites (with blokada on I think, but it doesn't happen as often) will time out or throw an SSL error which normally load fine. I'm not sure about how blokada works but I'm guessing the SSL errors at least have little to do with blokada

**Comment by alexa-v2** [comment]
Sorry it took me so long to respond, I was offline there for awhile.

**Comment by emp1623** [comment]
Not sure what happened, but it now appears to be working just fine, as if nothing was ever wrong. Thx.

**Comment by alexa-v2** [comment]
This seems to be a very sporadic issue
Still unsure what causes it, but occasionally randomly nothing gets blocked

Checked memory usage: blokada using 113 (avg) mb/4GB so no issue there. Not occuring in high memory usage scenarios either (eg, gaming)

Tested reboot, restart VPN, switch between network, nothing specific seems to trigger it (needs further testing such as time between occurrences, apps open when in occurs, etc)

**Comment by PrintableCharacter** [comment]
How are the chances that Resurrection Remix is causing this issue?

**Comment by kar** [comment]
It is possible. I did quite a rewrite of tunnel management for 4.3. So lets try it out once it's available and update this issue.

**Comment by emp1623** [comment]
Greetings. Will Blokada still function (block ads, etc...) without paying for the VPN service? If yes, will you please cancel my VPN service (I've never actually used it). Thanks.

Eric M. Petru

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by peterroth** [comment]
Yes, it will. To cancel the subscription, please open a support ticket from the app (this is not the platform to manage such requests).
