### ISSUE TITLE
Ads in Google Search aren't blocked

### ISSUE THREAD

**Issue by iriseecz** [blokadaorg/blokada#399]
### Steps to reproduce
1. Open google.com in browser or open Google app
2. Search for Something
3. Ads ("ads" in czech = "**reklama**") aren't blocked
[Screenshots.zip](https://github.com/blokadaorg/blokada/files/3244129/Screenshots.zip)

### Expected behaviour
No ads

### Actual behaviour
Ads

### Configuration
1. Blokada version: 3.7 (022000)
2. Device model: Nokia 6.1
1. Android version / ROM: 9

### Questions
1. How long have you been using Blokada? ~4 months
2. How long time ago has the problem started to happen? 1-2 months ago
3. How often does this problem happen to you? always

**Comment by fmilligan** [comment]
Ads in search cannot be blocked as they originate from Google itself. Blokada only does host blocking, that needs cosmetic filtering (like ublock origin)
________________________________
