### ISSUE TITLE
Blocks kdeconnect connection

### ISSUE THREAD

**Issue by lssj** [blokadaorg/blokada#40]
Found out that exploring phone filesystem from the linux-pc using kdeconnect is impossible while this app is activated.

**Comment by kar** [comment]
Tried whitelisting?

**Comment by lssj** [comment]
Whitelisting a mobile app doesn't resolve the issue

**Comment by kar** [comment]
Then I'm afraid it won't work with the current version. You may also try standard blocking and see if it works with it.

**Comment by jeroen7s** [comment]
aha that's why it doesn't work for me
never realized it was blokada since everything else from kdeconnect works for me, thought it was just because i was using it on gnome-desktop

**Comment by pizzadude** [comment]
Whitelisting fixed it for me.
