### ISSUE TITLE
Can't Navigate Blacklist in Nvidia Shield App

### ISSUE THREAD

**Issue by IronFuturist** [blokadaorg/blokada#400]
Doesn't show me where my currently located on screen only on options on the actionbar that's it. Any ideas or suggestions?

**Comment by Thomas499** [comment]
A screenshot or picture would be awesome

**Comment by PrintableCharacter** [comment]
Please try the new v4.
It has full Android TV etc Support.

**Comment by IronFuturist** [comment]
Thanks.
