### ISSUE TITLE
Doesn't work in Android Q beta

### ISSUE THREAD

**Issue by sonphanusa** [blokadaorg/blokada#401]
### Steps to reproduce
1. install android q beta
2.
3.

### Expected behaviour

it works

### Actual behaviour

it doesn't block ads

### Configuration
1. Blokada version
latest 3.7

2. Device model
pixel 3a

3. Android version / ROM
android q beta 4

### Questions
1. How long have you been using Blokada? 
like forever

2. How long time ago has the problem started to happen? 
since android q 

3.  How often does this problem happen to you?
every time

**Comment by rpeter85** [comment]
Android Q is still in beta. It won't work as long as the final version released.
