### ISSUE TITLE
Words With Friends & Words 2 Blocked Completely

### ISSUE THREAD

**Issue by thescarletfire** [blokadaorg/blokada#402]
Hi.
Just a heads up that the included-by-default "CoinBlockersList" in Blokada is now preventing all Words and Words 2 apps from functioning. Disabling this coin blocking "simple" list allows Words with Friends to function correctly.

With Blokada enabled and the coin list enabled, Words shows a connection problem and the entire app is broken.

Just an FYI.

**Comment by Stajin** [comment]
I think it's more than that, I think they're checking for Blokada itself, with the update released today it shows no internet connection even if I have *no* lists active whatsoever, just simply having blokada loaded causes it to show no internet connection in words with friends 2

**Comment by Stajin** [comment]
Can confirm: they're booking Blokada specifically, I used APK mirror to go to the may update, using blokada with 0 blacklisted, it loads fine.

The June update under the same condition says it has no internet.

I would assume it's because the VPN is listed as Blokada and they're just checking for that. Some way of renaming the VPN may help?

**Comment by thescarletfire** [comment]
You're right. Blokada 100% does not work with Words now. Ugh. Damn Words!

**Comment by Stajin** [comment]
A workaround for now is to disable autoupdates on the play store and then install the previous version from https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=693772 which doesn't search for Blokada.

I'm reasonably certain they're just looking at what your VPNs name is and if it's Blokada it fakes that you have no internet.

If they give us the option to change the VPN name we should be OK.

If on the other hand they're searching around your phone for what other apps are installed looking for Blokada they're gonna have a bunch of fun with GDPR and fines.

**Comment by thescarletfire** [comment]
> 
> 
> If on the other hand they're searching around your phone for what other apps are installed looking for Blokada they're gonna have a bunch of fun with GDPR and fines.

Absolutely.
So evil. Ugh. Thanks all for helping test this.

**Comment by Stajin** [comment]
No worries, hoping it's a simple fix - allow renaming of the VPN so it doesn't just show up as "Blokada".

If it does turn out that they're mooching round my phone checking for what other apps I have I shall refer them to Google's playstore (pretty sure it's against policy) and GDPR (pretty sure I have to opt in for them checking through my data and they also have to allow it to work correctly *without* giving consent).

**Comment by thescarletfire** [comment]
> 
> 
> No worries, hoping it's a simple fix - allow renaming of the VPN so it doesn't just show up as "Blokada".
> 
> If it does turn out that they're mooching round my phone checking for what other apps I have I shall refer them to Google's playstore (pretty sure it's against policy) and GDPR (pretty sure I have to opt in for them checking through my data and they also have to allow it to work correctly _without_ giving consent).

Good points indeed, thanks for that. I hope it's an easy VPN fix. Can you imagine if they seriously *are* spying on the apps on your device? Damn. That fallout...epic. Yikes.

**Comment by thescarletfire** [comment]
Yes same here on Pixels and Galaxy tablets:

_Edit: I've tried it on two different devices, on an S8 and a Pocophone, same result, having Blokada active with no active blacklist causes it to no longer work._

**Comment by Stajin** [comment]
If they're looking around phones without permission it's hefty fines and a possible ban from play store, plus they shouldn't be able to do it anyway I don't think, that's why I'm reasonably sure they've gone the easy route of "is the thing I'm connected to called Blokada and if so, fall over". They can't even be checking to see if a connection works because with 0 blacklisted everything is allowed by default.

The only thing that changes is you're on a VPN called Blokada.

**Comment by thescarletfire** [comment]
> 
> 
> If they're looking around phones without permission it's hefty fines and a possible ban from play store
> The only thing that changes is you're on a VPN called Blokada.

Oh I see. I hope it's that too then. Still, leaves a bad taste in my mouth. I mean. What's preventing every app from doing the same thing and scan for the Blokada VPN? If found, then - kill connection. 

Nothing right? :(

**Comment by Stajin** [comment]
I assume it's going to become a thing for apps made by this developer and probably followed by others, they want the ad money.

Just hoping it does turn out to be a quick and easy fix.

**Comment by rpeter85** [comment]
Blokada cannot prevent installed package discovery, which means, other apps will see that Blokada is installed on your device. Thus, we can't do anything with such issues.
