### ISSUE TITLE
I want several new DNS

### ISSUE THREAD

**Issue by ghost** [blokadaorg/blokada#404]
@kar @rpeter85

 Dns list

### Steps to reproduce
1.
2.
3.

### Expected behaviour

I hope you can add these two DNS into the built-in list。

https://tenta.com/dns-setup-guides
https://www.freenom.world

### Configuration
1. Blokada version
3.7.030500

2. Device model
Samsung A7

3. Android version / ROM
8.0

### Questions
1. How long have you been using Blokada? 
uncertain.

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by Thomas499** [comment]
What I need from youfor each DNS you want added is this.
1. Primary DNS address i.e. on Adgaurd DNS it is 176.103.130.130
2. Secondary DNS address i.e. on Adguard DNS it is 176.103.130.131
3. A description i.e. on Adguard DNS it is AdGaurd DNS is an alternative solution for ad blocking, privacy protection, ad parental control. 

Look them up on the website and post it here and i'll make the changes to the code

**Comment by tw-e** [comment]
Hello,
@kar @Thomas499

Name:Quad101
Primary DNS:101.101.101.101 
Secondary DNS:101.102.103.104
A description:
Quad101 is TWNIC's experimental Public DNS project. TWNIC (Taiwan Network Information Center) is a ccTLD (country-code Top Level Domain) registry operator. TWNIC runs one of the world's fastest DNS infrastructure.
The specific IP address (101.101.101.101) has been assigned to Quad101 Public DNS systems. TWNIC's world-class network infrastructure along with comprehensive Quad101 features will build a better Internet in Taiwan.
Official website:https://101.101.101.101/index_en.html

Name:Quad101
Primary DNS:101.101.101.101 
Secondary DNS:101.102.103.104

Description:
Quad101 is TWNIC's experimental Public DNS project. TWNIC (Taiwan Network Information Center) is a ccTLD (country-code Top Level Domain) registry operator. TWNIC runs one of the world's fastest DNS infrastructure.
The specific IP address (101.101.101.101) has been assigned to Quad101 Public DNS systems. TWNIC's world-class network infrastructure along with comprehensive Quad101 features will build a better Internet in Taiwan.
Official website:https://101.101.101.101/index_en.html

Name:Tenta DNS 
First Group:ICANN
Primary DNS:99.192.182.200
Secondary DNS:99.192.182.201
Description:
Tenta DNS is your open source, privacy-first DNS solution that supports DNS over TLS and DNSSEC for a safer and more reliable internet.Read our announcement.
Official website:https://tenta.com/dns-setup-guides

Second Group:OpenNIC
Primary DNS:99.192.182.100
Secondary DNS:99.192.182.101
Description:
Tenta DNS is your open source, privacy-first DNS solution that supports DNS over TLS and DNSSEC for a safer and more reliable internet.Read our announcement.
Official website:https://tenta.com/dns-setup-guides

Freenom is about domains and DNS. As the second largest domain provider Freenom operates a large AnyCast infrastructure providing authoritative DNS services for TK, ML, GA, CF and GQ domains. This infrastructure is already in place and it's a no-brainer to offer also resolving DNS services on this large infrastructure. Freenom World's DNS resolvers are always close by, fast and we will - unlike other DNS resolvers - never store your IP address information in our logfiles.

**Comment by rpeter85** [comment]
Tenta, Quad101 and Freenom are added with [PR#40](https://github.com/blokadaorg/blokadaorg.github.io/pull/40)
OpenNIC already on the list.
FDNS.SB's website didn't tell much about their service, wasn't added.
