### ISSUE TITLE
How to whitelist specific host?

### ISSUE THREAD

**Issue by Marco-Sulla** [blokadaorg/blokada#405]
Blokada blocks me also mozilla telemetry, that I explicitly allowed in firefox. Where.can I see the list of blocked host, and how can I whitelist *.mozilla.com? Now I can see only the number of blocked host and I can only whitelist entire apps.

### Configuration
1. Blokada 3.7 02000

2. Device model Honor 6x bln-l21

3. Android 7 with emui 5

### Questions
1. How long have you been using Blokada? 

 1 day...

2. How long time ago has the problem started to happen? 

Today!

3.  How often does this problem happen to you?

I resonably think that it will occour 100% of times

**Comment by rpeter85** [comment]
The help page covers the steps:
http://go.blokada.org/help#whitelist
Instead of App, choose the corresponding one.

**Comment by Marco-Sulla** [comment]
Thank you for pointing me to the right direction to whitelist the host. But remains the problem I can't see the list of blocked host in any way. How can I see if other not offending sites are blocked and should be putted in the whitelist?

**Comment by rpeter85** [comment]
Turn on Notifications in Blokada. Then you'll see what is blocked.
Alternatively add write permission for Blokada, set logging to external and check what hosts are blocked in the log file.

**Comment by Marco-Sulla** [comment]
How can I activate the log? there's no option about logging, and the only activable permission is Archive.

**Comment by Marco-Sulla** [comment]
Hello?

**Comment by rpeter85** [comment]
Logging can be turned on on system level. Check in system settings --> Apps. Grant storage permission.

**Comment by Marco-Sulla** [comment]
And the log is located in...?

**Comment by rpeter85** [comment]
You will find it in /Downloads/Blokada

**Comment by Marco-Sulla** [comment]
Oh My God... this is not only the list of blocked hosts, it's the entire log.

Please, can't you add a simple view when you click "# blocked" (that actually does nothing if clicked) that shows the blocked hosts and the number of times they was blocked?

**Comment by Marco-Sulla** [comment]
Can I open a feature request about it?

**Comment by rpeter85** [comment]
Already requested.

**Comment by Marco-Sulla** [comment]
Where?

**Comment by Marco-Sulla** [comment]
(-(-_(-_-)_-)-)

**Comment by Marco-Sulla** [comment]
>>> Please, can't you add a simple view when you click "# blocked" (that actually does nothing if clicked) that shows the blocked hosts and the number of times they was blocked?

>> Already requested.

> Where?

I quote myself...

**Comment by Marco-Sulla** [comment]
P
L
E
A
S
E
?
?
?

**Comment by rpeter85** [comment]
Here, on Github. I think that is being closed now as Host Log is implemented and you can see blocked and allowed hosts in the app.
