### ISSUE TITLE
Add PornHosts filter lists.

### ISSUE THREAD

**Issue by thanuj10** [blokadaorg/blokada#407]
Some people like me would like to see out of the box support for pornblocking, So i request the devs to add some porn hosts other than just Steven Blacks, There are many in GitHub itself.

Ex - https://github.com/Clefspeare13/pornhosts 

### Steps to reproduce
1. N/A
2.
3.

### Expected behaviour
None

### Actual behaviour
None

### Configuration
1. Blokada version
3.7

2. Device model
Nokia 6.1 Plus

3. Android version / ROM
Android 9 Pie

### Questions
1. How long have you been using Blokada? 
A year and a half.

2. How long time ago has the problem started to happen? 
N/A

3.  How often does this problem happen to you?
N/A

**Comment by PrintableCharacter** [comment]
Blokada makes it easy for you to add your own blocklists.
The standard lists are chosen to be sufficient for a broad range of users.
I do not see this as an urgent issue as you can simply add other blocklists.

**Comment by thanuj10** [comment]
I know we can add out own Filter lists but what about people who aren't as tech savvy, Like grandpas and so on. That's why i wanted to suggested adding more options such as blocking porn too.

**Comment by cauthulhu** [comment]
How about AdGuard DNS (Family)? If it does what it says on the tin then it should block porn (i.e. adult content)

**Comment by PrintableCharacter** [comment]
Sounds like an idea
