### ISSUE TITLE
I want the size of data (traffic) for every blocked or allowed hosts

### ISSUE THREAD

**Issue by Osho-1** [blokadaorg/blokada#416]
Please include a feature (under Ad blocking section of the app) to show the size of data (traffic) for every blocked or allowed hosts.
I would also like to see a number for total data saved at the bootom, if possible

An example: 

graph.facebook.com **8kb** 0 min ago

DATA SAVED: **50 MB**

Here's a pictorial representation of my feature request:
![2019-06-28-17-16-51~2](https://user-images.githubusercontent.com/52267009/60341362-dc99f980-99cb-11e9-91e3-bf6572e4d7e5.jpg)

**Comment by bgunnink** [comment]
Blokada null-routes such requests; there's no way to know in advance how big the payload of the request would be (because it never gets to the server in question).

**Comment by Osho-1** [comment]
> Blokada null-routes such requests; there's no way to know in advance how big the payload of the request would be (because it never gets to the server in question).

Oh, I see. Then how could similar apps like Adguard could estimate the size of data?

**Comment by cauthulhu** [comment]
@Osho-1 Because AdGuard reads the requests? Unlike blokada which doesn't. That's why AdGuard is able to do cosmetic filtering. CMIIW

**Comment by PrintableCharacter** [comment]
They might as well simply timeout the requests instead of dropping them directly

**Comment by kar** [comment]
Yeah I don't know how could we give any useful estimates... Let me know if you have any ideas. For now I'm closing.
