### ISSUE TITLE
Strange hosts in Host-Log

### ISSUE THREAD

**Issue by The-Michael-R** [blokadaorg/blokada#419]
### Steps to reproduce
1. Install and start Blokada
2. Wait few seconds
3. Go to the host-log screen within Blokada

### Expected behaviour
I would expect to see only valid hosts on the list

### Actual behaviour
Some entries are just a bunch of letters and no top level domain.
![Screenshot_20190629-184351](https://user-images.githubusercontent.com/21987859/60387262-e1c07c80-9a8f-11e9-976a-3cf0f346a7f8.png)
This strange domains are also listed in the  logs:

1561828383770,a,shlllgsbiijb
1561828383799,a,hilbijqwh
1561828383833,a,hkwwiprlwvzi
1561828383876,a,shlllgsbiijb
1561828383887,a,hilbijqwh
1561828383988,a,hkwwiprlwvzi
1561828384087,a,hilbijqwh
1561828384137,a,hilbijqwh
1561828384142,a,hkwwiprlwvzi
1561828384245,a,hkwwiprlwvzi
1561828384303,a,hkwwiprlwvzi

### Configuration
1. Blokada version 4.0

2. Device model Huawei P9 lite

3. Android version / ROM Stock Huawei Image Android 7.0

### Questions
1. How long have you been using Blokada? 
Few months.Uninstall and new installation doesn't solve the problem. 

2. How long time ago has the problem started to happen? 
Since version 4 on Blokada came out. Before the issue could not observed because the information wasn't logged that way. I haven't looked into the log file through. 

3.  How often does this problem happen to you?
Constantly. But it seems to happen more often right after starting Blokada.

**Comment by rpeter85** [comment]
Google Chrome causes them:
https://unix.stackexchange.com/questions/363512/chrome-dns-requests-with-random-dns-names-malware

**Comment by The-Michael-R** [comment]
Ok, this is not a Blokada problem. So from my point of view this ticket can be closed as won't fix or invalid.

Thank you for the prompt response.

**Comment by rpeter85** [comment]
Feel free to close it ;)
