### ISSUE TITLE
[Feature Request] ability to turn off key symbol in notification bar

### ISSUE THREAD

**Issue by tessus** [blokadaorg/blokada#42]
It would be great, if there were an option to disable the key symbol in the notification bar.

I know when the app is running and I don't want to clutter the notification bar with a constant symbol. Thus it would be really helpful, if it were possible to disable the symbol in the notification bar. 

Maybe and additional slider option in the app's main screen would do the trick.

**Comment by TPS** [comment]
This _might_ be possible, but _only_ via root, as the 🗝️\🔑 is a function of Android itself notifying the user of a VPN, & can't be overridden w/o @ _least_ such permissions.

**Comment by tessus** [comment]
Thanks for the info. I didn't know it was an automatic function of Android w/o having the option to turn it off. Sometimes an API let's you choose the behavior. I guess not in this case. :-(
