### ISSUE TITLE
question: could we please have a build without the Blokada (Beta) VPN service?

### ISSUE THREAD

**Issue by hoshsadiq** [blokadaorg/blokada#423]
First of all, thank you to all devs for all your hard work and I very much appreciate all you guys have done.

Having said that, I just upgraded to v4 and I'm a bit disappointed. I appreciate you have to make money and you have to monetize somehow, but forcing your own VPN service down our throat should not be the way to go.

I honestly won't be buying any VPN service from any third parties, and I'd rather not have an app that connects to additional websites, especially not an app that has the ability to send all my traffic to a server that I have no control over.

This why I use blokada, to prevent apps from phoning home and sending my data to servers I don't have control over.

It's obviously up to you as developers of this app to decide how you go forward with this issue and I have no intention to fight for such an alternative build so make of this issue what you will. 

Have a great day, and I hope you make the right decision. Meanwhile, I'm uninstalling v4 and go back to v3 and will consider any alternatives.

Regardless of what you will do, and once again, thanks for all of your hard work.

**Comment by cauthulhu** [comment]
@hoshsadiq Blokada VPN is optional, you can continue using the ad-blocker function without ever subscribing to the VPN/incurring charge

**Comment by rpeter85** [comment]
Nobody tries to force the VPN down on your throat. The app is free, the filtering is free, the VPN is optional and you can use the app itself without subscribing for the VPN.
