### ISSUE TITLE
Current version not available in F-Droid 

### ISSUE THREAD

**Issue by Krawei** [blokadaorg/blokada#424]
Dear team,

when I take a look on your project page the current version is 4.0, in the F-Droid store the current version is 3.7.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

Steps To Reproduce

Search Blokada's current Version in blokada.org
Search Blokada in F-Droid
Compare version numbers
Expected behavior
There shouldn't be a gap regarding Blokadas' version number between project Page and f-droid after two weeks.

Actual behavior
See bug description

Device info (please complete the following information):

Device: BQ Aquaris X Pro
OS: Android 9.0 (LOS 16)

Reproduce rate
100%

**Comment by rpeter85** [comment]
Due to the number of reported issues, v4 wasn't published on f-droid. 4.1 will be available there.
