### ISSUE TITLE
Can't activate the Blokada VPN feature on Amazon FireTV

### ISSUE THREAD

**Issue by TheCorrector** [blokadaorg/blokada#425]
### Steps to reproduce
1.Install Blokada V4 on Amazon FireTV stick
2.Open Blokada and attempt to activate the VPN feature
3.The VPN feature is blank and does not let you connect

### Expected behaviour

Able to activate the VPN feature 

### Actual behaviour

The VPN activation feature is blank. I am attaching a photo first shared by user Zakir on the Blokada Telegram chat

### Configuration
1. Blokada version

Version 4
2. Device model
Amazon FireTV

3. Android version / ROM
Not sure of version but I have the most recent Amazon updates

### Questions
1. How long have you been using Blokada? 
Been using Version 4 for 3 days

2. How long time ago has the problem started to happen? 
Last Night

3.  How often does this problem happen to you?

I am.abke to use Blokada Version 4 to block ads on Amazon FireTV but I can't use the VPN feature
![IMG_20190707_193512_291](https://user-images.githubusercontent.com/52642321/60779355-48c4dd80-a0ef-11e9-91f2-1ceaa7386f81.jpg)

**Comment by TheCorrector** [comment]
Using photo first submitted by Zakir to Blokada Telegram chat

**Comment by kar** [comment]
Which firestick generation is it?

**Comment by TheCorrector** [comment]
It is a second generation Firestick. Currently have Fire OS 5.2.7.0.

**Comment by zakirhussain1988** [comment]
Any time frame when this will be fixed still facing issues on firestick I found its same problem on Amazon tab 7 probably its same issues with all Amazon devices.

**Comment by kar** [comment]
4.3 will have some changes for this... due in coming weeks.

**Comment by kar** [comment]
Anyone still having problems with 4.3, please send logs to hello@blokada.org, or at least comment here and what device you have.

**Comment by kar** [comment]
4.3.5 fixes it
