### ISSUE TITLE
[Note 9] Blokada will only work on Wi-Fi

### ISSUE THREAD

**Issue by Costin-Nox** [blokadaorg/blokada#426]
### Steps to reproduce
1. Turn on Blokada, test while connected to a wifi network. Ads are blocked.
2. Turn off wifi, allow phone to connect to LTE
3. Blokada is active but ads no longer being blocked.

### Expected behaviour
Adblocking should work on cellular data.

### Actual behaviour
Adblocking stop working when on mobile data vs wifi.

### Configuration
1. Blokada version
V4.0

2. Device model
Samsung Note 9 (SM-N960W)

3. Android version / ROM
stock v9

### Questions
1. How long have you been using Blokada? 
~3 months

2. How long time ago has the problem started to happen? 
Never worked

3.  How often does this problem happen to you?
Always

I can get proper ad-blocking on mobile data using the app "dns changer" and adguard dns servers.

**Comment by cauthulhu** [comment]
@Costin-Nox Which DNS are you using?

**Comment by Costin-Nox** [comment]
> @Costin-Nox Which DNS are you using?

default dns server set in the app, i could not see an obvious way to change it.

**Comment by cauthulhu** [comment]
@Costin-Nox To change DNS: swipe up on the home screen (1st page), then swipe right

**Comment by kar** [comment]
Update, star the app, let it set up, try accessing sites that have ads, send log to me hello@blokada.org

**Comment by rpeter85** [comment]
No info from the last 2.5 month, closing it.
