### ISSUE TITLE
I want a smaller notification

### ISSUE THREAD

**Issue by depuytnl** [blokadaorg/blokada#427]
The new Blokada 4 notification is nice, but I don't mind too much what domains we blocked recently and would prefer for it to be much smaller, still allowing me to switch blokada on and off quickly, while not taking too much space; Can this be made a configuration option at least? (In my mind most users will not require the level of detail it currently gives, so this could be a good default, but opinions may differ!)

Cheers!

**Comment by depuytnl** [comment]
found the option :O

**Comment by pm-at** [comment]
Where is that option?

**Comment by depuytnl** [comment]
What I thought I found seems to be a standard option for any notification to collapse it. Sadly it doesn't stay collapsed, so I disallowed notifications for the app altogether. It's a bit crude and makes it harder to toggle if blokada is enabled, but it solves the issue for me.
