### ISSUE TITLE
Blokada stays active in Airplane mode and drains battery

### ISSUE THREAD

**Issue by beatschubser** [blokadaorg/blokada#429]
# Steps to reproduce
1. Activate airplane mode on phone

### Expected behaviour
1. Blokada disables VPN
2. "Key"-Icon disappears
3. Quick settings tile switches to "disabled"

### Actual behaviour
1. Key icon disappears
2. Blokada quick settings tile stays active
3. Battery gets drained about 2%/hour

### Configuration
1. Blokada version
3.7

2. Device model
Xiaomi Mi Mix 3

3. Android version / ROM
MIUI 10.3.1

### Questions
1. How long have you been using Blokada? 
Since a month

2. How long time ago has the problem started to happen? 
From the very beginning

3.  How often does this problem happen to you?
About 2 in 3 times - sometimes the quick settings tile switches to "disabled" as expected

I know you could probably use watchdog to fix this, but I don't think the watchdog is really meant for airplane mode-detection. And like described above, sometimes it's working fine.

**Comment by kar** [comment]
You need to enable "watchdog" for that behaviour.
