### ISSUE TITLE
I want more advanced blacklist refresh settings

### ISSUE THREAD

**Issue by xmiseggs** [blokadaorg/blokada#43]
Please add the update frequency and be able to do it only by wifi or update when the user wants to do so.
Oh, thank you.

**Comment by kar** [comment]
Manual refresh function added, the rest will come later.

**Comment by jerryn70** [comment]
I want options like update on every week or update on every Monday, tuesday or etc etc day.  Or update every 3 days .

**Comment by kar** [comment]
Done in 3.6.
