### ISSUE TITLE
Apps accessing hosts in my private network at home don't work

### ISSUE THREAD

**Issue by lordyavin** [blokadaorg/blokada#430]
### Steps to reproduce
1. Set up owncloud in your local network behind your Internet router.
2. Use owncloud, and CalDAV and CardDAV apps to access and synchronize with the server
3. Enable blokada

### Expected behaviour
I use "Standard DNS" setting so I assume address resolving should work as if blokada is disabled.

### Actual behaviour
Access (sync) to owncloud, CalDAV and CardDAV does not work because apps can't connect to server. The blokoda app logs the host as allowed.

### Configuration
1. Blokada version: 4.0 (062700)
2. Device model: Sony Xperia XZ2 Compact
3. Android version / ROM: 9 / 52.0.A.8.107

### Questions
> 1. How long have you been using Blokada? 

Since 2 months?

> 2. How long time ago has the problem started to happen? 

Since ever

>3.  How often does this problem happen to you?

Everytime I'm at home and blokada is enabled.

**Comment by Alf626** [comment]
I'm having the same issue with 4.0 (062700).  

Setup for "Default DNS servers", but DNS request seem to be sent to an external DNS, since any local non-public host are unreachable.  When checking "Current DNS server(s)" it always shows "1.1.1.1, 1.0.0.1".  Tried disabling DNS fallback, but that didn't help.  

Tried on 2 phones (Galaxy S8 and Galaxy S10e) both running Android 9.0.

3.4(100500) seems to work fine and it properly shows my local DNS server IP address under "Default DNS servers".

**Comment by kar** [comment]
Disable DNS fallback, try again, send me log to hello@blokada.org

**Comment by Alf626** [comment]
Disabling DNS fallback does not fix issue.  Logs have been sent.

**Comment by lordyavin** [comment]
Same for me

**Comment by kar** [comment]
I havent received it, could you try again?

**Comment by lordyavin** [comment]
@kar: Who you are talking to?

**Comment by kar** [comment]
Anyone who can try sending logs. BTW 4.1.6 has a fix for dns fallback disabled, so you should check if you can reproduce it

**Comment by lordyavin** [comment]
Works for me with 4.1.6

**Comment by Alf626** [comment]
4.1.6 seems to address the issue with local DNS servers.

**Comment by kolewu** [comment]
I have had the same issue with a samsung tablet and android 8.0.0 and it is solved with 4.1.6.

**Comment by lordyavin** [comment]
In principle it looks like the issue is fixed but just now I got the problem again. Disabling and enabling DNS fallback made it work again. I assume the app does not update the DNS fallback server when changing networks.

**Comment by kar** [comment]
Please retry in 4.3 once its out
