### ISSUE TITLE
Unable to block Reddit.com within Chrome 75 on Android 9 (Pie)

### ISSUE THREAD

**Issue by Rhodizzle** [blokadaorg/blokada#431]
### Steps to reproduce
1. Add a custom list or individual host entry for reddit.com and redditstatic.com
2. Enable Blokada
3. Open www.reddit.com from current Chrome browser.

### Expected behaviour
I expect to get an error that reddit.com could not be resolved. Using Firefox, I get the expected behavior, but with Chrome it loads normally. Other sites blocked via custom list or host entry are blocked as expected from Chrome. Reddit is the only site affected.

### Actual behaviour
Reddit loads normally in Chrome, but is blocked within Firefox.

### Configuration
1. Blokada version
I've tried 3.4, 3.7 and 4.0.

2. Device model
OnePlus 6T

3. Android version / ROM
OxygenOS 9.0.15

### Questions
1. How long have you been using Blokada? 
1 year

2. How long time ago has the problem started to happen? 
A couple of months.

3.  How often does this problem happen to you?
Consistently.

4. What troubleshooting steps have you attempted so far?
I have disabled Asynchronous DNS in Chrome and verified that DoH (DNS over HTTPS) is not working when Blokada is active. I have also flushed Chrome's DNS cache after enabling Blokada.

**Comment by rpeter85** [comment]
Did you turn off Chrome's async DNS feature? That prevents every adblocker to. function as exlected.

**Comment by Rhodizzle** [comment]
I did and mentioned that in question 4 about what I've done so far to attempt resolution.

**Comment by Rhodizzle** [comment]
So, after more testing it turns out that I've run into a feature request for wildcard blacklisting and whitelisting. I had been blocking reddit.com assuming that all subdomains were also blocked, but that is not the case as you have to add each one individually.
