### ISSUE TITLE
What is each file?

### ISSUE THREAD

**Issue by xmiseggs** [blokadaorg/blokada#44]
Please explain to me what is the difference between the following latest versions, each one has a different size, how are they different?
Thank you very much.

2.69 MBblokada-fdroid-v2.2.2.apk
9.19 MBblokada-legacy-v2.2.2.apk
9.19 MBblokada-origin-v2.2.2.apk
2.89 MBblokada-v2.2.2.apk

**Comment by kar** [comment]
- fdroid - build available on fdroid
- legacy - used to migrate users of old versions of Blokada (before 2.0), can ignore
- origin - works for Android 4
- (nothing) - like fdroid, but can send development info (like crashes) to me so I can debug them
