### ISSUE TITLE
Turn blokada off automatically while connected to pi hole

### ISSUE THREAD

**Issue by Thomas499** [blokadaorg/blokada#440]
I'm looking for feedback on if blokada turned off when connected to pi-hole, would that save users battery? Also, would users want this feature? If so, where should user be able to access this feature? 

As a start to implement this, In the dns.kt file the following changes would need to be made: 

`dnsServers.doWhenChanged(withInit = true).then {
            val current = dnsServers()
            val current2: String = dnsServers().toString()

// Note: only enabled if fallback is enabled for testing stage only. In long run, will need to create another option (turn off while connected to pi hole) instead of using fallback. 

            if (fallback() && isLocalServers(current)!=0) {
                dnsServers %= listOf(
                        InetSocketAddress("176.103.130.130", 53),
                        InetSocketAddress("176.103.130.131", 53)
                )
            
//Note: create interface that allows user to change the ip below to match the ip of their pihole

                if(current2.contains("192.168.1.123")) {
             // Turn blokada off
                }
                else{
                    // turn blokada on
                }
                "dns".ktx().w("local DNS detected, setting AdGuard as workaround")
            }
        }`

**Comment by rpeter85** [comment]
The above thing can be achieved using Tasker in Blokada 4.3 and newer versions. Not directly on PiHole networks, but on predefined networks.
