### ISSUE TITLE
Change how fallback works

### ISSUE THREAD

**Issue by Thomas499** [blokadaorg/blokada#441]
If user enables fallback blokada currently checks for if the dns is local. If the user is connected to wifi and has default dns enabled this will 100% be the case. Blokada then changes the dns to cloudfair, then changes the DNS back to the default every few seconds in a constant fight. This constant fighting drains the battery, and also if the local dns really does have an issue this will cause the phone to slow down drastically (slow down by 50%) because half the time it is trying to use the default dns and thus any internet activity will not work until it switches to cloudfair. 

Ironically, by default on blokada default dns and fallback are both enabled thus insuring the highest likely that the user will run into the stated issues.

**First suggestion** (not best suggestion in my opinion) would be to change "fallback" to "idiot proof" and not have the default and fallback dns constantly fight with each other. If user selects "idiot proof" just have it do the same thing that would happen if user selected cloudfair as the DNS from the list of options.

**Second suggestion** (best suggestion in my opinion) is don't even have a fallback option and instead tell the user they are better off selecting any dns from the list of dns options that are NOT DEFAULT. - To do this, without risking the possibility of another disaster with the UI, beside dns put a blue question-mark with a circle around it in the upper right hand corner which the user can click on. If user clicks on the question-mark have a pull down window come up that explains this. 

**third suggestion**, if user selects fallback, just have that disable  "default dns" from list of dns options. Like remove it as an option that user can't even see. If default dns was enabled when this was done have it automatically select cloudfair from the list of options but still give user ability to change to another option on the list of dns options if they want. If user de-selects fallback have default dns come back up as an option in the dns section. 

**forth suggestion:** have blokada check to see if the local dns is causing an issue before it switches to cloudfair. In my opinion, this is how most users would expect fallback to work. How would you do this? If DNS changes and if (fallback() && isLocalServers(current) then have blokada ping a website. Any website will do. If the ping doesn't come back as null and doesn't time out then the default dns doesn't have an issue thus no need to switch to cloudfair. If the ping comes back as null or if it timesout have blokada switch to cloudfair (not by the fighting method which switches the two every few seconds but instead invoke the code that does the same thing as if cloudfair was the dns user selected as primary) then if dns changes again, have it recheck ping and timeout and if there are no issues then have blokada use the primary dns user selected.

This should go without saying, but give user ability to choose the fallback dns.

**Comment by rpeter85** [comment]
"If user enables fallback blokada currently checks for if the dns is local. If the user is connected to wifi and has default dns enabled this will 100% be the case."
Not really. I'm connected to WiFi all the time, still, I use the default (ISP) DNS servers.

**Comment by Thomas499** [comment]
1. In wifi settings on your phone did you specify a dns to use as the default? - I myself did this and if you do this you are correct. But most users doesn't do that and doing that makes it not use the default that the modem recommends but instead uses the DNS that you entered into the phone. Blokada of course will still think the custom dns you entered in advanced wifi settings on the phone side is the default. 

2. What brand of wifi modem do you have? On linksys routers it will always show the DNS as 192.168.1.1 (which is the address of the router) even though in the linksys advanced settings I inputted it to use 176.103.130.130 and 176.103.130.131 as the DNS.
