### ISSUE TITLE
[question] Lots of requests to ssl.google-analytics.com

### ISSUE THREAD

**Issue by lnicola** [blokadaorg/blokada#442]
This should have been a chat question, but the Telegram site doesn't seem to load for me.

### Steps to reproduce

Enable ad blocking with the default list (Energized blu) and notifications.

### Expected behaviour

N/A

### Actual behaviour

Every 30 seconds or so a request to `ssl.google-analytics.com` gets blocked. This probably means that an application tries to contact GA, but it seems far too often, and is probably bad for the battery life.

My theory is that some apps or the SDK notice they couldn't contact GA and retry too often. I found https://discourse.pi-hole.net/t/find-which-android-app-is-causing-so-many-dns-requests/4448 which seems related, and it mentions that resolving the blocked domains to 0.0.0.0 is better than 127.0.0.1.

Looking at https://github.com/blokadaorg/blokada/blob/master/app/src/tunnel/kotlin/tunnel/DnsProxy.kt#L62, it seems that Blokada simply doesn't resolve the blocked hosts. I know nothing about how these SDKs behave, but would it be worth trying a different approach like resolving to 0.0.0.0? I guess not, since the SDK could still retry the request much too quickly. What about listening on 443 and returning a 200 status code to trick the app?

Other than this, do you have any tips for finding out which application does this? My phone is not rooted.

### Configuration
1. Blokada version: 4.1.4

2. Device model: OnePlus 6T

3. Android version / ROM: Android 9 / OxygenOS 9.0.15

### Questions
1. How long have you been using Blokada? 

A couple of days.

2. How long time ago has the problem started to happen? 

Right from the start.

3.  How often does this problem happen to you?

Always.

**Comment by lnicola** [comment]
More details:

```
07-19 21:15:41.598 27949  3474 V b4:onWifi:changed:        event:emit   <--   REQUEST, Request(domain=ssl.google-analytics.com, blocked=true, time=Fri Jul 19 21:15:41 GMT+03:00 2019), Thread[tunnel-10,5,main]
07-19 21:15:41.601  6641  9118 W GAv4-SVC: Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host "ssl.google-analytics.com": No address associated with hostname
07-19 21:17:47.110 27949  3474 V b4:onWifi:changed:        event:emit   <--   REQUEST, Request(domain=ssl.google-analytics.com, blocked=true, time=Fri Jul 19 21:17:47 GMT+03:00 2019), Thread[tunnel-10,5,main]
07-19 21:17:47.112  6641  9626 W GAv4-SVC: Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host "ssl.google-analytics.com": No address associated with hostname
07-19 21:19:47.190 27949  3474 V b4:onWifi:changed:        event:emit   <--   REQUEST, Request(domain=ssl.google-analytics.com, blocked=true, time=Fri Jul 19 21:19:47 GMT+03:00 2019), Thread[tunnel-10,5,main]
07-19 21:19:47.191  6641 10323 W GAv4-SVC: Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host "ssl.google-analytics.com": No address associated with hostname
07-19 21:21:47.277 27949  3474 V b4:onWifi:changed:        event:emit   <--   REQUEST, Request(domain=ssl.google-analytics.com, blocked=true, time=Fri Jul 19 21:21:47 GMT+03:00 2019), Thread[tunnel-10,5,main]
07-19 21:21:47.278  6641 10805 W GAv4-SVC: Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host "ssl.google-analytics.com": No address associated with hostname
07-19 21:23:47.361 27949  3474 V b4:onWifi:changed:        event:emit   <--   REQUEST, Request(domain=ssl.google-analytics.com, blocked=true, time=Fri Jul 19 21:23:47 GMT+03:00 2019), Thread[tunnel-10,5,main]
07-19 21:23:47.363  6641 10973 W GAv4-SVC: Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host "ssl.google-analytics.com": No address associated with hostname
07-19 21:25:47.450 27949  3474 V b4:onWifi:changed:        event:emit   <--   REQUEST, Request(domain=ssl.google-analytics.com, blocked=true, time=Fri Jul 19 21:25:47 GMT+03:00 2019), Thread[tunnel-10,5,main]
07-19 21:25:47.455  6641 11157 W GAv4-SVC: Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host "ssl.google-analytics.com": No address associated with hostname
07-19 21:27:47.570 27949  3474 V b4:onWifi:changed:        event:emit   <--   REQUEST, Request(domain=ssl.google-analytics.com, blocked=true, time=Fri Jul 19 21:27:47 GMT+03:00 2019), Thread[tunnel-10,5,main]
07-19 21:27:47.571  6641 11212 W GAv4-SVC: Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host "ssl.google-analytics.com": No address associated with hostname
```

One request every two minutes, made by `com.google.android.gms`. Now what? :confused:.

**Comment by Tobias-B-Besemer** [comment]
I think sending the blocked domains to 0.0.0.0 is anyway a good idea...
...or add a option to configure it...

**Comment by kar** [comment]
This is the response we generate: https://github.com/blokadaorg/blokada/blob/master/app/src/tunnel/kotlin/tunnel/DnsProxy.kt#L25

**Comment by lnicola** [comment]
Yes, I saw that line; I assume it means that no record was found.

My question was whether it's sometimes desirable to return a response of `127.0.0.1` or `0.0.0.0` and, more generally, if others have the same issue and if anything can be done about it.

**Comment by kar** [comment]
yes this needs more investigation

**Comment by lnicola** [comment]
Did you label this as input-needed because I have to provide more info?

**Comment by kar** [comment]
It would be nice if someone knowledgeable about DNS could chip in. I have a feeling no matter what we respond, some apps will still aggressively retry anyway.

**Comment by lnicola** [comment]
There is the option to return 127.0.0.1 or whatever, and fire up a socket listener that returns a 200 OK to each client. That way the SDKs would think they sent the data. Two issues, though:

- you'd need a certificate
- some SDKs might use certificate pinning

**Comment by kar** [comment]
You can't listen on ports below 1024 on Android without root, so that's not doable for us..

**Comment by lnicola** [comment]
You can't but since Blokada works as a VPN it doesn't need to listen to anything, and can synthesize the raw TCP packets.

**Comment by kar** [comment]
Good point, but only in VPN mode. In adblocking-only mode it only routes DNS requests towards itself.

**Comment by lnicola** [comment]
I have no idea what that is. I thought Blokada works as a VPN that intercepts DNS requests and passes everything else right through. I wasn't talking about the paid VPN service.

Anyway, it probably won't work because of the certificate problem.
