### ISSUE TITLE
Keeping notification always collapsed

### ISSUE THREAD

**Issue by pm-at** [blokadaorg/blokada#443]
### Steps to reproduce
1. Turn on notifications for blokada
2. Wait for it to block some traffic

### Expected behaviour

The notifications should appear collapsed as we're generally not interested in what is being blocked. We keep the notifications ON to prevent blokada being killed by power saving features of OS.

### Actual behaviour

The notification always appears expanded with no way to permanently collapse it.
..

### Configuration
1. Blokada version
4.0

2. Device model
Honor 6x

3. Android version / ROM
Android 7, EMUI 5.0.2

### Questions
1. How long have you been using Blokada? 
1.5 Yrs

2. How long time ago has the problem started to happen? 
Since upgrading to v4

3.  How often does this problem happen to you?
Always when I pull notifications drawer

**Comment by cauthulhu** [comment]
FWIW it's always collapsed on mine (LG V20, Oreo 8.0 stock ROM). Oh and v4.1.4 has been released

**Comment by alexa-v2** [comment]
Not collapsed by default here, every reboot I have to recollapse
Resurrection Remix 7.0.2, Android 9, Moto Z3 Play

**Comment by pm-at** [comment]
Upgraded to v4.1.4. but the issue still persists.

**Comment by rpeter85** [comment]
The OS sets the Notification to appear in a chatty way, showing everything. Can you guys check if in the system settings there's a way to disable Expanded Notifications?

**Comment by pm-at** [comment]
I couldn't find it in either common system settings or app notification settings.

Thanks

![IMG_20190724_123125](https://user-images.githubusercontent.com/37295029/61772524-22ea4900-ae10-11e9-8f85-0615da6e12c5.png)

**Comment by alexa-v2** [comment]
@rpeter85 I don't know what ROM you use, but I use Resurrection Remix and I still don't have that option. And RR is something like the best ROM for customization

**Comment by rpeter85** [comment]
Havoc OS. The main point is, that the system can force to have the full notification, and you might don't have the ability to change it.
Dunno how much the developer can manipulate the notification, though.

**Comment by alexa-v2** [comment]
Did you just say you use Havoc? Get out of here xD

**Comment by alexa-v2** [comment]
@rpeter85 TBH it's not too hard to collapse it manually and it stays that way until reboot
Lowering priority also works btw, which _us_ something an app developer can do

**Comment by pm-at** [comment]
On my phone, even after collapsing the notification always comes expanded after reopening notifications drawer.

**Comment by cauthulhu** [comment]
I set the notifications to Medium: No Sound, so maybe that's why mine is always collapsed, even after a reboot

**Comment by kar** [comment]
It has no sound configured. Are we talking about the ad blocked notification or keep alive notification?

**Comment by pm-at** [comment]
Its about Keep Alive Notification, where it shows the total count of blocked and also displays some recently blocked urls (screenshot attached).
![Screenshot_20190725-193651](https://user-images.githubusercontent.com/37295029/61881283-fddefe80-af13-11e9-97a2-3246dd3709f2.png)

**Comment by ps100000** [comment]
> @rpeter85 TBH it's not too hard to collapse it manually and it stays that way until reboot
> Lowering priority also works btw, which _is_ something an app developer can do
The priority is already set to the minimum. You can check here: https://github.com/blokadaorg/blokada/blob/master/app/src/legacy/kotlin/notification/ANotificationUtils.kt#L105

**Comment by ps100000** [comment]
The notification uses only default layouts/functions so it's completely Androids decision how the notifications is shown and how it reacts to user input. :man_shrugging:

**Comment by Sispheor** [comment]
On Android 10 the notification takes almost half of the screen. It is possible to disable logs? I would like to have only one line.
