### ISSUE TITLE
Blokada v4 not available on F-Droid

### ISSUE THREAD

**Issue by wolkenschieber** [blokadaorg/blokada#444]
Blokada v4 isn't available on F-Driod. Following the link on the project's repository main page leads to [Blokada v3 (ad blocker)](https://f-droid.org/packages/org.blokada.alarm/).

**Comment by rpeter85** [comment]
The code is pushed to F-droid, the release depends on their processing time.

**Comment by wolkenschieber** [comment]
Fyi, merge request is still pending in fdroid: https://gitlab.com/fdroid/fdroiddata/merge_requests/5088
