### ISSUE TITLE
Bring "Blokada DNS" to the v4.x code base

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [blokadaorg/blokada#447]
As explained in https://github.com/blokadaorg/blokada/issues/302#issuecomment-513557526 I can't ATM use the normal Blokada App, because I have NorthVPN and Blokada don't support ATM OpenVPN (see: Issue #111). But Blokada DNS can maybe help me to reach my goal to use OpenNIC as DNS, too. So I want friendly ask to bring Blokada DNS to the 4.x code base. This will hopefully be the first step to have a development future for Blokada DNS and to bring maybe IPv6 support later to the App, too. Because this seems to be ATM missing and should come to prevent DNS leaks over IPv6.
For more explanation issue follower can read: https://www.vpncrew.com/understanding-ipv6-and-dns-leaking/

**Comment by bossey1** [comment]
I am also using 3 year subscription to ipvanish and cannot afford to pay for Blokada internal VPN. Just discovered Blokada a few days ago and was really happy until I discovered my VPN shutdown whenever I enabled it. I'm very sad to say goodbye.

**Comment by ps100000** [comment]
The VPN feature is completely optional. if You just want to change your DNS you can still install v4.1. Just deactivate the adblocking feature and you're basically left with a v4 DNS changer. :)

**Comment by ps100000** [comment]
> I am also using 3 year subscription to ipvanish and cannot afford to pay for Blokada internal VPN. Just discovered Blokada a few days ago and was really happy until I discovered my VPN shutdown whenever I enabled it. I'm very sad to say goodbye.

Sadly there is no way to block ads on Android without using the VPN API. At least if you don't want to root your device.

**Comment by bossey1** [comment]
> 
> 
> > I am also using 3 year subscription to ipvanish and cannot afford to pay for Blokada internal VPN. Just discovered Blokada a few days ago and was really happy until I discovered my VPN shutdown whenever I enabled it. I'm very sad to say goodbye.
> 
> Sadly there is no way to block ads on Android without using the VPN API. At least if you don't want to root your device.


My device is rooted and I've been using Adaway but this seems to only work well if also using _Magisk_ and I find it invloved and finicky.
Blokada seems smooth to use . I wonder if in future there will be a switch inside the program that allows rooted devices to use their own VPN

**Comment by kar** [comment]
It's ready and called Blokada Slim now. Google Play is reviewing (and rejecting) the update, so hopefully we'll figure out what they want soon.
