### ISSUE TITLE
Add more VPN payment methods

### ISSUE THREAD

**Issue by jwsp1** [blokadaorg/blokada#448]
With blokada v4, you can use integrated VPN. But currently the only way to pay for this is via credit card. 
It would be nice if you consider adding other payment methods like 
•PayPal (one-time payment or subscription), 
•gift card codes (x€ = x Days), 
•Telegram Payment,
•pay with cash by sending a postal letter with € and account number (x€ = x Days),
•...
Thanks :)

**Comment by powerxale** [comment]
Telegram Payments would be great: through the Blokada group, the payments could be managed easily

**Comment by jwsp1** [comment]
> Telegram Payments would be great: through the Blokada group, the payments could be managed easily

I'm not sure whether it is possible to manage payments via public group. 
Instead, what about a blokada-bot? It could handle payments easily (e.g. see http://t.me/Premium_TheFeedReaderBot) and answer questions (what rose-bot currently does in the blokada group, but this makes the group VERY spammy and chaotic).

**Comment by Notabas-iC** [comment]
Hello,
it got requested by a user in the german telegram group to add the german payment method "Sofortüberweisung" (https://www.klarna.com/sofort/).

**Comment by PrintableCharacter** [comment]
PayPal has been added in the most recent updates.

**Comment by jwsp1** [comment]
IMHO, PayPal is not enough. Yes, I'd use it, but PayPal doesn't respect privacy that much.
For a future update, cash payment, payment via gift cards, etc would be more privacy friendly :)

**Comment by PrintableCharacter** [comment]
What do you mean by "it doesn't respect privacy that much"? All it does is it shares your information with over 600 third parties. :joy:
Don't worry. More payment methods will be implemented. There's just no ETA and guarantee which ones will make it.

**Comment by jwsp1** [comment]
Good to hear, thank you! Keep up the great work!

**Comment by kar** [comment]
As you noticed Paypal is added in 4.2, we are testing stability of the integration. I'll keep this task open for future discussion about other methods.

**Comment by kar** [comment]
We've added cryptocurrency payment through Stellar a while ago, and Google Pay support through Stripe. I'll close this for now, but feel free to add new comments.
