### ISSUE TITLE
DNS over HTTPS

### ISSUE THREAD

**Issue by RichardEb** [blokadaorg/blokada#449]
You may want to implement a DNS over Https resolver in your app? Blokada can't block requests that uses DoH. But if you combine the VPN based Blocker with a DoH resolver your app also supports the new DoH approach.

What you shouldn't do is intercepting DoH requests as man in the middle and read the encrypted content. This is a nogo for me. 

But a DoH resolver would be nice.

**Comment by rpeter85** [comment]
See #198
