### ISSUE TITLE
Is there a back-door to this?

### ISSUE THREAD

**Issue by jmiker919** [blokadaorg/blokada#45]
I installed this about 3 days ago. This morning I was talking on the phone, using an earpiece, and I noticed the photo Gallery button kept being put into edit mode. I'd hit another button to clear it and a moment later it would happen again.

Then I noticed the Gallery was open and the list of folder thumbnails was being scrolled. I immediately shut down the phone and restarted it. 

Obviously I have no way to know if it was due to this app. But after years and years of having smartphones and never once seeing this before it has to make me seriously question it.

Any insights or comments are definitely welcome.
Thanks.
Mike

**Comment by kar** [comment]
Are you rooted?

How did you download Blokada? Website, fdroid?

**Comment by jmiker919** [comment]
The phone is not rooted. I got the file from blokada.org. Downloaded the .apk to the phone and installed from there.
Thanks for the response.

**Comment by zyklide** [comment]
Try a proxy server to watch.

**Comment by kar** [comment]
I doubt your problem is related to the app. You may wanna try downloading (after uninstalling) using direct links from github: https://github.com/blokadaorg/blokada/releases/tag/v2.2.2
