### ISSUE TITLE
Add a "Tour" or a "Blokada Manuel" link to main page

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [blokadaorg/blokada#451]
I'm new to v4.x and I just realised that Blokada have after install no, or nearly now funtionality with the default settings, or at least - if you wanna ignite the power of Blokada - you have to adjust some/many settings. Maybe this is a "Don't change just all"-Policy of Blokada, but the user maybe expect (know it from other apps) that Blokada "just do its job" after install with the default settings...
Also I needed some time to find out, that in settings I can click on a setting to see an explanaition of the setting...
I think this all can be inproved by adding a) a "Tour" to Blokada that gets started by the first start of Blokada and maybe later from a button in the menu, or b) by adding a "Blokada Manuel" link to the main page, that open a online manuel.

**Comment by Tobias-B-Besemer** [comment]
Btw.: I don't know what a "Filter" is compared to a host file. Maybe someone can in short explain that to me.

**Comment by kar** [comment]
There's "Learn more" section in the menu, you can find a lot of info there. For new questions just head to our Telegram. We update the help based on the feedback there.
