### ISSUE TITLE
Problems with German translation

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [blokadaorg/blokada#452]
I found two glitches in the German translation...

1) The description of "Filter Counter" is hard to read, there should be maybe a hypen before and after "abhängig von anderen Apps auf Deinem Gerät".

![Screenshot_20190724-063805_Blokada](https://user-images.githubusercontent.com/11881073/61767021-26b3a680-ade3-11e9-8adb-cb15a29d9fb9.jpg)

2) On main page, the dialog "Donate" have the word "Hier" included with a typo (second letter is also big) that you can read "HIer".

![Screenshot_20190724-063954_Blokada](https://user-images.githubusercontent.com/11881073/61767030-303d0e80-ade3-11e9-909a-75faa7a6d0f4.jpg)

If someone point me to the right procedure/page/file, I will change that...

**Comment by rpeter85** [comment]
The translation is available on CrowdIn: https://crowdin.com/project/blokada
Please suggest translation things there.

**Comment by Tobias-B-Besemer** [comment]
Never worked with CrowdIn and the platform seems to be "not so easy"...
![Screenshot_20190724-075505_Firefox Beta](https://user-images.githubusercontent.com/11881073/61768769-b019a780-ade8-11e9-9fca-6092ae65e32c.jpg)
![Screenshot_20190724-075511_Firefox Beta](https://user-images.githubusercontent.com/11881073/61768778-b4de5b80-ade8-11e9-8139-b4a517f4c483.jpg)

**Comment by rpeter85** [comment]
Still, the translation can be done there.
