### ISSUE TITLE
First tip in Blokada v4.x is, to update to v4.x

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [blokadaorg/blokada#453]
The first tip I got on Blokada v4.x was to update to Blokada v4.x... ^^

![Screenshot_20190724-062813_Blokada](https://user-images.githubusercontent.com/11881073/61767238-eacd1100-ade3-11e9-8f88-cc056b142b1f.jpg)

**Comment by Tobias-B-Besemer** [comment]
Also: The line with "You can download it Donate" looks wrong... ;-)

**Comment by kar** [comment]
Are you getting this on 4.1?

**Comment by kar** [comment]
Fixed link. for technical reasons 4.0 message will show this v3 mention. It should not for 4.1 onward.
