### ISSUE TITLE
Problems with the setting "Notification"

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [blokadaorg/blokada#454]
The setting "Notification" have...

1) As description, that it don't have a description what is not helpfuly.
![Screenshot_20190724-063506_Blokada](https://user-images.githubusercontent.com/11881073/61767616-23b9b580-ade5-11e9-95fb-7789cec9a231.jpg)

2) If I activate it, I get two notification, that are redundant.
![Screenshot_20190724-063430_Blokada](https://user-images.githubusercontent.com/11881073/61767639-359b5880-ade5-11e9-8429-6f76338eb216.jpg)
![Screenshot_20190724-063443_Blokada](https://user-images.githubusercontent.com/11881073/61767660-3df39380-ade5-11e9-8a36-8a65d390d11d.jpg)

**Comment by rpeter85** [comment]
Just a short question, based on the screenshots, is it possible you have Blokada and Blokada DNS from Play Store on your device?

**Comment by aadegbite** [comment]
> The setting "Notification" have...
> 
> 1. As description, that it don't have a description what is not helpfuly.
>    ![Screenshot_20190724-063506_Blokada](https://user-images.githubusercontent.com/11881073/61767616-23b9b580-ade5-11e9-95fb-7789cec9a231.jpg)
> 2. If I activate it, I get two notification, that are redundant.
>    ![Screenshot_20190724-063430_Blokada](https://user-images.githubusercontent.com/11881073/61767639-359b5880-ade5-11e9-8429-6f76338eb216.jpg)
>    ![Screenshot_20190724-063443_Blokada](https://user-images.githubusercontent.com/11881073/61767660-3df39380-ade5-11e9-8a36-8a65d390d11d.jpg)

Is this by any chance a Xiaomi device? If yes what is the device model? Also, what version of Blokada did you install?

**Comment by ps100000** [comment]
they are different notifications. The first is visible if you activate the notifications. The second, permanent one is always there if you activate "keep alive". They show slightly different information and have different actions. If you don't need the "normal" notifications I would recommend you deactivate the notifications and leave only "keep alive" active.
