### ISSUE TITLE
FR: "Root Mode" without internal VPN

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [blokadaorg/blokada#455]
Think this will need some work and be a long term goal, but I open a FR (Feature Request) for it anyway...

On rooted devices it is IMHO "not so nice" to run a internal VPN if it isn't needed...
Therefor a "Root Mode" were Hosts file and DNS is done without internal VPN would be nice!
This would also fix issue #111 at least for root users...

**Comment by rpeter85** [comment]
Blokada won't go into that direction. There are already tools that work on rooted devices.

**Comment by kar** [comment]
#302 related
