### ISSUE TITLE
I want to add Digitalcourage DNS

### ISSUE THREAD

**Issue by cybertschunk** [blokadaorg/blokada#457]
hi guys,

the german civil rights NGO Digitalcourage hosts a DNS-server which isn't censoring or logging at all. The server also supports DoT and DNSSEC. You can read more about it here: https://digitalcourage.de/support/zensurfreier-dns-server (in german) and in the german wikipedia: https://de.wikipedia.org/wiki/DNS_over_TLS

It would be great, if you could add the server to your list.

**Comment by rpeter85** [comment]
It is added with [PR#40](https://github.com/blokadaorg/blokadaorg.github.io/pull/40)
