### ISSUE TITLE
I want to add hunfilter to blokada

### ISSUE THREAD

**Issue by Muvuk** [blokadaorg/blokada#458]
Helo, 

there is a hungarian adblock filter list what is maintained and up to date. It focus ads on Hungary, but maybe it worth to use in another country. 

Could you add this list, please?
https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter.txt

here is the github repo: 
https://github.com/hufilter/hufilter

Or is there a way to fix asap list adding feature in blokada? I cant add this huge list per lines by hand. 

keep up the good work!

**Comment by rpeter85** [comment]
Hello,
Thanks for the list, but unfortunately it cannot be added, as Blokada works on host level, not in application level.
Refer here: go.blokada.org/help#adblock


BTW, I use HUfilter on my PC, thank you for your work.
