### ISSUE TITLE
cant browse net on mobile data, wifi works fine

### ISSUE THREAD

**Issue by Gibbz** [blokadaorg/blokada#46]
I have this odd issue with my new install of blakada.
It was working fine on my home wifi. But when im out using mobile data i cant browse the net or get any net data. Whats the fix for this?

**Comment by kar** [comment]
Please answer those questions and put your username in the report go.blokada.org/bug_en

**Comment by kar** [comment]
I can see you entered the report, but please also respond to the questions you selected "I don't know" for, you'll find info in the about screen.

**Comment by Gibbz** [comment]
I wiped my phone and reinstalled my rom. This looks to have fixed the issue. So i don't think I'll be able to help find the issue. 
Thanks for the app.

Will you be adding this to fdroid open android store?

**Comment by kar** [comment]
It's already there.
