### ISSUE TITLE
apps bypass not working

### ISSUE THREAD

**Issue by sterno1966** [blokadaorg/blokada#460]
### Steps to reproduce
1.bypas app
2.app still broken
3.

### Expected behaviour

app not be blocked

### Actual behaviour

app wont work

### Configuration
1. Blokada version
414

2. Device model
nvidia shield

3. Android version / ROM
8.0

### Questions
1. How long have you been using Blokada? 
over a year

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by rpeter85** [comment]
Did you restart the device after you bypassed the app? On some devices that can help, give that a try.

**Comment by sterno1966** [comment]
ya i tried that it breaks the cbsn app i tried rebooting and but not help

**Comment by PrintableCharacter** [comment]
Can you provide me with an specific App name?

**Comment by sterno1966** [comment]
cbsn cbs news

**Comment by sterno1966** [comment]
issue fixed thank you
