### ISSUE TITLE
Dns cache should be flushed when changing network

### ISSUE THREAD

**Issue by esheesle** [blokadaorg/blokada#461]
### Steps to reproduce
1.  Connect to mobile network while running blokada and browse to a website
2. Connect to wifi network running blokada
3.  Try to connect to website where dns response differs when on wifi and it fails

### Expected behaviour

Dns cache should be flushed when changing networks to account for differing dns results.

### Actual behaviour

Cache is not flushed

### Configuration
1. Blokada version
4.1

2. Device model
Xperia XZ3

3. Android version / ROM
9.0

### Questions
1. How long have you been using Blokada? 
1 week

2. How long time ago has the problem started to happen? 
Always

3.  How often does this problem happen to you?
Always

**Comment by ps100000** [comment]
Blokada doesn't cache the dns response. Only the apps your having trouble with could in therory cache the IP but Blokada can't clear the cache of another app after a network change. If you're having trouble with some page try deleting your browser cache.

**Comment by esheesle** [comment]
If i'm not running Blokada, when I go from 4g network to my home network, my website works correctly.  If i am running Blokada it does not work correctly (unless i reboot the phone).  The dns resolution remains the same as what it was on the first query.  Without blokada, the dns response is immediately different when changing between network.  Maybe it is related to the vpn connection and not blokada specifically, but there is a different behavior.

**Comment by ps100000** [comment]
is your page a local domain resolved by your router or whatever local DNS you have set up you are connected to your wifi or is it the same as on mobile network?

**Comment by esheesle** [comment]
Page is local and has different IP resolution on local wifi vs external.

**Comment by ps100000** [comment]
deactivate DNS fallback if you it's active.
