### ISSUE TITLE
Suggestion: The v4.1.4 UI is too confusing

### ISSUE THREAD

**Issue by Sandaidev** [blokadaorg/blokada#462]
Hello! This is my first reported issue here, and it's more of a suggestion/observation.

Keep in mind that this is from an end user perspective, I don't necesseraily dislike the current UI, I know that some things are complicated to implement etc...

Keep also in mind that this is a ***subjective*** observation, my opinion may differ from yours.

Now here are my observations:
- The UI, while simplified on the main screen, feels too cluttered because of the sub-menus of sub-menus, it is less intuitive than v3's UI
- The UI feels like it was designed for developers, not users. A lot of the options that could be easily found in v3's interface are well hidden inside sub-menus here
- The persistant notification now displays more than one host blocked, it feels too big for a background service
- I cannot longer clear the number of blocked hosts anymore, it was possible in v3

### Configuration
1. Blokada version
v4.1.4

2. Device
Honor 6X Pro

3. Android version / ROM
Android 7 (EMUI 5.0.3)

### Questions
1. How long have you been using Blokada? 
Since mid-2018

2. How long time ago has the problem started to happen? 
Since I started using Blokada v4

3.  How often does this problem happen to you?
Everytime since I started using v4

**Comment by PrintableCharacter** [comment]
Hello,
It is impossible to return to the v3 Design due to new and future functionalities of blokada.

The possibility to reset the "blocked" counter is already implemented and will be pushed out with the next update.

**Comment by Sandaidev** [comment]
I am not necessarily saying that Blokada should return to its v3's design, but it was just some feedback on the new design, I just find the new UI too complicated and less user-friendly than the old one, but again, I agree that the UI had to be changed and I'm okay with that, but maybe review and improve the new one in order to make things simpler?

In any case, thank you for your response, have a good day, sir!

**Comment by sterno1966** [comment]
i had a little trouble with the new gui but once i got aquanted with it its ok now

**Comment by kar** [comment]
Changes always feel confusing, give it some time to get used to. If you still see things that could be improved, feel free to create a new issue. The persistence notification point is a good feedback, feel free to create issue for it. The rest is not precise, but we'll keep evaluating and improving the Ui as we go!
