### ISSUE TITLE
[Riot.im/Matrix] Blokada by default blocks connections making Riot.im unusable

### ISSUE THREAD

**Issue by KopfKrieg** [blokadaorg/blokada#463]
# Steps to reproduce
1. Install [Riot.im from f-droid](https://f-droid.org/de/packages/im.vector.alpha/)
2. Register & Login to Riot.im (I've used the default servers from matrix.org)
3. Install [Blokada v4.1.5 from f-droid](https://f-droid.org/de/packages/org.blokada.alarm/)
4. Enable Blokada
5. Switch back to Riot.im and try to chat

### Expected behaviour
Chatting should be working fine.

### Actual behaviour
It shows an no-connection error (connection to server not possible)

### Configuration
1. Blokada version
Version 4.1.5

2. Device model
OnePlus 2

3. Android version / ROM
One of the current releases of LineageOS 16.0 (Android 9)

### Questions
1. How long have you been using Blokada?
I've used it in the past (but haven't been using Riot.im back then), and now installed it again (literally a day ago).

2. How long time ago has the problem started to happen? 
Since I installed it. Not sure if it worked earlier or if it's a regression.

3.  How often does this problem happen to you?
Every time, the error's reproducable.

**Comment by rpeter85** [comment]
Hey,
Try whitelisting the app: go.blokada.org/help#allowlist

**Comment by KopfKrieg** [comment]
I wanted to configure the allowlist for Riot.im, but it's working now. I don't know why, it didn't work before, but I'm closing the issue for now. Hopefully the app won't get blocked again.
