### ISSUE TITLE
Bring back master switch 

### ISSUE THREAD

**Issue by alexa-v2** [blokadaorg/blokada#465]
In version 3.7 and different in 4.0 there was a master switch as it were to disable all Blokada functionality

Now (in my experience, apparently no one else has the issue) I have to force stop Blokada and reopen to toggle vpn, Toggling vpn is needed for apps white/blacklist

According to @Seba_J on telegram there's now at least two switches you have to toggle to shut off Blokada and it's not clear that you need to do this to toggle the VPN

So my suggestion is to make sure there's a clearly labeled master switch to disable _all_ functions of Blokada and disconnect the VPN entirely 

_Sent from my moto z3 play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rich123** [comment]
Seconded - the old Blokada UI had a single, global, on/off switch.

The new UI has two separate switches to produce a global on/off state.

Please bring back the single on/off (for all Blokada functionality) single button switch.

**Comment by kar** [comment]
Brought back in 4.1.6
