### ISSUE TITLE
Blokada sometimes blocks all traffic

### ISSUE THREAD

**Issue by beatschubser** [blokadaorg/blokada#466]
### Steps to reproduce
Everyday use

### Expected behaviour
Blokada working as expected

### Actual behaviour
Sometimes Blokada starts blocking all traffic. It seems to happen when switching between mobile and Wifi or after using a local Hotspot or another VPN.

Disabling Blokada solves the problem, but to make Blokada work again you have to restart the phone.

### Configuration
1. Blokada version 
4.1.4 (also happens with 3.7)
Default settings, no custom DNS or anything.

2. Device model
Xiaomi Mi Mix 3

3. Android version / ROM
MIUI 10.3.2

### Questions
1. How long have you been using Blokada? 
For two months

2. How long time ago has the problem started to happen? 
From the very beginning

3.  How often does this problem happen to you?
1-2 times a day

**Comment by kar** [comment]
Try sharing logs with us privately soon after that happens... for example send them to hello@blokada.org

**Comment by fruity101079** [comment]
The same for me. Last updates (1 or 2 months) brings this bug.
It's becoming unusable, everyday network is completely blocked.
Im on oneplus 6 , blockada 4.1.6, Android last August update by oneplus.

**Comment by waclaw66** [comment]
Same here on Mi 9T, using Blokada 4.1.6 randomly freezes apps acessing internet (no matter on wifi or mobile data) for cca 10-20s. Everything works fine after uninstalling Blokada.

**Comment by racuna** [comment]
I think bug #284 is back. I have the same issue and switching between DNS servers resolve the problem temporarily (v. 4.1.5 from F-droid on Android 9)

Using Cloudflare, Quad9, FreeDNS and DNS.WATCH

**Comment by kar** [comment]
Thanks guys, and thanks for sending over logs. I'm raising the priority of this issue. Stay tuned.

**Comment by peloy** [comment]
Just in case it helps, when this problem (or what happens to me that looks like the problem described in this issue) occurs, Blokada's Host Log says that the domain resolution for a host has been allowed but the answer somehow does not seem to make it to the application making the DNS requests -- I tested by running ping on a terminal window: the ping hangs waiting for DNS resolution to complete, I see the allowed entries in the Host Log, and after a minute the ping gives up and produces a "host not found" error message.

**Comment by Oizaro** [comment]
I don't know if it is related to this bug, but after turning on my Samsung S10 the ad blocker keeps trying to activate without success, and also after activation there is an abnormal power consuption.

There is something that could be done to avoid this behaviour? Thanks

**Comment by agrenott** [comment]
Hi, the issue still persists in blokada 4.3.5.

**Comment by waclaw66** [comment]
> 
> 
> Hi, the issue still persists in blokada 4.3.5.

I have the same feeling, not so often, but it does.
