### ISSUE TITLE
Blokada 4.1.5 does not load lists and does not block ads

### ISSUE THREAD

**Issue by camelCaseNick** [blokadaorg/blokada#469]
### Steps to reproduce
1. select host list and/or add hosts to to blacklist
2. check if any request is block to host, to which the request should be blocked

### Expected behaviour
requests should be blocked

### Actual behaviour
* requests are not blocked
* in list settings it says, that 0 rules where updated 0 min ago
* no requests are shown in the host log

### Configuration
* Blokada version: Blokada 4.1.5
* Device model: Huawei P8 lite 2017
* Android version: EMUI 8.0.0 (based on android 8.0.0)

### Questions
* How long have you been using Blokada? since January 2019
* How long time ago has the problem started to happen? since update to v4.1.5
*  How often does this problem happen to you? always

**Comment by ps100000** [comment]
Could you connect to a WiFi network or deactivate "Download on WiFi only" and click on "Download lists now"? If the problem still remains you could try clearing cache & storage of Blokada.

**Comment by camelCaseNick** [comment]
I am connected to a WiFi. It always stated that 0 rules where updated 0 min ago, no matter what really was the case. A already had tried to clear the cache and the storage. It hadn't work. Though now clearing and restarting before reconfigurating did the job. (And I have no clue why.) But it is resolved for me. (And as nobody else commented on this I assume it, it was only for me.)

**Comment by camelCaseNick** [comment]
It says again 0 rules where updated 0 min ago. It only lasted for less than an hour. Clearing the storage works. Though it will loose something again. Is there any way of obtaining a log file?

**Comment by camelCaseNick** [comment]
I have an idea now. It works if stored on internal storage, but not on external storage. I have permitted Blokada to store on the microSD card. Is there a problem with encrypted android partitions?

**Comment by rpeter85** [comment]
The external storage in this case isn't the SD Card, but a directory on the system that users can also access. That's /Downloads/Blokada
Is your device encrypted?

**Comment by camelCaseNick** [comment]
@rpeter85 Yes, my device is encrypted. Though my download directory is selected to be on my microSD card, which of course isn't encrypted.

**Comment by rpeter85** [comment]
Could you let me know how did you set to store the settings on your SD card?
The reason of my question is the fact I shared in my previous comment.

**Comment by camelCaseNick** [comment]
In the android settings in the menu `storage` one can select a default path – either the internal storage or the microSD card. If the latter is selected, the `/Download` directory is stored on the external storage of the phone. In that i find a directory named `./blokada`. If in Blokada the external storage is selected and apparently the android download directory is used, that is on my microSD card.

**Comment by ZorroTheImpaler** [comment]
I think I am having the same issue as the OP. My blokada does not show lists to choose from (just a blank page with the option to add a host) and has the app has 0 rules. Android also does not show the VPN icon. I am running Pixel Experience on the Xiaomi K20 pro. Other VPN services work fine and show the icon. I am running blokada 4.2.1

I have downgraded to v3.4 and it works great.

**Comment by PeterDaveHello** [comment]
Looks like Blokada v4.1.5/4.2.1 doesn't properly determined if the device is on WiFi environment, so when the "Download on WiFi only" option is on, the functionality could be broken, that's what I'm seeing.

**Comment by ZorroTheImpaler** [comment]
> Looks like Blokada v4.1.5/4.2.1 doesn't properly determined if the device is on WiFi environment, so when the "Download on WiFi only" option is on, the functionality could be broken, that's what I'm seeing.

That does not seem to be the case. To test your recommendation I decided to update from v3.4 via the in app update option (to 4.1.4). The app is now running perfectly fine at 4.1.4 with the lists from my previous version selected automatically and applied. Other lists also appear. _Download on WiFi only_ is still checked. The VPN icon on the top bar of android also appears as it should. 

Maybe this is a problem with a file (broken in 4.1.4) that does not get overwritten by an update that prevented my clean (first time) install of blokada 4.1.4 from working. If the file was kept from 3.4 (maybe a config) and carried over in the update it would explain the behavior. Alternatively it could be a problem with permissions that the older version did not have which were carried over to the new version (as I was not asked for vpn permission after the update). Maybe the author can also try upgrading from a working instance of 3.4 to 4.1.4 via the app to see if what happened for me wasn't just a fluke.

**Comment by PeterDaveHello** [comment]
> > Looks like Blokada v4.1.5/4.2.1 doesn't properly determined if the device is on WiFi environment, so when the "Download on WiFi only" option is on, the functionality could be broken, that's what I'm seeing.
> 
> That does not seem to be the case. To test your recommendation I decided to update from v3.4 via the in app update option (to 4.1.4). The app is now running perfectly fine at 4.1.4 with the lists from my previous version selected automatically and applied. Other lists also appear. _Download on WiFi only_ is still checked. The VPN icon on the top bar of android also appears as it should.
> 
> Maybe this is a problem with a file (broken in 4.1.4) that does not get overwritten by an update that prevented my clean (first time) install of blokada 4.1.4 from working. If the file was kept from 3.4 (maybe a config) and carried over in the update it would explain the behavior. Alternatively it could be a problem with permissions that the older version did not have which were carried over to the new version (as I was not asked for vpn permission after the update). Maybe the author can also try upgrading from a working instance of 3.4 to 4.1.4 via the app to see if what happened for me wasn't just a fluke.

How to verify my description for v4.2.1 on your v4.1.4?

**Comment by ZorroTheImpaler** [comment]
> How to verify my description for v4.2.1 on your v4.1.4?

Whoops. Sorry! I seem to have gotten the versions mixed up. The app updated me to 4.1.4 which is working on my device. I just tested 4.2.0 which i updated from the website and it also works fine, even when download on WiFi only is checked.

**Comment by PeterDaveHello** [comment]
Hi @kar,
Does this was fixed already? Thanks.

**Comment by PrintableCharacter** [comment]
@PeterDaveHello as you can see, kargs closed this issue and 4.3.5 is already published. Give it a try :)
