### ISSUE TITLE
Blokada don't work properly since 1 month ago

### ISSUE THREAD

**Issue by Igmc** [blokadaorg/blokada#47]
Blokada don't start automatically, and It don't block all the ads (they have been blocked before). 
It's hard to activate it, because It not responses.

**Comment by kar** [comment]
Can you try one of the older versions and see if it works better for you? https://github.com/blokadaorg/blokada/releases

**Comment by Steve2Go** [comment]
I'm also having issues with auto start. 
I believe it's related to sdk 27 start service in 8.0
https://developer.android.com/reference/android/content/Context.html#startService(android.content.Intent)

Hope this helps

**Comment by kar** [comment]
Autostart is another issue, please move the discussion .
