### ISSUE TITLE
Blocks legitimate site

### ISSUE THREAD

**Issue by alleluia20** [blokadaorg/blokada#470]
I am using Blokada, latest version (4.1.5), using the hosts: Unified Stevenblack, Energised Blue and AdZHosts. I cannot browse the site of the community help of IMDB, https://getsatisfaction.com/imdb: I get DNS_PROBE_FINISHED_BAD_CONFIG

If I disable Blokada, I can browse the site without issues.

Thank you.

**Comment by camelCaseNick** [comment]
@alleluia20 In the Energised Blue filter list getsatisfaction.com is blocked. You could add it to your whitelist in Blokada or open an issue over there.

**Comment by cauthulhu** [comment]
@alleluia20 Just a heads-up, adZHosts is no longer maintained for about a year
