### ISSUE TITLE
blacklist item not working

### ISSUE THREAD

**Issue by BlueValori** [blokadaorg/blokada#471]
### Steps to reproduce
1. Create new blacklist with g00.wetteronline.de
2. Browse www.wetteronline.de
3. View Log and see that all content from *.g00.wetteronline.de is allowed

### Expected behaviour
I would expect the domain to be blocked.

### Actual behaviour
All traffic from the domain g00.wetteronline.de is allowed.

### Configuration
1. Blokada version
4.1.4

2. Device model
Samsung SM-P905
Sony Xperia E5823

3. Android version / ROM
5.0.2
7.1.1

### What else have I tried?
Try different browsers.
Reinstallation.
Restarts.
For the few other blacklist domains like graph.facebook.com it works just fine. Its so far only the g00.wetteronline.de that is not blocked.

### Questions
1. How long have you been using Blokada? 
3 months

2. How long time ago has the problem started to happen? 
Since I try to block the domain.

3.  How often does this problem happen to you?
Always.

**Comment by ps100000** [comment]
Blokada only blocks the specified domain and not any subdomains. So if only domains like _something_.g00.wetteronline.de are allowed but the domain g00.wetteronline.de is getting blocked there is no issue. If g00.wetteronline.de isn't blocked you could try adding www.g00.wetteronline.de. Additionally you should check that you don't use to many rules for your device.

**Comment by BlueValori** [comment]
Thanks for the reply.
I only have 3 items on my blacklist so far and the blocklist from default installation. So I expect it to be ok in that regard.
Opening the website www.wetteronline.de displays tons of ads that are loaded through the subdomain g00.wetteronline.de. At least thats how I understand it.
The links are many very long adresses:

![Image_1565268715870](https://user-images.githubusercontent.com/53758495/62705468-c3826080-b9ed-11e9-8ef9-ed5f8599db36.png)

Adding www.g00.wetteronline.de to the blacklist changes nothing.

**Comment by BlueValori** [comment]
Seems like I clicked the wrong button.
Its not solved.

**Comment by rpeter85** [comment]
Blokada blocks what is _exactly_ on the list. If the ads are feom g00.wetteronline.de, then that domain must be on the list. To test, add it with www and without as well.
Currently there is no subdomain or wildcard blocking functionality in Blokada.

**Comment by BlueValori** [comment]
Ok, now I understand that and its a pitty wildcard is not available.
What I don't understand yet is if for example the part "c-6rtwjumjzx78777x24ux2ewknmzgx2ehtr" from c-6rtwjumjzx78777x24ux2ewknmzgx2ehtr.g00.wetteronline.de is a subdomain or not.

**Comment by ps100000** [comment]
wildcards will probably be implemented at some point but there is no ETA. 
yes the long part is a subdomain.

**Comment by BlueValori** [comment]
Oh, ok, so generating random subdomains makes blocking ads impossible at the moment, until wildcards are implemented.
Thanks for helping and clearing my misunderstandings
