### ISSUE TITLE
PIA VPN blocked on Android

### ISSUE THREAD

**Issue by juliangent** [blokadaorg/blokada#472]
Blokada prevents PIA VPN from turning on on my Pixel android phone. 

[blokada.log](https://github.com/blokadaorg/blokada/files/3479537/blokada.log)

### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by alexa-v2** [comment]
No **Android** blocks it
Only one VPN can run at the same time

**Comment by juliangent** [comment]
Got it. 07.08.2019, 20:22, "Alexa" <notifications@github.com>:No Android blocks itOnly one VPN can run at the same time—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
