### ISSUE TITLE
Is it viable to add a non-list based blocking? (like the uMatrix extension) 

### ISSUE THREAD

**Issue by samantohermes** [blokadaorg/blokada#475]

**Comment by kar** [comment]
could you provide a link describing what umatrix is?

**Comment by alexa-v2** [comment]
@kar if you know what ublock origin is (who doesn't) its like a **MUCH**  more complex version of that. It's really meant for advanced users

Also, in its current form, it's impossible to implement in blokada because it also employs cosmetic filtering

**Comment by alexa-v2** [comment]
See https://github.com/gorhill/uMatrix

**Comment by kar** [comment]
Thank you for filling me in. Yeah, we are quite far from tackling the cosmetic filtering..
