### ISSUE TITLE
https://play.google.com/store/apps/details?id=org.blokada.alarm.dnschanger

### ISSUE THREAD

**Issue by nettw** [blokadaorg/blokada#482]
@ps100000 
@rpeter85
@kar 

### Steps to reproduce
https://play.google.com/store/apps/details?id=org.blokada.alarm.dnschanger

### Expected behaviour

It is required to support the input of IPv6 addresses.
Need to have the next new version.

### Actual behaviour

It is still an old version.

### Configuration
1. Blokada version
3.7.030500

2. Device model
Samsung

3. Android version / ROM
9.0

Thanks!

**Comment by rpeter85** [comment]
Sure, thanks.

**Comment by kar** [comment]
duplicates #447
