### ISSUE TITLE
Feature Request: Granular App Bypass> WIFI or DATA :using: Allow | Only In Foreground

### ISSUE THREAD

**Issue by English106** [blokadaorg/blokada#483]
Granular Bypass Control for Host Blocking

**Bypass by connection type** 
     WiFi / Data
**Applicable Rules per connection type**
     Allow / "Only in Foreground"

**Comment by alexa-v2** [comment]
I'm going to add my support to this request because for instance I don't mind rewarded ads while I'm on wifi but on data.... 😒
