### ISSUE TITLE
Chromecast does not work if VPN is active

### ISSUE THREAD

**Issue by balboah** [blokadaorg/blokada#485]
### Steps to reproduce

Stream with chromecast while connected to Blokada VPN.

### Actual behaviour

Chromecast can't connect.

### Configuration
1. Blokada version 4.1.6 
2. Device
android-28 adblockerHome armeabi-v7a samsung-j6lte

**Comment by kar** [comment]
Fixed in 4.2

**Comment by edent** [comment]
I'm on 4.5.2 and still seeing this problem. Anyone else?

**Comment by thunderjew** [comment]
> I'm on 4.5.2 and still seeing this problem. Anyone else?

Yep.

I couldn't configure my chromecast, at all. It said the WiFi had to use a login, but once I deactivated blokada entirely, it worked like a charm.

Blokada v. 4.8.3
