### ISSUE TITLE
Blokada loses selected VPN Gateway

### ISSUE THREAD

**Issue by Smartieman007** [blokadaorg/blokada#486]
Blokada loses the setting of the selected VPN gateway if there is no connection to the Internet for a longer period of time.

###Steps
1: Activate VPN, select gateway for it
2: Airplane mode on over several hours
3: Airplane mode off

###Expected condition
VPN remains active because the selected gateway is retained

###Actual state
The previously selected gateway is deselected.

###Configuration
Blokada V4.1.6
Smartphone Moto G5 Plus
Android 8.1.0

###Frequency
Issue happens every day in the morning after disabling airplane mode. This, since Blokada supports VPN with V4.0.

###Addition
When selecting the VPN gateway BEFORE canceling the airplane mode, the list of VPN gateways is empty.

###Summary
Blokada deletes the list of VPN gateways after some time without an internet connection.

**Comment by Smartieman007** [comment]
###addition
When selecting the VPN gateway BEFORE canceling the airplane mode, the list of VPN gateways is empty.

###Summary
Blokada deletes the list of VPN gateways after some time without an internet connection.

**Comment by tanmay-bhat** [comment]
Can you try with V4.2?. please say whether the issue repeats or not. Thank you.

**Comment by Smartieman007** [comment]
Hi, I updated Blokada to 4.2.0 and the issue is stil open.
Regards, Andreas

**Comment by Smartieman007** [comment]
It's solved with 4.3.0.
Many thanks for solving it.
