### ISSUE TITLE
I want to block only trackers

### ISSUE THREAD

**Issue by Skallwar** [blokadaorg/blokada#487]
I don't mind visual ads on my screen because it is the business model of some of the apps and websites I use. However I don't whant de tracked by the ad provider.

Don't know if it is possible

**Comment by rpeter85** [comment]
Yes. Create a list with only trackers and that will be possible.
Blokada uses 3rd party lists and doesn't check what that host is.

**Comment by Skallwar** [comment]
Maybe a solution would be to classifie the lists to add a toggle on the app, or have two separated list in the Gosthery style

**Comment by rpeter85** [comment]
We can't be sure what a list contains. Only trackers, only ads, both, additional types.
I don't really think it's viable, and with more (and overlapping) lists it would be a complex task to track all of them.

**Comment by Skallwar** [comment]
That a sad, because I want website and apps of small independent dev to keep a revenue...

**Comment by PrintableCharacter** [comment]
You can whitelist these apps...
