### ISSUE TITLE
Allow host for Firebase Dynamic Links

### ISSUE THREAD

**Issue by PerLycke** [blokadaorg/blokada#488]
Blokada blocks datamixer-pa.googleapis.com by default and this prevents Firebase Dynamic Links from working. Blokada is great in blocking ads, but shouldn't harm functionality. Preventing Firebase Dynamic Links from working results in users not being able to sign up in apps using this feature in the process.

### Steps to reproduce
1. Install Blokada and use with default settings.

### Expected behaviour
Firebase Dynamic Links should work.

### Actual behaviour
Firebase Dynamic Links doesn't work due to blocking of datamixer-pa.googleapis.com

### Configuration
1. Blokada version
4.1.6

**Comment by rpeter85** [comment]
Please contact the maintainer of the list you use. Blokada uses 3rd party lists and blocks what are on the lists.

**Comment by iamareebjamal** [comment]
Just whitelist the URL

**Comment by PerLycke** [comment]
@iamareebjamal White list, is that some racist kind of shit? I don't like racism so I can't do what you propose.

**Comment by alexa-v2** [comment]
@PerLycke I recommend you Google "whitelist"

**Comment by PerLycke** [comment]
@alexa-v2 no way dude, not googling any racist stuff. I'm sure guys like you keep a list of blacks too. Unacceptable!

**Comment by PerLycke** [comment]
Psst I'm trolling with you lot because the suggestion from @iamareebjamal was stupid. Probably he didn't care to understand the issue. Stupidity coming from ignorance sometimes inspires to trolling.

Cheers, have a good day!

**Comment by iamareebjamal** [comment]
My suggestion was not stupid as I'm currently using it and it is working as expected. Since you are a troll, I won't waste any more time on you

**Comment by PerLycke** [comment]
> My suggestion was not stupid as I'm currently using it and it is working as expected. Since you are a troll, I won't waste any more time on you

Ignorant and stupid still stands then.
