### ISSUE TITLE
Subdomain blocking

### ISSUE THREAD

**Issue by Oizaro** [blokadaorg/blokada#489]
Currently blokada displays of all those domains, that don't respond exactly to those present in the host file. However I assume that could be possible to add a verification system for subdomains (strings verification?), starting from the main one.

-->

### Steps to reproduce
Open a site with subdomains

### Expected behaviour
Main site and related subdomains blocked

### Actual behaviour
Only main domain is blocked

### Configuration
1. Blokada version 4.1.6

**Comment by tanmay-bhat** [comment]
Hey can you elaborate your issue with which subdomain you're having problem? .It helps to assist you better. thank you.

**Comment by Oizaro** [comment]
@tanmay-bhat 

I'll explain better... For example:

If I block the following site "www.hdblog.it", this block will be not applied on it's subdomain "android.hdblog.it". In this case my expectation is block every page of "hdblog.it" site.

**Comment by kar** [comment]
Duplicates #48
