### ISSUE TITLE
I want Blokada to restart by itself after an update

### ISSUE THREAD

**Issue by Porkepix** [blokadaorg/blokada#490]
### Steps to reproduce
1. Update Blokada with F-droid 
2. During update, Blokada will close, which is normal to update the package.

### Expected behaviour
Blokada should be registered as a service and therefore restart by itself after update have ended

### Actual behaviour
Blokada does not restart and need to be manually restarted by the user.

### Configuration
1. Blokada version
4.1.6

2. Device model
Sony Z3 Compact

3. Android version / ROM
Android Marshmallow - 6.0.1

### Questions
1. How long have you been using Blokada? 
Quite some time

2. How long time ago has the problem started to happen? 
No idea but noticed it now

3.  How often does this problem happen to you?
I guess on every update?

**Comment by kar** [comment]
Correct me if I'm wrong, but no app can restart itself during an update.

**Comment by Porkepix** [comment]
Not *during* the update, but after the update was done, yes it can. I'm not developer on Android so I don't know about the details, but I guess it registers as a service, or something similar.
IM applications for example does so (at least the ones I use).

**Comment by kar** [comment]
which one as a concrete example?

**Comment by Porkepix** [comment]
Conversations does so, I think Riot too but can't tell for sure.

Blokada does it partially as when it's crashing due to lack of memory it's able to relaunch by itself.

**Comment by kar** [comment]
Could you paste links to those apps?

**Comment by Porkepix** [comment]
> Could you paste links to those apps?

Conversations:
https://play.google.com/store/apps/details?id=eu.siacs.conversations&hl=fr
https://f-droid.org/en/packages/eu.siacs.conversations/
https://github.com/siacs/Conversations

Riot:
https://play.google.com/store/apps/details?id=im.vector.app&hl=fr
https://f-droid.org/en/packages/im.vector.alpha/
https://github.com/vector-im/riot-android

**Comment by kar** [comment]
Does Conversations do it immediately after update, or it takes a while before it starts again?

**Comment by Porkepix** [comment]
Honestly, I can't tell for sure as I don't use it very often and it would require that someone talk to me right after update. The best might be to ask them. All I can say is that it's indeed running when someone talk to me later on.

**Comment by Porkepix** [comment]
Did something change? Updated today with F-droid from 4.3.11 to 4.4.2 and it looks like this time, it restarted by itself?

**Comment by peterroth** [comment]
Feature implemented, Blokada restarts in 4.5 and newer versions.
