### ISSUE TITLE
I want to know which list triggered a detection

### ISSUE THREAD

**Issue by AndyP2** [blokadaorg/blokada#493]
In the log, can you identify the list that triggered a block? Then if you see in the log that one or more sites you need are being blocked by a particular list, you can do something about it, e.g. manually editing the list, contacting the list maintainers, or discarding the list entirely. Of course you still have the option to whitelist each site, but if a list starts blocking a class of sites you want, gets a bit over-zealous or maybe stops being maintained, it could be identified and dealt with as a whole.

I reckon it could be done by adding a single byte to each blocking rule to identify which list it came from, which is then copied into the log entry when that rule is triggered. You don't want to consume any more memory than is absolutely necessary, but hopefully adding just one byte to each log entry will be ok.

Numbers could also be assigned to the user's manually added lists; if they were in the range 100-200 it would keep them separate from the standard lists while still fitting in the one byte.

A particular host could be being blocked by rules loaded from more than one list, but (to save memory) it would be sufficient to only identify the first one. When that one had been dealt with, if it subsequently shows up being blocked by another list the user can repeat the process.

**Comment by rpeter85** [comment]
It's not viable. There are a lot of overlaps on the lists, Blokada merges them to have only the unique hostnames (so it won't consume memory for duplicate or triplicate entries), thus, it won't be able to point which list shipped that given blocked site.

**Comment by AndyP2** [comment]
I'm not sure I agree, identifying just one of the lists that blocked a host would allow the user to get them all eventually. I bet most problems would occur on a single list at a time, but currently there is no way to know.

**Comment by rpeter85** [comment]
If the user uses only one list, then it's easy to identify, it more than one is enabled, the lists are merged in memory and Blokada doesn't track from which list the given entry originated from.
