### ISSUE TITLE
Option To default disable for all apps

### ISSUE THREAD

**Issue by LeSnake04** [blokadaorg/blokada#494]
I use blockada only for some Apps. Please Add an option to default disable Blockada for all apps. 

Then the user only have to setup the exeptions and dont have to turn off for every app manually.

**Comment by rpeter85** [comment]
Another request was to block everything by default. So it's a bit contrary. Big number of users want block all, another allow all.

**Comment by LeSnake04** [comment]
Thats why i sad an OPTION.:wink:

 So everyone can use Blokada he want.

**Comment by rpeter85** [comment]
"to default disable" = by default, nothing blocked. Something is either blocked (the feature requested long ago) or allowed.
The option to allow everything is given, you can whitelist every communication in the settings.

**Comment by KoumiCZ** [comment]
I agree, I am in favor!
