### ISSUE TITLE
Host log filled with unknown requests which are automatically allowed.

### ISSUE THREAD

**Issue by kratura** [blokadaorg/blokada#496]
![Screenshot_20190828_202124_org blokada origin alarm](https://user-images.githubusercontent.com/54645212/63889935-82b8ae80-c9d1-11e9-9903-792fc582dadd.jpg)

Here's an example. Where can I send my logs for analysis.

**Comment by cauthulhu** [comment]
If you see random hostnames in Blokada v4, on the 'Ad blocking' screen, you most probably have Google Chrome on your device and face the below situation:
https://unix.stackexchange.com/questions/363512/chrome-dns-requests-with-random-dns-names-malware
This is not a malware, neither a bug. This is how Chrome works.
