### ISSUE TITLE
Some youtube videos are not working properly with blokada activated.

### ISSUE THREAD

**Issue by alexanderadam** [blokadaorg/blokada#497]
_Some_ youtube videos are blocked. Sometimes it's not a whole video but only a part of it.

### Steps to reproduce

I can reproduce it with the following video:

1. watch the video [Drifting Ruby - Episode #002 - Impressionist](https://www.youtube.com/watch?v=YgPAZUw7wfk)
2. The domain `r2---sn-4g5edns7.googlevideo.com` appears in the blocked URLs of blokada and the YouTube app shows `No connection: (Playback ID: $some_random_string)`

However, depending on how YouTube delivers the video for your device and location this could be a different video.

I also can reproduce it with [this video here](https://www.youtube.com/watch?v=tPpvxN-Kqj4) (because the domain `r1---sn-4g5e6ns7.googlevideo.com` is blocked).

I obviously don't want to whitelist the youtube app in general. It is not clear to me why those URLs are blocked in particular. Because most of the other `*.googlevideo.com` requests are working fine. There are just a few that aren't working.

I whitelisted the domain `googlevideo.com` but this doesn't seem to help and [I can't whitelist `*.googlevideo.com` (see open issue 48)](https://github.com/blokadaorg/blokada/issues/48) because it says that this is an invalid domain.

At the moment I am manually allowing those hosts with the help of the host log but I guess most of the users just won't know what happened and what they could do to avoid this.

### Expected behaviour

Playing youtube videos should work in general. :wink: 

### Actual behaviour

It doesn't.

### Configuration
1. Blokada version

`4.1.6` from F-Droid

2. Device model

All devices

3. Android version / ROM

All versions

I'm using those lists:

* Energized Blu
* Goodbye Ads by Jerryn70
* Coin Blocker List

**Comment by peterroth** [comment]
I tested with 4.4.4 and the given video loaded and I was able to watch it while Blokada was on.
Can you please check if it is still blocked for you? If yes, which hosts are recorded in Host Log?

**Comment by alexanderadam** [comment]
The issue happens every now and then with different videos and I have the feeling it also depends to which videos youtube is directing to (which itself is probably also dependent on your location).
It appears random and seldom though and I usually whitelist this host afterwards.

Currently I'm not watching so many youtube videos so I don't know whether it is still happening but I can close this for now and if I continue binge watching youtube videos one day I will write about the next video on where it happens.

**PS:** I can't remember which videos these were that caused this blockings but this is an excerpt of my allow-list. Maybe the cause is some substring of `---sn-4g5e` or so because my allow list contains entries like these:

* `r1---sn-4g5e6ns7..googlevideo.com`
* `r2---sn-4g5edns7.googlevideo.com`
* `r1---sn-4g5e6nzs.googlevideo.com`
* `r2---sn-4g5ednly.googlevideo.com`
