### ISSUE TITLE
"keep alive"-option does not working

### ISSUE THREAD

**Issue by mleenings** [blokadaorg/blokada#498]
#71 # Steps to reproduce
1. Open blockada
2. Switch blockada active
2.1 "keep alive" option is true
3. press the "recents" button, wipe blockada to the left (the App is closed, and DNS switched off)

### Expected behaviour
If I set "keep alive = true", then I expected that the App keeped alive and not closed and turned the DNS off, If I close the App like 3 ....
(If I press the Home Button and let run it in the background, It worked, but this is very battery unfriendly, and this)

### Actual behaviour
Blokada has the settings "keep alive = true" and "start on boot = true". It worked , when I do not close the app (I leave it open in the background). But when I close the app I hoped the "keep alive" option keep it alive, but blockada is closed and is not active. So it only worked if i let it open and the battery do not like it and if I close alle running apps, then the blockada is inactive :(
So please fix the "keep alive" option, so that this really keep alived :)
(I tried Blokada v .4.1.6, but this is not correct packed as apk, I get "There was a problem parsing the package")

### Configuration
1. Blokada version
3.7 (I tried 4.1.6, but when I open the apk a window with "There was a problem parsing the package" opened)

2. Device model
Xiaomi 9T

3. Android version / ROM
MIUI 10
Android 9

### Questions
1. How long have you been using Blokada? 
One week.

2. How long time ago has the problem started to happen? 
Since I used it.

3.  How often does this problem happen to you?
Always.

**Comment by PrintableCharacter** [comment]
Hey there,
Generally speaking blokada stops because your device is killing it. Check your phones settings for battery "optimization" and exept blokada from it. You can also "lock" 🔒 the app in the recents screen. On Xiaomi devices you can also boot blokada once using the quicksettings tile and it won't stop anymore

**Comment by kar** [comment]
Make sure you install correct build, either fdroid version or from blokada.org, if you are updating. I think thats why you are getting the error. Or clean install.

Keep alive is putting a foreground service (and that mandatory notification) to raise its priority and hint the OS to not kill it. That's all it is and it's up to system decision whether to kill the app or not. We cannot do anything more about it. Correct me if I'm wrong.

**Comment by mleenings** [comment]
Hello,

I installed it firstly from google playstore it has the same problem, after
that I tried the version from blokada.org (clean installed), but booth does
not working correctly (booth from last week).
I did the "lock" in the recents screen and did the Xiaomi battery saver
off. Booth does not helping.
For example WhatsApp works in the "background", Blokada not, so I think
there is something to do at blokada. Correct me if I am wrong.

Best regards
Marcel Leenings


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 9. Sept. 2019 um 21:55 Uhr schrieb Karol Gusak <
notifications@github.com>:
