### ISSUE TITLE
Can't download email attachments in Gmail app

### ISSUE THREAD

**Issue by Gemmu** [blokadaorg/blokada#50]
With Google's Gmail app attavhments can't be downloaded if Blokada is in use. There are no notifications of any blocked items but the Gmail app has a progressbar for download which stays in 0 percent. When Blokada is paused the attachments are available as expected. 

This from lineageos 14.1
Android version 7.1.2
Gmail app ver 7.8.27.168289052

**Comment by Gemmu** [comment]
Whitelisting the Gmail app resolved the issue.

**Comment by alleluia20** [comment]
The problem is that the whilelist is not saved (see #64), so you have to whitelist Gmail every time you turn on the device.  
Strictly speaking, it may be correct to keep this bug closed, but #64 should be fixed ASAP (I think that must be easy...).
