### ISSUE TITLE
Some blacklisted hosts may still slip in

### ISSUE THREAD

**Issue by Coasie** [blokadaorg/blokada#501]
1. Blokada version 4.1.6

2. Device model Oneplus 6 and Oneplus 7 Pro

3. Android version / ROM 9

### Questions
1. How long have you been using Blokada?  About a year

2. How long time ago has the problem started to happen? Probably with the last update, it did work on a previous v4 build.

3.  How often does this problem happen to you? continuously

You can see an image of the blokada blocked hosts page here:
https://res.cloudinary.com/jlr/image/upload/v1567302681/Phone/Blokada_Screenshot.jpg

And an image of open.oneplus.net sliping through and being blocked by the pihole here:
https://res.cloudinary.com/jlr/image/upload/v1567302681/Phone/PIHole_Oneplus_screenshot.png

**Comment by issueseverywhere** [comment]
I have the same problem.


Blokada version 4.1.6

Device model Crosscall Action X3

Android version 7.1.2

I blocked those domains:
- some google.com subdomains (mtalk and its "alt", www, play, android.clients)
- some googleapis.com subdomains (play, www, fonts, safebrowsing, android, clientservices...)

They keep being authorised by blokada.

**Comment by issueseverywhere** [comment]
I checked my log and it seems it was because of memory limit that the filters couldn't be applied when needed.

I uninstalled and reinstalled Blokada, stayed with default blacklist Energized Blu, blocked those same domains manually as they appeared in my log, and it works!

**Comment by Coasie** [comment]
problem continues on 4.2

**Comment by kar** [comment]
Please send any logs to hello@blokada.org.

If you have low memory try using smaller lists. I'll add a notification if the limit is reached.

**Comment by Coasie** [comment]
It is not a memory issue, at least not for me.

**Comment by kar** [comment]
Log received, thank you, working on it.

**Comment by kar** [comment]
A clear message about reaching the limit added. We'll continue working on the list management in other tickets.

**Comment by Coasie** [comment]
This issue has not been fixed in the latest 4.3.5, it still fails to block blacklisted hosts.
