### ISSUE TITLE
Blokada blocks all traffic with private DNS on Android 10

### ISSUE THREAD

**Issue by pitaj** [blokadaorg/blokada#503]
### Steps to reproduce
1. Enable Blokada ad blocking
2. Go into Network settings and enable private DNS to `1dot1dot1dot1.cloudflare-dns.com`
3. Try to access a site

### Expected behaviour

Access works, or Blokada warns about private DNS breaking the functionality.

### Actual behaviour

Accessing any site fails. The host log in Blokada says "Allowed `1dot1dot1dot1.cloudflare-dns.com`"

### Configuration
1. Blokada version

4.1.6

2. Device model

Google Pixel 2 XL

3. Android version / ROM

Android 10

### Questions
1. How long have you been using Blokada? 

Several months

2. How long time ago has the problem started to happen? 

Today

3.  How often does this problem happen to you?

Always until disabling Blokada or disabling Android Private DNS

**Comment by nitper** [comment]
I'm experiencing the same issue - the same setup was working perfectly on Android 9.

**Comment by PrintableCharacter** [comment]
Hello there,
Android 10 is not officially supported by blokada yet. Make sure to switch any DNS Setting of your device to "Off". You can always choose a custom DNS from within blokada.

**Comment by Gamegenorator** [comment]
@PrintableCharacter Do we know if they're working on Android 10 support?

**Comment by rpeter85** [comment]
@Gamegenorator Android Q is supported, the only thing we can't get around is the private DNS thing. We tried to find ways (this is why we said it's in development and not yet supported) but it seems to be restricted to change for apps (thus, we can say Q is fully supported, with a small requirement).

**Comment by Gamegenorator** [comment]
@rpeter85 Ok, Thanks, I'd love to see if you guys can find a way around it in the future though.

**Comment by rpeter85** [comment]
Me too, but as I said, apps are restricted to change system settings (without root only a few can be toggled, as I know), thus, it will remain an uncracked nut.

**Comment by Gamegenorator** [comment]
@rpeter85 All we can to is wait and see how things play out :pensive:

**Comment by kar** [comment]
I checked this, adblocking will not work under private DNS. You have to disable it in order to use adblocking. This is by definition, it makes DNS encrypted and we do not decrypt your traffic.

We are investigating if it'd make sense for Blokada to become a private DNS (DoH) provider and provide adblocking this way.
