### ISSUE TITLE
Not blocking ads after Android 10 Upgrade

### ISSUE THREAD

**Issue by English106** [blokadaorg/blokada#505]
### Steps to reproduce
1. Upgrade to android 10 or factory reset and then upgrade
2. Install Blockada and turn on adblocking, change nothing.
3. Visit known site with ads that would normally be blocked with the default setup

Also troubleshot a bit:
Cleared Cache
Deleted Blockada and did a fresh install of the app
Tried using different host files'
Tried turning off and on all lists
Experimented with downloading/syncing lists

### Expected behaviour
I expect to see the Blocked counter go up and ads blocked.

### Actual behaviour
Nothing gets blocked, I see all the ads both in browser and in several apps of various developers

### Configuration
1. Blokada version
latest

2. Device model
pixel 2 xl

3. Android version / ROM
Android Q/10

**Comment by PrintableCharacter** [comment]
Hello there,
Be sure to set your phones internal DNS to "Off". Private DNS will not work anymore.
You can always use blokada to set a custom DNS

**Comment by kar** [comment]
@English106 please get back to us once you try setting "private dns" to off (it's in system preferences).

**Comment by English106** [comment]
That did the trick. Thanks.
