### ISSUE TITLE
The time counter for list status resets on leaving the menu in v4.2

### ISSUE THREAD

**Issue by Notabas-iC** [blokadaorg/blokada#507]
### Steps to reproduce
1. Install Blokada v4.2.
2. Open Blokada. Go to ad blocking / List settings / List status
3. Check the time counter. It shows '0 min. ago'
4. Leave the menu or close the app.
5. Check List status again. It again shows '0 min. ago'

### Expected behaviour
Time counter only resets, when the ruleset actually gets build. 
### Actual behaviour
Counter resets everytime the menu gets opened, not depending on the download.

### Configuration
1. Blokada version
V4.2

**Comment by PrintableCharacter** [comment]
Yes. That's known. Very creative username by the way xD
