### ISSUE TITLE
Feature Request: Per App - Block all connection

### ISSUE THREAD

**Issue by English106** [blokadaorg/blokada#509]
Simply put, select and app and block it from making any connections, forcing it to behave as if offline.

I've been using NetGuard and I really wish Blockada, which has add filtering and a VPN could stop apps from connecting outright. I use about 2 percent battery on Blockada.

NetGuard has an outright block all connection and a block when screen off and it's made my battery consumption plummet to less than a half a percent an hour.

With NetGuard off, using or not using Blockada, passive consumption sits at 2.2 percent

**Comment by PrintableCharacter** [comment]
Hello there,
Issue #49 is exactly the request you're having. Consider supporting it and closing this issue :)
Thank you very much
https://github.com/blokadaorg/blokada/issues/49

**Comment by English106** [comment]
Thanks! I will do so.
