### ISSUE TITLE
Online Only Switch Error

### ISSUE THREAD

**Issue by hdudhhhdh** [blokadaorg/blokada#51]
The first time I run the app,I activated the service,But it automatically shutdown after a short time.it said:something went wrong,please check internet connection and try again.
PS.
I'm in China, maybe the site used for check connection is blocked by fw in China.

plz forgive my poor English.^_^

**Comment by kar** [comment]
"Online only" mode won't work on every device and it's designed to turn itself off on several failed activation attempts. Does the app work once the switch is off?

**Comment by hdudhhhdh** [comment]
it has no problem when I turn this switch off,thanks :D
