### ISSUE TITLE
Blokada blocked domains still show as "authorized" in journal

### ISSUE THREAD

**Issue by FinduschkaLi** [blokadaorg/blokada#513]
### Steps to reproduce
1. choose a domain that regularly is connected to in journal (I want to block: dailercallinfolookup-pa.googleapis.com) and add to blacklisted domains
2. Verify that is in blacklisted domain (OK)
3. Reproduce a connection (redial a number on your phone) -> In the journal, the domain is shown as "authorized" altough in the blacklist

### Expected behaviour

Blacklisted domains should be blocked in the journal.

### Actual behaviour

Blacklisted domains do show as authorized connections

### Configuration
1. Blokada version
4.1.6

2. Device model
Motorola g7 power

3. Android version / ROM
Android PPOS29.114-134-2 (Version 9 + security patch 1/8/19

### Questions
1. How long have you been using Blokada? 
1 month

2. How long time ago has the problem started to happen? 
right away

3.  How often does this problem happen to you?
always

**Comment by FinduschkaLi** [comment]
Remark: No app is allowed to overgo Blokada in settings.

**Comment by PrintableCharacter** [comment]
Hello there,
Be aware that you'd have to block both addresses e.g. Google.com and www.google.com
Please also make sure to clear the cache of your browser after updating this domain. 
Please try it and let us know if that fixed your issues.

**Comment by FinduschkaLi** [comment]
Hi thank you for your reply.
Just tested, but no change in behaviour.
Both www. and non www. address is in black-list but keeps beeing 
authorized.

**Comment by PrintableCharacter** [comment]
Could you try this again on v4.2?

**Comment by FinduschkaLi** [comment]
Sure. Will install and get back to you.

**Comment by FinduschkaLi** [comment]
No change in behaviour. This is tested with 4.2:
![journal1](https://user-images.githubusercontent.com/18465405/65051521-8b195f00-d969-11e9-8aa5-2c8e5764a961.png)
![journal2](https://user-images.githubusercontent.com/18465405/65051527-8ce32280-d969-11e9-9a35-b38e1dbd0b06.png)

**Comment by PrintableCharacter** [comment]
Try adding all cnames of 'dialercallinfolookup-pa.googleapis.com to the blacklist as well (with and without 'www.').
I quickly searched and found 'googleapis.l.google.com'.

**Comment by FinduschkaLi** [comment]
Sorry the late reply. I also tried the cnames added. I actually think that some of the requests are blocked now, meaning "sometimes" in function of which app issues the requests maybe? It's definitely not blocked always.

**Comment by kar** [comment]
I checked the code again and couldn't find any reason for mishebavior here, as long as you don't select too many lists (you'd see a message then that not all lists were loaded). There is cache involved so if you're playing with settings and trying to see effects immediatelly, this might be a problem. Please try again with 4.4 which is coming very soon. If you experience those problems again, open another ticket with maybe even more precise step-by-step instructions to reproduce your issue.
