### ISSUE TITLE
Social hosts file URL wrong

### ISSUE THREAD

**Issue by Gugiman** [blokadaorg/blokada#514]
Predefined social hosts file does not increase filter rule counter. Therefore social media isn't blocked.
Reason seems to be that the URL fron "social hosts file" is wrong:

Right URL:
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts

### Steps to reproduce
1. Watch filter rule counter
2. Enable "social hosts file"
3. Reload filters
4. Watch filter rule counter again and see that there is no increase.
5. Add a new host file with this Url and enable:
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts
6. Watch filter rule counter increase

### Expected behaviour
Counter should increase.
And of course blocking social media.

### Actual behaviour
Nothing.

### Configuration
1. Blokada version
4.2.1

2. Device model
OnePlus 5T

3. Android version / ROM
Android 9 / Lineage OS

### Questions
1. How long have you been using Blokada? 
I'm new. maybe a week.

2. How long time ago has the problem started to happen? 
Since the beginning

3.  How often does this problem happen to you?
Continuously

**Comment by PrintableCharacter** [comment]
I can confirm that the list address is incorrect.
Thank you for notifying

**Comment by rpeter85** [comment]
I fixed it and created a request to merge the change: [41](https://github.com/blokadaorg/blokadaorg.github.io/pull/41)

**Comment by PrintableCharacter** [comment]
@Gugiman
See? That's quick right? 😉

**Comment by Gugiman** [comment]
@PrintableCharacter
Absolute Amazing :blush:

First I Was trying to make a PR myself but didn't find the right location :sweat_smile:
