### ISSUE TITLE
Watchdog bug on 4.3.0 

### ISSUE THREAD

**Issue by Tornadoduke** [blokadaorg/blokada#517]
### Steps to reproduce
1.
2.
3.

### Expected behaviour

Watchdog to function normally as it used to work on the previous versions. 

### Actual behaviour

Watchdog on settings no longer work after the latest update. After toggling the watchdog to turn on the VPN when data network is activated & turn off when data network gets deactivated, it doesn't work.
It keeps the VPN active whether the data network is of or on, as if the features was not enabled.

### Configuration
1. Blokada version
4.3.0

2. Device model
Xiaomi Mi Mix 2S 

3. Android version / ROM
Android 9 pie

### Questions
1. How long have you been using Blokada? 
4 years

2. How long time ago has the problem started to happen? 
The issue with watchdog started since 4.3.0 update

3.  How often does this problem happen to you?
Regularly on version 4.3.0

**Comment by rpeter85** [comment]
Hi,
By any chance, didn't you enable Always-on VPN in system settings?

**Comment by Tornadoduke** [comment]
> Hi,
> By any chance, didn't you enable Always-on VPN in system settings?

No... Though we've discussed this on Telegram :)
