### ISSUE TITLE
Block stats missing, useless keep-alive notification after refactor in v4.3.2

### ISSUE THREAD

**Issue by immanuelfodor** [blokadaorg/blokada#518]
### Steps to reproduce
1. Upgrade from v4.3.0 to v4.3.2
2. Observe the new keep-alive notification content

### Expected behaviour
The global block counter and the latest blocked domain is shown in the keep-alive notification. 

### Actual behaviour
A "useless" static text is displayed: 

>**Keep Alive (tap to hide)**
>Android requires to display a notification to keep the app running, but ..

And the text is even truncated at the end. 
Please give us back the useful previous stats that was removed in this commit: https://github.com/blokadaorg/blokada/commit/7af533a4ca362d7cd0555147990042fda4ec06f7

### Configuration
1. Blokada version
4.3.2

2. Device model
Oneplus 7

3. Android version / ROM
9 / latest official Oxygen OS

### Questions
1. How long have you been using Blokada? 
2 years and I'm a great fan of the app!

2. How long time ago has the problem started to happen? 
This evening after upgrade from 4.3.0 to 4.3.2

3.  How often does this problem happen to you?
All the time.

**Comment by rpeter85** [comment]
Hi
it is so by design. You have much more option under the notification settings and the 2 things are separated.

**Comment by immanuelfodor** [comment]
Hmm, but at least if we have the constantly shown notification for keep-alive, why not use it for something useful, why need to show a second notification for the same thing? Can't we have a simple fallback for basic stats in the keep-alive? I was totally satisfied with it until today.

**Comment by agamotto** [comment]
Sorry but this "re-design" is a step backwards for me: where is the option to disable/enable Blokada from the notification area now? It was so much more convenient than actually opening the app.

**Comment by joboj** [comment]
Sorry rpeter85 I agree with the other posters here. It was much more functional with some simple notifications in the keep alive notification and also the ability to click it to open the app.

**Comment by waclaw66** [comment]
I'm also missing the Disable button on the "Ad blocking" notification, it was very useful. Please revert this functionality, 4.3.0 was perfect.

**Comment by immanuelfodor** [comment]
The Keep Alive notification works as before in the newest v4.3.5, thank you so much!
