### ISSUE TITLE
I want to be able to view full list of recent blocked domains

### ISSUE THREAD

**Issue by AnonymousWP** [blokadaorg/blokada#519]
### Steps to reproduce

1. Update to 4.3.2
2. Swipe down the notification bar and see that there's only 1 domain being showed as blocked
3.

### Expected behaviour

Before, it was common behaviour to see 5-6 domains that got blocked recently. I liked it way more to have that much of control and it doesn't hurt anyways, because you can 'minimise' it.

### Actual behaviour

It only shows 1 domain being blocked instead of 5-6 recents.

### Configuration

1. Blokada version

4.3.2

2. Device model

OnePlus 7 Pro

3. Android version / ROM

9

### Questions

1. How long have you been using Blokada? 

Over a year

2. How long time ago has the problem started to happen? 

4.3.2

3.  How often does this problem happen to you?

Always, of course.

**Comment by immanuelfodor** [comment]
Yeah, this is also related to the notifications refactor observed in #518 :(

**Comment by immanuelfodor** [comment]
This is done, the Keep Alive notification works as before in the newest v4.3.5 release.
