### ISSUE TITLE
Could not load all filters to memory Error

### ISSUE THREAD

**Issue by TheMrBooyah** [blokadaorg/blokada#522]
### Steps to reproduce
1. Enable/Disable the app and it shows "Could not load all filters to memory. Check your adblocking settings"
2.
3.

### Expected behaviour
I'm not expecting this Warning/Error. It started after I updated to 4.3.2.

### Actual behaviour
Warning/Error showing "Could not load all filters to memory. Check your adblocking settings"

### Configuration
1. Blokada version
4.3.2

2. Device model
Moto X4

3. Android version / ROM
9 with security patch 1-09-2019

### Questions
1. How long have you been using Blokada? 
Since beginning of 2019

2. How long time ago has the problem started to happen? 
After I upgraded to 4.3.2

3.  How often does this problem happen to you?
Everytime I either enable or disable the app.

**Comment by cauthulhu** [comment]
How many lists do you enable?

**Comment by TheMrBooyah** [comment]
I have in total 618067 rules enabled.
My phone has 4 GB of RAM of which 1.1 GB is still available.

It also shows this error when I pause the application. Which in my opinion should not happen since I'm disabling the functionality of the application.

**Comment by cauthulhu** [comment]
Lists, not rules :) The reason why I asked is some lists are overlapping (e.g. everything in Energized Blu is included in Energized Basic). Overlapping lists makes Blokada works harder to sort and eliminate same hosts, which in turn consume resources (battery and memory)

**Comment by TheMrBooyah** [comment]
My Bad.

Lists I'm using:
Energized Basic
Energized Blu
Goodby Ads by Jerryn70
HpHosts
Social hosts file
Coin Blocker List

**Comment by cauthulhu** [comment]
Worth checking out https://t.me/blokadachat/104350

**Comment by TheMrBooyah** [comment]
I noticed that the Energized Basic creates too much rules. My device is not able to handle it apparently.
Maybe a better warning/error could be shown to indicate that you have too many rules?

**Comment by rpeter85** [comment]
Like a warning, that "Could not load all filters to memory"? :)
A warning is requested, hit a +1 for that if you think that's useful: https://github.com/blokadaorg/blokada/issues/320

**Comment by TheMrBooyah** [comment]
Well indeed the warning itself does give a clue on what is happening. However it does not really give you any direction in which list might be the cause. 
#320 is indeed a good option I'll give a +1 ;)

**Comment by TheMrBooyah** [comment]
One question remains, will it then only load the entries it can load or does it not load anything at all?

**Comment by kar** [comment]
It loads the ones it can from top to bottom and ignores the rest. It was exactly the same before 4.3, but you simply would not see the message.
