### ISSUE TITLE
I want a block counter in standard notification

### ISSUE THREAD

**Issue by speedlever** [blokadaorg/blokada#524]
Would it be possible to include a block counter in the standard notification bar drop down? I know keep alive shows the block counter, but keep alive causes Blokada to randomly stop on my phone so I don't use it. Phone is stock OnePlus 3 on Pie. Blokada v 4.3.5

### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by alexa-v2** [comment]
As this is implemented I recommend closing
