### ISSUE TITLE
I want an easier update process

### ISSUE THREAD

**Issue by anstosa** [blokadaorg/blokada#525]
When an update is available, the app helpfully notifies you and says "tap to proceed", but tapping just opens the app and then you have to dig through multiple levels of settings menus to find the update button manually. Tapping the notification should start the download immediately.

**Comment by kar** [comment]
From 4.2 onward I believe, it leads you to the home screen where you have the "update" item you can tap to start the actual update. But I agree we should do it better.

**Comment by anstosa** [comment]
Hmm I'm on 4.3.5 now so I assume I should have seen that. I don't recall seeing it this morning but I could have missed it

**Comment by kar** [comment]
I think if you never tapped the "whats new" away, you would not see the update item.

**Comment by anstosa** [comment]
I don't see a what's new section so I assume I dismissed it at some point
