### ISSUE TITLE
I can't change blokada settings.

### ISSUE THREAD

**Issue by nameman** [blokadaorg/blokada#532]
HI
I can't change blokada settings.
I downloaded the latest version of blokada from the blokada.org site, when my smatphome blokada is turned on it activates, but if I try to access the settings, the browser selection appears (firefox or crome) and it does not allow me to change the settings of blokada. My smartphome is a huawei p9 lite model vns-l31c02b346 with emui 5.0.4 and android version 7.0

Thanks for your help

**Comment by rpeter85** [comment]
Hello,

Could you join our Telegram channel (https://go.blokada.org/chat) and ping me (rpeter) there? I need a video about it, nobody ever reported such a misbehaviour and I would like to check what's going on.

**Comment by nameman** [comment]
I installed a previous version (3.7) and activated ... I found myself with two apps blokada the active 3.7 and the 4.3.5 paused.
I have uninstalled 3.7 and reactivated 4.3.5 and now I can change the settings of the latest version of blokada .......
