### ISSUE TITLE
Blokada is unable to update to 4.3.5

### ISSUE THREAD

**Issue by karaluh** [blokadaorg/blokada#538]
### Steps to reproduce
1. Open the app.
2. Tap "Update is available".
3. "Updating, please wait" message is displayed.

### Expected behaviour
Blokada installs the update.

### Actual behaviour
Nothing happens. Tapping the update available once more tries to open Blokada github in chrome but the tab is immediately closed.

### Configuration
1. Blokada version
4.2.0

2. Device model
Google Pixel 1

3. Android version / ROM
10

### Questions
1. How long have you been using Blokada? 
Over a year.

2. How long time ago has the problem started to happen? 
Just now.

**Comment by rpeter85** [comment]
hey,
do you have "Download on WiFi only" enabled in 'Ad blocking' - 'Adblocking settings'?

**Comment by kar** [comment]
Yes 4.2.0 had a bug, you need to go to blokada.org/#download and download it manually.

**Comment by karaluh** [comment]
Any news on the issue?
