### ISSUE TITLE
Blokada sometimes doesn't recognize connectivity and shows 'Waiting for network'

### ISSUE THREAD

**Issue by alexanderadam** [blokadaorg/blokada#547]
### Steps to reproduce
1. Occasionally go on and offline

### Expected behaviour

Blokada would work

### Actual behaviour

It shows that it is connected to the Blokada 'VPN' but it shows `Waiting for network...` instead.
As you can see I have 4G internet connectivity in the screenshot but Blokada keeps showing the `Waiting` message:

![Screenshot_20191012-081025_Blokada](https://user-images.githubusercontent.com/372620/67158096-00df6480-f334-11e9-9d09-24280c7880f1.jpg)

### Configuration
1. Blokada version `4.3.3 (android-28 community release arm64-v8a samsung-startlte touch api)`
2. Device model `Samsung S9`
3. Android version / ROM
  One UI version 1.0
  Android version 9
  Kernel version G960fXXU6CSI1

### Questions
1. How long have you been using Blokada? 
since ages

2. How long time ago has the problem started to happen? 
Just recently. I think it must be one update in the last two months or so.

3.  How often does this problem happen to you?
daily

**Comment by leonmelein** [comment]
Since I upgraded my Nokia 8.1 (Android One) to Android 10, I'm experiencing the same issues on both 4G and WiFi. It renders Blokada fully unusable for me, including NXDOMAIN error messages in Chrome - even though I don't use the custom DNS option. Disabling Blokada is the only thing that solves it.

**Comment by PrintableCharacter** [comment]
Hello there,
Would you be so kind to try the Blokada version found on GitHub or the official website. It should work with those. Fdroid takes its time to update the Application.

**Comment by ulu** [comment]
Another "me too". Staying at the same Android Activity results in more or less periodical "waiting for network" message. The difference to the Issue reporter is that I am using a DNS (settings from blokada). The DNS is sometimes off now. I have to start Blokada to become the DNS automatically activated. I did not change blokada nor the Android version but installed some Google (Play) Service Updates.

I am using
blokada/4.3.3 (android/26 community release arm64-v8a OnePlus-OnePlus3T touch api)
from F-Droid.

App Settings:
. Keep alive: Yes
. Watchdog: Yes
. Aggressive wakeup: Yes

System settings used by me:
. Blokada > App Info > Permissions: all granted
. Blokada > App Info > Notifications: all allowed
. Battery optimization: don't optimize
. unrestricted data access: On

**Comment by PrintableCharacter** [comment]
@ulu please try the Blokada version available here on GitHub or the website. Fdroid could take some time to update the repository with the new blokada version

**Comment by ulu** [comment]
@PrintableCharacter under circumstances this could solve the problem, but this leads to the next 2 problems:
. reproducible, signed builds
. automatic updates using (F-Droid) repository

All these problems could be avoided if Blokada were properly tested.

**Comment by PrintableCharacter** [comment]
You can rest assured that blokada is getting tested ^^ but some issues only appear on specific phones.
As blokada is an open source project it neither has the time  nor the financial resources to be tested on every single device out there.
It relies entirely on feedback which can be given here, on Telegram and a lot of other platforms.

**Comment by kar** [comment]
4.3.5 should be on fdroid any moment. let me know if you still experience problems.

**Comment by alexanderadam** [comment]
> 4.3.5 should be on fdroid any moment. let me know if you still experience problems.

So it seems to work again but my mobile is vibrating now very often.

I'm not sure though whether it is related to blokada or due to an update from another app.
Is it plausible that it is blokada or rather not?

**Comment by kar** [comment]
Hm, Blokada doesn't have vibrating notifications, so I don't think so.

**Comment by ulu** [comment]
For the record: works again with F-Droid version 4.3.11.

**Comment by alexanderadam** [comment]
@kar okay so I can still confirm [the behaviour since the bugfix](https://github.com/blokadaorg/blokada/issues/547#issuecomment-546515856): the phone vibrates the moment I activate blokada.

Is there a possibility to [disable vibration notifications](https://github.com/blokadaorg/blokada/blob/279b0a20bc4b9c26f2492962fc4b39732a765691/app/src/ui-blokada/kotlin/notification/ANotificationUtils.kt#L220-L267) in the UI?

Should I open another issue for it?

**Comment by ulu** [comment]
I cannot confirm this odd behavior. I have no vibration at all but all Notification set to ON (unlock screen > swipe down > go to Blokada Notification and swipe it to left or right > select gearwheel > ALL CATEGORIES).
