### ISSUE TITLE
I want Blokada to have a learning mode

### ISSUE THREAD

**Issue by ps100000** [blokadaorg/blokada#548]
I want Blokada to have a "smart mode". If this mode is active Blokada logs all allowed requests. After one day it loads all selected blacklists and checks which domains should have been blocked. Those domains get added to the rules that are used by Blokada to block ads/trackers.
This way Blokada only loads rules that are needed.

get log for one day -> scan all lists for new domains that should have been blocked that day but where not -> add them to "real" list -> use for the next day -> repeat

**Comment by PrintableCharacter** [comment]
O_O
That sounds promising.

**Comment by alexa-v2** [comment]
As this is implemented I recommend closing
