### ISSUE TITLE
Blokada stops when switching networks

### ISSUE THREAD

**Issue by ErikAbele** [blokadaorg/blokada#553]
### Steps to reproduce
1. Switch WiFi on/off or otherwise change network

### Expected behaviour
Blokada keeps running.

### Actual behaviour
Blokada stops and I get the following notification from the system: "Disconnected from always-on VPN". As soon as I open Blokada, it re-connects and works fine.

This was working fine until the last two recent updates, so it was working for me pre 4.3.4. I updated this week to 4.3.4 and it started above behaviour, even with the latest update to 4.3.5 it is still the same :-(

Also tested with Watchdog & AgressiveWakeup turned on though I didn't need this before and it doesn't make a difference. It still simply dis-connects on network changes.

Oh, and battery optimizations and other things are all set up correctly.

### Configuration
1. Blokada version
Latest, 4.3.5 although it reports 4.3.11 by itself

2. Device model
Umidigi S3 Pro

3. Android version / ROM
9.0

### Questions
1. How long have you been using Blokada? 
Since ages.

2. How long time ago has the problem started to happen? 
With the 4.3.4 update.

3.  How often does this problem happen to you?
Every time I change the network

**Comment by kar** [comment]
So I understand you have 'always on vpn' enabled? also blocking connections outside of vpn?

**Comment by kar** [comment]
After you leave blokada and it stops, come back to the app and send the log from about menu, to hello@blokada.org

**Comment by ErikAbele** [comment]
> So I understand you have 'always on vpn' enabled? also blocking connections outside of vpn?

Yes, it's an "Always-On VPN" and no, it is NOT set up to block connections outside of VPN.

> After you leave blokada and it stops, come back to the app and send the log from about menu, to [hello@blokada.org](mailto:hello@blokada.org)

Ok, just sent the log, the actions taken are as follows:

- opened Blokada app
- went back to home screen (app still running)
- disabled WiFi
- got message that it disconnected, then after 2-3 seconds it re-connected automatically
- closed Blokada app
- connected to WiFi
- got message that it disconnected, does not re-connect automatically for several mins
- opened Blokada app and it connected instantly
- sent log via about menu

Hope this helps and thanks for looking into it - let me know if I can do anything else.

**Comment by ErikAbele** [comment]
By the way, I discovered this while leaving the house so it's not only happening when actively switching WiFi on/off. It is also happening when being out of reach of WiFi or when loosing cellular connections...

**Comment by kar** [comment]
Some changes were made to address this. Please retry once 4.4 is out (beta testing is ongoing).

**Comment by ErikAbele** [comment]
Thank you, will do and report back.

**Comment by ErikAbele** [comment]
Ok, after testing for two days now it seems to be resolved: although I can still see some disconnects happening when switching networks, Blokada instantly re-connects and keeps working fine without any manual intervention.

Great, thank you, Karol – Blokada rules ;-)
