### ISSUE TITLE
Preview, viewing and downloading the pdf doesn't work

### ISSUE THREAD

**Issue by marcelopm** [blokadaorg/blokada#554]
### Steps to reproduce
1. Install gmail app
2. Send a message to yourself with a pdf attachment
3. Open the message

### Expected behaviour
Preview, viewing and downloading the pdf to work

### Actual behaviour
1. Preview, viewing and downloading the pdf doesn't work
2. An error message about downloading the pdf is raised
3. There are no blocked domains listed in the logs

### Workaround
1. In blokada, click touch to pause
2. Make sure the vpn icon on the bar has gone
3. Make sure to close and restart gmail app
4. Go to the message with pdf, preview, viewing and downloading works

### Configuration
1. Blokada version
4.3.3

2. Device model
Moto G4

3. Android version / ROM
LineageOS 15.1

### Questions
1. How long have you been using Blokada? 
1 year

2. How long time ago has the problem started to happen? 
Since ever

3.  How often does this problem happen to you?
Everytime

**Comment by kar** [comment]
It works for me with 4.3.5. Anyone can reproduce it?
