### ISSUE TITLE
all hosts lists other than "Energized Blu (recommended)" seem to be ignored

### ISSUE THREAD

**Issue by hotaru2k3** [blokadaorg/blokada#557]
### Steps to reproduce
1. enable any host list other than "Energized Blu (recommended)"
2. disable "Energized Blu (recommended)"

### Expected behaviour
hosts in the selected list are blocked

### Actual behaviour
no hosts are blocked. Blokada says "You have no filters configured. Check your adblocking settings." adblocking settings shows 0 rules.

### Configuration
1. Blokada version
4.3.5

2. Device model
Pixel XL

3. Android version / ROM
10

**Comment by peterroth** [comment]
Are you sure the list is downloaded? Did you enable "download on WiFi only"? In this case, the newly enabled list/s won't be loaded, only if you are connected to a wifi network. Without that, Blokada won't block anything.

**Comment by alexa-v2** [comment]
@peterroth I believe that's default behavior, download on wifi only (IMO bad practice but I'm mostly on mobile data)

**Comment by peterroth** [comment]
Correct. This is why I ask, if it was disabled or enabled.

**Comment by hotaru2k3** [comment]
@petterroth I'm on WiFi, but disabling "download on WiFi only" does seem to fix it. looks like the app is failing to detect that I am on WiFi?

**Comment by peterroth** [comment]
Thank you, let me reproduce it.
