### ISSUE TITLE
I want Tasker support/intents

### ISSUE THREAD

**Issue by winnieXY** [blokadaorg/blokada#56]
It would be very good if it would be possible to start/stop blokada via Tasker. The easiest solution would be to add intents to start/stop the service.

**Comment by Crsmsg** [comment]
Is there any updates on this

**Comment by kar** [comment]
Nope and it's not prioritised. If anyone is willing to jump in and make a
PR I can help.

**Comment by Wibblyw** [comment]
It may be possible to drive this via controlling the UI (at least with the Automagic app, not sure about Tasker) in a messy/horrible kind of way, by pressing the on/off button at the bottom of the main Blokada screen programmatically. This would be complicated by the fact that Blokada occasionally pops up an information screen which would get in the way. Exposing an intent that does the same thing would be much more reliable :-)

**Comment by kar** [comment]
Are people still using Tasker today?

**Comment by rpeter85** [comment]
Yes. At least, I do :D

**Comment by arjan-s** [comment]
Yes! Can't live without it!

**Comment by nobodyspecial** [comment]
Me too!

**Comment by tjeffree** [comment]
I really wanted this behaviour but could not find a good way to implement it as it is. What I have done, hopefully temporarily, is to use [my.nextdns.io](https://my.nextdns.io) along with [DNS Changer](https://play.google.com/store/apps/details?id=com.burakgon.dnschanger) which has Tasker intents.

Tasker detects whether I'm at home, and if not changes my DNS to nextnds servers and back again when I return. I would much rather have the filtering done through Blokada on my device, but this helps for now.

**Comment by Crsmsg** [comment]
Me as well. Tasker 👌

**Comment by kar** [comment]
4.3 has basic Tasker support. For more advanced intents lets open new tasks.

**Comment by szaimen** [comment]
@kar is Tasker support already implemented in Blokada v5?

**Comment by peterroth** [comment]
@szaimen not yet.
