### ISSUE TITLE
Blokada is unable to update to 4.4.2

### ISSUE THREAD

**Issue by karaluh** [blokadaorg/blokada#568]
Same story as issue #538 

Steps to reproduce
Open the app.
Tap "Update is available".
"Updating, please wait" message is displayed.
Expected behaviour
Blokada installs the update.

Actual behaviour
Nothing happens. Tapping the update available once more tries to open Blokada github in chrome but the tab is immediately closed.

Configuration
Blokada version
4.3.5

Device model
Google Pixel 1

Android version / ROM
10

Questions
How long have you been using Blokada?
Over a year.

How long time ago has the problem started to happen?
Just now.

**Comment by peterroth** [comment]
Issue tracked in #538
