### ISSUE TITLE
Host lists downloaded via HTTP ignored

### ISSUE THREAD

**Issue by smandon** [blokadaorg/blokada#570]
### Steps to reproduce
1. Add a new host list with an http URL or enable one from the predefined hosts list (eg. MVPS)

### Expected behaviour
New rules should be added and applied

### Actual behaviour
The rules counter doesn't take the new rules into account. If this is the only list enabled blokada complains that there are no rules, and it doesn't block any connection.
If the host list is downloaded over HTTPS instead (same file on same server), it works as expected.

### Configuration
1. Blokada version: 4.4.2
2. Device model: Xiaomi Mi A1
3. Android version / ROM: Android 9.0

### Questions
2. How long time ago has the problem started to happen? 
I don't know. I just realised because after updating blokada from 4.3.5 to 4.4.2 all the host lists disappeared from the app (custom set ones as well as predefined ones) and I had to reset the app and start over, which made me realize that connections to domains in my list were not blocked.

**Comment by peterroth** [comment]
Hey,
Is it possible you tried to download them while you were on mobile, but the downloads are restricted for wifi connections in the settings?

**Comment by smandon** [comment]
No, I downloaded it over wi-fi and tested with the wi-fi restriction turned off just in case. I tested on another device (a tablet which only has wi-fi) and the result is exactly the same. Simply changing the URL to https works without chaning anything else.

**Comment by smandon** [comment]
Additionally, before you ask:
- the http URL is good, I didn't mistype it
- there is no other filtering done on that connection that could block it
- the URL can be accessed without issue from the same devices in a browser
- I also tested it on two different internet connections

**Comment by peterroth** [comment]
It worth to know Blokada merges the downloaded lists, thus, if MVPS contains all the entries from other hosts, the host number's counter won't increase.
Can you let me know which list did you try to download through HTTP, so I can try to reproduce the issue you described?

**Comment by smandon** [comment]
But it doesn't increase even when it is the only list, where there is no merging.

I checked logcat and found this, the message is the same whatever http URL:

> 11-20 09:48:41.241  5462  5666 V b4:tunnel-main: fetching ruleset    b_mvps
11-20 09:48:41.242  5462  5666 E b4:tunnel-main: failed fetching ruleset    b_mvps, java.lang.Exception: failed to fetch ruleset (size 0)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: java.lang.Exception: failed to fetch ruleset (size 0)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager$1.invoke(FilterManager.kt:13)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager$1.invoke(FilterManager.kt:8)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager$syncRules$1.invoke(FilterManager.kt:182)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager$syncRules$1.invoke(FilterManager.kt:8)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager.syncRules(FilterManager.kt:170)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager.access$syncRules(FilterManager.kt:8)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager$sync$1.invoke(FilterManager.kt:120)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager$sync$1.invoke(FilterManager.kt:8)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager.sync(FilterManager.kt:118)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.FilterManager.sync$default(FilterManager.kt:118)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.TunnelMain$sync$1.invokeSuspend(TunnelMain.kt:162)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at tunnel.TunnelMain$sync$1.invoke(Unknown Source:10)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at kotlin.coroutines.experimental.migration.ExperimentalSuspendFunction1Migration.invoke(CoroutinesMigration.kt:134)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at kotlin.coroutines.experimental.migration.ExperimentalSuspendFunction1Migration.invoke(CoroutinesMigration.kt:130)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at kotlin.coroutines.experimental.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnchecked$$inlined$buildContinuationByInvokeCall$IntrinsicsKt__IntrinsicsJvmKt$2.resume(IntrinsicsJvm.kt:122)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at kotlin.coroutines.experimental.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnchecked$$inlined$buildContinuationByInvokeCall$IntrinsicsKt__IntrinsicsJvmKt$2.resume(IntrinsicsJvm.kt:98)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-20 09:48:41.243  5462  5666 E b4:tunnel-main: 	at java.lang.Thread.run(Thread.java:764)

The corresponding file at http://winhelp2002.mvps.org/hosts.txt can be downloaded without issue in a browser on the device, so there's definitely nothing on the network blocking the connection.

**Comment by kar** [comment]
it may be because of unencrypted connection, could you try any https link?

**Comment by smandon** [comment]
That's exactly my point, as stated in my initial message:
it works with https urls and not with http urls.

**Comment by kar** [comment]
Ok. AFAIR Android default HTTP client won't let unencrypted HTTP connections in strict mode (from some Android version I don't remember), and I think that's why it fails.
