### ISSUE TITLE
Main switch doesn't work on FireTV

### ISSUE THREAD

**Issue by peterroth** [blokadaorg/blokada#571]
On FireTV devices, the big switch in Blokada 4.4 doesn't work as it intended to, every time when the user tries to turn it on it turns itself back off again as soon as the focus is moved away from that.

**Comment by alexa-v2** [comment]
I'd like to suggest that you guys start maintaining a separate build for TV type devices: the modification you've made for TVs doesn't work well on phones, it's laggy, but some of the phone stuff doesn't work well on TV devices

**Comment by Aliciabibi** [comment]
Same issue here.
Not only the main switch though for me. Blokada doesn't work at all because all the switches (under the different sections) don't work.

**Comment by kar** [comment]
Yes we will be slowly moving away from the one UI concept I think. In the meantime I fixed the switch problem and will be releasing a hotfix version 4.4.4 today. It won't be pushed through the updater to not annoy people about often updates, but you will be able to download it from the website.
