### ISSUE TITLE
google translate

### ISSUE THREAD

**Issue by larrythecow** [blokadaorg/blokada#573]
blokada is blocking offline download of languages from google translate.

#### default installation with "adguard DNS"
install google translate with offline (e.g spain & german)
--> Download will not work
#### deactivate blokada
--> Download will work

### Expected behaviour
Download should work

### Actual behaviour
download does not work

### Configuration
1. Blokada version 4.4.2

2. Device model
xt1952-2

3. Android version / ROM
9

### Note
Sorry, i am a bit in hurry and in vacation. I hope it is reproduceable

**Comment by peterroth** [comment]
Add Translate app to allow list in Blokada.
