### ISSUE TITLE
Blokada Slim deactivation

### ISSUE THREAD

**Issue by Indranil012** [blokadaorg/blokada#576]
After updated to Blokada Slim 4.4.2 it's not  deactivating normally(force stop does the job). 
Device : samsung, lollipop, arm32
Repoduction procedure:
1. turn on custom dns
2. activate blokada
3. deactive
4. If deactivated Restart device
5. step 2> step 3``

**Comment by peterroth** [comment]
Hi there,

Can you please check if you reinstall the app reboot the device solves the problem you described?

**Comment by Indranil012** [comment]
not working

**Comment by kar** [comment]
Fixed in 4.4.3
