### ISSUE TITLE
I want to add Bancuh DNS

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [blokadaorg/blokada#581]
Hello, 

I would like to know if you could add the DNS Bancuh DNS. This DNS blocks 99.9% of ads, fraudulent site etc... and is very fast, the developer is very friendly and is listening to the users of the server. I am currently working with him in partnership with my IT company Tech Computer Service Dunkerque and I am satisfied with it. Here are these DNS: 

Primary: 139.59.219.245
Secondary: 139.59.218.207

Website: https://blog.bancuh.com/adblock-dns/

I recommend Blokada to my customers for Android, but I am still required to manually set Bancuh DNS to main DNS on the application.

It would be great, if you could add the server to your list.

Amicalement, Jordan 

https://tcsdunkerque.eu/blokada-le-bloque-pub-qui-elimine-les-pubs-sur-android/

**Comment by peterroth** [comment]
Thanks for the idea.
Even the servers are based on an open source project, which is a very positive, their availability isn't guaranteed unfortunately, outages are expected, and based on the feedbacks there are times when they unreachable for a long time.
Therefore this DNS servers won't be added to Blokada's default list.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

yet I still use it and I've never had a breakdown. It's kind of weird what people are saying.
