### ISSUE TITLE
Downgrade failure

### ISSUE THREAD

**Issue by quent** [blokadaorg/blokada#586]
### Steps to reproduce
1. Go to F-Droid, Blokada, versions
2. Select a previous version, hit downgrade
3. Download is successful, hit install

### Expected behaviour
A message indicated that the installation/downgrade was successful

### Actual behaviour
A popup reading "Error installing Blokada v4 (ad blocker)
Failed to install due to an unknown error <Ok>"

### Configuration
1. Blokada version
Installed: 4.4.3
Downgrading to: 4.4.2 & 4.3.11

2. Device model
Samsung S7

3. Android version / ROM
8.0.0 stock, up to date on security (Samsung schedule...)

### Questions
1. How long have you been using Blokada? 
~6+ months

2. How long time ago has the problem started to happen? 
Just today. Experienced issues where Blokada was not operational (opened an app at different times and ads were showing, then switched to Blokada to find that it was busy starting up after switching instead of showing "Blokada is active". Thought I'd downgrade to see first if it was an issue with the latest version of Blokada.

3.  How often does this problem happen to you?
Just today, have never tried downgrading before from this version nor from earlier versions

**Comment by alexa-v2** [comment]
Just so you know that's default package installer behaviour. It doesn't permit downgrades.
If you really want to downgrade, try `adb install -r blokada.apk`

Recommend closing as this is android level, not blokada's fault.

**Comment by PrintableCharacter** [comment]
@quent Is the issue solved by now if you follow the given advice? :)

**Comment by quent** [comment]
I haven't tried manual ADB but since F-Droid provides the option to select previous versions with a downgrade button, I'm confused about why it's an Android issue. Is it a feature the F-Droid shouldn't be implementing, specific to some versions of Android?

**Comment by alexa-v2** [comment]
@quent thing is it's not possible on purpose. To prevent an user from downgrading on accident

I don't know if it's possible if you're using the F_
-Droid priv-apps plugin but definitely not normally

**Comment by quent** [comment]
From upstream F-Droid: https://gitlab.com/fdroid/fdroidclient/issues/1213
Happy for the issue to be closed, thanks!
