### ISSUE TITLE
Request to add xiaomi system updater to default whitelisted apps

### ISSUE THREAD

**Issue by eXPerience83** [blokadaorg/blokada#587]
Request to add xiaomi system updater to default whitelisted apps
com.xiaomi.discover

![Screenshot_2019-11-25-16-44-40-670_org blokada origin alarm](https://user-images.githubusercontent.com/16572400/69559152-b2b02780-0fa9-11ea-9eab-48922e8856e2.png)

**Comment by peterroth** [comment]
This is a knife with 2 edges. On one side bypassing it will allow the user to update the system. On the other side the app may reports user data and information, what is the main goal to block by Blokada.

**Comment by peterroth** [comment]
PR [#50](https://github.com/blokadaorg/blokadaorg.github.io/pull/50) to add XSU to default whitelist is created.
