### ISSUE TITLE
Could not load all filters to memory

### ISSUE THREAD

**Issue by Felina-Lain** [blokadaorg/blokada#592]
#Steps to reproduce
1. Go to the host lists
2. turn a host list on
3. get the error message
4. blokada no longer block ads

### Expected behaviour
Choosing the lists I wanted, and have them working

### Actual behaviour
The lists I select all give me the filter error and despite being turned on, blokada doesn't block ads
the only list that doesn't give that error is the recommended blu

### Configuration
1. Blokada version
4.4.4

2. Device model
lenovo tab2

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 
Three years, give or take

2. How long time ago has the problem started to happen? 
A week ago maybe? I didn't notice it immediately

3.  How often does this problem happen to you?
It only just happened
I also isn't happening to my other device (a wiko phone with blokada 4.4.2 on it)
edit: I still had the apk from my other device, so I tried uninstalling 4.4.4, and using the old apk to install 4.4.2 on my lenovo, and see if it worked, it didn't)

**Comment by peterroth** [comment]
The amount of lists you can load depends on what is the limit of the heap (java memory) the Android system allows to use. Merging the lists is the most memory intensive process in Blokada, thus, allowing a very big list or multiple lists at the same time can cause OOM (Out Of Memory). To avoid it, there's a safety limit which prevents the user to enable list/s that cannot fit into the maximum allocatable heap (memory).
right now I'm working on the fine-tune of this value.

**Comment by peterroth** [comment]
The change was merged and released with 4.5, closing this ticket.
