### ISSUE TITLE
Blokada blocks apps when using mobile network connection (LTE, 3G, etc..)

### ISSUE THREAD

**Issue by doctorapple** [blokadaorg/blokada#597]
**Steps to reproduce**

Turn on Blokada, test while connected to a wifi network. Ads are blocked. Apps are working without having to add in whitelist.

Turn off wifi, allow phone to connect to LTE.

Blokada is active but apps are blocked from internet.

Adding apps to whitelist, stopped apps and Blokada - apps are working functional

Remove apps from whitelist, they are blocked from internet again while using mobile network.

Turned off Blokada - apps are working normal

Switch back to Wi-fi (regardless of Blokada), apps are working as normal

**Expected behaviour**

Blokada should be working as intended in mobile network just as if it were using Wi-fi

**Actual behaviour**

Apps are blocked from internet connection without being added to whitelist in mobile network

**Configuration**

Blokada version
V4.4.4

Device model
Samsung Galaxy S10 (SM_G973F /DS)

Android version / ROM
v10 / UI 2.0

**Questions**

How long have you been using Blokada?
~3 months

How long time ago has the problem started to happen?
I'm not sure, I just recently found.

How often does this problem happen to you?
Always, when switching to mobile network

Additional info:
Host List: Energized Blu
DNS: Cloudfare

**Comment by peterroth** [comment]
Hey,
Can you try to switch to the default/standard DNS and check if you face the same issue?

**Comment by doctorapple** [comment]
> 
> 
> Hey,
> Can you try to switch to the default/standard DNS and check if you face the same issue?

I have switched the DNS to default, the issue still persists.

**Comment by doctorapple** [comment]
Okay! I got this fixed by turning off "Data saver" in Data Usage section. However, adding Blokada as execption doesn't help.

**Comment by peterroth** [comment]
Turn Data Saver off completely, that'll solve the issue

**Comment by doctorapple** [comment]
Anyway, I know it's not related to Blokada, but what could I do to stop apps from running in the background to avoid data loss? After this, we can close this issue. :D

**Comment by peterroth** [comment]
Settings -> Apps and notification -> select the app -> Data usage -> disable what you want to prevent.
