### ISSUE TITLE
Create git repository for host blacklists

### ISSUE THREAD

**Issue by jmliz** [blokadaorg/blokada#60]
I can't access the blacklists from the app itself and for some reason I can't find the links to add them manually via google search. I think it would be a good idea to create a git repository at blokadaorg so the community can contribute to the backlist creation and review. 

There's also the problem that ISPs/some_other_intermediaries may block the server Blokada gets the blacklists from. Having a public repo from which users can download add them manually would solve the problem. Or integreate a git client to the app.

Thanks for the excellent app :)

**Comment by kar** [comment]
This is a great idea!

It's a bit hacky and there's no documentation yet, but in case you're curious, there's a repo where Blokada gets the default blacklists from, you can take a look at it here:

https://github.com/blokadaorg/blokadaorg.github.io/blob/master/api/v2/prod/filters.txt

**Comment by jmliz** [comment]
@kar thanks for the link. I had no idea it was hardcoded somewhere. I thought the app was 'calling home' in some way for that list.

**Comment by kar** [comment]
It is home ;)
