### ISSUE TITLE
Continuous crashes after Storage permission is denied with External settings storage

### ISSUE THREAD

**Issue by szotsaki** [blokadaorg/blokada#600]
### Steps to reproduce
1. Open Blokada application > Settings > Application settings
2. Tap on "Settings storage" while it says "internal storage" > Android asks for Storage permission
3. Tap on Deny

### Expected behaviour

Blokada reports that the access was denied, internal storage you have to go.

### Actual behaviour

Blokada crashes immediately. When you try to restart it, it crashes again and again until in Android settings you grant the Storage permission.

I think the issue is when you tap on "Internal storage", Blokada immediately set it to "External storage" and issues the permission check after that (or in parallel, but not before). Since the external check is in place already the application will get into a problem trying to use that.

Based on this it's also worth testing how the application behaves with external storage setting set and then Storage permission revoked in Android settings.

### Configuration
1. Blokada version: 4.4.3
2. Device model: Sony XPERIA X
3. Android version / ROM: Android 8.0.0

**Comment by kar** [comment]
The external storage feature has to be reworked and this requires a deeper refactor of persistance layer. For now, I will remove this feature altogether.
