### ISSUE TITLE
Unable to block data.mistat.intl.xiaomi.com?

### ISSUE THREAD

**Issue by NoobieNewb** [blokadaorg/blokada#601]
I have Pihole installed on my network. I recently installed Blokada so that in the event that I am outside of my network, I can still block ads. The device in question is a Xiaomi Mi Pad 4 with Android 8.1 on MIUI 10.3.1.0.

The Xiaomi device is very loud, often sending request to data.mistat.xiaomi.com as well as data.mistat.intl.xiaomi.com every time I opened an app. I know this by checking my pihole requests. 

I have confirmed that Blokada works, because data.mistat.xiaomi.com as well as other ads sources no longer appear in the pihole requests, and they are showing up on the host log and is confirmed to be blocked by Blokada.

The problem is that it is still trying to connect to data.mistat.intl.xiaomi.com. I have confirmed by checking my router that the request is coming from the Xiaomi. Not only does Blokada unable to block the url, it does not even show up on the host log in Blokada. 

Any advice is appreciated.

**Comment by peterroth** [comment]
Hi,

Add the data.mistat.intl.xiaomi.com explicitly to the blocked hosts:
1.) Swipe up on Blokada’s main screen
2.) Tap on 'Ad blocking'
3.) Tap on 'Blocked Hosts'
4.) Tap on the + sign

By default there is a Xiaomi host block list, called "Xiaomi blocker by Jerryn70", check. if that's enabled on your device.

**Comment by NoobieNewb** [comment]
Adding the default block list fixes it! 
Thank you very much!
