### ISSUE TITLE
Datavolume in the widget isn't correct 

### ISSUE THREAD

**Issue by Marcus-CH** [blokadaorg/blokada#604]
When you use the Widget tve shown data volume will be always the same. 

### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version
4.4.4

2. Device model
Galaxy Note 8 and Huawei Mediapad M5 

3. Android version / ROM
9.0.1

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 
Since weeks

3.  How often does this problem happen to you?
every time

**Comment by peterroth** [comment]
Hi,
You mean the number of blocked domains, right?

**Comment by Marcus-CH** [comment]
No.
There ist a number. e. g..0.1 or 0.4 which is normally the MBite or MBit.
Greetings
Marcus 

Am 21. Dezember 2019 22:45:39 MEZ schrieb "Péter Róth" <notifications@github.com>:

**Comment by peterroth** [comment]
Is it possible you see that on 2x1 sized widget? That's not data volume, that's the number of blocked domains with SI prefix format to ensure it fits on the widget.

**Comment by Marcus-CH** [comment]
Blocked domains in million?
Not really clearly.


Am 22. Dezember 2019 19:12:44 MEZ schrieb "Péter Róth" <notifications@github.com>:

**Comment by peterroth** [comment]
Which is shorter to display:
0.4m
or
400.000

0.4 million = 0.4*1000000 = 400000
