### ISSUE TITLE
Blockada

### ISSUE THREAD

**Issue by opposruch** [blokadaorg/blokada#607]
### Steps to reproduce
1.
2.
3.

### Configuration
1. Blokada version

2. Device model

3. Android version / ROM

### Questions
1. How long have you been using Blokada? 

2. How long time ago has the problem started to happen? 

3.  How often does this problem happen to you?

**Comment by peterroth** [comment]
Other than the typo in the title, is, there anything to report?

**Comment by PrintableCharacter** [comment]
Savage
But on point :P
