### ISSUE TITLE
Feature Request: desktop version (windows, linux, mac)

### ISSUE THREAD

**Issue by erlangp** [blokadaorg/blokada#608]
Desktop version (windows, linux, mac) that generate 1 hosts file that contains all parsed host list. Thanks :)

**Comment by PrintableCharacter** [comment]
Hello,
Blokada Tunnel is already usable on most platforms. There are no plans to port the entirety of Blokada to windows devices at the moment. Consider using HostsMan or Spybot on windows devices. :)

**Comment by erlangp** [comment]
hm.. may be add feature to export host file? so i can manually edit hosts file in windows? :)

**Comment by peterroth** [comment]
@erlangp
You can download any of the host lists, they are publicly available and then you can edit them too.

**Comment by JM480** [comment]
Is there an alternative to this for Linux and Linux mobile devices like the Pinephone Pro? https://www.pine64.org/pinephonepro/
