### ISSUE TITLE
Enhanced Firewall feature

### ISSUE THREAD

**Issue by DI555** [blokadaorg/blokada#609]
please, implement Enhanced Firewall features !
since local vpn one intance possibility only , wold be great to use Blokada with enhaced firewall features !!!

**Comment by peterroth** [comment]
Duplicate of #49?

**Comment by DI555** [comment]
i supposed to miss it whild did the search....
but anyway, would like to see in Blokada all the features similar like in NetGuard and AFWall+ ....
... is it possible to fork , may be partly,  NetGuard or AFWall+ ?
