### ISSUE TITLE
Digitalcourage DNS settings outdated

### ISSUE THREAD

**Issue by JohannesKlug** [blokadaorg/blokada#612]
#71 Steps to reproduce
1. Enable DNS in Blokada
2. Select "Digitalcourage" as DNS server
3. Try accessing anything on the internet by name

### Expected behaviour
Connections succeed

### Actual behaviour
Name resolution fails

### Configuration
1. Blokada version 4.4.3

2. Device model irrelevant

3. Android version / ROM irrelevant

### Questions
1. How long have you been using Blokada? 
late 2019

2. How long time ago has the problem started to happen? 
beginning 2020

3.  How often does this problem happen to you?
always

Root cause: Digitalcourage changed their DNS IP address, see:

https://digitalcourage.de/support/zensurfreier-dns-server

> Bei neuen Konfigurationen bitte nur noch folgenden Server verwenden: 46.182.19.48 bzw. 2a02:2970:1002::18. Unser alter DNS-Server (85.214.20.141 bzw. 2a01:238:42f6:ac00:2a29:4f7f:b6d:ef46) wird 2020 abgeschaltet!

**Comment by JohannesKlug** [comment]
This seems like a trivial fix and I'd do it myself and raise a pull request, but I could not find where in the repo the DNS servers are configured.

**Comment by peterroth** [comment]
The IP address that is provided on the website is the one that is set for a long time: 46.182.19.48. You can find the DNS default file [here](https://github.com/blokadaorg/blokadaorg.github.io/blob/master/api/v4/canonical/defaults/dns.txt).

**Comment by JohannesKlug** [comment]
Sorry, my bad. Issue can be closed, thanks for the clarification!

**Comment by peterroth** [comment]
No worries. Don't forget to validate what you want to report.
