### ISSUE TITLE
Add DataMaster-Android-AdBlock-Hosts to the default blockinglist

### ISSUE THREAD

**Issue by DataMaster-2501** [blokadaorg/blokada#616]
(I was told by Peter to open this here)

I make my own Hosts filter list & wanted to know if I could have it added to the list of filter lists that users get to pick from?
I work hard to keep this list updated & want to share it with as many people as I can so they don't have to do all this work to enjoy ad free Internet & Apps. I also try to respond to any issues with my list as fast as I can & I try to encourage people report any kind of issue with my list.

https://github.com/DataMaster-2501/DataMaster-Android-AdBlock-Hosts

https://github.com/DataMaster-2501/DataMaster-Android-AdBlock-Hosts/blob/master/hosts?raw=true

Small Description: This list blocks Ads/Marketing Services, Analytics/Tracking Service.
                                 I can be contacted on GitHub for any issues.

**Comment by Ch4t4r** [comment]
Off-topic, but

> If you want to make money💰 then make people pay for your App

Almost all users expect free apps. Free apps reach far more users. Just imagine if Blokada was paid, there are other apps which can do similar things and Blokada would have never gotten this popular.

> If you want to make the App free then make it free with no Ads you Greedy Pigs!!!!

Don't use it then? A developer invested his time and offers you an App for free and you blame them for adding ads. Good job.

I'm not really sure if you are sarcastic with these statements. I hope you are.

Now, on topic:

I don't really believe that you compiled a 10mb hosts file yourself - if you did: good job (again). You don't mention any sources in your repository, which did you use (if any)?

Also, why did you choose the AGPL? The GPL should be enough for a hosts file.

**Comment by alexa-v2** [comment]
Wait are we saying _blokada_ has ads or did I miss something?

**Comment by Ch4t4r** [comment]
No, I just criticised his readme.

Also, he seems to be pretty disrespectful (https://github.com/AdAway/adaway.github.io/issues/23)
> " I've administered KES Endpoint Security myself and I found it to be the most thoroughly impressive software I've ever administered."
Shows what you know LOL!

**Comment by alexa-v2** [comment]
Omfg what has GitHub come to?
>"Shows what you know LOL"

Anyhow enough OT

**Comment by DataMaster-2501** [comment]
So is that a no to my request??😕
Also the AdAway people were being illogical over why they will not add my list to the "HostsSources"
Users get to pick what lists they use,
so if it does not work them pick some other list.
No one is forcing the list down the users throat.
@Ch4t4r As for my README that is how I feel & I really don't care what you think about it.😒

**Comment by DataMaster-2501** [comment]
p.s.
"I don't really believe that you compiled a 10mb hosts file yourself - if you did: good job (again). You don't mention any sources in your repository, which did you use (if any)?"
@Ch4t4r I did compiled a 10mb hosts file myself. I've been working on it for many many years long before I started a git for it 😜
It's one of my many hobbies.

**Comment by peterroth** [comment]
Thank you for the request @DataMaster-2501.
I checked the mentioned list and I can see you redirect 166630 hosts once for IPv4 (0.0.0.0) and once for IPv6 (::1). May I ask why?
4 hosts are redirected only for IPv4.
The following hosts are redirected 3-4 times:
```
Number of redirections | Hostname
3 | analytics.kingoapp.com
4 | d346whrrklhco7.cloudfront.net
4 | microsoftsto.112.2o7.net
```

If I check the microsoftsto.112.2o7.net I can see 2 lines carry not only one hostname, but 2:
```
0.0.0.0       microsoftsto.112.2o7.net
0.0.0.0       microsoftsto.112.2o7.net go.com
::1 microsoftsto.112.2o7.net
::1 microsoftsto.112.2o7.net go.com
```

**Comment by DataMaster-2501** [comment]
@peterroth Let me start off with sry about the type typo & duplicate lines.
My last update was rushed a little bit so that's why I have some duplicate lines so really sry about that.
As for the typo ::1 microsoftsto.112.2o7.net go.com I'm not sure how go.com got in there
but Thank you soo much for pointing that out, **I will fix all of this soon.**

"I checked the mentioned list and I can see you redirect 166630 hosts once for IPv4 (0.0.0.0) and once for IPv6 (::1). May I ask why?"
Well back when I started this list it was on my rooted phone
& there was no "blokada app" So I just added it to my /etc/hosts file on phone.
back then I only did IPv4 in the list.
Over time I saw that some domains were not being blocked when I was on 3g or LTE.
Then I saw that when I was on 3g or LTE I had both IPv4 IPv6 & that the domains getting by my block also used both IPv4 and IPv6.
So I added IPv6 and that fixed everything.
I made this list to be dropped into /etc/ on a rooted phone.
So that is why.
My phone is rooted & I don't use blokada
but my mom & many of my friends don't have rooted phones
so they use my list with blokada that I had setup for them & everything works fine for them.
I like blokada it's a well made app.

**Comment by DataMaster-2501** [comment]
@peterroth I fixed everything & updated list.
https://github.com/DataMaster-2501/DataMaster-Android-AdBlock-Hosts/releases/tag/1.8

p.s. after looking over somethings in blokada, I now see where you are coming from about the IPv4 & IPv6 but blokada is not loading both. It stops at 170725 so by having both is not hurting anything other then making users download 5MB more of data then they need.
If you want I could make 2 files:
my normal /etc/hosts file & one just for blokada
Let me know.

**Comment by peterroth** [comment]
Most of the hosts are added twice to block IPv4 and IPv6 as well, however there are 4 that added once:
www.google.comsecure.adultfriendfinder.com
ad.rtbq.spotx.tv
rtbq.spotx.tv
r.254a.com

Additionally, I'm not sure if the hostname _www.google.comsecure.adultfriendfinder.com_ really exist, it seems to be a merged one.
