### ISSUE TITLE
Request to add Threema to the default whitelist

### ISSUE THREAD

**Issue by lgrahl** [blokadaorg/blokada#619]
Hey folks, Threema is basically running into the same issue as Signal (see #62) where WebRTC is not picking up any local candidates. For Threema, it even goes beyond calls because the web client relies on WebRTC for direct unrelayed data transmission.

Threema has no ads and we're promising that this will remain so indefinitely. The package names are `ch.threema.app` and `ch.threema.app.work`.

**Comment by peterroth** [comment]
Thank you for notifying us!
PR [#50](https://github.com/blokadaorg/blokadaorg.github.io/pull/50) to add Threema to default whitelist is created.
