### ISSUE TITLE
I want easier way to contact support

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#620]
and to send logs to support.

**Comment by kar** [comment]
integrated zendesk sdk

**Comment by linuxandria** [comment]
I'm not so sure Zendesk is very privacy friendly.......

**Comment by kar** [comment]
I made sure the sdk won't even initialise unless you attempt to create a ticket.

**Comment by kar** [comment]
Also we setup an anonymous identity only.

**Comment by linuxandria** [comment]
I'll wait to pass judgement until I see it in action but nevertheless this isn't a comforting move for the privacy conscious
