### ISSUE TITLE
Add language option Please

### ISSUE THREAD

**Issue by NewUserHa** [blokadaorg/blokada#625]
some translations are very incomplete and problem that is unable to make users know exactly what a function does. hope some good translaters can help here.
but before that complete, could you add an option to disallow the translations?

Appreciate it!

Blokada version: 4.4

**Comment by peterroth** [comment]
Hi,

Translations are done on CrowdIn (https://crowdin.com/project/blokada) where anybody can contribute, translate and recommend other word or sentence.
Which language did you find inaccurate?

**Comment by NewUserHa** [comment]
Chinese Simplified

**Comment by peterroth** [comment]
Thanks. You can find the translations here: [Chinese Simplified](https://crowdin.com/project/blokada/zh-CN#).
