### ISSUE TITLE
blokada stores settings in downloads folder instead of Android/Data (for example)

### ISSUE THREAD

**Issue by eladkarako** [blokadaorg/blokada#626]
not sure why it's so, 
I'm using v4.3.

![Screenshot_20200119-011307_X-plore](https://user-images.githubusercontent.com/415238/72672066-617a5c80-3a5d-11ea-893e-37f809ef7423.jpg)

**Comment by peterroth** [comment]
If you set Blokada to store data in external storage, the Download folder will be used. There are plans to rework it, but it requires some refactoring.

**Comment by eladkarako** [comment]
shouldn't this remains open though?... 🤔

**Comment by peterroth** [comment]
There is another issue for the same request.

**Comment by eladkarako** [comment]
it seems to happen regardless what the storage have been set to 
(and I've been pre-set to allow storage-permission before the first run), 
maybe it works as extected in earlier version of Android, 
as for Android Pie 9.1 on Samsung devices, it seems to stick to using the <code>/Downloads</code> folder.

**Comment by eladkarako** [comment]
> There is another issue for the same request.

@peterroth I could not have found the already opened issue you've been mentioned above, 
so I've updated it in here instead. 

It seems it happens when the app is working in internal-storage (default) as well, 
I've cleared storage, and tested it in a fresh install of each of the 4.4.3-4.51 versions.

**Comment by peterroth** [comment]
Let me clarify the report.
Blokada leaves a blokada subdirectory in the /Download directory after you set to store the configuration in external storage and then switching back to internal. Right?

**Comment by eladkarako** [comment]
no, I have done a clean installation, deleting and existing Blokada folder from Downloads, clearing storage, then uninstall, and installed X version (repeated for each version). I did not specify in any way the place for the folder. each time it creates that Blokada folder under downloads. 
thanks.
