### ISSUE TITLE
Recommendation: proper heise download Link

### ISSUE THREAD

**Issue by wienfuchs** [blokadaorg/blokada#627]
proper Heise download link should be:
[https://www.heise.de/download/product/blokada](https://www.heise.de/download/product/blokada)

**Comment by peterroth** [comment]
Could you be a bit more specific, where do you see the wrong download link?
Blog, website or in the app?

**Comment by wienfuchs** [comment]
https://github.com/blokadaorg/blokada :)

"The trustworthy sources to download":

    https://blokada.org
    https://www.heise.de   <<====
    https://f-droid.org/
    https://labs.xda-developers.com

**Comment by peterroth** [comment]
Ok, thanks.

**Comment by peterroth** [comment]
Link is removed from README file because we do not maintain that source, can not upload the app there.
