### ISSUE TITLE
Why doesn't Blokada show up in apps list

### ISSUE THREAD

**Issue by pcause** [blokadaorg/blokada#630]
I am on Android 10 and just upgraded to 4.5.1.  if I go to the systems settings/apps blokada isn't in the list.  Not there is I show system apps.  Also if I go to special permissions and then all to install permission (which I had to grant to update) it isn't there.  Other VPN software shows up.  is there some reason for this?  This is the kind of behavior malicious software exhibits

**Comment by peterroth** [comment]
An app can't hide itself from the system, can't toggle "visibility". Malicious codes arrive with an app, and Blokada is open source, the full code can be accessed on GitHub, so everybody could see if we do something evil.
Restart your phone and check if you can see Blokada in the installed app's list.
