### ISSUE TITLE
OpenNICEU DNS is broken

### ISSUE THREAD

**Issue by cm-mc** [blokadaorg/blokada#631]
#71 # Steps to reproduce
1. Select openniceu dns
2. Make sure dns is active
3. Try to do something that needs dns lookup (e.g.: refresh weather app)

### Expected behaviour
Quick refresh

### Actual behaviour
Endless unsuccessful attempt to refresh

### Configuration
1. Blokada version
4.5.1

2. Device model
Samsung Galaxy S9+

3. Android version / ROM
9

### Questions
1. How long have you been using Blokada? 
Years

2. How long time ago has the problem started to happen? 
Months

3.  How often does this problem happen to you?
Everytime, with opennniceu; other dns, like keweon work fine.

**Comment by peterroth** [comment]
The DNS isn't broken, that is up and available, but extremely slow. Let me find another ones later on.

**Comment by cm-mc** [comment]
That's odd, because I use opennic dns on the pc (and router), and never had that problem.

**Comment by peterroth** [comment]
I checked the one that are set by default in Blokada.

**Comment by cm-mc** [comment]
I've set two nl anon, crypt servers (146.185.176.36, 51.15.98.97), and though I haven't checked speed, it's been working fine so far.
Btw, there should be an option to edit the servers, in the app, instead of just remove and readd them.

**Comment by peterroth** [comment]
The server's IPs in Blokada are static and were picked by me. I'll check the servers you mentioned, thank you.

That's a requested feature, see in #199.

**Comment by cm-mc** [comment]
I asked because opennic servers can be here today, gone tomorrow, so if blokada could regularly check their status and update according to chosen policies, the problem would be solved for good.

**Comment by kar** [comment]
Because of the problems, I decided to remove all opennic servers from Blokada.
