### ISSUE TITLE
4PDA app downloads are blocked

### ISSUE THREAD

**Issue by cm-mc** [blokadaorg/blokada#633]
#71 # Steps to reproduce
1. Open 4pda app
2. Try to dl something
3.

### Expected behaviour
Download successful

### Actual behaviour
Download fails

### Configuration
1. Blokada version
4.5.1

2. Device model
Samsung Galaxy S9+

3. Android version / ROM
9

### Questions
1. How long have you been using Blokada? 
Years

2. How long time ago has the problem started to happen? 
Not sure; months, ever since?

3.  How often does this problem happen to you?
Everytime, though no seemingly relatable entry in blocked list.
Adding 4pda, fourpda to app whitelist, allowed hosts doesn't work.
Only way around is to disable Blokada.

My hosts lists:
Energized blu
Goodbye Ads
AdAway
Social hosts
Coin Blocker
MobileAdTrackers

Disabling all the hosts lists above doesn't solve it.

**Comment by peterroth** [comment]
Please refer to our Knowledgebase Article in this topic: [Allow list](https://support.blokada.org/hc/en-us/articles/360010352200-Intro-to-adblocking-with-Blokada)

**Comment by cm-mc** [comment]
Don't know why you closed this issue, or pointed me to that article, because I've stated I tried both whitelisting the app and 4pda, fourpda hosts, and none worked.
Btw, 4pda hosts are already allowed through by default, anyway.

**Comment by peterroth** [comment]
Setting an app on allow list means the given app isn't included in the filtering channel, excluded from VPN, so the app can access everything as it does normally. The only thing I can think of that can block the app is the DNS server you configured.

**Comment by cm-mc** [comment]
I have dns is disabled in Blokada (issue #631); disabling Blokada quickly fixes the dl failure issue.

**Comment by cm-mc** [comment]
No longer an issue after reinstalling/resetting 4 pda.
