### ISSUE TITLE
Log can't be shared

### ISSUE THREAD

**Issue by Notabas-iC** [blokadaorg/blokada#635]
### Steps to reproduce
1. Try to share the log via 'Share log'-buttons (maybe when the log is larger than 5 MB)

### Expected behaviour
Log gets shared. 

### Actual behaviour
- Trying to share to telegram causes an 'unsupported attachment'-error. So the log can't be shared.
- Sharing to PhoneSaver (https://f-droid.org/app/link.standen.michael.phonesaver) causes the following exceptions: 'Save failed. -> INFO: Action: Android.intent.action.SEND -> INFO: Type plain/* -> DEBUG: Text has stream -> DEBUG: converting mime: plain/* -> DEBUG: converted mime: plain/* -> DEBUG: converting filename: blokada.log -> DEBUG: converted filename: blokada.log -> INFO: Supported: true.' -> Afterwards it still can't be shared. 
- Usually a reboot or force-stop fixes the problem. Afterwards the log only contains information since the reboot/force-stop.  (That worked on bq, Samsung, OnePlus phones, but didn't work for a Note 10+.)
- my hypothesis is that it has something to do with the file size. I could only share files till 4.something MB, not with more than 5 MB. 

### Configuration
Blokada version: v. 4.4., v4.5.1

**Comment by cm-mc** [comment]
I've found that (at least in my case) log is actually missing.

**Comment by peterroth** [comment]
@cm-mc from the internal storage, from `/data/data/org.blokada.alarm` ?

**Comment by cm-mc** [comment]
Can't read that folder (no root).
What I have is `/data/data/org.blokada.**origin**.alarm/`, btw.
I looked for the log in `/sdcard/Android/data/org.blokada.origin.alarm/files`, though.
Nevertheless, when trying to save it, I get a notification saying 'the item "blokada.log" was not found'.

**Comment by peterroth** [comment]
Yeah, sorry, origin was missing from the path I mentioned, thanks for the correction.
I checked and yep, the log file is in `/data/data/org.blokada.origin.alarm/files`, in `/sdcard/Android/data/org.blokada.origin.alarm/files` only the updates are stored.

**Comment by cm-mc** [comment]
That how I tried to save it (also copying it to clipboard).
I wonder whether lack of root access to that folder is preventing its creation/saving.

**Comment by peterroth** [comment]
The issue is solved with the release [4.5.2](https://github.com/blokadaorg/blokada/releases/tag/4.5.2).
