### ISSUE TITLE
Host log has no entries on 4.5.1

### ISSUE THREAD

**Issue by eigerzoom** [blokadaorg/blokada#637]
### Steps to reproduce
1. Update to latest 4.5.1 from 4.4.4 (github)
2. Use blokada for any amount of time
3. Check Host Log within app

### Expected behaviour
Host Log updates with requests

### Actual behaviour
Host Log shows no entries since previous version (5 days for me)

### Configuration
1. Blokada version
4.5.1

2. Device model
LG V30+ LS998u/US998

3. Android version / ROM
9 COSP/microg/nanodroid

### Questions
1. How long have you been using Blokada? 
since version 3.x

2. How long time ago has the problem started to happen? 
5 days

3.  How often does this problem happen to you?
Persistent

**Comment by eigerzoom** [comment]
Uninstalled and reinstalled manually and fixed the issue, however, naturally all my settings and block/allow are gone.

**Comment by peterroth** [comment]
I tried to reproduce this issue, but it didn't happen on my device. Can somebody else also try it?

**Comment by ChrisTech97** [comment]
I've also updated to 4.5.1 and my Galaxy S7 with stock Android 8.0 also had no new host log entries since the update. I've been using Blokada approximately since version 3.6. 
After I deleted the app data, the host log worked again.

**Comment by And96** [comment]
Same on my device.
No new log since the update.
Same also on 4.5.2.

**Comment by peterroth** [comment]
@And96 where did you look for the log?

**Comment by And96** [comment]
In host log page.
![photo_2020-02-09_14-28-15](https://user-images.githubusercontent.com/42185838/74102993-b4b96980-4b48-11ea-9db8-68411dc88318.jpg)

**Comment by And96** [comment]
uo

**Comment by eigerzoom** [comment]
i wrote down all of my blocks and reinstalled the latest version and manually entered them since there was no development on this issue.

**Comment by peterroth** [comment]
Just for clarification, the value of Blokada’s menu - Ad blocking Settings - Request Logger isn't "Disabled" but something else, right?

**Comment by And96** [comment]
It was disabled. Now i changed to internal memory and it works.

Solved thanks

**Comment by eigerzoom** [comment]
mine was always set to internal.

**Comment by And96** [comment]
Yes.

There is no problem.

**Comment by peterroth** [comment]
Thanks. It seems the mystery is solved.
