### ISSUE TITLE
Random Domain Names are not blocked

### ISSUE THREAD

**Issue by poode** [blokadaorg/blokada#639]
I am using Poco phone F1
Installed the app and saw that there are random domain names are allowed with filtering them and I need a rule to block them.
I need just to understand what is it?
It us weird!

![Screenshot_2020-01-29-02-32-12-490_org blokada origin alarm](https://user-images.githubusercontent.com/275428/73317820-21c32a00-4240-11ea-9682-cb29fc029185.png)

**Comment by peterroth** [comment]
Hi,
Please refer to our Knowledgebase Article: https://support.blokada.org/hc/en-us/articles/360011120160-What-are-the-random-hostnames-in-Host-Log-
