### ISSUE TITLE
Blokada 4 crashes on start

### ISSUE THREAD

**Issue by LightWayUp** [blokadaorg/blokada#640]
Blokada 4 is not supported anymore, closing the stale issue.  
Thanks to everyone who contributed to Blokada!

**Comment by kikz0rsk** [comment]
Same problem here, app crashes on launch. Cant post logs right now.
Honor View 10, Android 9, Blokada version 4.5.2

**Comment by fokditkak** [comment]
@LightWayUp Hey there! I have some questions regarding the problem you are facing:
- Does this issue persist on version **4.5.2**?
- Have you tried to play around with the **permissions** (such as notifications, storage access, etc.)? 
- What **language/locale** are you using? 
- Do you have **NTP** enabled on your device? (It is a fairly common issue, when it comes to applications using such functionality, to not start and/or crash when the time of the device isn't set properly)
