### ISSUE TITLE
Problem with Blokada on my office wifi Network only

### ISSUE THREAD

**Issue by LeZVince** [blokadaorg/blokada#642]
Hello,

When I use Blokada on my personnal wifi network (Freebox) and on another WIFI (Livebox) the application blocks the advertising as expected, but when I'm at my office on a Wifi Hotspot network, with the same Blokada configuration as my personal network, Blokada blocks everything.

For example if I run Google News ("Google Actualité" don't know the exact name in English sorry) at Home's wifi it works perfectly to block the Ads, but at my office's Hotspot Google News is not able to load anything so I have to disable Blokada for this to work and I "eat" a lot of Ads.

Is there any way to make it work properly at my office's hotspot too ?

Thanks per advance for your help :)

I am on Android 10 on a Xiaomi Mi 9T.

**Comment by peterroth** [comment]
Hi,

May I ask if you configured a 3rd party DNS server in Blokada? If yes, is that available on the office network?
If you use the default, we need much more information about your office network's configuration to find what is the cause. Companies have their variety of equipment that are not visible for the clients and they all can play a role.

**Comment by peterroth** [comment]
Hi,

I am just checking in to ask if you had time to read my previous message.

**Comment by LeZVince** [comment]
> 
> 
> Hi,
> 
> I am just checking in to ask if you had time to read my previous message.

Hello yes I have read your message :) Thanks for your answer.
I have been configured Blokada with a DNS --> DNS AdGuard list.
On a WIFI network what could create problems when you use a DNS on the Android application ?

**Comment by peterroth** [comment]
If the company enforces its own DNS server or proxy, filters packages, uses firewall, keeps port/s closed, uses encryption or the connection is routed (for example to a one of the above devices) for external communication.

**Comment by LeZVince** [comment]
Thanks for your answer **peterroth**.

**Comment by peterroth** [comment]
Sure thing :)
