### ISSUE TITLE
Firefox not working with Blokada 4.5.2 (?)

### ISSUE THREAD

**Issue by deesnook** [blokadaorg/blokada#644]
Hi everyone,

being new to Blokada I'm not sure if this is really an issue, but it might be worth having a look at it:

I just installed Blokada 4.5.2 from F-Droid for the first time running LineageOS for microG 16.0-20200130 on a OnePlus 3T.

If I block network access for Blokada (both WIFI and GSM) in the system settings, both Firefox Preview 3.2.1 (without add-ons) and 68.5.0 (with uBlock Origin and NoScript) do not work at all with Blokada activated. No website is accessible, the screen remains blank. Chromium 82.0.4053.0 works fine though. I'm using the default settings in Blokada (hostlist EnergizedProtection Blu).

As soon as I allow network access, both Firefoxes work fine, too. I think I had the same issue with some messengers (Threema and Riot), but I haven't been able to verify this so far.

Any ideas if this is an expected behavior? Thanks!

**Comment by PrintableCharacter** [comment]
Hi,
Wait.
Why do you block network access for Blokada?

**Comment by deesnook** [comment]
No specific reason, I block as many permissions as possible as long as things work. I downloaded the blacklist and then blocked network access, which seemed to work at first glance until I encountered the mentioned problem (which I'm not sure is a real problem at all, I'm just curious about it)

**Comment by peterroth** [comment]
Ok, so, if you block internet access for an app that works as a "gateway" (VPN client, where the VPN is the tunnel to the internet), then of course nothing will access internet (only bypassed apps).

**Comment by deesnook** [comment]
Sure, that's logical, but I don't use Blokada as VPN Client. The VPN tunnel is deactivated.

Unless the mere adblocking functionality uses VPN gateway functions as well, but I couldn't tell if that's the case since I don't know how Blokada works. I was just astonished that Chromium worked and Firefox didn't.

**Comment by peterroth** [comment]
Blokada, to filter ads, uses the VPN API, thus, it acts as a "local VPN client". It doesn't connect to anywhere, but a local tunnel is created. You can read about it [here](https://support.blokada.org/hc/en-us/articles/360010501959-How-does-Blokada-work-)
