### ISSUE TITLE
Blokada breaks internet 

### ISSUE THREAD

**Issue by h2oox** [blokadaorg/blokada#649]
Blokada is breaking internet connection with latest Feb security update on Samsung note 8.  Internet is restored only when app is fully uninstalled. Issue only occurs if private DNS is CONCURRENTLY set to use adguard DNS.  Blokada works when private DNS is disabled.

**Comment by peterroth** [comment]
>Blokada works when private DNS is disabled.
Yes, because private DNS encrypts the DNS queries and as they cannot be read by the application (and due to this, Blokada can't filter ads) the internet access is blocked.

**Comment by h2oox** [comment]
Thank you for the quick response!
