### ISSUE TITLE
I want a widget for turning on/off filtering

### ISSUE THREAD

**Issue by notramo** [blokadaorg/blokada#65]
A homescreen widget would be cool.

**Comment by guyllheaume** [comment]
Would be great, and cool if widget could show total number of blocked ads (like in "always active" notification) great work anyway dev

**Comment by xDeaRxDeViLx** [comment]
Hey yoooo,
I will only say to you, Thank you very much for the Blokada Application, Very good structure and very good menu.
Is my constant companion and am very satisfied with it.
20min a go i have send to you a little donation for the good Creation. 
Wish you all the best and keep it up.

**Comment by lartomar2002** [comment]
Thanks for this great app and I do not even have to be rooted.
