### ISSUE TITLE
Blokada does not block some google domains although blacklisted multiple times

### ISSUE THREAD

**Issue by KuenzelIT** [blokadaorg/blokada#652]
### Steps to reproduce
1. See www.googleapis.com in the Host-Log
2. Select "block" for that domain.
3. See the domain again the Host-Log later on while not being blocked.

### Expected behaviour
The domain should have been blocked

### Actual behaviour
The domain is still allowed whilst being listed on the blacklist.

### Configuration
1. Blokada version
4.5.2 (android-26 community release arm64-v8a samsung-starlte touch apie compatible)

2. Device model
Samsung Galaxy S9

3. Android version / ROM
Android 8.0.0 Stock with removed Bloatware

### Questions
1. How long have you been using Blokada? 
A few days

2. How long time ago has the problem started to happen? 
The problem started after I removed some domains from the black list again just for testing. After this the google domains (yes so far only google) don't get blocked anymore.

3.  How often does this problem happen to you?
Every time a dns request is sent for:
- www.googleapis.com
- android.clients.google.com
- android.googleapis.com

The issue really irritates me because it worked right at the beginning before I removed some domains from the blacklist again. I hope you have an idea. Thanks!

**Comment by peterroth** [comment]
Hi,
Do you face the same issue if you force-close Blokada and restart it?

**Comment by KuenzelIT** [comment]
Hi,
I did a force-close in the app settings a few hours ago, but that didn't help. I also blocked those domains again and waited, but they still appear as allowed.

**Comment by KuenzelIT** [comment]
Hi again,
the problem was that the domains were on my whitelist and I wasn't aware of that. I assumed that if I block a domain again, that it get's removed from the whitelist. Is it an intended behaviour, that domains can be on both, the blacklist and whitelist?
