### ISSUE TITLE
Please include the Energized Regional list in the built-in choices.

### ISSUE THREAD

**Issue by palopezv** [blokadaorg/blokada#655]
Since I started using Blokada some 3 years ago, I've noticed that no matter what Energized list I use, it won't block ads in my native language. A couple of days ago I discovered that Energized provides extension packs and among them one called "Regional" that includes all the AdGuard language specific lists. All other Energized lists, even the Unified list, do not include that information. I believe not having this list in the default choices is a bug.

I request that the Energized Regional list be included by default.

**Comment by peterroth** [comment]
PR [#52](https://github.com/blokadaorg/blokadaorg.github.io/pull/52) is created to add the list.

**Comment by peterroth** [comment]
Regional list is added. Thanks for the request.

**Comment by palopezv** [comment]
Much appreciated.
