### ISSUE TITLE
"https://ad.doubleclick.net"    Is creating ads in the mangarock definitive app

### ISSUE THREAD

**Issue by deeparora9414** [blokadaorg/blokada#658]
https://ad.doubleclick.net.            Is creating ads in the mangarock definitive app. Even though i created a different block list for it.
-->

### Steps to reproduce
1.install mangarock definitive app from their original website.
2.mvps, goodbyeads by gerryn70, energized blu(recommended), seperate entry for ad.doubleclick.net . All these hosts lists are activated in blokada.
3. Open chapter 24 of "the fincee of the wizard" or any other chapter of any manga in the app . After 2-3 minutes of reading the chapter.
4. There is add at the bottom as shown in screenshot in landscape mode.

### Actual behaviour

1. On and off the blokada app many times.
2. Quit the mangarock definitive app many times even from background.

### Configuration
1. Blokada version 4.5.2

2. Device model samsung galaxy on nxt SM-G610F

3. Android version 8.1.0

### Questions
1. How long have you been using Blokada? 
- For 1-2 years.

2. How long time ago has the problem started to happen? 
- from sunday, 1st march 2020, This morning from 6 am, Indian standard time.

3.  How often does this problem happen to you?
- This is the first time.
![Screenshot_20200301-082426_Manga Rock](https://user-images.githubusercontent.com/23583833/75618646-4117e480-5b69-11ea-8512-a2828bc5caa9.jpg)

![Screenshot_20200301-085439_Blokada](https://user-images.githubusercontent.com/23583833/75618889-40348200-5b6c-11ea-9ea0-b399aa93c4e2.jpg)

[0_blokada.log](https://github.com/blokadaorg/blokada/files/4271290/0_blokada.log)

Log is also uploaded.

**Comment by peterroth** [comment]
Hi,

After you installed Blokada, did you clear every other apps cache? Ads are fetched and shown from local storage (originally for offline times).

**Comment by peterroth** [comment]
Additional thing that I just spit on the screenshot: if you want to block one entry, that should be added under _Ad blocking - Blocked Hosts_, not in _Ad blocking - Host Lists_.

**Comment by deeparora9414** [comment]
> Hi,
> 
> After you installed Blokada, did you clear every other apps cache? Ads are fetched and shown from local storage (originally for offline times).

I had cleared the cache from settings>apps>mangarock definitive>storage>clear cache. Many times but it didn't work.

**Comment by deeparora9414** [comment]
> Additional thing that I just spit on the screenshot: if you want to block one entry, that should be added under _Ad blocking - Blocked Hosts_, not in _Ad blocking - Host Lists_.

I indeed add the domain wrongly as "https://ad.doubleclick.net/"  so it went to hosts lists instead of blocked hosts. By adding simply "ad.doubleclick.net" would have done the trick.

So i, just corrected it and waiting to check if it works or not. I would close this issue in 2-3 days if it works fine. Thanks for pointing out the issue.

**Comment by peterroth** [comment]
So, just to clarify, there were 2 failures:
1. the hostname was added as list, instead of (blocked) domain name
2. you added the protocol (https) and not only the domain name
