### ISSUE TITLE
Blokada does not block a certain domain in blacklist

### ISSUE THREAD

**Issue by Spielmops** [blokadaorg/blokada#661]
I start Firefox and goto wetteronline.de. The hostlog of Blokada shows a certain domain "ytwkco.com" which is doubious for me. Ok, I make an entry in the blacklist "ytwkco.com" and observe the log. This domain stays white and is still loaded. Why is a blacklisted domain going through Blokada?

OS: LineageOS 16
Blokada 4.5.2

Spielmops

**Comment by peterroth** [comment]
Hi,
Where did you add that domain? And how? Can you attach a screenshot about it?
Did you try to restart Blokada and check if then it works as expected?

**Comment by Spielmops** [comment]
I added that domain sitting at our breakfast-table in our home in Oldenburg. I used a tablet from Huawei and the middle-finger of my right hand for that. I restartet Blokada by going to "Settings" -> Apps -> Bokada -> force stop and then calling Blokada again.

The Website calling the domain ytwkco.com is "wetteronline.de/regenradar". 

Spielmops

**Comment by Spielmops** [comment]
![Blokada-blockt_nicht-2](https://user-images.githubusercontent.com/3194177/75962489-24124700-5ec4-11ea-9ea3-e4ed6995f57f.png)
![Blokada-blockt_nicht-1](https://user-images.githubusercontent.com/3194177/75962490-24aadd80-5ec4-11ea-84a4-42f2a902c959.png)

**Comment by peterroth** [comment]
That's cool.
As I can see you added only the 2nd level domain, ytwkco.com. However, what goes through is all the subdomains of that. Add wildcard hostname while you are sitting at at breakfast-table in your home in Oldenburg. Please use your middle-finger of your right hand for that.

**Comment by Spielmops** [comment]
Sorr, that does not make sense. If I blacklist a second-level-domain, than all subdomains have to be blocked too. Nevertheless, i tried that and it did not work. ("*" is a working wildcard?) Itried it even with another finger, but it did not blcok anything. I tried it with the whole hand, but that blocked only my children ...

**Comment by peterroth** [comment]
Makes sense for you or not, here are the commits that allow wildcard blocking: [af53b2c4](af53b2c4b7915e3d056497975377b23619e69596) and [7c690df3](https://github.com/blokadaorg/blokada/commit/7c690df3799ebb43581be3b49e9faec34677f2f1).
You need to turn on the feature in Blokada menu - Ad blocking - Ad blocking Settings - Advanced adblocking rules. Do it with your elbow, that may help.

**Comment by Spielmops** [comment]
OK, I did not know of this setting. Switched the wildcard-setting to on, force stopped Blokada, started it anew and the subdomains are blocked. I#M curious, what kind of data have been loaded from there, because is website "wetteronline.de/regenradar" is still working ...

Thanks for the hint,
Spielmops

**Comment by peterroth** [comment]
You mean the solution ;)
Welcome.
