### ISSUE TITLE
I want the option to use DuckDuckGo's new Tracker Radar host lists

### ISSUE THREAD

**Issue by ParanoidCommie** [blokadaorg/blokada#662]
As described in https://spreadprivacy.com/duckduckgo-tracker-radar/

**Comment by m4dc4p** [comment]
Yes! Please!

**Comment by kar** [comment]
So I found a way to generate a blocklist from DDG data, that may make sense, but its reliability may be questionable. Read this https://github.com/duckduckgo/tracker-radar/issues/2. We'll have to test it out.
