### ISSUE TITLE
Dutch Donate button leads to French screen (the next screen is Dutch again)

### ISSUE THREAD

**Issue by StijnBousard** [blokadaorg/blokada#665]
#71 # Actual behaviour
In the Android app (not on the website), if you click the Donate button in the Dutch version ("Doneren"), you're redirected to a French page (https://blokada.org/api/v4/content/fr_FR/donate.html). I don't know how the language is detected. Maybe it's because I'm in Belgium, where we have two main languages (Dutch & French), but from a Dutch Blokada app, it should go to https://blokada.org/api/v4/content/nl_NL/donate.html.

On the website, this screen is simply skipped, and maybe it's a good idea to skip it in the app as well and to move immediately to the next screen, which is in Dutch again (https://donorbox.org/blokada) - I suppose this screen detects the user's language correctly.

### Expected behaviour
When you click the Dutch "Doneren" button, that it goes to https://blokada.org/api/v4/content/nl_NL/donate.html, or directly to https://donorbox.org/blokada.

### Steps to reproduce  
See the same numbered attached files
1. Open a Dutch version of Blokada on Android.
2. Slide up the hamburger menu to see the settings screen.
3. Click on "Doneren".
4. **The French screen appears** _[Click on "Faire un don")
5. The Dutch screen appears (= correct)
6. Scroll down: there is a misspelling (but that's something for donorbox.org): 
instead of 'weekelijks' (with 'ee'), it should be 'wekelijks' (with 'e')]_

### Configuration
1. Blokada version: 4.5.2
2. Device model: Sony Xperia XA2
3. Android version / ROM: Pie 9 / Build 50.2.A.3.22

### Questions
2.  How often does this problem happen to you?
Always

Attachment 2:
![2](https://user-images.githubusercontent.com/10280315/76801701-77469c80-67d6-11ea-83c4-277472d641bc.png)
Attachment 4:
![4](https://user-images.githubusercontent.com/10280315/76801705-77df3300-67d6-11ea-8ea4-7c260affba0b.png)
Attachment 5:
![5](https://user-images.githubusercontent.com/10280315/76801708-7877c980-67d6-11ea-8a25-5becbcef64e4.png)
Attachment 6:
![6](https://user-images.githubusercontent.com/10280315/76801710-7877c980-67d6-11ea-8232-a47d134deff0.png)

**Comment by fokditkak** [comment]
Hi, @StijnBousard !
Can you please tell me the exact language/locale/variant you are using?

I've tried to reproduce this issue but without success. Whenever I click "Doneren" I do **not** get a pop-up like yours. Instead Blokada opens a link in browser and in English.

> On the website, this screen is simply skipped, and maybe it's a good idea to skip it in the app as well 

I can agree with you on that!

**Comment by StijnBousard** [comment]
Hi,

This is the 3rd time I start to reply, but now I'll go till the finish :-)

I've done some more investigation. The language depends on the system language.

Device settings > System > Languages & Input > Languages:
I had two languages installed:
1 Nederlands (België) = Dutch (Belgium)
2 Français (France) = French (France)

When I remove French, it takes me to the English version.
Even if I install Nederlands (Nederland) (=nl_NL) as primary language, it takes me to https://blokada.org/api/v4/content/en/donate.html, even if https://blokada.org/api/v4/content/nl_NL/donate.html exists!

But to be good, the 'Doneren' button should go to https://blokada.org/api/v4/content/nl_NL/donate.html for both Nederlands (België) and Nederlands (Nederland).

I've also done some more investigation concerning the popup. If I have only Brave as a browser (Chrome stopped & disabled), then I get the popup (with English links at the bottom... 'Open in browser'/'Close'). The popup even shows a short message in Dutch ('Laden, even geduld...' = 'Loading, please wait...') before the French (or English) text appears. (*)

If I also enable Chrome, I immediately get a browser window, as well in Chrome as in Brave.

(*)
![Laden, even geduld](https://user-images.githubusercontent.com/10280315/78070188-aabf2480-739b-11ea-98d9-b4c186745506.png)
