### ISSUE TITLE
Blokada is blocking audio- and video-signals for jitsi-meet

### ISSUE THREAD

**Issue by mdosch** [blokadaorg/blokada#669]
### Actual behaviour
You can join a conference with jitsi-meet but you don't receive others a/v and also others don't receive your a/v. Blokada has no hosts blocked being in use for the jitsi-meet instance and also allowing jitsi-meet to bypass Blokadas filtering doesn't help.
When disabling Blokada everything works as expected.

### Expected behaviour
The a/v stream should work with Blokada enabled.

### Steps to reproduce  
1. Have Blokada running on an android mobile
2. Enter a conference with jitsi-meet on another device or a WebRTC-enabled browser
3. Enter the same conference from 2. with jitsi-meed on the android mobile from 1.
4. A/V streams are not working
5. Close conference on the android mobile from 1
6. Disable Blokade
7. Repeat 3. then proceed to 8.
8. A/V streams are working now

### Configuration
1. Blokada version: Version 4.5.2 (405000002) (fdroid)
2. Device model: Wileyfox Swift (crackling)
3. Android version / ROM: Android 9/LOS16 2020-02-24 microG

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
No

2.  How often does this problem happen to you?
I just tried to use jitsi-meet since yesterday and was able to find Blokada is causing this today.

**Comment by peterroth** [comment]
Hi,
Can you please check the followings: et the jitsi-meet application to allow list, kill/stop Blokada, restart it and check if then the audio and video stream goes as expected.

**Comment by mdosch** [comment]
I already added it to the allow list earlier, but there was no indication that a restart is required. Now after re-enabling Blokada jitsi-meet works again.
Thanks for the hint. :)

**Comment by peterroth** [comment]
In some cases the tunnel isn't restarted and thus, the allowed app is still blocked.
Happy to read it helped you.

**Comment by mdosch** [comment]
I opened a PR to add jitsi-meet and conversations to the whitelist as it happened several times now that jitsi-meet or conversations calls didn't work for friends. They usually do not know they have to whitelist VoIP apps. 
https://github.com/blokadaorg/blokadaorg.github.io/pull/55
