### ISSUE TITLE
Blokada block Plex Syncing

### ISSUE THREAD

**Issue by slimdizzy** [blokadaorg/blokada#67]
Plex wont sync unless you disable Blokada.

Repro Steps:
- Have Plex server and app on phone
- Sync an item

Expected Result:
- item gets synced

Actual Result:
- no notification at all, none for the conversion and none for the sysnc
- no sync happens
- Plex reports sync is "Pending"

Disable Blokada and the sync starts right up.

**Comment by kar** [comment]
Tried whitelisting Plex?
