### ISSUE TITLE
PL VOD App: Player - Blocked VPN usage.

### ISSUE THREAD

**Issue by ghost** [blokadaorg/blokada#670]
Hello,

Latest version of polish VOD platform app 'player' does not work with VPN tunnels. Tried with blokada and zerotier. 
Error: 'there is no internet connection'
With VPN connection i.e blokada/zerotier disabled everything is working again.

Affected versions:
ATV 1.0.83: https://play.google.com/store/apps/details?id=pl.tvn.player.tv
Phone: 5.1.1 https://play.google.com/store/apps/details?id=pl.tvn.player
Screen:
https://i.postimg.cc/pPBL6B73/1111111111.jpg
https://i.postimg.cc/jTBtv92L/Screenshot-2020-03-18-20-47-43-508-pl-tvn-player.jpg

Is there any way to hide (within OS or Blokada) working VPN connection? Or there is no way and other app devs will follow this trend...

edit:
```
declared permissions:
      pl.tvn.player.tv.ACCESS_VIDEO_DATA: prot=signature, INSTALLED
      pl.tvn.player.tv.ACCESS_MOVIES_DATA: prot=signature, INSTALLED
    requested permissions:
      android.permission.INTERNET
      android.permission.ACCESS_NETWORK_STATE
      android.permission.ACCESS_WIFI_STATE
      android.permission.RECORD_AUDIO
      android.permission.CAMERA
      android.permission.READ_PHONE_STATE
      android.permission.ACCESS_COARSE_LOCATION
      android.permission.ACCESS_FINE_LOCATION
      com.google.android.c2dm.permission.RECEIVE
      android.permission.WAKE_LOCK
      com.android.providers.tv.permission.READ_EPG_DATA
      com.android.providers.tv.permission.WRITE_EPG_DATA
      android.permission.RECEIVE_BOOT_COMPLETED
      pl.tvn.player.tv.ACCESS_VIDEO_DATA
      pl.tvn.player.tv.ACCESS_MOVIES_DATA
      com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE
      android.permission.FOREGROUND_SERVICE
    install permissions:
      com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE: granted=true
      com.google.android.c2dm.permission.RECEIVE: granted=true
      android.permission.RECEIVE_BOOT_COMPLETED: granted=true
      com.android.providers.tv.permission.READ_EPG_DATA: granted=true
      android.permission.INTERNET: granted=true
      com.android.providers.tv.permission.WRITE_EPG_DATA: granted=true
      android.permission.ACCESS_NETWORK_STATE: granted=true
      pl.tvn.player.tv.ACCESS_MOVIES_DATA: granted=true
      android.permission.ACCESS_WIFI_STATE: granted=true
      pl.tvn.player.tv.ACCESS_VIDEO_DATA: granted=true
      android.permission.WAKE_LOCK: granted=true
    User 0: ceDataInode=-4294863555 installed=true hidden=false suspended=false stopped=false notLaunched=false enabled=0 instant=false
      lastDisabledCaller: com.android.vending
      gids=[3003]
      runtime permissions:
```

Tried with
c:\adb>adb shell pm revoke pl.tvn.player.tv android.permission.ACCESS_NETWORK_STATE or android.permission.ACCESS_WIFI_STATE
but got
Operation not allowed: java.lang.SecurityException: Permission android.permission.ACCESS_NETWORK_STATE is not a changeable permission type

**Comment by peterroth** [comment]
I would reach out to the other app's developer/maintainer what's the reason behind the restriction. I'm afraid there is very less what we can do, if the app can use the network API the system will show something uses the VPN API (if Blokada or any other VPN related app is running).

**Comment by fokditkak** [comment]
> Latest version of polish VOD platform app 'player' does not work with VPN tunnels. Tried with blokada and zerotier.

Do earlier versions work with VPN?

I agree with @peterroth that the 'player' you are using is restricting such connections.

 **BUT** if you're feeling lucky I would suggest to setup a basic VPN server (if you have administrative access to a router with such capabilities) and connect your device directly to that VPN so that you can be sure it's from the 'player' at the very least.
