### ISSUE TITLE
Blokada 4.5.2 connects to journal.blokada.org without opt-in

### ISSUE THREAD

**Issue by OmarLipton** [blokadaorg/blokada#671]
### Actual behaviour
Blokada keeps connecting to several URLs
blokada.org
api.blocka.net
journal.blokada.org

It does this even though I have not opted in to send crash reports or anything. 

### Expected behaviour
I expect to be able to see Blokada in the list of installed apps. Blokada should not whitelist itself and not allow blocking its connections.

This app should not make ANY connections to the internet unless I ask it to do so.

**Comment by peterroth** [comment]
This app uses the internet to fetch the lists you are using, they aren't stored in the app (that would 
 drastically increase its size).
Sidequestion: do you know what journal.blokada.org does? If not, why do you think that's something with the crash reports?

**Comment by fokditkak** [comment]
> This app uses the internet to fetch the lists you are using, they aren't stored in the app (that would
> drastically increase its size).

I'd guess it also checks for newer versions of the app.

> I expect to be able to see Blokada in the list of installed apps.

Have you restarted your device? Prior to restart many newly installed apps do not show in lists.

**Comment by peterroth** [comment]
@OmarLipton I'm just checking in to ask fi you had the chance to read our messages.
