### ISSUE TITLE
Revision DNS Fallback's default setting

### ISSUE THREAD

**Issue by peterroth** [blokadaorg/blokada#672]
The 'DNS Fallback' option is enabled by default.
It addresses issues where the system uses a DNS server on the local network, what probably cannot be addressed when Blokada is enabled.
There are cases when this option is the source of issues users experience, for example when the Fallback Server (currently Cloudflare) cannot be accessed from the user's device.

**Comment by s4pun1s7** [comment]
Would having multiple fallback DNSs resolve this?

**Comment by peterroth** [comment]
Because we cannot be sure which DNS servers are available from the users' network, it would make things more difficult to debug. Plus it requires a check. if DNS 1 is accessible, if not check DNS 2, if not DNS 3, etc, and the user only sees endless waiting time for a website to load.

**Comment by s4pun1s7** [comment]
Would it suffice if there were 2 fallback DNS - Cloudflare and Google (8.8.8.8 or 8.8.4.4). If there's no connection to both of them it would mean that there is no connection to the Internet, wouldn't it?

**Comment by peterroth** [comment]
There is an easier and much more resource-friendly way that the Android system provides through its [API](https://developer.android.com/training/monitoring-device-state/connectivity-status-type).
