### ISSUE TITLE
Samsung S8+, Android 7.0 August 2017 security patch

### ISSUE THREAD

**Issue by azfirefighter** [blokadaorg/blokada#68]
I've installed the most recent as well as the previous version, but the program never asks to set permissions and keeps saying it can't connect to the internet whether I'm on Wifi or cellular.

**Comment by kar** [comment]
Try turning off "online only" and report back.

**Comment by azfirefighter** [comment]
Did that.  Still wouldn't work.

**Comment by kar** [comment]
Try going to android settings and remove the Blokada VPN if there is one. Also reboot your phone. I don't have any more ideas, it's weird. ;/
