### ISSUE TITLE
Blokada blocks internet.

### ISSUE THREAD

**Issue by qazip** [blokadaorg/blokada#685]
### Actual behaviour

When I turn on blokada, internet stops working. That is, all apps which require an internet connection no longer function. The browser no longer connects, etc

### Steps to reproduce  
1. Open blokada;
2. Activate/Enable blokada;

### Configuration
1. Blokada version: 4.5.2
2. Device model: Xiaomi Mi A2 Lite 
3. Android version / ROM: Android 10, though it also happened on android 9. It started after doing the March security upgrade, **I think**;

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
Yes, I think it started happening after the March security update that xiaomi released for my phone;

2.  How often does this problem happen to you?
All the time. I can't have blokada enable if I want internet.

**Comment by peterroth** [comment]
Hi,
Take a look in this Knowledgebase Article: https://support.blokada.org/hc/en-us/articles/360011685360-Can-t-browse-the-internet-when-Blokada-is-enabled

Additionally, check if the DNS server you might set in Blokada is available on your internet.

**Comment by qazip** [comment]
Oh ya, seems like I was using a dns in android's settings. Weird, I don't remember changing that! Thank you @peterroth!
