### ISSUE TITLE
I want a new UI interface (more like chromium (looks like chrome browser))

### ISSUE THREAD

**Issue by Selflabyrinth1** [blokadaorg/blokada#686]
I want just a new UI interface as the title says and if it's possible an immersive mode feature in-app (only in the app). And the chromium UI interface (as mentioned before and in the title).

**Comment by peterroth** [comment]
Hi,
Just for clarification, you want a totally new design of the app?

ps: UI stands for User Interface

**Comment by Selflabyrinth1** [comment]
Dear Blokadaorg/Blokada,

What I want is:

#1: Theme selection (Dark (Amoled if it's possible) - White).

#2: Rounded buttons (like chrome (not circle buttons just the corners to be
more rounded).

#3: Fullscreen (like games (not all games have fullscreen just an
example)), (what I mean by fullscreen is immersive in-app (no navigation
shows (example: see attachment))).

Thanks for asking me what exactly I want.

Sincerely yours,
Jonathan Georgiou (SelfLabyrinth1 (on Telegram English Group))

PS: Thanks for the correction.

**Comment by kar** [comment]
We'll port the UI from iOS version (v5) to Android.

- dark/light theme will come

I'm closing this, the port is already planned.
