### ISSUE TITLE
Feature Request: I want to see new DNS server preset added.

### ISSUE THREAD

**Issue by c933103** [blokadaorg/blokada#688]
Hello, I see there are preset option of OpenNIC - USA and Openniceu in the DNS setting but both of them doesn't function correctly here from my home in East Asia. On the other hand, when I manually typed IP address of Asian OpenNIC server into the app, they functions correctly, thus I would like to request a preset for Asian OpenNIC DNS server address, so that Asian users of the app can use OpenNIC DNS servers directly. Specifically I am now using 139.162.24.92 and 172.105.220.183 from the official OpenNIC DNS server list.

**Comment by peterroth** [comment]
PR [#57](https://github.com/blokadaorg/blokadaorg.github.io/pull/57) ships OpenNIC Asia.

**Comment by c933103** [comment]
Thank you.
