### ISSUE TITLE
HTTPS on website

### ISSUE THREAD

**Issue by edent** [blokadaorg/blokada#69]
Love the app - but I'm a bit concerned about its security.  The configuration is only downloaded over HTTP.  Ideally, the `http://blokada.org/api/` URLs should be protected with `https`.

Additionally, in http://blokada.org/api/20/dev/filters.txt the following should be replaced by their HTTPS equivalents.

http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0 -> https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0

**Comment by kar** [comment]
Definitely

**Comment by hoshsadiq** [comment]
CloudFlare can be used to enable https: https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by hoshsadiq** [comment]
@kar one more thing, would be nice to enable http to https redirect.

**Comment by kar** [comment]
Yes absolutely. Once I update all the clients and there is no unexpected problems, I'll do so.
