### ISSUE TITLE
App bypass vs blocked host not working

### ISSUE THREAD

**Issue by pscalmic** [blokadaorg/blokada#697]
Hi and thank you for a great app!
Blokada 4.5.2, Android 10 May update (Galaxy S10)
Enpass 6.4.3.344 (io.enpass.app) synced with OneDrive

I have the domain graph.microsoft.com in the blocked hosts list.
I put Enpass in the app bypass list but the sync with OneDrive isn't working.
Removing graph.microsoft.com from the blocked list works instantly.

Tried shutting down both apps and reboot with the same result.

Let me know if i can be any help.

**Comment by peterroth** [comment]
Hello,

Try the following:
1. Block the domain
2. Add the app to the bypass list
3. Kill/stop Blokada (not only press the button on main screen but kill the app)
4. Start Blokada
5. Test if app works

**Comment by pscalmic** [comment]
Thanks for you advice.
I managed to get it working after clearing the app cache. Which is the only thing I didn't do.

All good now.

Thanks a lot anyway


-------- Original message --------

**Comment by peterroth** [comment]
Awesome, happy to read it works now.
