### ISSUE TITLE
Energized Filter Lists stopped working

### ISSUE THREAD

**Issue by elkangaroo** [blokadaorg/blokada#699]
### Actual behaviour
When enabling one of the "Energized" host filter lists, nothing is blocked. In settings it says "Filter now contain 1 rule".

### Expected behaviour
There shouuld be > 1 rule (e.g. Energized Blu ~230.000 rules).

### Steps to reproduce  

1. Enable any of the "Energized" host lists
2. Check that only 1 rule was added

### Configuration
1. Blokada version: 4.5.2
2. Device model: Huawei P9 Lite
3. Android version / ROM: 7.0

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 

It seems like the host list URLs are not working anymore, e.g. https://gitlab.com/energized-protection/block/-/raw/master/blu/formats/hosts will just redirect to https://gitlab.com/users/sign_in

2.  How often does this problem happen to you?

Everytime, but started only recently

**Comment by peterroth** [comment]
[Energized](https://github.com/EnergizedProtection/) switched their URL, back to GitHub and this change isn't (yet) set in Blokada.
We enabled Steven Black's list as default for the time being, till everything settles on Energized side.
