### ISSUE TITLE
Feature request: indicate when device is connected to Blokada Tunnel

### ISSUE THREAD

**Issue by pebogufi** [blokadaorg/blokada#700]
### Actual behaviour
What happens, what malfunction do you see? Please describe as detailed and good as possible, it helps us to narrow down the scope and start debugging.

After some time (may be after beeing disconnected from internet for some time)
- Blokada is active again,  BUT
- Blokada tunnel (the paid tunnel) is deactivated and does not reactivate automatically
- I only see that if I check for it

### Expected behaviour

What I would LIKE to have:
If I have the paid Tunnel, and if Blokada is active and the tunnel is NOT active, I would like to see any kind of hint, may be in the top bar next to shield symbol / Key symbol
OR if the tunnel works display a symbol in the top bar next to shield symbol / Key symbol
---

### Configuration
1. Blokada version:  4.5.2
2. Device model:   Samsung Galaxy S7 SM-G930F
3. Android version / ROM:  Android 8.0

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
all should be curent

2.  How often does this problem happen to you?
quite often, nearly every day.

**Comment by peterroth** [comment]
Hi,

Just for clarification, is it a feature request to show an indicator that Blokada Tunnel is active, or it is an issue report that the Tunnel isn't reactivated in some cases?
The title and the body pointing to different things.

**Comment by pebogufi** [comment]
First, it is an issue report that the Tunnel isn't reactivated in some cases.
As a workaround it could help, if there would be an indicator to show the problem, when it occurs.
Sorry, for beeing unclear.

**Comment by peterroth** [comment]
One of the cases is reported earlier, for example if you turn on Airplane mode, and later turn that off. Enabling Always-on VPN in the system's settings can help to resolve it.
I'll turn this report into a feature request if you don't mind. Let me know your thoughts.

**Comment by pebogufi** [comment]
>Enabling Always-on VPN
I try that and observe.
ok to feature request.
Thanks, Peter

**Comment by pebogufi** [comment]
After seversl problems each day, now after update to 4.6.4 NO MORE problems.
Thanks s lot. 
Peter
