### ISSUE TITLE
Blokada removes manually blocked hosts and reverts original lists

### ISSUE THREAD

**Issue by NickVolt77** [blokadaorg/blokada#701]
### Actual behaviour
Blokada removed my blocked hosts and reverted deleted original lists (I removed all of them) dispite setting updates to "never". I don't recall to push "update now" or anything like it. But even if, it should not remove my blocked hosts and active first list if it was removed.

### Expected behaviour
If I remove all predefined lists and add manully my own hosts, Blokada should never revert original lists if I won't ask to do it.

### Steps to reproduce  
1. Remove all predefined lists.
2. Block some hosts manually.
3. Use for few days (1 week, maybe more)?
4. Your blocked hosts would be removed, original lists would be reverted, first list will be turned on.

### Configuration
1. Blokada version: 4.5.2 (from F-Droid)
2. Device model: Moto G7 Power
3. Android version / ROM: Stock Android

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
No app update. There was system update, but I can't recall if it was during Blokada was on my phone.

2.  How often does this problem happen to you?
Once. Then I removed Blokada. :/ But now I'm trying again.

**Comment by peterroth** [comment]
Hi,

Do you have any cache- or storage cleaner tool on the device where you experienced this issue, or did you delete Blokada's cache or storage manually? That is the only known thing that has such an effect.

**Comment by NickVolt77** [comment]
I do not remember. I doubt it but I can't tell. Anyway:
- settings should be clear (for example in "check for update every" I see "once a week" and "twice a week" on the bottom. All settings should be visible - if I don't click, I will not find "never" setting)
- when I set updates to never, all options with updates (for example "download now")  should be disabled just in case someone misclick.

**Comment by peterroth** [comment]
Never disables automatic updates, not the manual. It won't disable the buttons.

**Comment by NickVolt77** [comment]
I do not use any cleaners.
Ok, I will keep on eye this.
