### ISSUE TITLE
Localhost DNS Server

### ISSUE THREAD

**Issue by st0rmr1der1994** [blokadaorg/blokada#705]
Hello,
I have a question, regarding Blokada DNS configuration. If I have a local running DNS server on my Android device, will it be possible to add such server into Blokada DNS settings. 
I browsed source code a little and noticed that DNS servers with 127.0.0.1 are skipped and fallback addresses (1.1.1.1 & 1.0.0.1) are used instead.
Seems that it is not possible to bind to a localhost DNS server or am I wrong?

**Comment by peterroth** [comment]
Hi,
No, you are correct. You need to address a non-local IP address, so for example if your router uses 192.168.2.24, that should be possible to be addressed.
