### ISSUE TITLE
Application exceptions don't update until Blokada is restarted

### ISSUE THREAD

**Issue by szotsaki** [blokadaorg/blokada#713]
### Actual behaviour
When I add an application to the exception list Blokada says it's working, then after some seconds the notification disappears. However, the application is not added to the exception list until Blokada is restarted.

### Expected behaviour
Application is added to the exception list immediately or at least a notification is shown that I need to manually restart Blokada.

### Steps to reproduce

1. Install [Jitsi Meet](https://f-droid.org/packages/org.jitsi.meet/), an open source videoconf software to test the behaviour.
2. Turn on some host lists (e.g. Energised Blue, Social, MobileAdTrackers)
3. Start a video conference on PC on https://meet.jit.si
4. Connect to the conference with Jitsi Meet on your mobile phone and observe that no video or audio is transmitted.
5. Add Jitsi Meet to the Blokada exceptions list
6. Try to reconnect in Jitsi Meet again
7. Restart Blokada
8. Try to reconnect in Jitsi Meet again. Only this time it works.

### Configuration
1. Blokada version: 4.5.2
2. Device model: Sony XPERIA X (F5121)
3. Android version / ROM: Android 8.0.0

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 

No.

2.  How often does this problem happen to you?

Fully reproducible.

**Comment by peterroth** [comment]
Hi,

The ticket #667 aims to ensure the local VPN is restarted and rebuilt after an app is added to bypass.
