### ISSUE TITLE
Disableing request logger doesn't result in Host log not logging

### ISSUE THREAD

**Issue by Notabas-iC** [blokadaorg/blokada#719]
### Actual behaviour
Despite setting request logger to 'disabled' Blokada still logs requests to the Host log and the Dashboard log. 

### Expected behaviour
Host log should stop logging the requests to the Hostlog (and Dashboard log) when setting the status for request logger to 'disabled'.

### Steps to reproduce  
1. Set Ad blocking / Ad blocking settings -> request logger to 'disabled'
2. Access various websites (optional)
3. Check the Host log

### Configuration
1. Blokada version: 4.6.3

**Comment by peterroth** [comment]
Even after killing and restarting Blokada?

**Comment by Notabas-iC** [comment]
Yes.

**Comment by Notabas-iC** [comment]
New feature for 4.6.3, so no bug ;)
