### ISSUE TITLE
I want support for more complex locales

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#72]
Currently Blokada's dynamic (online) localised content can be only fetched for simple language tags, like "de" or "pl". Add support for ones with a country code, like "zn_CN".

**Comment by Sak94664** [comment]
Forgot to mention that I only translated Simplified Chinese(essential).And I would like to continue translating (English) into simplified Chinese,because i love this app!😁😁

**Comment by kar** [comment]
Yes there are translations started both for the Simplified and Traditional Chinese. Thank you! Just keep up your work and I'll integrate all updates in next releases, so the translations will be getting better gradually.
