### ISSUE TITLE
Can the Blokada app block ads for the YouTube app?

### ISSUE THREAD

**Issue by vyujitanaka** [blokadaorg/blokada#722]
Hi there!

I wonder if the Blokada app can block YouTube ads. If so, how do I block?

Thank you in advance!

**Comment by peterroth** [comment]
Hello,

Please refer to our Knowledgebase Article in this topic: https://support.blokada.org/hc/en-us/articles/360010458939-Ads-in-YouTube-aren-t-blocked-
