### ISSUE TITLE
I want NextDNS to be an option in the recommended DNS servers list

### ISSUE THREAD

**Issue by Mezito80** [blokadaorg/blokada#723]
This is a feature request.

**Comment by peterroth** [comment]
Hi,
Do you mean [NextDNS](https://nextdns.io/)? That requires a registration, the free access is allowed up to 300.000 DNS queries, based on [pricing](https://nextdns.io/pricing).

**Comment by naoliv** [comment]
It says "300,000 queries/month¹" where ¹ is `When exceeding the free monthly quota, NextDNS will continue to answer DNS queries like a classic non-blocking DNS service.`

That is, it will continue to resolve names.

NextDNS seems to be the fastest/best option with my current provider.

It's also one of the options that Firefox offers when using DNS over HTTPS (being Cloudflare the other one).
So basically I am using it on my browser, PC, etc without any problems (and without registering); I am only missing it on my phone with Blokada.

Could this be reconsidered, please?
