### ISSUE TITLE
DNS Server OpenNIC - Europa not working

### ISSUE THREAD

**Issue by fuessli** [blokadaorg/blokada#724]
The DNS Server List "OpenNIC - Europa" doesn't work. Both servers 82.141.39.32 / 50.3.82.162 don't answer on DNS-queries and are not listed in OpenNIC (https://servers.opennic.org/).
I use 195.10.195.195 (ns31.de) and 94.247.43.254 (ns8.he.de) as OpenNIC Servers.

**Comment by kar** [comment]
Thanks. Opennic servers have been removed now.
