### ISSUE TITLE
Blokada uses 'Default' (cloudflare) dns even when DNS is deactivated

### ISSUE THREAD

**Issue by adithya-s-sekhar** [blokadaorg/blokada#725]
### Actual behaviour
When DNS service is deactivated, blokada uses the inbuilt Default DNS server (which is cloudflare) to resolve urls.

### Expected behaviour
It should use the DNS provided by the router when it's specifically told not to resolve urls.

### Steps to reproduce  

1. Disable DNS within Blokada
2. Visit https://1.1.1.1/help to check if it's still using cloudflare instead of letting android handle it.

Is this a limitation of using a VPN?

### Configuration
1. Blokada version: 4.6.4
2. Device model: Xiaomi Redmi 5 Plus
3. Android version / ROM: Android 8.1/MIUI 11

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
Yes

2.  How often does this problem happen to you?
Always

**Comment by peterroth** [comment]
There is no "built in Default DNS". The "default DNS" is the one that the system uses (usually the Internet Service Provider's one).
The Fallback DNS is Cloudflare and that is set when the device receives a local IP address for name resolution and it can be disabled in Blokada's menu - DNS.

**Comment by adithya-s-sekhar** [comment]
Oh I am terribly sorry, didn't knew there was a fallback option underneath. This must be the stupidest issue someone raised. 😅 Sorry for wasting your time.

**Comment by peterroth** [comment]
Not at all stupid, it was something you faced and wanted to clarify. It's all OK. Happy to see it's cleared :)
