### ISSUE TITLE
host log - which app made the call?

### ISSUE THREAD

**Issue by 10000hzl** [blokadaorg/blokada#726]
It would be nice if the host log could show **which app** made a certain call that has been allowed/blocked. As of now, we only see which call is made but we don't know which app made it.

**Comment by ParmuSingh** [comment]
Agreed. Though issue#418 already exists for this. Make sure to search before opening.

https://github.com/blokadaorg/blokada/issues/418

**Comment by ps100000** [comment]
Duplicate of #418
