### ISSUE TITLE
Blokada randomly closes (or getting Closed?)

### ISSUE THREAD

**Issue by DarkenLX** [blokadaorg/blokada#73]
Blokada version 2.2.2
Steps I've tried to resolve this issue: 
1. Installed as a system app
2. Toggle Keep Alive on both in normal install and as system app. No effect.
Seems that after a certain amount of time (yet to nail down the exact amount seems very inconsistent) running blokada closes, gets closed (not by me) or killed not sure what's causing it nothing installed should. But re open & it acts like you closed it normally. :-/
Device: BLU R1 HD
OS: Android 6.0
RAM: 2GB
Root: Yes

**Comment by WulftheNordicRanger** [comment]
I've also noticed that it frequently does this when my phone locks or goes into deep sleep mode and it will say that something is wrong with my internet connection even though I have internet only turned off and it takes a really long time to start to  turn back on. 
Running the latest  version  on an Alcatel ideal with 1 gig of ram, android 5.1 and no root.

**Comment by rpeter85** [comment]
Check if your system doesn't kill unauthorised applications. On Miui, for example, I had to configure in the settings that this app shouldn't be optimised and it is allowed to start at boot.
So, check if there are battery optimisation options in your ROM and if you can add Blokada as exemption.

**Comment by WulftheNordicRanger** [comment]
The only setting I have like that  is restrict from running in the background and one of the first things I did when I installed blokada was to tell the system not to restrict it. And I don't have any task killer apps or any other apps that would stop it from running in the background.

**Comment by DarkenLX** [comment]
Update: seems to still be doing it less frequent however.. also if wifi gets turned off/disconnected or airplane mode is turned on even if online only switch is turned off.

**Comment by kar** [comment]
(check if the keep alive service is really running)

**Comment by kar** [comment]
(maybe use job scheduler to periodically check on blokada)

**Comment by DarkenLX** [comment]
Kar How do i check if the service is really running im rooted so is there like a terminal command or something?

**Comment by kar** [comment]
Ignore this, it was a note to myself

**Comment by DarkenLX** [comment]
Oh lol my bad

**Comment by kar** [comment]
3.0.0. (not the preview) will have some additional mechanisms to prevent the closing and restart if killed by the system. We'll need to test it though so if you will experience problems reopen this issue.

Make sure you activate "Keep Alive", it should really make a difference now.
