### ISSUE TITLE
blokada stops when changing the theme on android 10

### ISSUE THREAD

**Issue by igalic** [blokadaorg/blokada#732]
### Actual behaviour

When changing the theme on android 10, i get a notification from android that my always on vpn is down.

when i click into that notification, it offers me to open the vpn app on question, and once Blokada is opened, it's all fine again

### Expected behaviour

the only thing i'd expect Blokada to do is to change the theme to what the system theme was changed to, but that's not what we're here for in this bug report

### Steps to reproduce  

1. set blokada to always on in your vpn settings
2. change your device's theme
3. get this notification:
  ![Screenshot_20200610-223118__01](https://user-images.githubusercontent.com/497249/84315705-5d64ed80-ab6a-11ea-9713-b0755096a730.jpg)
4. click notification to see this dialogue 
  ![Screenshot_20200610-223107](https://user-images.githubusercontent.com/497249/84315824-7d94ac80-ab6a-11ea-8689-363150cab4d4.jpg)

### Configuration
1. Blokada version: 4.6.4
2. Device model: OnePlus 5t 
3. Android version / ROM: Android 10 / OxygenOS 

### Questions

1. Do you know about recent updates (for example system update, security patch update)? 

this has been happening consistently

2.  How often does this problem happen to you?

twice a day (which is how often a day i change the device theme)

**Comment by kar** [comment]
If you could deliver a log after the crash, I could look into it. Otherwise, it's a VERY niche corner case.

**Comment by igalic** [comment]
<summary>here's a <code>adb logcat D</code>, filtered for blokada:</summary>
<details>
<pre>
06-30 22:52:01.219  3913  3913 D NotificationListener: onNotificationPosted# sbn: 128813747, package = org.blokada.origin.alarm
06-30 22:55:09.539  1449 11200 E NotificationService: NotificationRecord is blocked. Package: org.blokada.origin.alarm isGroupBlocked: false isPreferencesImportanceNone: false isRecordImportanceNone: true
06-30 22:55:09.655  3913  3913 D NotificationListener: onNotificationPosted# sbn: 108452678, package = org.blokada.origin.alarm
06-30 22:55:12.525  1449  7555 E NotificationService: NotificationRecord is blocked. Package: org.blokada.origin.alarm isGroupBlocked: false isPreferencesImportanceNone: false isRecordImportanceNone: true
06-30 22:55:12.637  3913  3913 D NotificationListener: onNotificationPosted# sbn: 93249799, package = org.blokada.origin.alarm
06-30 22:55:15.733  8086  8086 D OPApplicationUtils: killRunningProcess--processName:org.blokada.origin.alarm uid:10254
06-30 22:55:15.737  1449  7555 I ActivityManager: Killing 11551:org.blokada.origin.alarm/u0a254 (adj 200): change screen resolution
06-30 22:55:15.742  1449  7555 W ActivityManager: Scheduling restart of crashed service org.blokada.origin.alarm/tunnel.Service in 20938ms
06-30 22:55:15.747  3913  3913 D NotificationListener: onNotificationRemoved# sbn: 147857972, package = org.blokada.origin.alarm
06-30 22:55:16.592  3913  3913 D Launcher.Workspace: updateAllIconLabelAndViewWithAnimation: shouldShow: true , textColor: Color(1.0, 1.0, 1.0, 1.0, sRGB IEC61966-2.1) , textAlpha: 255 , textVisibility: 0 , textSize = 34.0 , icon info: WorkspaceItemInfo(id=67 type=APP container=56 screen=0 cell(0,1) span(1,1) minSpan(1,1) rank=4 user=UserHandle{0} title=Blokada hidden=false dirty = false newInstallTag=null)
06-30 22:55:16.816  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:17.133  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:17.245  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:17.261  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:17.263  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.195  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.196  2542  9219 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.207  2542  9219 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.242  2542  9219 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.244  2542  9219 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.245  2542  9219 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.261  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.630  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.635  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.637  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.875  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.889  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:18.894  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.030  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.495  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.496  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.501  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.690  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.693  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.695  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.705  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.827  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.827  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:19.830  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:20.061  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:20.069  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:20.070  2542  9254 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:23.805  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:23.810  2542  9646 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:23.812  2542  9646 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:23.947  2542  9646 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:23.950  2542  9646 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:23.951  2542  9646 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:32.982  1449  6403 D OemSceneCallBlock: isCallBlockedWithUidIntent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10008000 pkg=org.blokada.origin.alarm cmp=org.blokada.origin.alarm/core.PanelActivity }, ResolveInfo{b303466 org.blokada.origin.alarm/core.PanelActivity m=0x0}, false
06-30 22:55:32.983  1449  6403 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10008000 pkg=org.blokada.origin.alarm cmp=org.blokada.origin.alarm/core.PanelActivity} from uid 10102 pid 9774
06-30 22:55:33.001  1449  1579 D OpRestartProcessManager: updateSelf :  org.blokada.origin.alarm, size : 30
06-30 22:55:33.013  1449  1603 I ActivityManager: Start proc 9775:org.blokada.origin.alarm/u0a254 for activity {org.blokada.origin.alarm/core.PanelActivity}
06-30 22:55:33.028  1449  6403 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{c621bfd token=Token{eb2f054 ActivityRecord{6193a7 u0 org.blokada.origin.alarm/core.PanelActivity t2994}}} pkgName org.blokada.origin.alarm
06-30 22:55:33.031  1449  1579 D Foreground_io: TOP_APP is ProcessRecord{2b97af9 9775:org.blokada.origin.alarm/u0a254} uid is 10254
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         **
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         ****
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         ******
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         ********
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         **********
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         ************
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         **************
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         ****************
06-30 22:55:33.091  9775  9775 V b4:main : BLOKADA         ******************
06-30 22:55:33.092  9775  9775 V b4:main : writing logs to file: /data/data/org.blokada.origin.alarm/files/blokada.log
06-30 22:55:33.169  9775 10012 V b4:gscore-workerX-1: setting content url         https://blokada.org/api/v4/content/en
06-30 22:55:33.169  9775 10012 V b4:gscore-workerX-1: url set         https://blokada.org/api/v4/full/official/repo.txt
06-30 22:55:33.170  9775 10012 V b4:gscore-workerX-1: url set         https://blokada.org/api/v4/full/official/repo.txt
06-30 22:55:33.181  9775 10012 D NetworkSecurityConfig: Using Network Security Config from resource whitelist_blokada debugBuild: false
06-30 22:55:33.183  1449  2751 E NotificationService: NotificationRecord is blocked. Package: org.blokada.origin.alarm isGroupBlocked: false isPreferencesImportanceNone: false isRecordImportanceNone: true
06-30 22:55:33.184   694 10029 D DnsProxyListener: GetAddrInfoHandler::run: {blokada.org 1086 1086 1086 984126 10254 0}
06-30 22:55:33.201  9775 10030 V b4:tunnel-main: >> setting tunnel configuration    TunnelConfig(tunnelEnabled=true, adblocking=true, wifiOnly=true, firstLoad=false, powersave=false, dnsFallback=true, report=false, wildcards=false, filtersUrl=https://blokada.org/api/v4/content/en/filters.txt, cacheTTL=86400)
06-30 22:55:33.202  9775 10030 V b4:tunnel-main: >> setting tunnel configuration    TunnelConfig(tunnelEnabled=true, adblocking=true, wifiOnly=true, firstLoad=false, powersave=false, dnsFallback=true, report=false, wildcards=false, filtersUrl=https://blokada.org/api/v4/content/en/filters.txt, cacheTTL=86400)
06-30 22:55:33.204  9775 10030 V b4:tunnel-main: >> setting filters url    https://blokada.org/api/v4/content/en/filters.txt
06-30 22:55:33.207  9775 10026 V b4:blocka-vpn-main: blokada/4.6.4 (android-29 full official arm64-v8a OnePlus-OnePlus5T touch api compatible)    
06-30 22:55:33.255   694 10029 D DnsProxyListener: reportDnsEvent{ 1086 1 0 71 blokada.org 10254}
06-30 22:55:33.395  1449  6403 E NotificationService: NotificationRecord is blocked. Package: org.blokada.origin.alarm isGroupBlocked: false isPreferencesImportanceNone: false isRecordImportanceNone: true
06-30 22:55:33.396  1449  1601 I ActivityTaskManager: Displayed org.blokada.origin.alarm/core.PanelActivity: +414ms
06-30 22:55:33.412  9775  9775 E blokada : KeepAliveService: bound
06-30 22:55:33.420  9775 10041 I chatty  : uid=10254(org.blokada.origin.alarm) ConnectivityRec identical 1 line
06-30 22:55:33.424  9775  9775 D OnePlusJankManager:  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = org.blokada.origin.alarm/core.PanelActivity--- jank level = 1
06-30 22:55:33.521  3913  3913 D NotificationListener: onNotificationPosted# sbn: 99197296, package = org.blokada.origin.alarm
06-30 22:55:33.522  3913  3913 D NotificationListener: onNotificationPosted# sbn: 78425454, package = org.blokada.origin.alarm
06-30 22:55:33.562  2542  2542 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/lib/arm64, /data/app/org.blokada.origin.alarm-ggPkewC5CS5YZ9qAyhMSVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
06-30 22:55:33.562  9775 10030 V b4:tunnel-main: loading from the persistence         /data/user/0/org.blokada.origin.alarm/files/io.paperdb
06-30 22:55:33.563  9775 10030 V b4:tunnel-main: loaded FilterStore from persistence    https://blokada.org/api/v4/content/en/filters.txt, 46
06-30 22:55:33.572  9775 10030 V b4:tunnel-main: syncing filters    https://blokada.org/api/v4/content/en/filters.txt
06-30 22:55:33.702  9775 10012 V b4:gscore-workerX-1: using gzip download         https://blokada.org/api/v4/full/official/repo.txt
06-30 22:55:34.060  9775 10012 V b4:gscore-workerX-1: using gzip download         https://blokada.org/api/v4/full/official/repo.txt
06-30 22:55:34.060  9775 10030 V b4:tunnel-main: using gzip download         https://blokada.org/api/v4/content/en/filters.txt
06-30 22:55:34.061  9775 10021 V b4:common-1: translation fetched         https://blokada.org/api/v4/content/en/filters.properties, 36
06-30 22:55:34.064  9775 10012 I chatty  : uid=10254(org.blokada.origin.alarm) gscore-workerX- identical 1 line
06-30 22:55:34.066  9775 10012 V b4:gscore-workerX-1: setting content url         https://blokada.org/api/v4/content/en
06-30 22:55:34.068  9775 10012 V b4:gscore-workerX-1: setting content url         https://blokada.org/api/v4/content/en
06-30 22:55:34.069  9775 10012 V b4:gscore-workerX-1: setting content url         https://blokada.org/api/v4/content/en
06-30 22:55:34.721  9775 10030 V b4:tunnel-main: saved FilterStore to persistence    46, https://blokada.org/api/v4/content/en/filters.txt
06-30 22:55:34.743  1449  6403 I Vpn     : Established by org.blokada.origin.alarm on tun0
06-30 22:55:34.777  9775 10030 V b4:tunnel-main: saved FilterStore to persistence    46, https://blokada.org/api/v4/content/en/filters.txt
06-30 22:55:34.816  1449  4014 E NotificationService: NotificationRecord is blocked. Package: org.blokada.origin.alarm isGroupBlocked: false isPreferencesImportanceNone: false isRecordImportanceNone: true
06-30 22:55:34.921  3913  3913 D NotificationListener: onNotificationPosted# sbn: 53317285, package = org.blokada.origin.alarm
06-30 22:55:35.305  1449  2751 E NotificationService: NotificationRecord is blocked. Package: org.blokada.origin.alarm isGroupBlocked: false isPreferencesImportanceNone: false isRecordImportanceNone: true
06-30 22:55:35.422  3913  3913 D NotificationListener: onNotificationPosted# sbn: 75117178, package = org.blokada.origin.alarm
06-30 22:55:37.043  1449  4014 E NotificationService: NotificationRecord is blocked. Package: org.blokada.origin.alarm isGroupBlocked: false isPreferencesImportanceNone: false isRecordImportanceNone: true
06-30 22:55:37.149  3913  3913 D NotificationListener: onNotificationPosted# sbn: 130341419, package = org.blokada.origin.alarm
06-30 22:55:37.833  3913  3913 D TouchInteractionService: runningTaskInfo: ComponentInfo{org.blokada.origin.alarm/core.PanelActivity}
06-30 22:55:37.847  3913  7917 D RecentTasksList: dumpTasks# id=2994, cmp=ComponentInfo{org.blokada.origin.alarm/core.PanelActivity}, uid=0, locked=false, isAppLocked=false
06-30 22:55:37.862  3913  6026 D RecentTasksList: dumpTasks# id=2994, cmp=ComponentInfo{org.blokada.origin.alarm/core.PanelActivity}, uid=0, locked=false, isAppLocked=false
06-30 22:55:37.867  1449  2942 E NotificationService: NotificationRecord is blocked. Package: org.blokada.origin.alarm isGroupBlocked: false isPreferencesImportanceNone: false isRecordImportanceNone: true
06-30 22:55:38.187  3913  3913 D TaskIcon: bind task icon: index= 6, TaskId= 2994, task= org.blokada.origin.alarm
06-30 22:55:38.249  3913  3913 D TaskIcon: bind task icon: index= 6, TaskId= 2994, task= org.blokada.origin.alarm
06-30 22:55:38.282  3913  3913 D NotificationListener: onNotificationPosted# sbn: 130746679, package = org.blokada.origin.alarm
06-30 22:55:38.293  3913  3913 D PopupDataProvider: onNotificationPosted dotShouldBeRefreshed = false, PackageUserKey = org.blokada.origin.alarm#0, containsDot = true
06-30 22:55:38.331  3913  3913 D BubbleTextView: applyDotState cn = ComponentInfo{org.blokada.origin.alarm/core.PanelActivity}, animated = false, wasDoted = false, isDoted = true, dotScale = 1.0, mDotInfo = net.oneplus.launcher.dot.DotInfo@86c9dfd
06-30 22:55:39.230  3913  3913 D TouchInteractionService: runningTaskInfo: ComponentInfo{org.blokada.origin.alarm/core.PanelActivity}
06-30 22:55:39.244  3913  3913 D TaskIcon: bind task icon: index= 6, TaskId= 2994, task= org.blokada.origin.alarm
06-30 22:55:39.403  3913  3913 D TaskIcon: bind task icon: index= 6, TaskId= 2994, task= org.blokada.origin.alarm
06-30 22:55:40.393  3913  7917 D RecentTasksList: dumpTasks# id=2994, cmp=ComponentInfo{org.blokada.origin.alarm/core.PanelActivity}, uid=0, locked=false, isAppLocked=false
06-30 22:55:40.483  3913  3913 D RemoveTaskHelper: getTaskId: pkgName= org.blokada.origin.alarm, id= 2994
06-30 22:55:40.484  3913  6026 D ActivityManagerWrapper: Task is removed: id 2994 pkgName org.blokada.origin.alarm, user:0, killAll:false
06-30 22:55:40.489  3913  6026 D ActivityManagerWrapper: Task is killed:org.blokada.origin.alarm, 0
</pre>
</details>

**Comment by igalic** [comment]
this seems to be fixed in 4.7.3, but i don't see any mention of it in the changelog, nor an update here, so maybe it's just wishful thinking in the early morning

**Comment by igalic** [comment]
this still happens on blokada 5.

**Comment by L31FY** [comment]
This is expected behavior maybe. It warms you that some apps may close and unsaved data may be lost when using a Samsung device and those themes and changing them.
