### ISSUE TITLE
(Bug) Cannot view the "about" page of user-added Hostlists

### ISSUE THREAD

**Issue by allendema** [blokadaorg/blokada#734]
### Issue
After going to Hostlists and clicking "about" in a user created Hostlist, contrary to default ones, nothing happens.

### Expected behaviour
Hostlist URL should be opened in browser.

### Steps to reproduce  
1. Go to Hostslists
2. Click on "about" of a prefered Hostlist.

### Configuration
1. Blokada version: 4.6.4
2. Device model: Pixel
3. Android version / ROM: Android 10

### Questions
1.  How often does this happen to you?
Every single time.

**Comment by kar** [comment]
This button opens up an author's website, not the bloclist link itself. If you created your own list, it has no website.

**Comment by allendema** [comment]
It would be good to open the raw link then, just to view what domains contains a given list.
