### ISSUE TITLE
Replacing the Android DNS address even when the option is disabled in Blokada

### ISSUE THREAD

**Issue by domker** [blokadaorg/blokada#735]
### Actual behaviour
If Blokada is disabled then I have my DNS address configured by router 192.x.x.x (from an internet provider)
When Blokada is enabled and the DNS change option disabled in app, the DNS address is changed anyway to 203.0.113.2 and 203.0.113.3 (IANA).

Blokada DISABLED:
![blokada-disabled](https://user-images.githubusercontent.com/4380767/84783319-65e57a00-afe9-11ea-987e-0d3dce5b3ed3.jpg)
![router_dns](https://user-images.githubusercontent.com/4380767/84783335-6aaa2e00-afe9-11ea-9559-0faa7136b072.jpg)

Blokada ENABLED:
![blokada-enabled](https://user-images.githubusercontent.com/4380767/84783379-7990e080-afe9-11ea-9f16-72c38397c863.jpg)
![changed-dns](https://user-images.githubusercontent.com/4380767/84783394-7eee2b00-afe9-11ea-8d62-9583a1a3dad8.jpg)
![whois-dns](https://user-images.githubusercontent.com/4380767/84783408-844b7580-afe9-11ea-914d-125bf84a15f7.jpg)

(sorry for the size of the screenshots, but Github I see that it doesn't support scaling in markdown)

DNS is changed by Blokada, even if another one is manually set in the WiFi connection options.

### Expected behaviour
Not changed DNS address configured by DHCP in Android options. (when DNS is disabled in app Blokada)

### Steps to reproduce  
1. Disable Blokada
2. Check DNS adress e.g. using the PingTools application.(DNS address consistent with the settings in WiFi options)
3. Enable Blokada 
4. Check DNS adress - is different despite disabling the DNS change option in the Blokada application.

### Configuration
1. Blokada version: 4.6.4 (from F-droid)
2. Device model: Xiaomi Mi5 Pro
3. Android version / ROM: 8.0.0 / MIUI.eu 11 (9.9.26) 

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
Yes, I know.

2.  How often does this problem happen to you?
Each time the Blokada application is enabled.

**Comment by peterroth** [comment]
Hi,
Turn off _Fallback DNS_ in Blokada's menu - DNS and check if then you face the same behaviour.
