### ISSUE TITLE
I want to be able to see which lists requested the block in Host Log

### ISSUE THREAD

**Issue by Porkepix** [blokadaorg/blokada#736]
In Host Log, it would be a nice feature to be able to see from which list(s) the blocking host happened.
Bonus points if it leads to the repository/commit that added here, but I don't think that's possible (rarely a repository, quite difficult to do) :)

So just know which filter is involved in this block so that user can look for more information would be a nice thing!

**Comment by peterroth** [comment]
Blokada merges all the lists you enable to filter unique entries, so it consumes less memory. As the lists are merged, Blokada doesn't track which host entry came from which list, thus, the request cannot be implemented.

**Comment by Porkepix** [comment]
> Blokada merges all the lists you enable to filter unique entries, so it consumes less memory. As the lists are merged, Blokada doesn't track which host entry came from which list, thus, the request cannot be implemented.

Only merged lists are stored? It doesn't keep a copy of unmerged ones? If it's not, would it be possible to have a search feature that perform a search in each of the used list files?

**Comment by peterroth** [comment]
No, it won't keep in memory the source lists. The goal is to use less RAM, not overutilise nor store unnecessary things there.

**Comment by Porkepix** [comment]
> No, it won't keep in memory the source lists. The goal is to use less RAM, not overutilise nor store unnecessary things there.

I didn't meant in ram, but in phone's storage, or SD card if lists are on the SD.
But it doesn't seems to be the case anyway, which is sad: that's a pain if user wants to know which list is at cause for blocking a specific domain. I think it should at least be possible to have such information in some kind of debug mode.
