### ISSUE TITLE
Blokada 4.6.4 want constantly update itself every other day - doesn't recognize is up-to-date

### ISSUE THREAD

**Issue by Snapuman** [blokadaorg/blokada#740]
### Actual behaviour
Blokada 4.6.4 on Android want every other day install a update by itself, altough your site says 4.6.4 is the latest (which I already have installed!) I have the download directly from ur site (https://github.com/blokadaorg/blokada/releases/download/4.6.4/blokada-v4.6.4.apk)
At first I did this update (like 2 weeeks ago) .. and then a few days later again .. but version remained on 4.6.4 and Blokada still wants update itself the next day when I start the app interface.

In my /data/org.blokada.origin.alarm/files/ directory there where meanwhile 14 apk's  named "blokada-update.apk" up to "blokada-update-19.apk" .. all filesize of 11.64 MB and all are identical (have checked them all with bit comparison against each other .. (at least that explains why version not change after install this updates).

These update files are all the same like the blokada-v4.6.4.apk
https://www.virustotal.com/gui/file/86e4c55ee8e36304a99156f560b3e56630b4f6d957da7b6a86643636a4c673d9/detection/f-86e4c55ee8e36304a99156f560b3e56630b4f6d957da7b6a86643636a4c673d9-1592593585

It's very annoying when I start blokada the next day (usually to look into the block-log) that I always  first have to denie the update install and then restart the whole interface again. 😕

I already contacted your staff @Facebook, got the hint to "Clear Blokada’s cache and storage, then restart the application. It may help to identify your version correctly. If it doesn't solve your issue, open a ticket on github [...]"

So I did. (stopped Blokada, cleared cache and app data, started Blokada fresh, applied settings again manually).
Sadly it hasn't changed the behavior, 5 minutes later Blokada said again it want to update itself and downloaded again the blokada-update.apk. So here is my report.

Btw, when I check In Blokada's about menu manually, it always say(d) that Blokada is up-to-date!

### Expected behaviour
No self-update pop-up behavior and download when app is up-to-date.

### Steps to reproduce  
I don't know?

### Configuration
1. Blokada version: Android 4.6.4
2. Device model: Samsung Galaxy S7 Edge (SM-G935F)
3. Android version / ROM: Android 8.0.0

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
Not since I installed Blokada (System IS on latest patches)

2.  How often does this problem happen to you?
like every other day

**Comment by kar** [comment]
If it downloads the apk, it means the operating system's download manager must be thinking the apk did not download before, and it keeps retrying. Sounds more like a quirk with the OS. You could try to uninstall and install again. Could you check your exact version string in the menu -> About?

**Comment by peterroth** [comment]
@Snapuman didnl you have the chance to test what Karol recommended?
