### ISSUE TITLE
[Feature Request] Add separate and extra buttons in host logs section

### ISSUE THREAD

**Issue by tur1ngb0x** [blokadaorg/blokada#741]
**Actual Behaviour:**

- Blokada App > Settings > Ad-blocking > Host Log.
- The "Search" button and "Clear host log" button are located quite close to each other.
- This sometimes results in accidently clearing host log when trying to search.

**Expected Behaviour:**
- There should be a well-defined buttons/region for "Search" and "Clear host log" function.
- Add extra buttons for toggling between "Allowed" & "Blocked" hosts.
- This should result in better user experience.
- I have attached a sample screenshot below
![blokada-suggestion](https://user-images.githubusercontent.com/25666761/85566803-fc4f1680-b64d-11ea-998a-dfbea68f426f.png)

**Configuration:**
Blokada Version: 4.6.4
Device Model: Realme 6 (RMX2001)
Android Version: Android 10 (Realme UI v1.0)

**Comment by nitramwin** [comment]
Adding a search button would be great!
