### ISSUE TITLE
Using Private DNS fuction on Android 9 blokada losses connection (no connect)

### ISSUE THREAD

**Issue by Fredy-1422** [blokadaorg/blokada#743]
### Actual behaviour
Setting the private DNS option to 1dot1dot1dot1.cloudflare-dns.com causes blockada to fail to see connectivity while this option is set.

### Expected behaviour
Private dns and blockada should not conflict with each other. 

### Steps to reproduce 

1.Set Private DNS to 1dot1dot1dot1.cloudflare-dns.com
2.Start Bockada
3.Launch Web Browser
4.Go To Random Website

### Configuration
1. Blokada version:4.6.4
2. Device model: LG Q7 Plus 
3. Android version / ROM: Android 9

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
Yes, the system did have an update from T-mobile 2 weeks ago

2.  How often does this problem happen to you?
Frequently, unable to do any internet stuff while blokada is active.

![Screenshot_20200626-115830](https://user-images.githubusercontent.com/20887687/85877888-d76db700-b7a5-11ea-9345-c461ec92d42f.png)
![Screenshot_20200626-120055](https://user-images.githubusercontent.com/20887687/85877891-d89ee400-b7a5-11ea-88c7-34e7e4561d2b.png)
![Screenshot_20200626-120839](https://user-images.githubusercontent.com/20887687/85877893-d89ee400-b7a5-11ea-9481-6720053b2095.png)

**Comment by peterroth** [comment]
It is because Private DNS, in reality, encrypts DNS requests, thus, Blokada cannot function properly. It's a known issue and DoH/DoT technology will be supported in an upcoming version of Blokada.
