### ISSUE TITLE
Why do DNS servers not work with WLAN?

### ISSUE THREAD

**Issue by Matzeeee** [blokadaorg/blokada#744]
Thanks for reporting issues back to Blokada! Please follow few simple rules:

- **Before** you go ahead and record the bug you found, we would like to ask you to take a look on our [Knowledgebase site](https://support.blokada.org). Maybe it is already solved and the solution is provided there.
- Use search here, on GitHub, to validate if your issue isn't already reported
- Read answers to common questions at http://go.blokada.org/faq
- Having a problem with a particular app? Maybe we know already, check http://go.blokada.org/issue_app
- Blokada not working at all? Maybe your device has known issues, check http://go.blokada.org/issue_device
- Reporting a bug? Your title must answer a question "What does not work for you?" (example: "Blokada randomly closes after few days", but not, "It doesn't work"). Also make sure you follow the rest of the template and provide complete information.
- Requesting a feature? Take a look around [here](https://github.com/blokadaorg/blokada/issues?q=is%3Aissue+is%3Aopen+label%3Atype-F) if that isn't yet requested. Your title must be a full sentence starting with "I want" (example: "I want a widget for turning filtering on/off", but not, "Tasker support"). You can skip the rest of the template.

### Actual behaviour
What happens, what malfunction do you see? Please describe as detailed and good as possible, it helps us to narrow down the scope and start debugging.

### Expected behaviour
What would you expect to happen instead of the one you see?

### Steps to reproduce  
Let us know how can we get the same result that you have. If it happened only once, please check if you can get the same misbehaviour again. Don't report one-time-only glitches.

1.
2.
3.
4.

### Configuration
1. Blokada version:
2. Device model:
3. Android version / ROM:

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 

2.  How often does this problem happen to you?

**Comment by peterroth** [comment]
@Matzeeee could you fill out the form? That can help to narrow down the issue you are facing. Without that, it'll be a long guess work.

**Comment by Matzeeee** [comment]
Some applications (email, calendar) and websites dont work (no onnection) with WLAN and alternative DNS server (OpenDNS,...).
I would like to understand why this DNS servers dont work on WLAN.
Thanks.

Blokada 4.6.4
Samsung Galaxy S7
Android 8.0

**Comment by peterroth** [comment]
The given/selected DNS server isn't available on WLAN, therefore, no name resolution is done and because the system doesn't know the IP address of the server you want to resolve, it cannot access the service (e-mail, calendar, etc). Your Internet Service Provider (shortly ISP) can give you more information why the DNS server is unavailable on their internet line.
