### ISSUE TITLE
USB tethering: Blokada 4.6 block network traffic

### ISSUE THREAD

**Issue by sputnick-dev** [blokadaorg/blokada#752]
### Actual behaviour
I can't ping any host nor IP from my Linux box when USB tethering is active and Blockada is enabled

If I disable Blockada, ping works.

I have another device, which works even with Blokada enabled.

### Expected behaviour
I expect network connectivity to work

### Steps to reproduce  
 - plug USB cable
 - enable USB tethering by hand or via adb `adb shell svc usb setFunctions rndis`
 - run `dhclient usb0` on linux box
 - ping 1.1.1.1 # does not ping

```
$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
From 192.168.42.129 icmp_seq=1 Destination Net Unreachable
^C
--- 1.1.1.1 ping statistics ---
5 packets transmitted, 0 received, +1 errors, 100% packet loss, time 63ms
```

### Configuration
1. Blokada version: 4.6
2. Device model: Samsung Galaxy J5 aka SM-J500FN
3. Android version / ROM: LineageOS 16

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
no recent update

2.  How often does this problem happen to you?

every times

**Comment by ps100000** [comment]
This is nothing new. It seems every manufacturer does tethering a bit different. In some cases people report that they have no internet connection over tethering, in other cases they have internet but Blokada can't filter the traffic and there are also reports of internet and adblocking working just fine. Not much we can do about this. If you have some idea how we could influence this behavior I would be glad to know but for now you can just hope for a OS update that fixes it for you. :)
