### ISSUE TITLE
You have no filters configured check your adblocking and wifi

### ISSUE THREAD

**Issue by 0pLuS0** [blokadaorg/blokada#754]
### Actual behaviour
What happens, what malfunction do you see? Please describe as detailed and good as possible, it helps us to narrow down the scope and start debugging.

After I installed Blokada, I turned on DNS and picked DNS.WATCH then I receieved a popup message at the bottom of the screen saying;

```You have no filters configured check your adblocking and wifi```

### Expected behaviour
What would you expect to happen instead of the one you see?

Not to see this message?

### Steps to reproduce  
Let us know how can we get the same result that you have. If it happened only once, please check if you can get the same misbehaviour again. Don't report one-time-only glitches.

1. Installed F-Droid
2. Installed Blokada
3. Ran Blokada
4. Enabled Blokada
5. Enabled DNS

### Configuration
1. Blokada version: 4.6.4
2. Device model: OnePlus 5T
3. Android version / ROM: OxygenOS 9.0.11

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 

Not sure the question here, yes I know about system updates, patches etc., not sure I'm understanding the point of this question...

2.  How often does this problem happen to you?
Every time I play with the DNS, disable and enable it...

I also have a OnePlus 8 I installed Blokada on, through F-Droid and I never saw this message on that phone, so not sure why I'm seeing it on the OnePlus 5T?

```Ad blocking is active``` I assumed I didn't need to adjust/touch anything here? As for WiFi, I'm not sure what this message is implying to do? Hmm

THANKS

**Comment by Notabas-iC** [comment]
Hey there,
currently Energized are maintaining their servers. Please select another Host list. For example Steven Black Unified or Goodbyeads, which aren't hosted by Energized. You then should be able to configure Blokada without problems again:)

**Comment by 0pLuS0** [comment]
I've only started using Blokada, ok so by default, it doesn't need any settings changes? I'm assuming by what you're saying, because of the maintaince, we switch...

If there are server issues in the future, where can we find out about this, to stay on top of it, in case I/we need to change servers again?

THANKS

**Comment by Notabas-iC** [comment]
You can use Blokada with default settings and it will work:) If you want to dig in deeper I recommend checking out our forum community.blokada.org, there are Blokada configuration posts (with different intentions on blocking content) that might be interesting for you. Or just ask which setup others would recommend to you:)

Which Host list(s) you select is up to you. Here is a guide on Host list selection: https://community.blokada.org/t/host-list-selection-in-blokada/160.

Energized has a TG channel: https://t.me/energizedprotectionupdates, Goodbyeads has a TG chat: https://t.me/goodbyeads. And usually if it's a longer time period out of maintainance you will see news in our forum.

You are very welcome:)

**Comment by 0pLuS0** [comment]
Funny I forgot about Host Lists for a sec there... LOL

I actually used Steven's before in Linux;

https://github.com/StevenBlack/hosts

THANKS
