### ISSUE TITLE
mx player won't work with blokda on

### ISSUE THREAD

**Issue by ghajini** [blokadaorg/blokada#756]
Thanks for reporting issues back to Blokada! Please follow few simple rules:

### Actual behaviour
MX player search section won't work(requires internet) 

### Expected behaviour
Search work
All app online functions work with blokda on

### Steps to reproduce  

1.open mx player with blokda on, internet on
2.navigate to search bar to bottom right
![Screenshot_2020-07-20-18-42-47-635_com mxtech videoplayer ad](https://user-images.githubusercontent.com/20338483/87941639-0e8b6b80-cab9-11ea-9a04-db389259c280.png)

3.try to search anything 
4.throws no internet error

![Screenshot_2020-07-20-18-12-04-845_com mxtech videoplayer ad](https://user-images.githubusercontent.com/20338483/87941190-5bbb0d80-cab8-11ea-80a5-dd79c507a9cf.png)

### Configuration
1. Blokada version: 4.7.3
2. Device model: redmi 
3. Android version / ROM: 7.1.2

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 

🤔
2.  How often does this problem happen to you?

Always

**Comment by animeking9901** [comment]
It would appear that a domain is being blocked that should not be blocked please check your host log list and see if anything should be unblocked immediately after attempting to search

**Comment by ghajini** [comment]
I just whitelisted `androidapi.mxplay.com` ,it works now

**Comment by animeking9901** [comment]
Glad to hear it!
