### ISSUE TITLE
I want to keep my lists if I delete all lists from memory

### ISSUE THREAD

**Issue by m-terlinde** [blokadaorg/blokada#759]
### Actual behaviour
If I drop the filter lists in the ad blocking section, my self chosen list entries get deleted in the meta list as well. Even though the description doesn't indicate it.
I need to manually re-enter all own lists again.

### Expected behaviour
Just delete the list from the internal memory and leave the entry intact.

### Steps to reproduce  
Let us know how can we get the same result that you have. If it happened only once, please check if you can get the same misbehaviour again. Don't report one-time-only glitches.

1. Enter a manual blocklist
2. Hit the clean-up button
3. Check, if the manual entry is still there

**Comment by ps100000** [comment]
The text for the slot literally says that "Drop" will delete all entries and reload the defaults:
https://github.com/blokadaorg/blokada/blob/fbb6394ae12a25fd7ed5d88ac7b171a711b9412d/app/src/ui-blokada/res/values/strings_panel.xml#L144

**Comment by m-terlinde** [comment]
Well then the German translation is wrong.
It says "and deselect all entries". I will update the translation on Crowdin later on.

Nevertheless, I have the feature request, that this button just deletes the downloaded lists on the storage. I see no reason, why it should delete manual entries.

This would solve my problems in #758.

**Comment by ps100000** [comment]
Like I said it just deletes custom entries if you tell it to do so. The lists in storage aren't changed by any of the 2 options. They just update the entries you are able to choose from.  If you want to force an update of the lists on disk then just click "Download lists now".

**Comment by m-terlinde** [comment]
Thanks for the explanation. I hope the updated German translation will make it into the next version.
