### ISSUE TITLE
Changing the Excluded app not working when the App is Active

### ISSUE THREAD

**Issue by AndRo-Marian** [blokadaorg/blokada#761]
I don't think is a bug. More an enchant but i update anyway.

### Actual behaviour
When adding or removing an app from Excluded apps when the app is Activated the app is not Bypassing immediately. 

### Expected behaviour
The app to be allowed or blocked without to stop and re-enable the app. 

### Steps to reproduce  
Enable the blocking.

1. Enter the Excluded apps and Bypass an app. 
2. Enter the Bypassed app and the Ads still blocked. 

### Configuration
1. Blokada version: 4.7.3
2. Device model: P10 Lite WAS-LX1
3. Android version / ROM: 8

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
No

2.  How often does this problem happen to you?
Not sure is a problem.

**Comment by ps100000** [comment]
Please change your issue so it follows the template for bugs.

**Comment by peterroth** [comment]
It happens because the VPN configuration changes and Blokada must reinitialise itself. Untill that happens, ads are being blocked.
