### ISSUE TITLE
I want the dashboard animations and layout to be changed

### ISSUE THREAD

**Issue by AndRo-Marian** [blokadaorg/blokada#762]
1. Not sure why but are some texts / font that are flashing when opening the app, activate / deactivate.
    = Not like it.
2. Where the options button is.
   - Has a weird curve.
   - The top and bottom space between Settings icon is too big.
   = Would be better in my opinion if is more a straight line and the icon has a space like a normal title bar.

**Comment by ps100000** [comment]
As you are the only one requesting these changes this won't be changed for now. If a lot of people feel the same way and hit +1 on this it might be taken into consideration.

**Comment by peterroth** [comment]
@AndRo-Marian you mean the iOS version's or the Android version's UI?

**Comment by AndRo-Marian** [comment]
> @AndRo-Marian you mean the iOS version's or the Android version's UI?

Android

**Comment by peterroth** [comment]
Android version't UI will be redesigned, following the iOS current setup and layout. Check the screenshots about the iOS version to see how it will look like on Android too :)

**Comment by AndRo-Marian** [comment]
I like that more.

**Comment by peterroth** [comment]
Well, you can give it a try: [v5 is available for testing](https://community.blokada.org/t/blokada-5-for-android-promoted-to-public-beta/2275).
