### ISSUE TITLE
Host lines with end-line comments are ignored

### ISSUE THREAD

**Issue by Deafm4n** [blokadaorg/blokada#766]
### Actual behaviour
Host file lines that contain a comment at the end seem to get ignored and the domains stay unblocked.

Some randomly picked example lines (from [StevenBlack's Unified Hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts))
`0.0.0.0 www.adultfriendfinder.com  #[Troj/Small-AG][Adware-Adroar.dll]`
`0.0.0.0 adultfriendfinder.com  #[Tracking.Cookie]`
`0.0.0.0 cc.iwon.com  #[iWon Progressive Counter]`
`0.0.0.0 sitestats.com  #[Tracking.Cookie]`

Some other random examples (from [Clefspeare13's pornhosts](https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts)):
`0.0.0.0 sxyprn.com	# Porn domain from Clefspeare13 list`
`0.0.0.0 e621.net	# Porn domain from Clefspeare13 list`
`0.0.0.0 exhentai.org	# Porn domain from Clefspeare13 list`
`0.0.0.0 hairymoms.net	# Porn domain from Clefspeare13 list`

### Expected behaviour
These domains should be blocked, as the lines are clearly valid and not commented out.

### Steps to reproduce  
1. Add a hosts list containing some lines ending with a comment
2. Try to visit the domains mentioned in these lines

### Configuration
1. Blokada version: 4.7.3
2. Device model: Huawei P20 Lite
3. Android version / ROM: 9.1

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
September 2019 security patch

2.  How often does this problem happen to you?
It happens every time, with every host file entry that ends with a comment.

**Comment by peterroth** [comment]
Blokada is a host based blocker, this is why the comments are ignored. It works as expected.

**Comment by Deafm4n** [comment]
@peterroth Comments at the end of the line following the domain names are valid according to the specification of the hosts file and lines containing them should not be ignored.

An excerpt from the Linux hosts manpage:
`Text from a "#" character until the end of the line is a comment, and is ignored.`
An excerpt from the FreeBSD hosts manpage:
`A '#' indicates the beginning of a comment; characters up to the end of the line are not interpreted by routines which search the file.`
An excerpt from the beginning of the default Windows hostfile:
`# Additionally, comments (such as these) may be inserted on individual`
`# lines or following the machine name denoted by a '#' symbol.`

According to all of these, a comment can be at the end of the line, and stuff before the comment should be read by the parser, therefore lines such as the following one shoudn't be ignored:
`0.0.0.0 www.adultfriendfinder.com #[Troj/Small-AG][Adware-Adroar.dll]`

Based on the specification, the `0.0.0.0 www.adultfriendfinder.com` part should be parsed, which currently is not the case. 
The parser makes a wrong assumption about comments being possible only at the beginning of the line, while according to the specifications of the file in at least three major operating systems, a comment can be at any place and the text to the left of the comment should be considered.

**Comment by Deafm4n** [comment]
Out of the default filter lists, the following ones are affected:

Filter list | Affected line count
--- | --- 
StevenBlack Fake News, Gambling, Porn | 726
StevenBlack Unified Porn | 724
MVPS | 412
StevenBlack Unified | 404
Dan Pollock's hosts file | 93

<details>
<summary>The script used to check this</summary>

```python
import requests

filter_url = 'https://blokada.org/api/v4/content/en/filters.txt'
prop_url = 'https://blokada.org/api/v4/content/en/filters.properties'

filters = [d.strip().splitlines() for d in requests.get(filter_url).text.strip().split('\n\n')]
filter_names = {
    a[:-5]: b for a, b in (d.split(' = ') for d in requests.get(prop_url).text.strip().splitlines())
    if a.endswith('_name')
}
result = {}

for f in filters:
    if f[5] == 'link':
        hosts_file = requests.get(f[6]).text
        count_bug = 0
        for line in hosts_file.strip().splitlines():
            if not line.startswith('#'):
                if '#' in line:
                    count_bug += 1
        if count_bug > 0:
            result[filter_names[f[1]]] = count_bug

print('Filter list | Affected line count')
print('--- | --- ')
for fname, count in sorted(result.items(), key=lambda x: x[1], reverse=True):
    print(f'{fname} | {count}')
```
</details>

**Comment by Deafm4n** [comment]
I also made a code example, illustrating the issue: https://pl.kotl.in/U359f13N5

**Comment by ps100000** [comment]
This issue is valid and should only be closed after the PR fixing it was merged.
P.S. I'm sure @peterroth just misunderstood your issue. Thanks for keeping calm and explaining your issue in such detail. :)
