### ISSUE TITLE
cant build the project 

### ISSUE THREAD

**Issue by sumeet-goibibo** [blokadaorg/blokada#77]
cant build the project ,as it cannot find '../version.gradle' file. need help to setup. 

Error:(3, 0) Could not read script '/Users/sumeet/AndroidStudioProjects/blokada/version.gradle' as it does not exist.

I am using  Android Studio 3.0
Build #AI-171.4408382, built on October 20, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

my gradle version is gradle-3.4.1

**Comment by Jpjob314** [comment]
Same here

The reference is in gitignore https://github.com/blokadaorg/blokada/blob/master/.gitignore#L3

**Comment by kar** [comment]
As a quick fix add this to `version.gradle` under project root

`
ext {
    extVersionName = "2.2.3"
    extVersionCode = 29
}
`

**Comment by sumeet-goibibo** [comment]
@kar problem is there is no version.gradle file in this repo.

**Comment by kar** [comment]
It's by design. This file would create merge conflicts and such. Just create a new file.
