### ISSUE TITLE
Feature request: IPv6 support

### ISSUE THREAD

**Issue by Kyhze** [blokadaorg/blokada#770]
Why is there no IPv6 support in 2020? 
DNS66 does it and plenty others. It shouldn't be a very difficult (optional) feature to add and would be greatly appreciated.
There are many services I can't access when Blokada is on due to this. So I have to temporarily disable it in order to access IPv6 hosted services, which is a hassle. It would be very nice to have such a simple feature included with Blokada.

**Comment by LanikSJ** [comment]
https://community.blokada.org/t/blokada-changelog/149

**Comment by Kyhze** [comment]
I'm confused. Am I missing something? I don't see anything in the changelog... 
And I assume the second link is a preview that contains the said feature then? 
Can you confirm? Thanks!

**Comment by LanikSJ** [comment]
The new 5.x beta has the IPv6 support. It's not fully baked yet, but I can confirm it supports IPv6.

Does that answer your question?

**Comment by Kyhze** [comment]
Ah! Thank you! I does indeed! Sorry for opening this issue then. I didn't know it was a planned feature. That's awesome. :) I'll be closing this now.

**Comment by LanikSJ** [comment]
No problem 👍 just like you I came here looking for the same answer. It took me a while to find the answer in one of the community posts.
