### ISSUE TITLE
YouTube app search return less results

### ISSUE THREAD

**Issue by andreapx** [blokadaorg/blokada#774]
### Actual behaviour
If Blokada is active, the search results on the YouTube return much less results and no channels at all.

### Expected behaviour
I would expect to see no difference in the YouTube app result if Blokada is active or not

### Steps to reproduce  
Let us know how can we get the same result that you have. If it happened only once, please check if you can get the same misbehaviour again. Don't report one-time-only glitches.

1. Enable Blokada
2. Open YouTube app
3. search for "last week tonight" (for example)
4. The channel "Last Week Tonight" is not present and the videos in the results are pretty old (except some)
5. Disable Blokada
6. search for "last week tonight" (for example)
7. You will see the "last week tonight" channel and more recent videos

### Configuration
1. Blokada version: 4.7.3 but I've had this problem with older version too
2. Device model: OnePlus 6T (A6013)
3. Android version / ROM: 10 / OxygenOS 10.3.5

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
I've had this problem with different version of Android and Blokada

2.  How often does this problem happen to you?
Always

**Comment by peterroth** [comment]
Which lists are enabled for you? I use Energized Basic, Regional, Phishing Army, DuckDuchGo, Social and the coin blocker lists, for me Youtube returned not only a video that was uploaded 12 hours ago but the channel as well.

**Comment by NoNamePro0** [comment]
At best, remove 1 list, check if it works. If not, remove one other, then you have the bugged list.

So it's not a Blokada issue, it's from the ad list.

**Comment by andreapx** [comment]
> At best, remove 1 list, check if it works. If not, remove one other, then you have the bugged list.
> 
> So it's not a Blokada issue, it's from the ad list.

I've had just the "AdGuard DNS (Family)", I've tried with others and I haven't noticed the problem anymore.
But...how could a DNS change the result of a YouTube search???

**Comment by bermeitinger-b** [comment]
I don't know the lists but maybe the aforementioned "Family" list redirects request to the child-safe domain of Youtube.

**Comment by peterroth** [comment]
Seems the DNS server change solved the issue :)
