### ISSUE TITLE
excluded/whitelistet app won't work 

### ISSUE THREAD

**Issue by ckals** [blokadaorg/blokada#777]
I Use a Synology NAS at home to backup my phones photos etc.
The Apps uses a dns hostname to resolve the internal (if in wifi at home) or external ip to the NAS.
When Blokada is active, i can not use the apps anymore. 
I whitelisted the apps but still its seems that they cannot resolve the FQDN to the right IP. 
When i blokada disable its working as expected

**Comment by peterroth** [comment]
Please kill/stop Blokada and restart it. Sometimes Blokada doesn't recognise there's a new bypassed app.
Let us know it if helped.

**Comment by ckals** [comment]
Tried that already
Even after a restart of the whole phone the problem is the same.

**Comment by peterroth** [comment]
Odd. May I ask you to disable "Fallback DNS" in the DNS section and try again?

**Comment by ckals** [comment]
I checked it today again now the app is working as expected, without the Fallback DNS disabling...
IDK what it was kinda strange
Thx for your help anyway
