### ISSUE TITLE
Blokada blocks DoH queries

### ISSUE THREAD

**Issue by RichardEb** [blokadaorg/blokada#778]
Blokada blocks DNS over HTTP requests. I have setup a "private dns" server in the android system configuration. (no root) I used dns.adguard.com as my custom DoH server. Unfortunately after that Chrome can't resolve any DNS lookups. If I disable Blockada the requests are resolved properly. I tried to whitelist dns.adguard.com in blokada but with no luck

I have a Huawei P20 Lite

**Comment by peterroth** [comment]
Blokada v4 and v5 don't (yet) support DoH nor DoT queries.
v5 will ship this feature, stay tuned ;)

**Comment by RichardEb** [comment]
@peterroth i think you don't understand the problem. I DONT want to have DoH support. I just want that blokada doesn't BLOCK the request.

There is no technical reason why blokada should drop DoH queries. Also Blokada don't have to have a special DoH support for this. DoH is just a HTTPS request. Blokada just don't have to DROP it.

**Comment by RichardEb** [comment]
@peterroth please reopen

**Comment by peterroth** [comment]
Blokada doesn't check (bypasses) the HTTPS traffic (DOH uses HTTPS), as that is encrypted, Blokada can't read the traffic. My best bet is that the VPN implementation is buggy.
Did you try this situation while another VPN application was running? Did you set any DNS server in Blokada?

**Comment by RichardEb** [comment]
@peterroth A buggy VPN implementation seems possible. Unfortunately I don't have a VPN service to test with. Can you suggest any free VPN service/app for the test?

I tried it with and without DNS Server enabled in blokada.
