### ISSUE TITLE
"A file from smartlists.host" entry in Host Lists missing description 

### ISSUE THREAD

**Issue by Gliptal** [blokadaorg/blokada#779]
### Actual behaviour
The Host Lists contains an entry named "A file from smartlists.host" that lacks a description.

![Screenshot_2020-09-13-00-01-52-865_org blokada origin alarm](https://user-images.githubusercontent.com/3907646/93006526-80ce7880-f55d-11ea-823b-9bdf3d232374.jpg)

### Expected behaviour
The entry is hidden, or a description is added. 

### Steps to reproduce  
1. Open the Ad Blocking Host Lists in the app settings. 
2. Scroll to the aforementioned entry.

### Configuration
1. Blokada version: 4.8.3
2. Device model: Xiaomi Redmi Note 6 Pro
3. Android version / ROM: MIUI Global 11.0.5

**Comment by m-terlinde** [comment]
Which version do you run? I'm on 4.8.3 and don't see this entry in my host lists.
I think I saw this entry in an old version, but I'm quite not sure.

You would help us a lot, if you fill out the issue template.

**Comment by Gliptal** [comment]
> Which version do you run? I'm on 4.8.3 and don't see this entry in my host lists.
> I think I saw this entry in an old version, but I'm quite not sure.
> 
> You would help us a lot, if you fill out the issue template.

I've update the OP.

**Comment by ps100000** [comment]
I would assume you had some older version installed where this entry was added by mistake. It shouldn't be a problem if you delete it and it shouldn't reappear afterwards.

**Comment by Gliptal** [comment]
Thanks, I've deleted the entry!
