### ISSUE TITLE
Add a "How it works" description

### ISSUE THREAD

**Issue by piu130** [blokadaorg/blokada#78]
On first start the app asks to make a VPN connection. On first look it looks like the app leads all traffic over a server but I think the app it-self is the VPN right?

Could you add a "How it works" section to the `README.md` or somewhere else, so the users doesn't have to look in the code?

**Comment by kar** [comment]
Definitely

**Comment by j-nix** [comment]
I'd like to help out with this one.

**Comment by kar** [comment]
http://blokada.org/content/en/help.html
