### ISSUE TITLE
I want a reduction of dependency on Energized lists

### ISSUE THREAD

**Issue by DandelionSprout** [blokadaorg/blokada#781]
### Actual behaviour

I've kept an eye on the Energized Protection project in the past few months, and I'm seeing that it's not as frequently maintained as it ideally should've been, considering that Energized Blu is currently the sole list to be enabled by default on new Blokada installations.

The current in-app description of Blu also fails to point out that it's [an amalgamation of 48 lists](https://github.com/EnergizedProtection/block#packs-2) (+ 1 whitelist), a fact that also makes it fairly difficult for issue reporters to figure out the source of specific entries in Blu, as well as in Basic.

Sometimes, any of the 48 source lists themselves could become a problem for Energized, especially after it was figured out a few weeks ago that Blu and Basic was (and for the most part still is) blocking Falun Gong info sites due to the political beliefs of *neoHosts Full*, whose entries have been used by Energized for quite some time now.

Blokada's settings also doesn't properly explain that only one of Spark, Blu, or Basic should be used at the same time, since many of Energized's lists are tiers that include all entries from the lists of the lower tiers (Spark is tier 1 and smallest, Blu is tier 3, and Basic is tier 4). I can only presume that many end-users are using all 3 of those lists, when only Basic would've been needed to be used in such cases.

Currently (as of the summer of 2020), requests for domain removals on Energized's GitHub repo take around 1½\~5 weeks before they're taken care of; and requests for syntax error correction (such as when `rehs..hu` with 2 dots began showing up in Energized Regional, which seems to have been fixed now), as well as ones for (re)moving a source list, take 2\~9 months. The efforts of enthusiasts like me and *badmojr* to speed up the latter category in particular, turned out to have been for nought because changes to the build scripts on GitHub are not actually being used by Energized's list generator script(s).

### Expected behaviour

A reduced dependency on at the very least Energized Blu (possibly replacing it with Blu Go on new installations), more focus (i.e. turning on by default) on singular lists that receive pretty frequent maintenance, and opening up for adding more new lists to the Blokada settings (especially in order to have more than one regional list in it).

### Steps to reproduce  
Let us know how can we get the same result that you have. If it happened only once, please check if you can get the same misbehaviour again. Don't report one-time-only glitches.

1. Reinstall Blokada.
2. Go to the blocklist menu.
3. See that Energized Blu is the sole list to be turned on, and is also branded as "(recommended)".
4. Head over to a web browser or text editor, and view the contents of https://block.energized.pro/blu/formats/domains.txt in some way.
5. Text-search `guangming.org`, a Falun Gong infosite.
6. See that it is (at the time of writing) present in that list.

### Configuration
1. Blokada version: 4.8.3 (android-28 community release arm64-v8a motorola-parker touch api compatible)
2. Device model: Motorola One Zoom
3. Android version / ROM: 9.9, stock

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 

PPHS29.59-51-13 (Security patch for 1st of July 2020)

2.  How often does this problem happen to you?

I would say 'Pretty often', considering it affects Blokada (re)installations and such.

**Comment by animeking9901** [comment]
I mean it IS open source and I haven't seen anyone else complain about
it,so for now you COULD roll your own with different defaults or even your
own list set! The fact that a host list is blocking those pages should say
a lot about trustworthiness imo

**Comment by animeking9901** [comment]
And this is coming from someone who doesn't even know who this politician is

**Comment by DandelionSprout** [comment]
Essentially, Falun Gong is a spiritual+Buddhist group that emerged from PR-China in the 90's. However, ever since they decided to stand up against its government, the PR-Chinese government quite literally wants their heads on a stake, to the sheer confusion of the rest of the world who see very little wrong with them.

**Comment by animeking9901** [comment]
While I don't know the full story I feel like blocking his content is
counterproductive,but I nor Blokada make the lists,I'd poke at Energized if
that at least gets you in the right direction. Can always strip those hosts
from the file on PC,then copy to phone and import as well

**Comment by davidpiano** [comment]
IMO this issue is trying to cover 2 different things that don't belong together and get in each other's way. First item: There's a large and complex list used by a lot of people, that probably needs better maintenance. Second item: Someone has a political/religious disagreement with some items on that list. 

My feeling (and it's only my feeling, and I don't have any authority) is that the political/religious disagreement doesn't seem like a Blokada issue to me - more like a personal disagreement with the compiler of one individual list. If I disagreed with a list compiler over such an issue, I'd probably want to stop using that particular list, because the same person is likely to make more decisions I disagree with in the future.

**Comment by DandelionSprout** [comment]
Essentially, I intended for this thread to be about "Maybe relying very heavily on Energized Blu Protection on new/casual setups may have its drawbacks", with various arguments for such a belief.

Admittedly I'm unsure how to word it according to the Blokada community's unwritten(?) norms. Similar list-maintenance problems in uBlock Origin and Adblock Plus would have (and has) raised some eyebrows in their communities, so I took a guess that it worked the same way here. 😅

**Comment by davidpiano** [comment]
I don't know any of the norms, it was my personal opinion only.

**Comment by kar** [comment]
Good input. We have been open for lists suggestions, since uhm, forever. Just propose something better to be used instead, or to be added to the app default blocklists, and we will add it. Energized used to be the most universal and updated, but things change.

**Comment by DandelionSprout** [comment]
I needed a couple of days to figure out **which** exact lists to suggest, to test out a couple of promising international lists, and to see which lists that wouldn't be part of Blu Go, but here is my recommendation blueprint:

### Global
* Make *Energized Blu* no longer enabled by default.
* Replace the version of *Peter Lowe's List* with [the wildcard-domain version](https://pgl.yoyo.org/as/serverlist.php?hostformat=adblock;showintro=1&mimetype=plaintext) and enable it by default.
* Add *[Energized Blu Go](https://block.energized.pro/bluGo/formats/domains.txt)* and make it a default list.
* Add *[Block List Project: Ads](https://raw.githubusercontent.com/blocklistproject/Lists/master/ads.txt)*.
* Add [*Spam404*'s domains version](https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt).
* Consider adding *[Anudeep's Blacklist](https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt)*.
* Consider adding *[Perflyst's SmartTV Blocklist](https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt)*, but only if Blokada works well on Android-based smart-TVs.
* Consider enabling **either** *Goodbye Ads* or *Block List Project: Ads* by default, since they have around 200,000 entries each.

### Standalone international lists that don't seem to fully be in *Energized Regional*
* *[Frellwit's Swedish Hosts File](https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt)*
* *[Dandelion Sprout's Nordic Filters](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltreDomains.txt)*
* *[hosts-jp Ads](https://raw.githubusercontent.com/tiuxo/hosts/master/ads)*
* *[Macedonian Pi-hole Blocklist](https://raw.githubusercontent.com/cchevy/macedonian-pi-hole-blocklist/master/hosts.txt)*
* *[Filtri DNS](https://filtri-dns.ga/filtri.txt)*
* *[YousList](https://raw.githubusercontent.com/yous/YousList/master/hosts.txt)*

**Comment by jawz101** [comment]
It is funny that I came here today to create an issue with my own complaints about the Energized lists and here another person with whom I know pays attention to list quality has expressed similar opinions.  My are a bit more blunt https://github.com/blokadaorg/blokada/issues/793
I went ahead and closed my issue to avoid redundancy.  As previous creator of the MobileAdTrackers and present maintainer of the Adaway list I just want to add that I agree with @DandelionSprout .  The Energized lists are blindly maintained, seem to only exist for attention, can cause significant breakage, and appear to exist only for donations.

**Comment by L31FY** [comment]
https://github.com/lightswitch05/hosts

These hosts lists here are some I've used along with the recently added OISD instead of Energized lists for less "breakage" and they seem better maintained to me. The AMP list and main block list are of particular interest but the Facebook one could maybe also be useful.

**Comment by kar** [comment]
Ok guys, in the next v5 beta build tomorrow, I'll set OISD as a default. I'll also add a few lists mentioned in this topic. Let me know if you notice anything. If all is good, I'll change the default blocklist to OISD in all builds next Friday.
