### ISSUE TITLE
Blokada doesn't display any active blocklist

### ISSUE THREAD

**Issue by naoliv** [blokadaorg/blokada#786]
### Actual behaviour
While browsing the active blocklists, nothing is displayed:

![](https://user-images.githubusercontent.com/982338/93008726-938d8100-f54e-11ea-90c7-85731bc89086.png)

### Expected behaviour
Since it's using some default blocklist(s), it should display something there, so the user could be aware (and confirm) that some list is in fact being used.
An empty list gives us the impression that nothing is being used (or blocked).

### Steps to reproduce 
1. Install Blokada 5
2. Go to Blocklists → Active

### Configuration
1. Blokada version: 5.1.0
2. Device model: Xiaomi Mi A2 Lite
3. Android version / ROM: 10

Edit: forgot the [blokada5.log.txt](https://github.com/blokadaorg/blokada/files/5213525/blokada5.log.txt)

**Comment by peterroth** [comment]
Hi,

Based on the screenshot you were not connected to the internet, thus, Blokada cannot sync with the repository. Can you check if you can reproduce the same misbehaviour if you are connected to a network?

**Comment by naoliv** [comment]
I am connected. Android hides the network icon (in the "dot" symbol, probably due to the notch in the phone), but I am connected.
A friend also said the same thing, that in his phone doesn't appear any active list.

**Comment by Notabas-iC** [comment]
hey there:)
please download and install the current version again from our website. Are lists being displayed afterwards again?

**Comment by naoliv** [comment]
Freshly installed on another phone, with network access.
It's possibe to see that Blokada is blocking stuff:

![](https://user-images.githubusercontent.com/982338/93498847-a86c6a80-f8e8-11ea-9bd4-5c3e08645504.jpeg)

But no list is active:
![](https://user-images.githubusercontent.com/982338/93498841-a6a2a700-f8e8-11ea-80a8-d899434ff2d3.jpeg)

**Comment by peterroth** [comment]
It worth to know Blokada will download the list on WiFi. Additionally, Energized Basic is included in the app to spare time and boost the first start-up.

**Comment by naoliv** [comment]
The issue here is that it's clear tha Blokada is using some kind of internal/default list, but the user can't see what it's using (nor we can't  disable or modify it).
Something is active but Blokada isn't displaying _what_ is active.

**Comment by khimaros** [comment]
i'm seeing the same behavior on Blokada 5. no block lists are activated, but domains are being blocked. its not clear where the block list is coming from.

**Comment by peterroth** [comment]
@khimaros from our repository, hosted on GitHub.

**Comment by gerbenvl** [comment]
Same issue here. Poco X3 NFC / Blokada 5.9.

Blocking works fine, but no active block list shown.
