### ISSUE TITLE
Blokada isn't displaying all blocked domains when filtering the list

### ISSUE THREAD

**Issue by naoliv** [blokadaorg/blokada#787]
### Actual behaviour
For example, I manually blocked `graph.facebook.com`:

![](https://user-images.githubusercontent.com/982338/93008861-3eeb0580-f550-11ea-8b7e-3ccde6f7a4d3.png)

But if I ask to `Show blocked only`:

![Screenshot_20200912-231404](https://user-images.githubusercontent.com/982338/93008862-401c3280-f550-11ea-8308-e30b8a31480b.png)

I can't see this blocked domain anywhere:

![Screenshot_20200912-231409](https://user-images.githubusercontent.com/982338/93008863-414d5f80-f550-11ea-9dc4-3e54cccbdb6d.png)

### Expected behaviour
When filtering the list of blocked/allowed domains it should include all the blocked/allowed entries (even when we did blacklist/whitelist something)

### Steps to reproduce  
1. Manually block some domain
2. Filter by `Show blocked only`

### Configuration
1. Blokada version: 5.1.0
2. Device model: Xiaomi Mi A2 Lite
3. Android version / ROM: 10

[blokada5.log.txt](https://github.com/blokadaorg/blokada/files/5213525/blokada5.log.txt)

**Comment by peterroth** [comment]
Issue fixed in 5.6 (currently in beta phase, the stable release will come this Friday).
