### ISSUE TITLE
Do NOT block unresolved domains automatically or at least respect the whitelist

### ISSUE THREAD

**Issue by ErikAbele** [blokadaorg/blokada#788]
### Actual behaviour
Right now Blokada auto-blocks all domains which do not resolve (have an empty A record), even when explicitly added to the whitelist.

### Expected behaviour
If a domain does not resolve (has an empty A record) it should not be blocked automatically by Blokada or, at least, it should be allowed when being added to the whitelist.

### Steps to reproduce  
Install the app for welt.de or bild.de (two major German news outlets) start them and see them requesting current.mob.welt.de which does not resolve and gets blocked by Blokada. Result is that both apps stop working with: "No internet connection!" even when this domain has been added to the whitelist.

### Configuration
1. Blokada version: latest from F-Droid
2. Device model: Umidigi S3 Pro & Lenovo M10 Plus
3. Android version / ROM: Android 9

### Questions
1. Do you know about recent updates (for example system update, security patch update)? 
no

2.  How often does this problem happen to you?
Every time I want to use those apps, no workaround available :-(

**Comment by ps100000** [comment]
Hey. I think you misunderstood something here. Query results without A records aren't blocked. There just marked in the log to contain none so a user knows that the domain probably doesn't exist if no query ever returns a valid A record for it.

**Comment by ErikAbele** [comment]
Well, it's certainly misleading then. Why name it blocked in the logs if it's not really blocked?

It's really hard to debug something with Blokada when you can't even trust its own log statements...

**Comment by ps100000** [comment]
That's why there is the little question mark giving you a detailed description. :)

**Comment by ErikAbele** [comment]
LOL, yes it says:

"**Blocked** current.mob.welt.de" and then, when clicking on the question mark icon:

"This domain was not correctly resolved by the DNS server. Either the the server **blocked** the domain or it doesn't exist."

Really, so I misunderstood something?!? Blargh, this is ridiculous. There was nothing blocked obviously so why talk about it and mislead people... I just waisted another 20min because of this crap...

**Comment by ErikAbele** [comment]
Closing this issue.

**Comment by ps100000** [comment]
I'm sorry for your trouble. This was introduced with the goal to help with debugging issues arising from using adblocking DNS server hence the wording.
