### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by NKid** [blokadaorg/blokada#79]
When I enabled blokada, and using Android's DownloadManager to download files.
They always be "Queued", can't download.
And few minutes later, the download status were change to "Unsuccessful".

Queued
![screenshot_20171211-093845_01](https://user-images.githubusercontent.com/2907483/33812405-2a2dfb0a-de58-11e7-90a8-c3a7456537fd.jpg)

Unsuccessful
![screenshot_20171211-095011_01](https://user-images.githubusercontent.com/2907483/33812493-d85089a0-de58-11e7-93ff-092e52572ec8.jpg)

Blokada 2.2.3
Android 7.1.1
OnePlus 3T

**Comment by kar** [comment]
Tried whitelisting?

**Comment by NKid** [comment]
I tried add "com.android.providers.downloads" and "com.android.providers.downloads.ui" to whitelist, but still can't download.
I paste the picture link to firefox, it can oepn and download.

When I was using Android 6.0 with Blokada 2.2.3, there is no problem with Android's DownloadManager.

**Comment by kar** [comment]
Do you have Play Store in your whitelist?

**Comment by NKid** [comment]
Yes, Play Store in whitelist by default setting.

**Comment by NKid** [comment]
Last night, I reinstall Android 7 on my OP3T.
Then the problem was never happened.
@kar thx for your helping!!

**Comment by Moradnejad** [comment]
In newer android APIs (such as API 27), URL should be encoded. Otherwise, it results in unsuccessful download. Check if your URL contains any [ or spaces or ....
