### ISSUE TITLE
Blokada 5 - VPN connection set as metered

### ISSUE THREAD

**Issue by feutl** [blokadaorg/blokada#790]
With Blokada 5 some apps stopped working properly. One was the Nextcloud Client and its Auto-Upload feature which always detected a metered WiFi as soon as Blokada 5 was running.

Blokada 4 worked without issues.

There is a community entry already
https://community.blokada.org/t/issue-blokada-vpn-connection-set-as-metered/5105

But I did not want to register for another service and I could not find the issue on github, I thought it would be good to create it and link.

Android: 10
Blokdada: 5.2.0

A pull request example from ICS-OpenVPN
https://github.com/schwabe/ics-openvpn/commit/25fabb3af600711aee548d7755a75fee41af50b1

**Comment by feutl** [comment]
Any news on this?
This makes Blokada 5 unusable for me, because I must deactivate it to get some apps to work, which is than allowing the others to start tracking me again.

**Comment by peterroth** [comment]
Hello,

5.3 just released and it delivers the solution for the metered network behaviour. You can download it from our website, https://blokada.org or from GitHub.
Give it a try and let us know if you still face the reported issue.

**Comment by feutl** [comment]
Is fixed, but I needed to uninstall and "reinstall" the app to make it work.
Don't know if this was a issue on my site or if this is a common problem when changing the VPN settings.
Thanks
