### ISSUE TITLE
How to add a DNS manually on blokada 5?

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [blokadaorg/blokada#791]
Hello, I'm looking to manually add the following French dns server: 51.158.99.7 .

Can you add the manual add option ? Where to add the Bancuh France server to your list. 

Thanks

**Comment by peterroth** [comment]
Hi,

Currently you can't add DNS servers in v5. The current focus for this version are stability and reliability, then the features will be ported from v4.
In case you want to ensure it is tracked here, please open a Feature Request.
