### ISSUE TITLE
please stop using the energized lists

### ISSUE THREAD

**Issue by jawz101** [blokadaorg/blokada#793]
They are but well maintained and simply combine others' lists without much effort invested.

I look at the blokada default list and it blocks id.google.com.  while it sounds privacy scary you're on a Google phone so question if you're actually breaking something.  In this instance, yes, you'd break Google Play auto updates by blocking that DNS entry.

Energized seems more interested in taking others'work and branding and disseminating it.  I'm fine with combo lists but it seems like they do it for credit or donations without contribution upstream or scrutiny of the quality.

I'll tell you right now the Adaway list on its own will block much of what is presently out there for mobile.  Any one person will probably ever encounter a few thousand dns entries from any list.  That's just personal observation.  Any list over
a few thousand entries is simply unnecessary.  Coupled with a browser ad blocker there is no reason for some 1 million entry blocklist and any list that large contains domains that have not been active in the past decade

**Comment by NatureHog** [comment]
@jawz101 Just downgrade to v4 and use Smart lists...

Btw, @kar is this coming to v5?

**Comment by peterroth** [comment]
@NatureHog the use of Smart List doesn't escape the use of Energized lists. That creates a list based on your actual blockings, but it needs time to be effective and until that point, the enabled lists are in use.
