### ISSUE TITLE
Blokada blocks all network traffic on data (Sprint) 

### ISSUE THREAD

**Issue by Nexinity7** [blokadaorg/blokada#796]
App version: 4.8.6
Device/OS: Samsung Galaxy S9+ (Snapdragon) / Android Q One UI 2.5

Expected behavior: Blokada blocks ads in the apps and on the websites I visit

Actual Behavior: Blokada blocks all network traffic

Ive recently noticed when im out on data my internet stops working, and when i turn blockada off everything resumes and goes back to normal.

Troubleshooting ive done: Reinstall, switch through all hosts lists, restart device, updated profile and PR

**Comment by peterroth** [comment]
Hi,

Please check if you choose another DNS server you have internet. The default may be unavailable on your network, hence the name resolution doesn't happen or times out.

**Comment by Nexinity7** [comment]
I just checked that, and I use the Cloudflare DNS and when i turn it off everythinf resumes normally

**Comment by peterroth** [comment]
Can you try with another DNS server?
