### ISSUE TITLE
Could not activate all block lists

### ISSUE THREAD

**Issue by aarakh** [blokadaorg/blokada#799]
**Blockada Version** : 5.5.0,
**Android Version** : 10
**Device:** OnePlus 7
**Issue:** When trying to activate Steven Black, AdAway, Blacklist, Exodus Privacy, Getting error which says "Could not install(or uninstall) this feature. Please try again later.

Tried to clear cache and force restart of app, still no luck.

**Comment by peterroth** [comment]
Usually the cause for this message is that the system is busy loading and merging the lists. You just need to wait a bit and retry to activate the newer list.

**Comment by aarakh** [comment]
This issue had been resolved
