### ISSUE TITLE
Bug: exclusion list doesn't work for some apps

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [blokadaorg/blokada#809]
I have an app that I work on, and don't want it to be blocked:
https://play.google.com/store/apps/details?id=com.lb.app_manager&hl=en&gl=US

I went to "Apps" on "Advanced" tab, and I made sure it's set "bypassed":

![image](https://user-images.githubusercontent.com/5357526/102134288-fb5dab80-3e5e-11eb-9791-4655a23f48c5.png)

However, when I check the app (ever after a restart of the device), it still gets blocked. 

Please fix this.

The version is:
5.5.0 - 505000000

Tested on Pixel 4 with Android R

**Comment by peterroth** [comment]
For clarification and to reproduce this behaviour, what is being blocked exactly? Which hostname should I look for on the activity screen?

**Comment by AndroidDeveloperLB** [comment]
@peterroth I don't think I changed anything in the settings. Can you please tell me where to check?

**Comment by peterroth** [comment]
Sure, of course.
Blocklist: Advanced screen - Blocklists
DNS: Advanced screen - Encryption & DNS

**Comment by kar** [comment]
This is outside of our control. We use API calls with package names, what Android does is another thing.

**Comment by AndroidDeveloperLB** [comment]
@kar  But it doesn't seem to work :(

**Comment by AndroidDeveloperLB** [comment]
@peterroth Here's about Blocklist: Advanced screen - Blocklists:

![image](https://user-images.githubusercontent.com/5357526/117680772-25bb5700-b1ba-11eb-9915-89237949c490.png)

But where is the "DNS: Advanced screen - Encryption & DNS" ?
