### ISSUE TITLE
Not blocking anything many times

### ISSUE THREAD

**Issue by alleluia20** [blokadaorg/blokada#81]
In the last weeks (before and after the last upgrade), blokada starts up (as configured) when the phone is powered up, blokada reports to be on, and the key symbol is displayed.
Nevertheless, the notification reads "nothing blocked yet" (I am translating from my language), and ads are displayed both inside the browser and the apps.
It is happening around 50% of the times from the last weeks. Sometimes things are correct for several consecutive days, and sometimes things are wrong for several days in a row.
Restarting blokada sometimes fixes the issue, but many times it does not.

**Comment by kar** [comment]
devices, android version?

**Comment by alleluia20** [comment]
Moto G5, Android 7.0.
When Blokada does not block at the beginning, restarting Blokada or rebooting the phone does typically not fix that. I then stop Blokada, start DNS66 and, when DNS66 hangs (or is killed) after a few hours, I restart Blokada and... it does block ads!
But I do not know the reason. Does Blokada maybe need some time to heal? Or, is it that DNS66 created a VPN before, and Blokada works when it is second to create a VPN?
Please let me know if you need any further information.

**Comment by kar** [comment]
also check what happens after coming back from airplane mode after a while

**Comment by kar** [comment]
3.0.0 (not the preview) will have changes that may have addressed it, but I'm not sure because this issue seems to be device specific. Feel free to reopen in case it keeps happening with the next release. Also, if it does, pay attention to the hosts count (it should not be displaying 0).
