### ISSUE TITLE
Recommended DNS server change (Digitalcourage)

### ISSUE THREAD

**Issue by CryptOwl** [blokadaorg/blokada#810]
Digitalcourage has set up a new DNS server for DNS-over-TLS since the old was causing a lot of trouble. It's highly recommended to switch over.

dns3.digitalcourage.de
IP: 5.9.164.112
Port: 853
SPKI pinset: 2WFzfO2/56HpeR+v/l25NPf5dacfxLrudH5yZbWCfdo=
Limited to 50 connections per second for a single IP so as many individuals as possible can use it.

More info: https://digitalcourage.de/support/zensurfreier-dns-server

Edit: Hm, since this new server exclusively supports DoT it won't have any use for Blokada - is that correct?

**Comment by peterroth** [comment]
Correct. Blokada supports DoH, not DoT.
