### ISSUE TITLE
[Feature Request] Suggestions for Blokada's Default Block List Selection and Some Notes

### ISSUE THREAD

**Issue by bongochong** [blokadaorg/blokada#813]
First, let me say thank you, for all of your continuing work on an application that is absolutely crucial for any un-rooted Android device, and for keeping it a community-oriented project. Now, onto the issue.

I was hoping for Blokada v5 to include the option of utilizing custom block list sources, but until then, I believe that at least some of the following lists should be added to the selection which Blokada offers OOTB (note that these are links to the raw files, so they are best viewed with a desktop browser):

1. [PGL Yoyo Hosts](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext) - General purpose, light weight.
2. [MVPS Hosts](https://winhelp2002.mvps.org/hosts.txt) - General purpose, light weight.
3. [URL Haus Hosts](https://gitlab.com/curben/urlhaus-filter/-/raw/master/urlhaus-filter-hosts.txt) - Malware prevention, medium weight.
4. [Dan Pollock's Hosts](https://someonewhocares.org/hosts/hosts) - General purpose, medium weight.
5. [CPBL Hosts](https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/newhosts-final.hosts) - General purpose, medium weight (I actually maintain this project myself).

Blokada's current selection is sorely lacking, but there are several other reasons why the aforementioned lists should be included as options. All of these are of a reasonable size, yet significantly reduce advertising, tracking, and other varieties of malicious traffic, without frequently introducing breakage of functionality in widely used applications and websites. Most importantly, these lists are high quality (properly formatted, de-duped, sorted etc...), actively maintained by responsive developers, and receive frequent updates. A few of these lists were even included by default in older versions of Blokada.

Additionally, any of these lists would make a solid choice for a default source, as they do well on devices with lower memory constraints, and rarely introduce notable false-positives. The classic combination of MVPS + PGL Yoyo + AdAway (thankfully already included), would be a particularly good default combo, and jumping off point for virtually every user on the planet.

Cheers!

**Comment by kar** [comment]
added in next update: dan pollock, cpbl.

more coming in the update after that.

**Comment by bongochong** [comment]
Quite pleased to hear. Thanks again for the great work!

**Comment by kar** [comment]
URLhaus will be added in 5.12. The rest (pgl and mvps) are part of a few other lists that are already available.
