### ISSUE TITLE
Blokada blocks rpi2, but it's not possible to whitelist

### ISSUE THREAD

**Issue by fekir** [blokadaorg/blokada#815]
Hello,

on my network I have an raspberry 2 named rpi2.

I can ping it successfully from my PC and Android phone (with blokada disabled) without any further configuration.

If I enable blokada on the phone, with the default settings, I can see from the logs that the ping to "rpi2" is blocked, and indeed ping from my Android phone returns "unknown hostname". 
If I ping the ip-address directly it works, so it should not be a network issue.

I tried adding "rpi2" under "Allowed Hosts", but I cannot save it, as the dialog tells me it's an invalid name.

**Comment by peterroth** [comment]
Hi,

that is expected, because Blokada (v5) doesn't use the system peovided gateway and/or DNS server, hence the local network name resolution doesn't work (the 3rd party DNS server doesn't know the IP of machines on your local network).

**Comment by fekir** [comment]
I just realized that I'm not using the latest version, but 4.9.0, as blokada (v5) is not an update but a separate application.

From your comment it seems there is no workaround, even if it's not clear to me why the whitelist approach should not work (lack of knowledge how the app works).

So, just to be clear: I cannot reach other devices in my network by name, correct?
A raspberry/computer, the modem/router, and so on (I do not have other "smart devices" to test, but can confirm that I cannot reach the login page of the modem too).

If that the case, it seems a big limitation.

**Comment by peterroth** [comment]
With v4, you have the ability to use the system's default DNS server. That can be the gateway/router's IP address, and that may helps.

**Comment by peterroth** [comment]
Update: since v5.8, you can set the network provided DNS server on the Advanced screen - Networks.
