### ISSUE TITLE
No option to whitelist apps in iOS version

### ISSUE THREAD

**Issue by danieltaylor** [blokadaorg/blokada#818]
The ability to whitelist specific apps is missing from the iOS version of Blokada 5.

I wasn’t able to find any existing documentation of this issue except for this Reddit thread: https://www.reddit.com/r/blokada/comments/ha52lp/i_tried_this_app_on_my_iphone_it_was_blocking/

**Comment by kar** [comment]
This is not implementable on iOS sadly.
