### ISSUE TITLE
Feature request [custom DNS] 

### ISSUE THREAD

**Issue by phil2sat** [blokadaorg/blokada#820]
I have pihole configured for my home network. But my Kids are clever. They activate DoH or custom DNS in Windows. For this reason my Firewall blocks all known DNS and DoH hosts. Only pihole can acces DNS.
I would like to use Blokada all the time, and not check every second if i leave my Wifi range. I guess best solution is custom DNS and different settings for LAN and Mobile connection. 

Sincerely yours 
Phil2Sat

**Comment by pfactum** [comment]
Can be a dup of #807, #808 and #816.

**Comment by peterroth** [comment]
Correct, closing it as duplicate.
