### ISSUE TITLE
why does the app connect to visit.rebrand.ly?

### ISSUE THREAD

**Issue by mailinglists35** [blokadaorg/blokada#827]
I'm not confortable with that.

**Comment by peterroth** [comment]
Which app doed that? I can't see this address in my Activity screen.

**Comment by mailinglists35** [comment]
android build Blokada 5S

org.blokada.alarm.dnschanger
5.7.0 (507000000)

**Comment by mailinglists35** [comment]
in settings - apps & notifications also says version 11.9.0-210107

**Comment by mailinglists35** [comment]
apk https://www.pastefile.com/gm8zc6

**Comment by peterroth** [comment]
That's just a DNS changer, nothing else. Open source just like any other app variant Blokada has; and it just reports what domains are looked up, Blokada Slim doesn't reach out to such domains.

**Comment by mailinglists35** [comment]
yes it does. I have installed "noroot firewall" and it reports that android blokada app attempts to connect to these IP to port 443

52.72.49.79 (visit.rebrand.ly)
172.67.167.56
104.21.11.200

**Comment by kar** [comment]
All go.blokada.org links we use are a redirector links through rebrandly. The reason we use them is so that we can easily change the destinations without making an update. We use them mostly for forum shortcuts, as well as some other links, like donation page etc.

**Comment by peterroth** [comment]
Here I stand corrected. Thanks @kar, I wasn't sure go.blokada.org links use rebrandly.

**Comment by mailinglists35** [comment]
is there any way to disable it? it's quite ironic for an app that tries to protect your privacy to use a data-collecting third party service...

**Comment by FRooter** [comment]
> All go.blokada.org links we use are a redirector links through rebrandly. The reason we use them is so that we can easily change the destinations without making an update. We use them mostly for forum shortcuts, as well as some other links, like donation page etc.

Why not setup the same easy redirect without involving additional third party entities?  e.g., Why not use the same service that hosts the `blokada.org` website?
