### ISSUE TITLE
How about add a repository?

### ISSUE THREAD

**Issue by Sak94664** [blokadaorg/blokada#83]
Hope to add a repository which stores blacklist rules(host file form).so that people from all over the world can contribute rules to it.(it's useful when other github repositories(stevenblack) haven't add the most recent rules.)

**Comment by Sak94664** [comment]
Inside the repository.We can add different rules to the matched countries.(Like adblock Easylist+China Easylist)

**Comment by kar** [comment]
That's a great idea, however Blokada doesn't support easylist. It's hostname only. Feel free to start by creating a repo on your account and I will link it in Blokada. If things work out well we can then move it to be an official Blokada repo.
