### ISSUE TITLE
5.8 beta doesn't work on firestick 4k model

### ISSUE THREAD

**Issue by MyPhoneNumber** [blokadaorg/blokada#832]
1. When the permission comes up to allow blokada to view the network name, the permission options are well below the screen thus user can't see them or select them. 

2. Prefer network DNS doesn't work. User is able to enable the option, but blokada still only uses the DNS listed in blokada. Default is blokada DNS. I know this because preferred network dns is pi hole which I can track and the firestick is not requested any DNS info from pi hole when blokada is enabled. Even disabling "Any WiFi network" option still doesn't route the DNS through the default network dns (pi hole). The only way the default network DNS is used is if blokada is turned off completely from the home button. 

3. In advanced section the built in mouse toggle feature is not enabled for the options. User can not scroll down to networks for example. Only way to select Networks is to have an external mouse toggle app downloaded and activated by double clicking the play button on the remote to use the external virtual mouse.

**Comment by peterroth** [comment]
Hi,

Blokada v5 isn't optimised for TVs and TV devices. Please install Blokada v4 on the FireStick.
