### ISSUE TITLE
Spurious numbered network types in Network menu

### ISSUE THREAD

**Issue by Gliptal** [blokadaorg/blokada#839]
Below the "Any mobile network" and "Any WiFi network" entries, I have three spurious network types I don't recognise. See the attached screenshot.

I have no idea what these networks refer to, nor how to remove them from the list.

![IMG_20210225_005509](https://user-images.githubusercontent.com/3907646/109082381-29cff080-7704-11eb-8b94-d6a78d462cb3.jpg)

**Comment by L31FY** [comment]
I also see this and I suspect it's a network I've yet to connect to with Blokada on but that my device has saved and therefore it isn't "named" in here.

**Comment by peterroth** [comment]
Blokada receives those names from the system itself, it isn't something that Blokada scans for on its own. If the system saved networks this way, Blokada will show them like on the screenshot.

**Comment by Gliptal** [comment]
Those networks were listed before I turned the discovery option on though. Checking my system's networks, I see no similarly named entries.

**Comment by kar** [comment]
This looks suspicious indeed. Have you granted permissions? Also share the log with me to hello@blokada.org.

**Comment by Gliptal** [comment]
I'll sene you the logs ASAP. I did briefly activate the discovery option (which is why there's an additional entry after the three spurious ones.

I'm sure these weren't here when I first installed 5.7, but can't say for sure when they fist popped up between then and 5.9.

**Comment by kar** [comment]
Thank you. This will be fixed in the next release.

**Comment by Gliptal** [comment]
Nice thanks, may I ask what the problem was?
