### ISSUE TITLE
Bitcoin mining

### ISSUE THREAD

**Issue by xmiseggs** [blokadaorg/blokada#84]
Please include a list to block bitcoin mining, if it is one that already exists, can you indicate which one is to activate it?
This is a list that supports uBlock Origin in case it can help you:
"https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt"

**Comment by jeroen7s** [comment]
easyprivacy includes entries for blocking cryptomining, so i'm not sure if a separate list is needed or nor

**Comment by ZeroDot1** [comment]
This is a very good app, please help stop the #Cryptojacking. I hope the #CoinBlockerLists are good for supporting the project.

https://github.com/ZeroDot1/CoinBlockerLists

| Format | Description | URL |
| --- | --- | --- |
| List | This list contains all domains - A list for administrators to prevent mining in networks| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt) |
| List | This list contains all optional domains - An additional list for administrators| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_optional.txt) |
| List | This list contains all browser mining domains - A list to prevent browser mining only| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt) |
| Hosts | This list contains all domains - A hostslist for administrators to prevent mining in networks| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts) |
| Hosts | This list contains all optional domains - An additional hostslist for administrators| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_optional) |
| Hosts | This list contains all browser mining domains - A hostslist to prevent browser mining only| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser) |
| List | This list contains all IPs - A additional list for administrators to prevent mining in networks| [Download](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/MiningServerIPList.txt) |

**Comment by kar** [comment]
Added CoinBlockerList
