### ISSUE TITLE
Blokada 5.9.0 erratic and defective behavior after Feb Google Play system update

### ISSUE THREAD

**Issue by dronewizard** [blokadaorg/blokada#840]
I noticed many apps slowing down to a halt or not working at all immediately after updating multiple devices with Blokada to the 02/2021 Google Play system update. When I disabled Blokada, they worked and extremely quickly. I tried cycling Blokada on and off and restarting my devices, but the issue persisted. I even disabled all blocklists and filters to no avail. The YouTube app slowed to a halt, certain websites wouldn't load, and stuff like Disney+ and Speedtest would not even connect at all whenever Blokada was enabled regardless of whether it was configured to block content. I noticed nothing wrong with the Blokada app whenever I opened it (no hangs and filter log looked normal). I'm on Android 11.

**Comment by arturbosch** [comment]
Can confirm this with the brave browser. Extremely slow, vivaldi is however fast.
Turning blokada off makes brave fast again.

**Comment by dronewizard** [comment]
Just to clarify, Blokada 5.9.0 worked fine all the way up until when I installed the Google Play system update for February. Only immediately following that did the issues begin.

**Comment by Gigabitzz** [comment]
Can confirm. Some websites and/or applications seem to have stopped connecting to the internet properly with Blokada enabled, regardless if all blocklists are disabled.

What I did is, instead of entirely disabling Blokada, I would just add apps I frequently use to the app bypass list. This can be accessed in Advanced -> Apps -> Select App.

Granted, whitelisting an app ruins the purpose of an "adblocker", but this seems to be the only way to use my apps until the devs fix the issue.

**Comment by oiisamiio** [comment]
Same here under ios. Blocks Store and Browser since last Update...

**Comment by paulverbeke** [comment]
I can confirm this on Android 11, Blokada v5.9.0.
And more noticely my search engine ecosia.org is no longer loading. Working fine without Blokada. And no blocked activity in the activity tab, so no possibility to allow the same domain safe passage (despite that it was already allowed Green

**Comment by rickined** [comment]
Same here.  Over the past few days I've gotten dns timeouts while browsing on my pixel 5 android 11 Feb 2021 update.  Maybe it's the dns server blokada is using?  The reliability of blokada has been bad over the past week and very bad over the past 1-2 days.

**Comment by oiisamiio** [comment]
Solution: Blokada DNS is broken. change DNS Server to another one...

**Comment by paulverbeke** [comment]
You're right, changing to cloudflare fixed everything. thanks

**Comment by paulverbeke** [comment]
Can I enquire why has this been closed ? Is changing the default DNS a real solution ? Shouldn't using Blokada be as easy as possible for non tech savvy people ?

**Comment by oiisamiio** [comment]
closed due update 5.10.0 Changed default DNS back to Cloudflare...

**Comment by peterroth** [comment]
Renamed it for future reference, in case somebody searches for the same behaviour.
