### ISSUE TITLE
Block list download failed

### ISSUE THREAD

**Issue by PL7963** [blokadaorg/blokada#844]
Before I was installing the new block list then the app stuck a few second. Then it crashed. After this I can't really connect to Blokada. And all the block list download failed.

**Comment by peterroth** [comment]
How much lists did you try to download in parallel? The app might ran out of memory (heap).

**Comment by PL7963** [comment]
About 4~5 settings in the list. And the list is the block list project.

**Comment by peterroth** [comment]
Try to download them one by one. Blokada downloads and merges them, this second process is memory consuming and the app may runs out of the configured heap, hence it crashes.

**Comment by PL7963** [comment]
OK. But now. I can't downloading anything. And I also can't connect to Blokada.

**Comment by peterroth** [comment]
Sorry for the delay, may I ask what does "can't connect to Blokada" mean?
