### ISSUE TITLE
Xiaomi connection allowed

### ISSUE THREAD

**Issue by Kreuger** [blokadaorg/blokada#845]
Hey all. On my tablet I noticed that Blokada allowed a connection to

_app.chat.global.xiaomi.net/_ 

But I dont have any Xiaomi apps and its a Lenovo device. Any idea whats going on?

**Comment by kar** [comment]
Seems like nobody has any idea. I'll close this but feel free to re-ask on our telegram or forum, I think more users hang around there than on our github.
