### ISSUE TITLE
Add TomTom AmiGO to the blokada default list

### ISSUE THREAD

**Issue by VincenzoVitale-TomTom** [blokadaorg/blokada#847]
Hello, multiple users of the TomTom AmiGO app are reporting problems when Blokada is used. 
AmiGO is a free navigation application with no advertisement and TomTom will never sell customer data to others. That is also what differentiate the AmiGO app (and the entire TomTom) from other free navigation applications.

IPA and APK available in the respective stores:
https://onelink.to/tomtomamigo

Is it possible to add AmiGO to the default bypass list?
We use:
Google Play Store: com.tomtom.speedcams.android.map 
Huawei Store: com.tomtom.amigo.huawei

Thanks,
Vincenzo.

**Comment by peterroth** [comment]
Hi @VincenzoVitale-TomTom,
I just created a pull request to bypass AmiGO in Blokada v5 by default, soon I'll create another one to bypass in v4 too.

**Comment by VincenzoVitale-TomTom** [comment]
Amazing @peterroth 

Thanks a lot!

**Comment by VincenzoVitale-TomTom** [comment]
Hello @peterroth, is this change in the latest release?

**Comment by peterroth** [comment]
Hi @VincenzoVitale-TomTom,

Yes, both changes were merged on the 11th of March. v4 syncs from the website, v5 is delivered with the bypassed value.

**Comment by VincenzoVitale-TomTom** [comment]
Great thank you
