### ISSUE TITLE
[Feature Request] Allow removal of networks

### ISSUE THREAD

**Issue by bluezed** [blokadaorg/blokada#848]
Under "Networks" I have quite a large collection of Wifi networks that I only used once.

I would really appreciate it if you could add a way to remove networks that I don't need any more. Or even remove them automatically if their settings haven't been customized and they weren't used for a while.

Thanks!

**Comment by PeterDaveHello** [comment]
@kar not sure if this was implemented? I checked v5.18.0, didn't see an option to remove a network.
