### ISSUE TITLE
Not possible to deactivate "Keep alive"

### ISSUE THREAD

**Issue by Ennneerrrgggyyy** [blokadaorg/blokada#854]
Whenever I set "Keep alive" to no and restart Blokada to save changes, the app sets "Keep alive" to yes again.

blokada/5.10.1
Blokada 5: F-Droid

**Comment by peterroth** [comment]
Disable "always-on VPN" in system settings - Wi-Fi and internet - VPN.

**Comment by Ennneerrrgggyyy** [comment]
It is disabled. That doesn't seem to be the problem here.

**Comment by kar** [comment]
You'll need to stop using the "Networks" feature (ie. configure only the "All networks" configuration, and have others disabled). Keep alive is required for that feature, otherwise Android likes to kill the app when it is re-configuring in the background on network change.
