### ISSUE TITLE
Block list not updating

### ISSUE THREAD

**Issue by terrorist96** [blokadaorg/blokada#855]
Hi, I think my Blokada still has issues with updating the lists

A change made to OISD on March 29 is still not showing for me as of April 18.

bitcoinads.growadvertising.com is blocked on the list but not for me in Blokada, meaning my list hasn't updated since end of March. I tried with both wildcard and standard and the issue is there.

**Comment by kar** [comment]
Please share log to hello@blokada.org, it should tell us if it is updating or not.

**Comment by terrorist96** [comment]
Done.

**Comment by terrorist96** [comment]
Any insight? I can only get the lists to update if I clear cache/data or uninstall/reinstall.

**Comment by terrorist96** [comment]
Another Friday comes and goes and my filter list is not updated.

**Comment by kar** [comment]
It will work from 5.12 onward.

**Comment by kar** [comment]
Check your config, re-select OISD blocklist, switch to "Basic (Wildcards)" or "Basic" and see if it helps.

**Comment by terrorist96** [comment]
I decided to just uninstall and reinstall. It is fixed now. Still need to test a new addition to the list and see if it updates. I'll report back in some time.
