### ISSUE TITLE
[Issue] Enabling blocklist returns "Couldn't install (or uninstall) this function. Try again later"

### ISSUE THREAD

**Issue by AnonymousWP** [blokadaorg/blokada#856]
- **App version:** 5.11.1

- **Device model:** OnePlus 7 Pro (8GB RAM, 256GB storage)

- **OS version:** Android 10

- **Steps to reproduce the bug:**
      1. Open Blokada
      2. Go to Advanced
      3. Go to Blocklists
      4. Enable or disable any filter, for example "The Block List Project" or "hBlock"
      
- **Expected behavior:**
It should apply the filter, considering I have plenty of RAM left. It should at least tell me what went wrong and what's causing it.

- **Actual behavior:**
When I try to disable or enable the aforementioned filters, I get the following error: "Couldn't install (or uninstall) this function. Try again later". I then tried to reproduce this with other filters, which returned the same error. I managed to fix this by clearing the app's cache, as it probably caches those filters, but unfortunately this didn't fix the issue for the aforementioned filters (see step 4). Steps were reproduced after I rebooted my phone, to be sure it's not a RAM-related issue.

https://user-images.githubusercontent.com/50231698/115585017-8c400a00-a2cb-11eb-9de7-955d1335d787.mp4

Let me know if you need any more information.

**Comment by peterroth** [comment]
How much lists do you have already enabled?

No app can use the full RAM of the device, they get smaller portions (called heap). So even if you have 12 GB RAM, the app maybe users only 256 MB.

**Comment by AnonymousWP** [comment]
> How much lists do you have already enabled?
> 
> No app can use the full RAM of the device, they get smaller portions (called heap). So even if you have 12 GB RAM, the app maybe users only 256 MB.

All of them, except those two. You're right about that, but then why if I try to disable some blocklists, it also throws the same error? Also, it used to work before just fine, and as I rebooted before I tested, I am not entirely sure if that's the problem.

**Comment by peterroth** [comment]
Enabling and disabling will also trigger a re-merge procedure where the duplicates are removed. It means, both procedures are memory intensive.
Do **not** activate all the lists. You won't face all the hostnames they all carry together.

**Comment by peterroth** [comment]
Logically, the bigger list you add to the currently active one, the more memory will be used and if you already close to the max portion (xmx) then the app will throttle to avoid Out Of Memory (OOM).

There is no smart function for this use case in v4. That just tells you how much free memory (heap) is available for you.
