### ISSUE TITLE
Minor Corrections for Description of My List (CPBL)

### ISSUE THREAD

**Issue by bongochong** [blokadaorg/blokada#857]
I should have mentioned this a couple of weeks ago, but there's a minor grammatical error in Blokada's description of my list. It should read as: *This list blocks malicious and harmfully deceptive content, like advertising, tracking, telemetry, scam, and malware servers. This list does not block porn, social media, or so-called fake news domains.*  

Currently it says *These lists block* in the first sentence, and *These lists do not* in the second sentence.  

Additionally, it would be nice if you could add another sentence at the end: *CPBL aims to provide block lists that offer comprehensive protection, while remaining reasonable in size and scope.*  

The relevant files appear to be:
- https://github.com/blokadaorg/blokada/blob/5/android5/app/src/main/java/repository/PackDataSource.kt
- https://github.com/blokadaorg/blokada/blob/5/ios/IOS/Pack/PackService.swift

Many thanks!

**Comment by peterroth** [comment]
Just for clarification: the lists do block also porn, social media and fake news. Right?

**Comment by bongochong** [comment]
Heheh, but no, my lists do not block such content.

**Comment by peterroth** [comment]
Ohh, ok, thank you for the clarification.

**Comment by bongochong** [comment]
No problemo!

**Comment by bongochong** [comment]
Oh yeah, and the slugline should read: *A general purpose, medium weight list*. Not *lists*.

**Comment by bongochong** [comment]
I just created two pull requests to make it easier for you guys. Probably should have done that from the start. Sorry about that.

PR #1: https://github.com/blokadaorg/blokada/pull/858

PR#2: https://github.com/blokadaorg/blokada/pull/859/
