### ISSUE TITLE
HTTPS filtering

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [blokadaorg/blokada#864]
there are so many ads in browsers and sites that use HTTPS so Blokada can not block them.

Adclear and Adguard are two apps that I tried and they can block HTTPS ads.

https://adclear.com/
https://adguard.com/adguard-android/overview.html

this is a very good and essential feature for Blokada.

**Comment by L31FY** [comment]
Blokada has a clear policy about this that has been stated before. This kind of filtering is not privacy friendly and goes against the ideology of Blokada and will not be included.

**Comment by HamidRezaAshkiyan** [comment]
I understand what you say but in these apps this is optional and you can ignore it and don't use it. so if this feature includes as an optional feature this could solve this problem.

**Comment by L31FY** [comment]
Including the feature at all breaks the trust we have and means we would be
involved in anti-privacy features that could expose personal data. It's not
an option or point of discussion and this isn't changing.

**Comment by HamidRezaAshkiyan** [comment]
Thanks for your explanation.
