### ISSUE TITLE
[Feature Request] Add description and rulecount for each Filter

### ISSUE THREAD

**Issue by ChiIllHOLA** [blokadaorg/blokada#865]
I think it would be quite convenient to display a short description and an estimated rulecount next to each of the default filters.

Most descriptions provided by their creator can be found in `Filterlists.com`

While the rulecount can just be an estimation depending on how frequently it updates

Ex. 
85688 ~ 90000
85688 ~ 85700

> Cheers, Pete

**Comment by peterroth** [comment]
The disabled lists are not downloaded, hence, not present on the device. This is why Blokada cannot check how much elements they have. Additionally, checking all of them (download, parse, go through and count) would be very battery draining.
And, in the end, Blokada merges the downloaded lists into one big list, filtering out the duplicated entries, so it's not like 2+4=6.
