### ISSUE TITLE
Distributing .ipa file

### ISSUE THREAD

**Issue by iMonZ** [blokadaorg/blokada#866]
I see that you distribute the apk files for android.
Could you release the ipa files for iOS too? Actually it shouldn’t be so hard

**Comment by kar** [comment]
What would be the use case for that? We distribute apk because the full version is not allowed on Google Play.

**Comment by iMonZ** [comment]
> What would be the use case for that? We distribute apk because the full version is not allowed on Google Play.

Because the same goes for iOS too.

**Comment by kar** [comment]
Blokada is available on App Store.
