### ISSUE TITLE
[Samsung Tab S3] VPN unable to setup

### ISSUE THREAD

**Issue by bradthurber** [blokadaorg/blokada#87]
After install there is a brief error when the VPN is setup. Simply does nothing with Tab S3. Adguard also has a similar problem with samsung tablets and reports that VPN is disabled. Other than adblocker VPNs I am able to use normal VPN on these devices without issue. Is there something I can submit that will help to troubleshoot this issue?

**Comment by kar** [comment]
Thanks for reporting this. Seems like at this point those devices are not supported. I'll get back to you once I get to work on this issue. In the meantime, have you tried other ad blockers? Are they working?

**Comment by kar** [comment]
What is the error message for VPN?

**Comment by DarkenLX** [comment]
Kar not sure if it helps but i know some if not all Samsung devices have a VPN client app pre installed in addition to the Android setting area the app is for "Advanced IPsec VPN" wondering if it might be causing conflicts on some of the devices.

**Comment by micressor** [comment]
I have the same problem on a **Galaxy Tab S2 SM-T813.** Shall I open a new ticket? I can also provide a debug log if needed.

**Comment by somestrangethings** [comment]
@micressor Hey! I'm using a Galaxy Tab S2 SM-T813, too. I updated Blokada 50 minutes ago and I tried ANYTHING, but Blokada doesn't work, no matter what I did. Then I decided to check github and that's when Blokada started working! It blocks ads, counts them, sends notifications... everything is fine again! So maybe that works for you as well.

**Comment by ckzo** [comment]
Same problem for me, and I'm also using a Galaxy Tab S2...

**Comment by kar** [comment]
Update to 4.1.4, start it, let it set up, try accessing some ads, send log to me hello@blokada.org (everyone having this problem)

**Comment by peterroth** [comment]
Can somebody validate if this ticket is still valid with version 4.5.2?

**Comment by bradthurber** [comment]
I am happy to say that this issue appears to be resolved. I gave up hope of anyone solving it. Really nice work.
