### ISSUE TITLE
Blokada 5.13 does not merge wildcard filters with non-wildcard filters

### ISSUE THREAD

**Issue by chrishub188** [blokadaorg/blokada#870]
## Steps to reproduce
1. Install Blokada.
2. Select Adaway filter list, or any other non wildcard filter list.
3. Select 1Hosts Lite filter list, or any other wildcard filter list.
4. Trigger a DNS request that is only  included in 1Host Lite wildcard and not in Adaway filter list, e.g. "forter.com".
5. Trigger a DNS request that is only  included in Adaway and not in 1Host Lite wildcard  filter list, e.g. "script.ioam.de".
5. Check  activity in Blokada.

### Expected behavior
The host entries from 1Host and Adaway are merged, and entries from both filter lists are blocked, e.g. "forter.com" and "script.ioam.de".

### Actual behavior
Host entries from the Adaway filter list are blocked, e.g. "script.ioam.de",  and wildcard  entries from 1Host are not blocked, e.g. "forter.com".  

### Additional information 
If only a wildcard filter list is selected, the entries are blocked. Only after merging, the wildcard entries are ignored
When merging  custom filters from "My Blocklist" with a wildcard filter list, there is the same behavior.

### Device information
* Android device: Pixel 4 (Android 11)
* Blokada version: 5.13.0

**Comment by kar** [comment]
Fixed in 5.14
