### ISSUE TITLE
[Enhancement] Option for Bypassed apps to ignore blocklist while still using selected DNS

### ISSUE THREAD

**Issue by e-t-l** [blokadaorg/blokada#874]
I noticed that when I bypass an app, it basically makes Blokada ignore it completely. However, I like having encrypted DoH; there's just a few apps that I'd like to give unrestricted access to domain requests. 

Would it be possible to add an option so that bypassed apps can still be routed through the selected DNS resolver/encryption while not being filtered by the Blocklist? (It could even be a 3rd option, so tapping an app name in the Apps screen toggles it between blank (default), Bypassed (ignored by blocklist + DNS), or Rerouted (DNS active, but blocklist ignored). The name could be workshopped.

**Comment by kar** [comment]
Sadly to my knowledge this is not possible on Android. Anyone feel free to post any info if that's not the case.
