### ISSUE TITLE
"TomTom Go" not working when Blokada is active

### ISSUE THREAD

**Issue by alleluia20** [blokadaorg/blokada#878]
This is strange... I am using the last version of Blokada 5 on Android, and the OISD block list.

I monitored the sites that are blocked after starting the app "TomTom Go" (a subscription app with no ads), and I whitelisted them: I whitelisted ssl.google-analytics.com, googleads.g.doubleclick.net, sessions.bugsnag.com and launches.appsflyer.com.    Right now, no site is blocked when I start TomTom (except for some ones clearly related to another app, like WhatsApp).

Still, TomTom is not working. After starting it without having made the first configuration:

1) After a very long time "loading app", TomTom says that it was impossible to get contact with its servers, and asks you to manually install the navigation maps.
2) On the TomTom map list, you open an area (e.g., Europe), and the app stays "loading" forever and ever.

The only fix that works is to whitelist the app "TomTom Go" itself in Blokada. Still, I find it weird that the app is not working even when no site is blocked (except for some ones clearly related to other apps), after having whitelisted the sites above.

Can you find any fix? Or, at list, may you whitelist this app in Blokada by default?

Regards.

**Comment by kar** [comment]
Did you maybe see any blocked hosts in the activity lists while TomTom is trying to connect?

**Comment by alleluia20** [comment]
On the one hand, your question is thoroughly answered in the opening post.
It takes a lot of time to me to write posts like that, and I am
disappointed to see how many people just do not bother to read.

On the other hand, I cannot understand why the bug is closed without
explanation, and without allowing any time for me to reply.

In case reporting bugs is not worth, please let me know, and I will not
waste my time again (several hours: for checking possibilities plus
writing).

Regards.

**Comment by alleluia20** [comment]
OK, when following this bug by email, I missed the commit that closes the
bug.

**Comment by peterroth** [comment]
The TomTom Go was whitelisted. It's possible the app won't work if the VPN API is in use, and in this case no site or host will be blocked, still the app won't work. In such case the only way is to whitelist the app.
