### ISSUE TITLE
Some apps are still getting ads through

### ISSUE THREAD

**Issue by DarkenLX** [blokadaorg/blokada#88]
Apps by Winr maybe others https://play.google.com/store/apps/details?id=com.winrgames.solitaire just one of many have been always trying to combat ad blocking by using its own embedded host file or you name it.. i tried packet sniffing only link it mostly connects to is an amazonaws one. most if not all ad servers it connects to are blocked not sure if its my device or everyone who uses winr games.
Device: BLU R1 HD "P6601" non Amazon version
Android: 6.0
Could someone look into this.

**Comment by Pinguinguy** [comment]
What ad service are they using?

Does the ads appear if you are in airplane mode?

**Comment by DarkenLX** [comment]
not sure on the ad service thats getting through i know they use multiple ad services.. no ads if in airplane mode.. ive had blokada close on me for no reason when playing the app not sure if its the app or blokada as blokada is latest so im thinking its the app since blokada set to stay alive.

**Comment by kar** [comment]
Thanks for doing some due diligence on it. Unfortunately, blocking everything is much harder on Android than on a desktop. I'll try to look into it, although there're many issues of higher priority. If anyone could do some more packet sniffing and report here what those apps are exactly doing, this would be very useful.

**Comment by DarkenLX** [comment]
I know what i ran into with packet sniffing some packet sniffing apps require making a VPN which also means blokada is not going to work while sniffing.. wire shark might work not really familiar with packet sniffing on Android.

**Comment by rpeter85** [comment]
I just saw ads in Facebook Messenger. I'll take a look if I can get a packet sniffer (if somebody has a working one please let me know) their source.

**Comment by kar** [comment]
I'm closing this one, it's too generic. Currently we know of few different causes:

- Blokada closing (it's being worked on)
- Embedded ads (not "blockable" by DNS based blocking - we need to postpone this one)
- Insufficient filter configuration - user should select different / more filters

If anyone has issues with any specific app, please open a new issue for that specific app.

**Comment by kar** [comment]
Forgot to mention, if you have a problem with specific app, please post it on this tracker, with (only) app name in the title:

https://github.com/blokadaorg/apps/issues

Feel free to repost Winr there.
