### ISSUE TITLE
Adding my own block lists

### ISSUE THREAD

**Issue by DUOLabs333** [blokadaorg/blokada#883]
How can you load up your own block lists, either through a url or local file? I'm using Blokada 5.

**Comment by kar** [comment]
As of today, you can only do it in Blokada 4

**Comment by DUOLabs333** [comment]
I just used ReThinkDNS.

**Comment by mtxadmin** [comment]
@DUOLabs333, but keep in mind that ReThinkDNS doesn't support asterisks in blocklists (at least, for now). See https://github.com/celzero/rethink-app/issues/411 about it.

If you would test Blokada, take version 4.11.1 - it can load custom lists and [doesn't have issues](https://github.com/mtxadmin/ublock/blob/master/docs/hosts_file_blokada_en.md) with blocking

**Comment by DUOLabs333** [comment]
Oh no, I meant that I just connected ReThink to my own DNS.

**Comment by mtxadmin** [comment]
I suppose, your own DNS doesn't support asterisks too :-)  It is very powerful feature, see the link above.

**Comment by DUOLabs333** [comment]
It does, in fact.

**Comment by mtxadmin** [comment]
Interesting and unusual. Can I ask you to share some details?

**Comment by DUOLabs333** [comment]
AdGuardHome supports wildcards, and probably PiHole too.
