### ISSUE TITLE
Crash on deactivating VPN/Plus after Update

### ISSUE THREAD

**Issue by cyrencooper** [blokadaorg/blokada#886]
- App version: 5.15.0
- Device: Teracube 2e
- OS version: Android 10 (Security-Updates: 2020-11; Googleplay: 2021-06-01)
- Steps to reproduce the bug:
  1. Update from 5.14.4 to 5.15.0
  2. Try turning off vpn/plus
- Expected behavior: VPN Gets turned OFF
- Actual behavior:
  - Blokada crashes and on reopening the VPN is still active
  - Clearing the Cache did not help
  - Changing Location was not possible; Could not load

Workaround i used: reinstalling Blokada; clearing user data probably should work too

**Comment by peterroth** [comment]
By "the VPN is still active" you mean the Blokada Plus service or that the VPN API was in use? I ask it to clarify what happens exactly.

**Comment by cyrencooper** [comment]
Blokada plus was still active

**Comment by kar** [comment]
We need logs for crashes. There's nothing we can do to investigate it now I guess since you reinstalled.
