### ISSUE TITLE
Tazz by EMAG is not working with Blokada activated

### ISSUE THREAD

**Issue by andreewmat** [blokadaorg/blokada#889]
[tazz by eMAG](https://play.google.com/store/apps/details?id=com.xtremeweb.eucemananc) doesn't want to connect to internet when I have Blokada activated, if I disable Blokada everything is fine. I'm using the latest version of Tazz and Blokada 4.15 with default lists (I tried with other filter lists too but without luck, still the same problem).

**Comment by peterroth** [comment]
Only this one app has issues? Did you try to change the DNS server in the app and check if that solves the issue?

**Comment by andreewmat** [comment]
@peterroth  Yes, I tried changing DNS but no luck. I tried DNS like Adguard DNS, Cloudflare 1.1.1.1, Google Public DNS, OpenDNS. Only on this app I saw this issue.

**Comment by peterroth** [comment]
Thanks, may I ask if you see blocked hosts when you open the tazz app? Maybe the list contains a host that is crucial for the app. You can also try to bypass tezz, that may helps.

**Comment by peterroth** [comment]
In v5: advanced screen, Apps, search for the Tazz app and tap that.

**Comment by andreewmat** [comment]
> In v5: advanced screen, Apps, search for the Tazz app and tap that.

Yes, this bypass made it works again, thanks. What does this bypass? The ads and trackers are not blocked anymore?

**Comment by peterroth** [comment]
The app's traffic, what is being bypassed, won't be filtered. Hence, as you mentioned, no ads nor trackers will be blocked.
If you want to still block ads and trackers in the Tezz app, you should check which hostnames are being blocked when Tezz isn't bypassed and inspect which one is required in order to get the expected function of the app.
