### ISSUE TITLE
[Feature Request] Add an "optimal" or "suggested" tab to the blocklist

### ISSUE THREAD

**Issue by AnonymousWP** [blokadaorg/blokada#890]
I've tried to look for similar issues, but couldn't find one quickly.

So, I remember [this](https://community.blokada.org/t/best-hostlists/2100/4) post which is very helpful. However, it's quite outdated as Blokada got way more blocklists now. Can it be either updated, or is it possible to create an "optimal" or "suggested" tab within the app? I know there's "highlight", but that's not accurate either (anymore) as, for example Energized, isn't present at "Highlights" while it's a combinated blocklist (see image). Could that be updated? I've read suggestions like "try enabling one filter, and see if it blocks enough", but that's not a great solution to me, as with tracking you'll obviously not know it (unless you're going to look at logs all the time.)

In the current situation it just leads me to enabling a lot of blocklists, which obviously isn't optimal (as you can read here: https://github.com/blokadaorg/blokada/issues/856). I am just looking for the most efficient and optimal way to block malicious domains, tracking and ads etc. I just want to avoid having duplicated blocklists in my phone's memory.

![image](https://user-images.githubusercontent.com/50231698/131137231-2328e7e1-819e-4411-98a2-35124ceb503b.png)

**Comment by kar** [comment]
"Highlights" tab intention is exactly that, although I agree it has grown a bit too much. I'll update it. Energized is not a recommended blocklist anymore hence it's not on that tab.

**Comment by AnonymousWP** [comment]
> "Highlights" tab intention is exactly that, although I agree it has grown a bit too much. I'll update it. Energized is not a recommended blocklist anymore hence it's not on that tab.

But it's not accurate anymore. Does this mean you'll update it in the next release/beta? Also: do you think the image above will be updated by anyone from the Blokada team?

**Comment by kar** [comment]
Yes I'll update the tab in the next update. The image actually comes from our Telegram so it depends on the author if it's going to get updated.
