### ISSUE TITLE
[Kindle Fire 7 tablet] Won't turn on after enabling WiFi

### ISSUE THREAD

**Issue by waqas** [blokadaorg/blokada#90]
I am using it on Kindle Fire 7 tablet. When I turn wifi off and then on, it doesn't activate itself (even with persistent notification). Also, it deosn't cache hosts files properly and has to re-download on every activation.

**Comment by waqas** [comment]
BTW, I also used DNS66 and that had no issues, except occasional intervention to re-enable that manually but rarely.

**Comment by kar** [comment]
Cache fixed. The other issue seems to be device specific. More to come

**Comment by kar** [comment]
@waqas could you try with 3.2.4?

**Comment by waqas** [comment]
@kar sorry for late reply. just tried and it is working great. many thanks.

**Comment by noelkra** [comment]
Closing it now :)
