### ISSUE TITLE
Blacklisting or whitelisting not possible (4.10.0)

### ISSUE THREAD

**Issue by terasolu** [blokadaorg/blokada#906]
**What exactly is not working?**
It's not possible to blacklist or whitelist a TLD that ends on a digit.

**How to reproduce your problem (steps you have taken that caused the problem)**
Connect to a TLD which is ending on a digit and try to blacklist or whitelist it.

**Which app version and which platform are you using?**
Android 12
Blokada 4.10.0

**DNS server issues are a common cause for some problems, have you tried selecting another DNS?**
Yes, doesn't work.

**Have you tried disabling DNS over HTTPS, or toggle other settings in Blokada?**
Yes, doesn't work.

**Comment by mtxadmin** [comment]
I checked on my smartphone - at least, version 4.11.1 definitely doesn't have such bug.
https://github.com/blokadaorg/blokada/releases/download/4.11.1/blokada-v4.11.1.apk
You can try this (if it's not your local issue, of course)

Later v4 versions have some other bug (https://github.com/blokadaorg/blokada/issues/900) so this is latest usable version for now.

**Comment by terasolu** [comment]
@mtxadmin I tried version 4.11.1 like you recommended, but the problem persists. I suspect there's a problem with the regex validation of domains, which seems to be very strict.
