### ISSUE TITLE
blokada5没有中国大陆dns和规则

### ISSUE THREAD

**Issue by biange200** [blokadaorg/blokada#908]
blokada没有中国大陆的DNS 也没相应的广告规则 
还有没有中国语言 
这些问题能不能尽快处理下

**Comment by Leowentao** [comment]
告诉你吧，用V4可以配置中国大陆的DNS 和相应的广告规则，区别也不大

**Comment by biange200** [comment]
说下 我自己也不清楚blokada里哪些规则是适合中国大陆的
adguard有adguard中文规则 还有其他的人写的第三方adguard中文规则
但是blokada没有

**Comment by Leowentao** [comment]
https://github.com/privacy-protection-tools/anti-AD

**Comment by biange200** [comment]
https://hosts.oisd.nl/basic/

Energized Blu https://blokada.org/mirror/v5/energized/blu/hosts.txt
这两个要不要添加的

**Comment by Leowentao** [comment]
我用的v4，开oisd,goodbye ads,anti ad, 实测效果跟只开1个没什么区别。甚至全关了也照样能过滤。但是同样的oisd,gba在v5上就过滤的数量比v4多。总之这个就是不太适合国内环境，而且也只能host层级过滤，但是毕竟免费

**Comment by biange200** [comment]
这是不是说明V5过滤广告效果比v4强
v4默认规则是energize推荐 到了vt就是默认规则是oisd blue了 这是不是也说明oisd比energize好
还有就是hosts的过滤广告效果比adguard的差？
还有新版什么时候可以有自定义中文规则和dns 和简体版

现在在中国 用的最多的还是adguard 但是不知道为什么我的adguard开了就上不了网 就用了blokada
你们要是多重视中国大陆用户就好了 中国人还知道adaway 却知道blokada的没几个

**Comment by biange200** [comment]
https://github.com/rentianyu/Ad-set-hosts

**Comment by biange200** [comment]
我在oisd官网上没看到blokada的图标  应该是选择哪个![Screenshot_2021-11-26-11-23-14-55_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/37582806/143522141-909d184d-29e9-43db-808e-ddcdc1b3bb94.jpg)

**Comment by Leowentao** [comment]
你的blokada不是自带oisd的？

**Comment by biange200** [comment]
blokada4没有的 要去官网上添加 自带的是energize

blokada5默认规则打开的就是oisd energize是手动打开的
Get Outlook for Android

**Comment by biange200** [comment]
我的其他问题能不能给我说说
Get Outlook for Android

**Comment by biange200** [comment]
我的其他问题能不能给我说说
Get Outlook for Android发件人: ***@***.*** ***@***.***> 代表 Leowentao ***@***.***>发送时间: 2021年11月26日星期五 22:43收件人: blokadaorg/blokada抄送: biange200; Author主题: Re: [blokadaorg/blokada] blokada5没有中国大陆dns和规则 (Issue #908)

你的blokada不是自带oisd的？

**Comment by biange200** [comment]
blokada4没有的 要去官网上添加 自带的是energize

blokada5默认规则打开的就是oisd energize是手动打开的
Get Outlook for Android发件人: ***@***.*** ***@***.***> 代表 Leowentao ***@***.***>发送时间: 2021年11月26日星期五 22:43收件人: blokadaorg/blokada抄送: biange200; Author主题: Re: [blokadaorg/blokada] blokada5没有中国大陆dns和规则 (Issue #908)

你的blokada不是自带oisd的？

**Comment by Leowentao** [comment]
v4默认是energize,但是过了几天它就出现oisd了，我也不知道为啥。这俩规则都差不多。
v5比v4过滤的多，至少它软件里是这么显示的，实际嘛感受不到。就用v4就行，至少能添加阿里dns
开发者说v5的自定义会有，但是没期。人家不重视中国的，不要幻想了。

**Comment by biange200** [comment]
谢谢 怪不得adaway发展的都比blokada好 在中国 原来是不重视
请问你是中国人吗

**Comment by biange200** [comment]
adaway blokada哪个过滤广告强？

**Comment by biange200** [comment]
问下你 oisd添加哪个规则
https://hosts.oisd.nl/

https://hosts.oisd.nl/basic/

**Comment by Leowentao** [comment]
https://t.me/blokadachat
这么多问题，快去电报问吧
