### ISSUE TITLE
Blokada produces comprehensive mobile data traffic

### ISSUE THREAD

**Issue by Smartieman007** [blokadaorg/blokada#909]
**App version:**
at least V5.16.0, up to V5.18.0

**Device model**
issue detected on both devices:
Moto G5+
Moto G6+

**OS version**
Android 8.1.0
Android 9

**Steps to reproduce the bug**
I found out that the high data consumption only happens when Blokada+ is activated.

**Expected behavior**
Data traffic of a few kilobytes

**Actual behavior**
the system shows in the settings for blokada a very high mobile data usage of many megabytes, over the period of a few days even several hundreds of megabytes

**Comment by Lennart01** [comment]
Hey,
Blokada plus is a VPN based on wireguard.
The mobile data usage is probably just caused by you browsing the web (wireguard also accumulates traffic overtime because it needs to maintain the connection).
