### ISSUE TITLE
[Feature Request] Show and adjust Connections per App

### ISSUE THREAD

**Issue by desolutionX** [blokadaorg/blokada#926]
Blokada is a very nice to have, thank u very much.
As feature Request i ask to add a per App List addional to the available Lists, newest and most. Everytime i search for a Connection to allow it through blokada, iam searching everytime trough the hole list. If i want to check wich connection could be part of the app, that has a connection wich i will block or allow. In this way iam missing a simple feature to show the Webconnections per App.
It seems that this not explicit being asked for.
Thank u very muchin advance

**Comment by kar** [comment]
Thanks. This has been reported many times, sadly to my knowledge this is not feasible to implement for technical reasons.
