### ISSUE TITLE
Icon is missing on F-Droid

### ISSUE THREAD

**Issue by ghost** [blokadaorg/blokada#929]
The app icon is missing on F-Droid.

**Comment by sdfsd2** [comment]
![Снимок экрана от 2022-04-27 08-49-10](https://user-images.githubusercontent.com/102774950/165450117-b8b1361b-abd4-460f-ad51-5a6cb1563a79.png)

Google Chrome 100.0.4896.127
site does not open.
blokada.org

Mozilla Firefox 91.8.0esr
site opens.
blokada.org

problem in google chrome?

**Comment by cosmicqbit** [comment]
The icon is missing for v5 only, v4's icon is still in position. 

Blokada v4
![](https://telegra.ph/file/79449ebdd2d432b37c8f7.jpg)

Blokada v5
![](https://telegra.ph/file/cbba0731c289ea0888996.jpg)

**Comment by kar** [comment]
Those are unofficial listings and we do not maintain them. Please only install from our website https://blokada.org
