### ISSUE TITLE
Whitelist clears automatic after every reboot.

### ISSUE THREAD

**Issue by BarryThrill** [blokadaorg/blokada#95]
Hello!

Finally I found your github even though its easy to find but some people aren't smart enough!

Anyways, Love the app. Saved me alot from ads and I can't complain going from Apple to Android and this is one of the best reasons actually!

However, there is few things I wish the Blokada could do and its about the whitelist and maybe Youtube & Facebook?

**whitelist issue:** The issue here is that everytime I reboot all my whitelists gets removed (Apps only such as Google Duo, Google Photo) - Which I need pretty much because of the synchronization and Google Duo to be able to Duo with people!! And that's it. Maybe there is a way to maybe keep a hosts file that saves automatics the app so I don't need to care about it or if you have any soulution at all?

**Bonus:**  Now I dont know how hard this is for you but what about Facebook and Youtube ads? Are they possible to be blocked? Because Facebooks ads are now going for every video im watchning and its just mad annoying and same thing with Youtube!

**Comment by kar** [comment]
#64

**Comment by kar** [comment]
Fb/yt - probably not. I'll try to have a look at it later after I fix more urgent things like the whitelist.
