### ISSUE TITLE
"Turn on/off" and "Hide" in notification don't work

### ISSUE THREAD

**Issue by TomasRiker** [blokadaorg/blokada#953]
**App version:**
22.4.7

**Device model:**
Google Pixel 4a (5G)

**OS version:**
Android 13

**Steps to reproduce the bug:**
In the Blokada notification, tap "Turn on", "Turn off" or "Hide".

**Expected behavior:**
Blokada should turn itself on/off or hide the notification.

**Actual behavior:**
Nothing happens.

**Comment by kar** [comment]
Fixed in 22.4.14
