### ISSUE TITLE
Autostart after reboot is unreliable

### ISSUE THREAD

**Issue by x2k13** [blokadaorg/blokada#96]
Moto X Play, Android 7.1.1, Blokada 2.2.3

Checked the start-on-boot switch to on.
Expected behaviour: Blokada loads after reboot.
Actual behaviour: Blokada doesn't load at all.

Starting the app manually everytime for now...

**Comment by rpeter85** [comment]
Did you check if your ROM let the app start on boot? In some cases (for example on Miui) the app won't start automatically, even it is enabled in Blokada. In such cases, you have to enable it in the ROM settings.

**Comment by x2k13** [comment]
Moto X Play uses (near-) Vanilla Android.
There isn't any additional option to enable apps to be started on boot.

**Comment by x2k13** [comment]
Update:

Had the F-Droid 2.2.3 apk installed, removed it and installed the one from the first post of the xda thread (2.2.3-origin-slim). Looks like it's working now. Might be the F-Droid build is borked somehow.

Leaving this open for additional information.

**Comment by kar** [comment]
Did some more investigations on this. Notes to self:

- [ ] Read https://developer.android.com/about/versions/oreo/background.html
- [ ] Use JobScheduler from BootReceiver to start a JobService to start VpnService and promote to foreground
- [ ] Adapt KeepAliveService to also work with periodic JobScheduler

**Comment by kar** [comment]
This should be fixed in 3.0.0 (not the preview). Feel free to reopen if you'll see problems still.

**Comment by chrisclark99** [comment]
For some reason adding Blokada to my notification toggles fixed this in Android 8.1.0
