### ISSUE TITLE
I want better notifications

### ISSUE THREAD

**Issue by Sarkie** [blokadaorg/blokada#97]
Please, rather than an annoying popup.

Can you do a permanent notification in the status bar?

Number of blocks
Last block and time
And maybe the app?

**Comment by kar** [comment]
If you turn on "keep alive" you have such a notification. Do you mean something else?

**Comment by kar** [comment]
> If we turn on notification we get one reach time it's blocked but can we make it so that each domain will only show up as a notification once.

**Comment by kar** [comment]
> I like notifications, but Currently it takes one fift of the screen , would be good of the notification was transparent or smaller in height.

**Comment by kar** [comment]
Use of channels for update vs other notifications to be able to hide one and not the others.

**Comment by jeroen7s** [comment]
Why not have a log of blocked domains with timestamp somewhere available in the app?

**Comment by StarTrekRocks73** [comment]
@jeroen7s Please refer to issue #162

**Comment by The-Compiler** [comment]
I'd also like to be able to have more granular notification control with a "notification whitelist", similar to what [AFWall](https://github.com/ukanth/afwall) provides. This way, I could turn off notifications for domains I see being blocked a lot (e.g. crash analytics for apps I use regularly), and only see notifications for things being blocked which I don't know about yet.

**Comment by schlamar** [comment]
> I like notifications, but Currently it takes one fift of the screen , would be good of the notification was transparent or smaller in height.

If you are refering to the permanent notification: you can set the priority to MIN, so it doesn't show an icon and it auto-collapses if it isn't on top of the notification list.
