### ISSUE TITLE
Is StevenBlack's host supported ?

### ISSUE THREAD

**Issue by Moxville** [blokadaorg/blokada#99]
Hi kar,

Would like to know whether StevenBlack's host is supported ?
https://github.com/StevenBlack/hosts
(automatic updates, consolidated list, etc..)

Just asking on behalf of my friend who is using it. Thanks

**Comment by kar** [comment]
Yes, in fact its the default selection (the "Unified" list). Also I've just added the "Social" extension as per discussion in #91, although this one will be disabled by default. You can always see the source of each list by clicking the "open in new window" icon [here](https://dl2.pushbulletusercontent.com/cKey0SW3Vzq7cLFBqdB59s4z4dIYIrVZ/Screenshot_20180220-123811_01.jpg).

**Comment by kar** [comment]
All lists in Blokada are automatically refetched from time to time.

**Comment by Moxville** [comment]
thanks kar for your reply and screenshot. Noted :)
